### ISSUE TITLE
Should `vec_data()` special case data frames?

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#1001]
Since we consider it an atomic type? This affects the "data" underlying S3 classes that use a data frame as a proxy. It also affects the "data" underlying a tibble.

I imagine we'd retain `row.names`, `names`, and `class = "data.frame"` as attributes.

``` r
library(vctrs)

vec_data(data.frame(x = 1, y = 2))
#> $x
#> [1] 1
#> 
#> $y
#> [1] 2

vec_data(as.POSIXlt(Sys.time()))
#> $sec
#> [1] 15.45129
#> 
#> $min
#> [1] 3
#> 
#> $hour
#> [1] 13
#> 
#> $mday
#> [1] 8
#> 
#> $mon
#> [1] 3
#> 
#> $year
#> [1] 120
#> 
#> $wday
#> [1] 3
#> 
#> $yday
#> [1] 98
#> 
#> $isdst
#> [1] 1
#> 
#> $zone
#> [1] "EDT"
#> 
#> $gmtoff
#> [1] -14400
```

<sup>Created on 2020-04-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DavisVaughan** [comment]
I think this invariant should hold

```r
vec_size(x) == vec_size(vec_data(x))
```

**Comment by lionel-** [comment]
Also it's unclear that `vec_data()` is really needed in the API.

**Comment by DavisVaughan** [comment]
Good point, I took a look and it looks like everywhere we use `vec_data()` could be replaced with `unclass()`. We generally are using it to avoid dispatch

**Comment by DavisVaughan** [comment]
Closed by https://github.com/r-lib/vctrs/pull/1223
