### ISSUE TITLE
`vec_rbind(<tbl_ts>, <tbl_ts>)` error

### ISSUE THREAD

**Issue by earowang** [r-lib/vctrs#1021]
Since I've got a slightly different error message, I open a new ticket on `vec_rbind()` (related to #982).

I've been making tsibble compatible with dplyr and vctrs dev. I have `vec_cast(<tbl_ts>, <tbl_ts>)` and `vec_ptype2(<tbl_ts>, <tbl_ts>)` implemented and working as expected. But can't proceed with `vec_rbind()`. It looks like the error from C, which I don't know how to debug. Can you please give any suggestions on this?

``` r
# remotes::install_github("tidyverts/tsibble@183/vctrs-tsibble")
library(vctrs)
library(tsibble)
vec_cast(pedestrian[0, ], pedestrian)
#> # A tsibble: 0 x 5 [?] <Australia/Melbourne>
#> # Key:       Sensor [0]
#> # … with 5 variables: Sensor <chr>, Date_Time <dttm>, Date <date>, Time <int>,
#> #   Count <int>
vec_ptype2(pedestrian[0, ], pedestrian)
#> # A tsibble: 0 x 5 [?] <Australia/Melbourne>
#> # Key:       Sensor [0]
#> # … with 5 variables: Sensor <chr>, Date_Time <dttm>, Date <date>, Time <int>,
#> #   Count <chr>
vec_rbind(pedestrian, pedestrian[0, ])
#> Error in vec_rbind(pedestrian, pedestrian[0, ]): STRING_PTR_RO() can only be applied to a 'character', not a 'integer'
```

<sup>Created on 2020-04-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

What's the timeline for new vctrs release, since dplyr is scheduled for May 1?

**Comment by lionel-** [comment]
The dplyr release is delayed. We'll send revdep emails for vctrs next week.

**Comment by lionel-** [comment]
oh and this is probably a bug on our end, we'll look into it.

**Comment by earowang** [comment]
Thanks. Initially I thought its tsibble's attributes caused the issue,  but it's columns instead (didn't notice the `Count` type column.

**Comment by hadley** [comment]
@earowang do you have enough information to fix tsibble? We're happy to help out more if needed. (We're planning to move the release date to May 15, so there's still a decent amount of time)

**Comment by earowang** [comment]
Do I need to use `tib_ptype2()` and `tib_cast()` as mentioned by @lionel-? but they're not exported yet?

**Comment by earowang** [comment]
I've used `vctrs:::tib_ptype2` internally to get `Count` type fixed (now integers).

``` r
library(vctrs)
library(tsibble)
vec_ptype2(pedestrian[0, ], pedestrian)
#> # A tsibble: 0 x 5 [?] <Australia/Melbourne>
#> # Key:       Sensor [0]
#> # … with 5 variables: Sensor <chr>, Date_Time <dttm>, Date <date>, Time <int>,
#> #   Count <int>
```

But when I run this, my rstudio session crashes

``` r
vec_rbind(pedestrian, pedestrian[1:2])
```

<img width="565" alt="image" src="https://user-images.githubusercontent.com/2456216/80557262-74bca100-8a2a-11ea-88b3-66b8a8a25b27.png">

<sup>Created on 2020-04-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
I'm working on exporting these functions + documentation. I'll look into the crash, which branch of tsibble are you using?

**Comment by earowang** [comment]
Great! Thanks. I'm working on https://github.com/tidyverts/tsibble/tree/183/vctrs-tsibble atm.

**Comment by lionel-** [comment]
This is now:

```r
vec_rbind(pedestrian, pedestrian[1:2])
#> Error in vec_rbind(pedestrian, pedestrian[1:2]) :
#>   Internal error in `df_assign()`: Can't assign 2 columns to df of length 5.
```

The reason is that you need to call `tib_cast()` from your `vec_cast()` methods. This will ensure that the result has the appropriate number of columns. Documentation coming soon!

**Comment by earowang** [comment]
Thanks. Solved with `tib_cast()`. 🎉

**Comment by earowang** [comment]
Well, now a new issue pops out.

I defined `vec_ptype2.data.frame.tbl_ts`, and `vec_rbind(<data.frame>, <tbl_ts>)` works. I'd expect `vec_rbind(<tbl_df>, <tbl_ts>)` work out of box, but receive warnings.

Should the S3 generic `vec_ptype2.tbl_df` be exported?

``` r
library(vctrs)
library(tsibble)

df <- vec_rbind(as.data.frame(pedestrian), scan_gaps(pedestrian))
tbl <- vec_rbind(as_tibble(pedestrian), scan_gaps(pedestrian))
#> Warning: Can't combine <tibble> and <tbl_ts>; falling back to <tibble>.
#> ℹ Convert all inputs to the same class to avoid this warning.
#> ℹ See <https://vctrs.r-lib.org/reference/faq-warning-convert-inputs.html>.
```

<sup>Created on 2020-04-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
There is no inheritance, you need to define ptype2 and cast methods for all pairs of classes that are compatible.

Note that method registration is now considerably simplified, you no longer need all the special roxygen boilerplate. Simply registering like this should work out of the box:

```r
#' @export
vec_ptype2.tbl_ts.tbl_ts <- function(x, y, ...) {
  tsibble_ptype2(x, y)
}
```

**Comment by lionel-** [comment]
And you need to pass `...` to `tib_ptype2()` and `tib_cast()`.

**Comment by earowang** [comment]
Nice. I'll remove these roxygen boilerplate.

Currently `vec_ptype2.tbl_df` isn't exported. Can I still define `vec_ptype2.tbl_df.tbl_ts` in the {tsibble} package?

**Comment by lionel-** [comment]
Yes, part of the simplification is that everything is now registered for the `vec_ptype2()` generic :)

The left-hand side method-generics are no longer needed (but still exist in vctrs for backwards compatibility).

**Comment by earowang** [comment]
Wow, wonderful! 💯 

All the warnings amazingly disappear for now. 🎉

**Comment by lionel-** [comment]
The process for implementing coercion methods for data frames is now documented here: https://vctrs.r-lib.org/reference/howto-faq-coercion-data-frame.html

Please also see this general reference about how coercion works in vctrs: https://vctrs.r-lib.org/reference/howto-faq-coercion.html

And the practical guide for implementing coercion methods for normal vectors might also be useful: https://vctrs.r-lib.org/reference/howto-faq-coercion.html

Any feedback on these would be very welcome!

**Comment by earowang** [comment]
Looks great, although have a quick note on roxygen boilerplate.

`vec_cast` and `vec_ptype2` have roxygen boilerplate simplified, but not `vec_arith`? Noticed that I still need to use `@method` tag to get it exported in the right way.

**Comment by lionel-** [comment]
That's a good point, we haven't changed `vec_arith()`. I have opened an issue: https://github.com/r-lib/vctrs/issues/1063
