### ISSUE TITLE
Export `vec_has_coercion()` predicate?

### ISSUE THREAD

**Issue by lionel-** [r-lib/vctrs#1022]
To figure out whether two classes implement ptype2 / cast methods.
cf https://github.com/r-spatial/sf/pull/1374 

Or maybe `vec_ptype2_has()` / `vec_cast_has()`? But I think it's fine to have only one predicate and assume that if ptype2 methods are implemented, cast methods are implemented as well.

**Comment by hadley** [comment]
vec_is_coercible?

**Comment by lionel-** [comment]
I think that name would imply something slightly different. That not only the classes have a ptype2 method, but also running the method would not cause a common type error.

**Comment by lionel-** [comment]
Let's revisit this if the need arises again. Maybe with a more general `s3_implements(inherit = )`.
