### ISSUE TITLE
vec_cbind() row.names strictness is a bit annoying

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#1058]
``` r
x <- data.frame(x = 1:5, a = 1)
y <- data.frame(y = 5:1, b = 2)

vctrs::vec_cbind(x[c(1, 1, 3, 5), ], y[c(1, 3, 3, 5), ])
#> Error: Can't column-bind data frames with different row names.
```

<sup>Created on 2020-04-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

If you've deliberately created the data frames so they line up, it's annoying to have to strip their row names. (This causes fuzzyjoin to fail with dplyr 1.0.0)

**Comment by lionel-** [comment]
This is a bug, there are no identifier row names in the data frames created in this example.

**Comment by lionel-** [comment]
Unfortunately this is not a bug in vctrs :-(

```r
attr(x, "row.names")
#> [1] 1 2 3 4 5

attr(x[c(1, 2), ], "row.names")
#> [1] 1 2

attr(x[c(1, 1), ], "row.names")
#> [1] "1"   "1.1"
```

The `[` method is repairing the row names even though they are automatic. I think it shouldn't do this, for example `rbind()` doesn't do it:

```r
attr(rbind(x, x), "row.names")
#>  [1]  1  2  3  4  5  6  7  8  9 10
```

**Comment by lionel-** [comment]
So this can't be an error. It would make sense to go in the direction of `vec_rbind()` and make the behaviour silent. The behaviour could be pasting the row names together (converting automatic to identifiers if needed).

**Comment by hadley** [comment]
Or maybe just preserve the names from the LHS?
