### ISSUE TITLE
Coercion documentation

### ISSUE THREAD

**Issue by earowang** [r-lib/vctrs#1065]
When reading this https://vctrs.r-lib.org/reference/theory-faq-coercion.html, found "Type compatibility" and "Richness of type" sections confusing. Primarily, the notion of "richer"/"rich" is ambiguous/changing when referring to 1d vectors and 2d data frames (acknowledged in the FAQ).

The `factor` vs `character` 1d example suggests that `character` is richer (general) than `factor` (specific), and hence a combination of two results in `character` (general). However, this  rationale doesn't hold for the following 2d example `data.table` (specific) vs `data.frame` (general), because we should choose richer behaviours instead of richer data. I could probably argue `factor` is richer in behaviours than `character`, since `factor` owns the `level()`. 

I'm not sure `data.table` vs `data.frame` is a good example (neither `tbl_df` vs `data.frame`). Would be `grouped_df` vs `data.frame` a better alternative? Any reason on `vec_ptype2(<grouped_df>, <data.frame>)` returns `<grouped_df>`? I think `data.frame` is richer than `grouped_df`, because it's more flexible with fewer attributes/constraints.

For 1d, we should choose a more general type, but 2d goes with a more specific type?

**Comment by lionel-** [comment]
It's not about 1d or 2d. In both cases combinations should return the more general type.

There's still fundamental ambiguities regarding what a richer type is. In particular I still struggle with the idea of strict restrictions (strict factor, list-of, ...). They create a constraint type, but typically you don't want to lose the restrictions, so if you want the strict type to be coercible with relaxed type as long as they contain compatible values, you need to return the restricted type, not the richer type.

I think one of the main principle for taking the decision is what is the most common usage made for these types. In doubt, it's best to leave types incompatible. We're still figuring these things out, so I don't have better advice.

> Any reason on vec_ptype2(<grouped_df>, <data.frame>) returns <grouped_df>?

Grouped-df has richer data (group information). A data frame is like a grouped-df that has a constant single group. Conceptually, groups are type parameters with a default argument. Also ideally grouped-df would have no additional behaviour: all functions defined on grouped-df should also handle df.
