### ISSUE TITLE
Optional hashing of string values

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#107]
Making it possible to use vctrs hashing for (e.g.) factor levels display, and eliminating the dependency on digest.

**Comment by DavisVaughan** [comment]
https://stackoverflow.com/questions/7666509/hash-function-for-string
http://www.cse.yorku.ca/~oz/hash.html

**Comment by DavisVaughan** [comment]
This is slower than `hash_char()`, but seems to work alright as a reproducible way to hash factor levels

```
static uint32_t hash_char2(SEXP x) {
  uint32_t hash = 5381;

  const char *string = CHAR(x);
  int chr = *string++;

  while (chr) {
    hash = ((hash << 5) + hash) ^ chr; /* hash * 33 ^ elt */
    chr = *string++;
  }

  return hash;
}
```

**Comment by hadley** [comment]
I think we'd want to opt in it; there's no way we'll be able to do better than hashing in the string pool if we only care about within-session hashes.
