### ISSUE TITLE
Error in vec_rbind(!!!dots, .names_to = .id) :    Internal error in `vec_assign()`: `value` should have been recycled to fit `x`. 

### ISSUE THREAD

**Issue by tungmilan** [r-lib/vctrs#1073]
Hello,

I only recently encountered this error. It worked fine about a week ago or so. I'm wondering what changes were made and how to fix it? Thanks!

```
Error in vec_rbind(!!!dots, .names_to = .id) : 
  Internal error in `vec_assign()`: `value` should have been recycled to fit `x`.
```

**Sample code:**

````

library(tools)
library(data.table)
library(tidyverse)

read_file_fread <- function(file_name, column_names) {

  DT <- fread(file_name, header = FALSE, col.names = column_names)
  DT <- DT %>%
    mutate(Year  = year(Date),
           Month = month(Date)) 

  return(DT)
  
}

dat <- txt_files %>%
  set_names(nm = (basename(.) %>% tools::file_path_sans_ext())) %>%
  map_df(~ read_file_fread(.x, column_names), .id = "Filename")
````

```
   vctrs         0.2.99.9011 2020-05-02 [1] Github (r-lib/vctrs@29e1101) 
```

**Comment by lionel-** [comment]
Can you provide a reprex please: https://reprex.tidyverse.org/

**Comment by tungmilan** [comment]
Thanks @lionel- ! I uploaded the sample RProject folder including sample data files and script. 

[vctrs_rbind_error.zip](https://github.com/r-lib/vctrs/files/4571236/vctrs_rbind_error.zip)

**Comment by lionel-** [comment]
Thank you!

Just so you know for next time, if you really have to write to a file it's better to it in a temporary file created with `tempfile()`. This way you don't write in the current directory on our computers.

But in general it's best to recreate synthetic data with R commands. Here is a minimal reprex:

```r
dt <- data.table::data.table(x = 1)
dts <- list(dt, dt)
purrr::map_df(dts, ~ .x)
#> Error: Internal error in `vec_assign()`: `value` should have been recycled to fit `x`.
```

I'll look into it, thanks for reporting.

Further investigation:

```r
bind_rows(dts)
#> Error: Internal error in `vec_assign()`: `value` should have been recycled to fit `x`.

vctrs::vec_rbind(!!!dts)
#> Error: Internal error in `vec_assign()`: `value` should have been recycled to fit `x`.
```

**Comment by tungmilan** [comment]
Thanks @lionel- !

**Comment by davelorino** [comment]
Im still getting this error when using purrr::map_df

**Comment by lionel-** [comment]
@davelorino We need a reprex.

**Comment by davelorino** [comment]
I'll provide one as soon as possible, i've rolled back to older versions of
dplyr and vctrs which has solved my problem for now

Thank you,

**Comment by lionel-** [comment]
thanks!

**Comment by StevenMMortimer** [comment]
@lionel- The problems mentioned above are coming from `bind_rows()` in {dplyr} v1.0.1 (which is called implicitly by `purrr::map_df()`). The error message doesn't appear in {dplyr 1.0.0}. I think you've already noted it in tidyverse/dplyr#5417. 

**reprex**
The example below recreates the error by trying to bind lists together where a column in one of the data frames does not appear in the other and that column has elements in it that are longer than length 1.
``` r
library(dplyr, warn.conflicts = FALSE)
l1 <- list(a = "a")
l2 <- list(bc = c("b", "c"), 
           d = "d")
bind_rows(l1, l2)
#> Error: Internal error in `vec_assign()`: `value` should have been recycled to fit `x`.
```

<sup>Created on 2020-08-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
@StevenMMortimer This sort of problem may have different causes. In the case you mention it's a problem in dplyr which creates corrupted data frames.

**Comment by lionel-** [comment]
(We've implemented `vctrs::df_list()` and `vctrs::data_frame()` to help safely and consistently transforming lists to data frames without overhead, but dplyr hasn't been updated to use those yet)

**Comment by GGAnderson** [comment]
IS there a plan to correct bind_rows?  I find the error is caused by fields containing NA or NULL values.    Of course, data from the internet in JSON format often contains empty fields, so this is more than a small annoyance.  Hope there is a plan.
