### ISSUE TITLE
vec_rbind (data.frame, list) awkward error message

### ISSUE THREAD

**Issue by jonasfoe** [r-lib/vctrs#1075]
I was trying to rowbind a list representing one row.
This kind of coercion might not be intended but the error message here seems to just not be true and is misleading.
```r
vctrs::vec_rbind(data.frame(a = numeric()), list(a = numeric()))
#> Error: Can't combine `..1$a` <double> and `..2$a` <list>.
vctrs::vec_rbind(data.frame(a = 1), list(a = 1))
#> Error: Can't combine `..1$a` <double> and `..2$a` <list>.
```
`..2$a` should still be `<double>`, right?

> vctrs      0.2.99.9011 2020-05-04 [1] Github (r-lib/vctrs@0ca806c)

**Comment by lionel-** [comment]
This is the expected behaviour and error message. Non-data frame inputs are transformed to data frames of 1 row and length(input) columns:

```r
str(vctrs:::as_df_row(list(a = numeric())))
#> 'data.frame':	1 obs. of  1 variable:
#>  $ a:List of 1
#>   ..$ : num
```

I agree the error message is confusing but we can't do much better than just deprecate the support for non-data frame inputs. Where does this come up?

**Comment by jonasfoe** [comment]
I had a bunch of lists, where each list was supposed to end up as one row.
I also had a template of what the final df should look like, so I thought I might as well use it to enforce it's structure.
```r
lists <- list(first = list(a = 1), second = list(a = 2))
template <- data.frame(a = numeric(), b = character())
rlang::exec(vctrs::vec_rbind, template, !!!lists)
#> Error: No common type for `..1$a` <double> and `first$a` <list>.
```
I was just testing to see if I can just skip the data.frame conversion of the rows.
Instead I have to do like this:
```r
rlang::exec(vctrs::vec_rbind, template, !!!purrr::map(lists, as.data.frame))
#>        a    b
#> first  1 <NA>
#> second 2 <NA>
```

The template has some purpose if there is optional columns that might not be present in any row. Also the` .names_to` option works nicely with the `!!!` if `lists` is named so it was just a nice all in one solution for what I was doing.

**Comment by lionel-** [comment]
Unfortunately we can't do much better. Inputs to cbind and rbind are treated as columns or rows, so your list of length n becomes a 1-row data frame of n list-columns. We'll keep this confusing message in mind if we need to review the UI. Thanks for reporting!
