### ISSUE TITLE
converting Date into POSIXct when time zone is not UTC

### ISSUE THREAD

**Issue by edzer** [r-lib/vctrs#108]
We now see:
```r
library(vctrs)
Sys.setenv(TZ = "EST") # anything non-UTC
vec_c(Sys.Date(), Sys.time())
# [1] "2018-10-03 00:00:00 EST" "2018-10-03 13:47:22 EST"
c(as.POSIXct(Sys.Date()), Sys.time())
# [1] "2018-10-02 19:00:00 EST" "2018-10-03 13:47:22 EST"
```
which means that unlike base R, `vctrs` conversion of `Date` to `POSIXct` depends on your time zone settings. I think this is not a good idea: R scripts would become non-reproducible across time zones.

What we want is that the way times are printed depends on time zone, not the values we assign during conversion. Also, deviating here from base R is asking for trouble.

**Comment by hadley** [comment]
`vec_c() uses the time zone in the date-time whereas `c()` always uses the current time zone:

``` r
library(vctrs)

Sys.setenv(TZ = "America/Chicago") # CST
x <- as.POSIXct("2010-01-10 09:00", tz = "America/New_York") # EST
vec_c(x, Sys.Date())
#> [1] "2010-01-10 09:00:00 EST" "2018-10-03 00:00:00 EDT"

c(x)
#> [1] "2010-01-10 08:00:00 CST"
```

**Comment by hadley** [comment]
`as.POSIXct.Date()` produces a date-time at midnight UTC with the current timezone; that feels like the worst of both worlds to me.

**Comment by edzer** [comment]
No: `as.POSIXct.Date()` creates an unambiguous time object (00:00 UTC), but `print.POSIXct()` shows it as converted to your local time zone. _Which does not change the time, but only its reference system_.

Semantically, dates and times are very different: dates refer to a 24h period, times to a zero duration moment. If R's `Date` would come with a time zone attribute, you could argue for a time zone dependent interpretation of it, answering e.g. _when (UTC) does this date of this TZ actually start?_. 00:00 local time zone. But it doesn't. 

If now `vctrs` interprets `Date`, when converted to `POSIXct` (meaning: to start of day) as depending on the time zone you're in, then a dataset with a `Date` column in it would have an entirely different meaning when opened on computers in different time zones. Is that what you want?

**Comment by edzer** [comment]
Time zones confused me once more. It seems my issue (on linux) only arises when TZ is not set:
```r
library(vctrs)
f = function() {
  d = as.Date("2018-10-04")
  t = as.POSIXct("2018-10-04 12:44")
  print(base <- c(t, as.POSIXct(d)))
  print(vec  <- vec_c(t, d))
  print(base - vec)
}
Sys.setenv(TZ="CEST")
f()
# [1] "2018-10-04 12:44:00 CEST" "2018-10-04 00:00:00 CEST"
# [1] "2018-10-04 12:44:00 CEST" "2018-10-04 00:00:00 CEST"
# Time differences in secs
# [1] 0 0
Sys.setenv(TZ="UTC")
f()
# [1] "2018-10-04 12:44:00 UTC" "2018-10-04 00:00:00 UTC"
# [1] "2018-10-04 12:44:00 UTC" "2018-10-04 00:00:00 UTC"
# Time differences in secs
# [1] 0 0
Sys.unsetenv("TZ") # regrettably default on ubuntu, but you not a good idea:
f()
# [1] "2018-10-04 12:44:00 CEST" "2018-10-04 02:00:00 CEST"
# [1] "2018-10-04 12:44:00 CEST" "2018-10-04 00:00:00 CEST"
# Time differences in secs
# [1]    0 7200
```
I overlooked the warning section of `print.POSIXct`; also: base R converts `Date` to 00:00 of the local time zone if TZ is set. 

Sorry for the noise!

**Comment by hadley** [comment]
No worries - the same issue just bit me in advanced R — mac will warn if you use an invalid timezone, but linux doesn't
