### ISSUE TITLE
`.names_to` docs look a little strange

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#1100]
![Screen Shot 2020-05-12 at 3 32 52 PM](https://user-images.githubusercontent.com/19150088/81737367-fcac9d00-9465-11ea-9fcf-2efbbec472b6.png)

It seems we just want 3 bullet points. I've hit this before - it is a weird case with roxygen2. I'm not sure if there is any way around it

https://github.com/r-lib/vctrs/blob/4ff6b79f92658452ef232f94c4334b9167a2d792/R/bind.R#L44-L51

**Comment by lionel-** [comment]
Reported in r-lib/roxygen2#1102.
