### ISSUE TITLE
Set names on complete data

### ISSUE THREAD

**Issue by lionel-** [r-lib/vctrs#1108]
`names<-` performs restoration checks, and thus can't be called on partial data.

```r
x <- set_names(new_vctr(1:2), c("foo", "bar"))

vec_c(x, x)
#> Error: If any elements are named, all elements must be named.
```

Related to #1107.

**Comment by hadley** [comment]
Or should we relax the restriction on names? Why do we even have that?

**Comment by DavisVaughan** [comment]
This feels related to https://github.com/r-lib/vctrs/pull/784 somehow

**Comment by lionel-** [comment]
@hadley This is from the first version of vctrs. I don't mind removing the restriction, but even so I think we should somehow couple set-names with vec-restore.

**Comment by hadley** [comment]
See linked haven issue for another reason why this is restrictive.
