### ISSUE TITLE
How to write.csv with vctrs data.frame

### ISSUE THREAD

**Issue by jpmarindiaz** [r-lib/vctrs#1115]
The following gives an error for character casting.
```
  new_percent <- function(x = double()) {
    vec_assert(x, double())
    new_vctr(x, class = "vctrs_percent")
  }
  x <- new_percent(c(seq(0, 1, length.out = 4), NA))
  d <- data.frame(x)
  d
  write.csv(d, "~/Downloads/tmp.csv") # Error: Can't convert <vctrs_percent> to <character>.
```
In the previous version I was able to declare an explicit cast to character using `vec_cast` to be able to use write.csv with my custom vector types. The change log for 0.3.0 says: "vec_cast() no longer converts to character. Use as.character()to deparse objects."
But I have no idea how to do that from inside my vctrs package, without changing `write.csv` or making sure to use `as.character` in all my custom vector types before writing to disk the data.frame.

Any ideas?

**Comment by lionel-** [comment]
The default `as.character.vctrs_vctr()` method uses `vec_cast(x, character())` for the case where the type is coercible to character. If they are not coercible, you simply need to add an `as.character()` method for your type.

**Comment by jpmarindiaz** [comment]
Thanks, it worked. Leaving this here in case some else finds it useful
```
as.character.vctrs_percent <- function(x) as.character(vec_data(x))
```
