### ISSUE TITLE
vec_slice() doesn't fall back to `[`

### ISSUE THREAD

**Issue by earowang** [r-lib/vctrs#1116]
Re https://github.com/tidyverts/tsibble/issues/189

I don't implement `vec_restore()`/`vec_proxy()` methods for tsibble. According to `vec_slice()` doc,  it falls back to the base generic `[`.

``` r
library(vctrs)
library(tsibble)
attr(pedestrian[1:3, ], "key")
#> # A tibble: 1 x 2
#>   Sensor               .rows
#> * <chr>          <list<int>>
#> 1 Birrarung Marr         [3]
attr(vec_slice(pedestrian, 1:3), "key")
#> # A tibble: 4 x 2
#>   Sensor                              .rows
#> * <chr>                         <list<int>>
#> 1 Birrarung Marr                   [14,566]
#> 2 Bourke Street Mall (North)       [16,414]
#> 3 QV Market-Elizabeth St (West)    [17,518]
#> 4 Southern Cross Station           [17,539]
```

<sup>Created on 2020-05-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
Work in progress at https://github.com/lionel-/vctrs/tree/fix-slice-fallback!

We also plan to fall back to `rbind.foo()` methods when a data frame doesn't implement ptype2.

**Comment by earowang** [comment]
Actually, what's the advantage to define `vec_proxy()`/`vec_restore()` for data.frame like objects, over `[`? faster?

**Comment by lionel-** [comment]
Yes with proxy and restore should be able to slice and combine data frames in parallel for instance. But that's not implemented yet. Also it may make the class work in more situations, it's unclear yet to what extent we can be generic by falling back to base methods.

**Comment by earowang** [comment]
That's excellent. Looking forward to trying the parallel out in the future.

**Comment by lionel-** [comment]
Unfortunately I think this will be too tricky to implement for 0.3.1, because of the way this fallback interacts with the current stopgap implementation for the `c()` fallback in `vec_rbind()`.

Do you need any help with tsibble + dplyr 1.0 @earowang?

**Comment by earowang** [comment]
No worries, I'll implement `vec_restore()` and `vec_proxy()`.

It has nothing to do with dplyr, but `slider::slide()` a tsibble re https://github.com/tidyverts/tsibble/issues/189

**Comment by lionel-** [comment]
It doesn't seem worth it to implement that fallback as the need hasn't resurfaced since the issue was open.
