### ISSUE TITLE
dplyr issue with dictionary size

### ISSUE THREAD

**Issue by lionel-** [r-lib/vctrs#1133]
https://github.com/tidyverse/dplyr/issues/5291

**Comment by DavisVaughan** [comment]
I took a look at this, and it looks like we overflow a `R_len_t` here
https://github.com/r-lib/vctrs/blob/f2f02a4dccb8233f80938104eb3e52597b0f0440/src/dictionary.c#L284

For example, with `vec_size(x)` of `1e9` as used in the original issue, the closest power of 2 is `2^31`, which is OOB for ints

```r
> 1e9 / .77
[1] 1298701299
> (2 ^ 30) < (1e9 / .77)
[1] TRUE
> (2 ^ 31) < (1e9 / .77)
[1] FALSE
> as.integer(2 ^ 31)
[1] NA
Warning message:
NAs introduced by coercion to integer range 
> 2 ^ 31
[1] 2147483648
```

This size is stored in the dict as `d->size` which is a `uint32_t`. I thought about just making sure that we store this instead as a `uint64_t`, but I don't think it is that simple. The hash values are all `uint32_t`, and we mix the hash with `k` here to get a `probe` which would have to be `uint64_t`. I think that would probably break things

https://github.com/r-lib/vctrs/blob/f2f02a4dccb8233f80938104eb3e52597b0f0440/src/dictionary.c#L316-L321

It seems like the first step to fix this if we stayed with the dictionary approach would be to change `hash.c` to return `uint64_t` hash values
