### ISSUE TITLE
What's the best way to use an expressions as an attribute to a vctrs object?

### ISSUE THREAD

**Issue by md0u80c9** [r-lib/vctrs#1134]
Hi,

I've been trying to apply vctrs to some of my code. Ones with regular attributes seem to be working well now.

However, some of my objects need expressions as one of their attributes.

I'm aware we are now introducing the problem that you can't have a vector of expressions, but I'm struggling to understand how to work around that in this context (I am assuming that you can't have a vector of expressions, but you can in principle have a vector of objects for whom a parameter is an expression).

How do I define the ptype (eg for use with vec_assert) of expr? Its type is reported as a language. Both base::call() and rlang::call2() can't be called without parameters. 

I've tried using rlang::exprs() and getting the convenience type to place the expression into a list of 1. That works, but then causes problems eg within the environment browser pane, where we trigger the inevitable: `Error in FUN(X[[i]], ...) : object of type 'symbol' is not subsettable` (presumably because it's a named list).

Is there a recommended way to work with expressions in this context?

**Comment by hadley** [comment]
Just use of a list instead?

**Comment by md0u80c9** [comment]
Aha - yes. I think I overcomplicated it. Thanks!
