### ISSUE TITLE
R 3.1 - double dispatch requires explicit exports in packages that build on vctrs

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#114]
I noticed that in `probably`, I was failing travis on R 3.1 every time.

I've created a small repo that demonstrates the problem:
https://github.com/DavisVaughan/testtravis

The issue is this:
- Use `@importFrom vctrs vec_cast`
- Create a function that calls `vec_cast(thing, integer())`
- This should call `vec_cast.integer`
- Then more double dispatch...

This works everywhere except on R 3.1 where I get the error:

```
Error in vec_cast.integer(1, integer()) : 
  could not find function "vec_cast.integer"
```

See travis:
https://travis-ci.org/DavisVaughan/testtravis/builds/439111560

The failure line:
https://travis-ci.org/DavisVaughan/testtravis/jobs/439111566#L1868

If I explicitly do `@importFrom vctrs vec_cast.integer`, things work fine again.

My guess is that something must have changed from R 3.1 -> 3.2 where in 3.1 if you are dispatching to something that is another generic, R wouldn't recognize that as being a method of the first generic which it should be able to dispatch to without needing the method to be exported.

**Comment by krlmlr** [comment]
Do we need to maintain support for R 3.1?

**Comment by hadley** [comment]
Our policy is to support 5 versions of R, so when 3.6 comes out, we can drop 3.1 support.

**Comment by DavisVaughan** [comment]
I have painfully also learned that this isn't enough for R 3.1 to always work. If you call `vec_cast.data.frame.data.frame` at some point in a dependent package, then at this line:

https://github.com/r-lib/vctrs/blob/36dd5592c2bca27e426d84c8e043b43323cf9163/R/type-data-frame.R#L161

the `vec_cast()` fails and can't find the first level dispatch function `vec_cast.<type>`. I have determined that this is because `vec_cast()` isn't wrapped in an anonymous function, so the dispatch can't occur correctly. See the [Note section of `lapply()`](https://www.rdocumentation.org/packages/base/versions/3.5.2/topics/lapply). (Strangely this is the second time in the past week I've seen this weird feature of `lapply()` and friends appear.)

If you change it to this everything works again:

https://github.com/DavisVaughan/vctrs/blob/e74fcf17fd9abcb7d529ad507aee3f9d3c519f62/R/type-data-frame.R#L161

(You'll still need the `@importFrom` tags in the downstream package too)

@hadley I believe this will solve your issue in `tidyr` (tidyverse/tidyr#565). There may be other cases where this will bite us, but I'm not sure (for instance [here](https://github.com/r-lib/vctrs/blob/36dd5592c2bca27e426d84c8e043b43323cf9163/R/type-data-frame.R#L137)?).

**Comment by hadley** [comment]
Ah that makes sense — I think either S3 dispatch or `lapply()` (or both) changed in 3.2 so it's not too surprising. Do you want to make a PR to resolve the `lapply()` problem?

**Comment by hadley** [comment]
Fixed by switching dispatch to C.
