### ISSUE TITLE
Documentation request: record-type vectors versus vctrs 

### ISSUE THREAD

**Issue by md0u80c9** [r-lib/vctrs#1152]
Hi,

I wonder whether it would be possible to expand the documentation to explain when and why you should use new_vctr versus when you should use new_rcrd? In particular when and why you would choose one over the other, and what things you should take into consideration when choosing. Apologies if this seems obvious: I've now used both types in a number of cases, and I'm still not entirely clear in my head about the rationale for my choice and indeed whether I've chosen 'correctly'.

**Comment by hadley** [comment]
You assume we know the answer 😉 

Unfortunately in my experience the primary way to figure out the "correct" design for a new class is to do it wrong a couple of a times. After you've done this multiple times for multiple classes, you slowly develop a better sense of where to start. I think we're still quite a long way from writing down exactly what it is that we do. But it's definitely something I know is a challenge, and I'll definitely come back to it in the future.

**Comment by lionel-** [comment]
On a practical level, if you have vectorised attributes the data can only be compared with record vectors:

```r
x <- new_vctr(list(list(foo = 1, bar = 2), list(foo = 1, bar = 3)))
y <- new_vctr(list(list(foo = 3, bar = 2), list(foo = 4, bar = 2)))

vec_compare(x, y)
#> Error: Can't compare lists with `vctrs_compare()`


x <- new_rcrd(list(foo = c(1, 1), bar = c(2, 3)))
y <- new_rcrd(list(foo = c(3, 4), bar = c(2, 2)))

vec_compare(x, y)
#> [1] -1 -1
```

Also the record vectors have the advantage of storing the data in contiguous memory. This allows vctrs to vectorise operations like equality or matching.
