### ISSUE TITLE
generic vctr class?

### ISSUE THREAD

**Issue by thebioengineer** [r-lib/vctrs#1162]
Hi there, 

I am working on a package [here](https://github.com/thebioengineer/colortable) that tries to apply styling to a vector across all sorts of outputs: console, html, word, pdf, etc. However, the actual content of the vector I don't care about. It could be a numeric, character, etc.. 

![image](https://user-images.githubusercontent.com/22481467/85359697-d7cb3100-b4cb-11ea-8dc7-2e95cbc00fce.png)

I want the contents to comply with with how {vctrs} merges vectors for stability and it seems like in order for it to work nicely with tidyverse, I need to move over to {vctrs}. I have this all implemented in base R but it does nto respect my subsetting. Would it be possible to have a vctr that is "generic", where any atomic vector would be an option or is that in direct opposition of this package where we clearly pre-define our inputs and transformations?

**Comment by lionel-** [comment]
Not currently, but this is tracked in #1080. It will take a while though.

**Comment by lionel-** [comment]
Just to be clear, you can get most of the way there by implementing coercion methods for your class with the most common classes. In the future you might be able to avoid this work and have a more general solution.

**Comment by thebioengineer** [comment]
thanks for the reply @lionel- ! So I have set up casting to and from the vctrs, (doubles, character, etc) into a color_vctr, but my question has do do if I have a color_vctr containing a character, and another containing a numeric, how to tell vec_c to behave. -> should there now be a "triple dispatch" for the under-the-hood behavior?

ie. `vec_c(color_vctr(1:5, text_color="orange"), color_vctr(LETTERS, text_color=rainbow(26)))` 

color_vctr is a vctr_rcrd. how does {vctrs} handle it when it is combining a field with different contents?

**Comment by lionel-** [comment]
ah good point! The trick is to call `vec_ptype2()` again, after unclassing your color object. See https://github.com/tidyverse/haven/blob/7a0d9f7d3ebe4f04572ce72df30ebfaf6edca6c5/R/labelled.R#L209 for an example.

**Comment by thebioengineer** [comment]
Hey, I implemented this in my vec_cast.color_vctr.color_vctr casting, so that I should be able to get a stable type when I combine vctrs.

```r
vec_cast.color_vctr.color_vctr <- function(x, to, ...) {
  data_type <- vec_ptype2(field(x,"vctr"), field(to,"vctr"))
 color_vctr(
   data_type,
   text_color = field(x, ".text_color"),
   background = field(x, ".background"),
   style = field(x, ".style")
 )
}
```

When I try to do a vec_c between a numeric and integer, I get:
![image](https://user-images.githubusercontent.com/22481467/85422265-42ab5500-b52a-11ea-8864-1014bb95604c.png)

I did a browser, it looks like color_vctr() is used in the "to", not what I would expect which would be the other color_vctr. Unless I am missing something?

**Comment by lionel-** [comment]
(you should pass `...` to the inner `vec_ptype2()` call)

That is strange, can you post a minimal reprex please?

**Comment by thebioengineer** [comment]
I will see what I can do to reproduce this!

**Comment by thebioengineer** [comment]
I just realized I was editing the vec_cast, not vec_ptype2.color_vctr.color.vtcr 🤦

**Comment by thebioengineer** [comment]
Thank you @lionel- for your time! I was indeed able to apply the method used in haven to get the desired behavior. I actually was wondering if it would be possible to apply that same idea to all of my `vec_ptype2` functions since my goal would be to have any vector that is being "added" to my color_vctr to then become one. Right now you manually have to define each vec_ptype2, but would it be possible to do a `vec_ptype2.color_vctr.*` and like a `vec_ptype2.*.colorvctr`? 

To wrap this story up, When I went to the casting, I then implemented the following, and now it works for any sort of vector that is internal. not sure if this will help with #1080, but I thought I might offer up my solution:

```r
vec_cast.color_vctr.color_vctr <- function(x, to, ...) {
  coerce_color_vctr(x, to)
}
coerce_color_vctr <- function(x, to){
  text_color <- field(x, ".text_color")
  background <- field(x, ".background")
  style <- field(x, ".style")
  x <- field(x, "vctr")
  x <- vec_c(x, get_ptype2(x, to))
  color_vctr(x, text_color = text_color, background = background, style = style)
}
```

in order to get any incoming vectors to a color_vctr properly:

```r
vec_cast.double.color_vctr <- function(x, to, ... ) coerce_color_vctr(x, to)
vec_cast.color_vctr.double <- function(x, to, ... ) coerce_to_color_vctr(x, to)

coerce_to_color_vctr <- function(x, to){
  x <- vec_cast(x, get_ptype2(x, to))
  color_vctr(x)
}
```

Example:
I applied this method across all my types as well, and it looks to work. except for cases where I have not defined the casting. For example, this is the {hms} library, that I can wrap into a color_vctr, and two color_vctrs containing an hms object are perfectly happy. But coercing an hms throws an error since I don't have a ptype and casting defined.

![image](https://user-images.githubusercontent.com/22481467/85826876-e9197500-b739-11ea-97a6-7934d49037c0.png)

**Comment by lionel-** [comment]
> Right now you manually have to define each vec_ptype2, but would it be possible to do a vec_ptype2.color_vctr.* and like a vec_ptype2.*.colorvctr?

Not currently, this is the issue I linked about in https://github.com/r-lib/vctrs/issues/1162#issuecomment-647930750
