### ISSUE TITLE
Feature Request: Add tolerance control to integer maybe_lossy_cast()

### ISSUE THREAD

**Issue by billdenney** [r-lib/vctrs#1163]
When casting from double to integer, it would help to have a tolerance argument.  I often load data from sources with less-than-perfect fidelity (e.g. MS Excel files) where integers have floating point error introduced as part of the file format.  (e.g. something like 0.2 => 0.2000000002 commonly appears).

It would help if `maybe_lossy_cast()` for the `.integer` casts would accept a tolerance argument to allow something intermediate between completely permissive casting with `allow_lossy_cast()` and the loss of `loss_type="precision"`

I think that this would take the form of an argument like `tol_integer=0` where `tol_integer` would be a double between 0 (current behavior) and 1 (completely permissive, the equivalent of `allow_lossy_cast()`).

Also, `maybe_lossy_cast(... loss_type="precision")` does not appear to allow loss of precision in a double-to-integer cast (see the last line of the reprex):

``` r
library(vctrs)
vec_cast(c(NA, 1, 1.1), to=integer())
#> Error: Can't convert from <double> to <integer> due to loss of precision.
#> * Locations: 3
allow_lossy_cast(vec_cast(c(NA, 1, 1.1), to=integer()))
#> [1] NA  1  1
maybe_lossy_cast(vctrs::vec_cast(c(NA, 1, 1.1), to=integer()), loss_type="precision")
#> Error: Can't convert from <double> to <integer> due to loss of precision.
#> * Locations: 3
```

<sup>Created on 2020-06-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
We don't currently allow passing arguments to methods, so we're unlikely to make that change soon. But coercion is not for cleaning data, I think the best thing to do is to preprocess your data to make sure it uses the correct types before you start using it.
