### ISSUE TITLE
Should vec_type2.factor.factor return sorted levels?

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#118]
Right now, this behavior occurs which is somewhat consistent with the hacky way you can combine factors in base R.

``` r
library(vctrs)

fct1 <- factor(c("a", "b"))
fct2 <- factor(c("b", "c"))

vec_type2(fct1, fct2)
#> factor(0)
#> Levels: a b c
vec_type2(fct2, fct1)
#> factor(0)
#> Levels: b c a

# base R behavior
# this is the only way to combine them?
unlist(list(fct1, fct2))
#> [1] a b b c
#> Levels: a b c
unlist(list(fct2, fct1))
#> [1] b c a b
#> Levels: b c a

# this doesnt work
c(fct1, fct2)
#> [1] 1 2 1 2
```

But with `vec_type2()`, you are creating a "new" common type from the underlying types. One could argue that the new type could follow the same procedure that a factor takes when being created from a character vector, sorting levels alphabetically:

```r
# a "fresh" factor has sorted levels
factor(c("b", "a"))
#> [1] b a
#> Levels: a b
```

This would make `vec_type2(fct1, fct2) = vec_type2(fct2, fct1)` in this example. It would require `levels_union()` to sort the levels.

I'm not particularly tied to either implementation, but @topepo mentioned that he thinks it might be more consistent with base R to sort them

**Comment by jennybc** [comment]
Well, you can get base R to catenate factors, but only if they live in a data frame.

``` r
fct1 <- factor(c("a", "b"))
fct2 <- factor(c("b", "c"))
df <- rbind(
  data.frame(x = fct1),
  data.frame(x = fct2)
)
str(df)
#> 'data.frame':    4 obs. of  1 variable:
#>  $ x: Factor w/ 3 levels "a","b","c": 1 2 2 3

df2 <- rbind(
  data.frame(x = fct2),
  data.frame(x = fct1)
)
str(df2)
#> 'data.frame':    4 obs. of  1 variable:
#>  $ x: Factor w/ 3 levels "b","c","a": 1 2 3 1
```

<sup>Created on 2018-10-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jennybc** [comment]
> sorting levels alphabetically

I've always thought a default of "in the order in which they appear" makes more sense than alphabetical. It also has this property that if feels like an emerging standard/principle: the result doesn't depend on the locale. But yeah, now it means that the order of the inputs matters.

**Comment by DavisVaughan** [comment]
Maybe this should be relaxed a little?
https://vctrs.r-lib.org/articles/double-dispatch.html

> In order to preserve commutativity, `vec_type2.x.y()` __must__ return the same value as `vec_type2.y.x()`. Unfortunately there’s no way to enforce this at the language level, so instead we use strong conventions (always defining the pair of methods next to each other) and unit tests to make sure that we’re consistent.

**Comment by hadley** [comment]
We're definitely not sorting.  It's only the class that has to be commutative, not the parameters (that's mentioned somewhere in the docs, and will be more prominent after I polish them)
