### ISSUE TITLE
vec_rbind(<table with numeric values>)

### ISSUE THREAD

**Issue by romainfrancois** [r-lib/vctrs#1190]
``` r
library(vctrs)

vec_rbind(
  table(c(1, 2)) / 2, 
  table(c(1, 2)) / 2
)
#> Error: Internal error in `vec_proxy_assign_opts()`: `proxy` of type `integer` incompatible with `value` proxy of type `double`.
#> Backtrace:
#>     █
#>  1. └─vctrs::vec_rbind(table(c(1, 2))/2, table(c(1, 2))/2)
#>  2.   └─(function () ...
```

<sup>Created on 2020-07-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

This is the root cause of https://github.com/keyATM/keyATM/pull/145, mentioned in https://github.com/tidyverse/dplyr/issues/5376. 

In https://github.com/keyATM/keyATM/pull/145, I propose a solution that works around it by essentially cancelling the "tableness" of the object as I presume it's not useful. I'm not sure we would want to cover objects like: 

``` r
str(table(c(1, 2)) / 2)
#>  'table' num [1:2(1d)] 0.5 0.5
#>  - attr(*, "dimnames")=List of 1
#>   ..$ : chr [1:2] "1" "2"
```

<sup>Created on 2020-07-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

but the error message was not helpful in https://github.com/keyATM/keyATM/pull/145

**Comment by DavisVaughan** [comment]
I just learned that `summary()` creates subclassed `"table"`s, which can be numeric, so it definitely isn't just used for integer contingency tables, even though the docs state:

```
table() returns a contingency table, an object of class "table", an array of integer values.
```

``` r
x <- summary(mtcars$mpg)

class(x)
#> [1] "summaryDefault" "table"

x
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>   10.40   15.43   19.20   20.09   22.80   33.90
```

<sup>Created on 2020-07-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

It seems to be more like a wrapper type around integer / numeric arrays
