### ISSUE TITLE
Add function to show prototype constructor

### ISSUE THREAD

**Issue by mgirlich** [r-lib/vctrs#1191]
In functions that guess the prototype e.g. with `vec_ptype_common` it would be great to be able to print the constructor instead of only the prototype itself. For example in the following code

``` r
df <- tidyr::tibble(x = list(list(a = 1L), list(a = 0.5)))

tidyr::hoist(
  df,
  "x",
  "a"
)
#> # A tibble: 2 x 1
#>       a
#>   <dbl>
#> 1   1  
#> 2   0.5
```

<sup>Created on 2020-07-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

it would be nice to help the user with useable code (e.g. like in `dplyr::left_join()`) for the `.ptype` argument, e.g. something like

```
Use
  .ptype = list(
    a = double()
  )
to be explicit about the prototypes
```

With `vec_ptype_full()` one gets a nicely printable prototype but one cannot use the text directly in code. So adding a function `vec_ptype_constructor()` would be a useful addition.

**Comment by lionel-** [comment]
This is currently not possible in a generic way because we have no way of figuring out what the constructor of an arbitrary type is. We might add more introspection generics for types, but this is not planned yet.
