### ISSUE TITLE
vec_slice(<POSIXct>) and attributes order

### ISSUE THREAD

**Issue by romainfrancois** [r-lib/vctrs#1204]
``` r
library(vctrs)

time1 <- as.POSIXct("2001-01-01 01:01:01")
time2 <- vec_slice(time1, 1)
attributes(time1)
#> $class
#> [1] "POSIXct" "POSIXt" 
#> 
#> $tzone
#> [1] ""
attributes(time2)
#> $tzone
#> [1] ""
#> 
#> $class
#> [1] "POSIXct" "POSIXt"
```

<sup>Created on 2020-07-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

originally from @nacnudus in https://github.com/nacnudus/unpivotr/issues/39

**Comment by lionel-** [comment]
I'm not sure this is a bug.

**Comment by lionel-** [comment]
Let's assume this is not a bug for now, but please let us know if this causes more trouble.
