### ISSUE TITLE
Records with fields of type list and [[

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#1205]
I think both should be identical. Probably there's a similar problem with `[[<-` . Happy to send a PR.

``` r
library(vctrs)

xx <- new_rcrd(list(x = 1:3, a = list(1, 2:3, 4:6)))
field(xx[3], "a")
#> [[1]]
#> [1] 4 5 6
field(xx[[3]], "a")
#> [1] 4 5 6
```

<sup>Created on 2020-08-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
Fixed by #1224 but I'll add your example as unit test just to be sure it's covered.
