### ISSUE TITLE
Pivot text data in R from columns to row

### ISSUE THREAD

**Issue by MontanaCabana** [r-lib/vctrs#1211]
I have a problem trying to pivot text data in R from columns to rows.  The data has numeric and text columns but the text columns won't pivot?  I am using dplyr but will use anything that works?

Code
long=pivot_longer(original, c('Col1','Col2','Col3' ))

![image](https://user-images.githubusercontent.com/29814809/89528728-6d542300-d7e3-11ea-8276-b95ea7a76d7c.png)
 
[pivot_.xlsx](https://github.com/r-lib/vctrs/files/5034594/pivot_.xlsx)

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
