### ISSUE TITLE
Some vctrs-based classes not formatted in RStudio notebook chunk output

### ISSUE THREAD

**Issue by davidchall** [r-lib/vctrs#1212]
It seems vector classes based on `new_rcrd()` and `new_list_of()` don't format nicely in the RStudio notebook chunk output (even though they do format correctly in RStudio's Data Viewer).

<img width="396" alt="image" src="https://user-images.githubusercontent.com/1804856/89473447-b5b60700-d737-11ea-9a9a-f8f093b77d37.png">

I'm not sure if this is something that can be fixed from the {vctrs} end, or if this can only be fixed in the RStudio code. But I thought it's probably still good to get this on your radar.

Here's a description of what I think might be going wrong: https://github.com/rstudio/rstudio/issues/6878#issuecomment-669598714

**Comment by lionel-** [comment]
I _think_ this will have to be fixed in RStudio.

@romainfrancois Could you take a look at the linked issue please?
