### ISSUE TITLE
Should `vec_set_names(array, NULL)` simplify the array attributes?

### ISSUE THREAD

**Issue by lionel-** [r-lib/vctrs#1221]
This would be consistent with `names(x) <- NULL` and with arrays created without names:

```r
x <- matrix(1:4, 2)
row.names(x) <- c("foo", "bar")
exp <- list(
  foo = matrix(c(1L, 3L), 1),
  bar = matrix(c(2L, 4L), 1)
)
expect_identical(vec_chop2(x), exp)
#> Error: vec_chop2(x) not identical to `exp`.
#> Component “foo”: Attributes: < Length mismatch: comparison on first 1 components >
#> Component “bar”: Attributes: < Length mismatch: comparison on first 1 components >

attributes(vec_chop2(x)[[1]])
#> $dim
#> [1] 1 2
#>
#> $dimnames
#> $dimnames[[1]]
#> NULL
#>
#> $dimnames[[2]]
#> NULL

attributes(exp[[1]])
#> $dim
#> [1] 1 2
```

**Comment by DavisVaughan** [comment]
I don't think so. I think we should be consistent with `row.names<-` for arrays, which doesn't simplify.

Otherwise you have to check if you can simplify, which would require looping through all `dimnames` except the first to check if they are all `NULL`.

``` r
x <- matrix(1:4, 2)

row.names(x) <- c("foo", "bar")
attributes(x)
#> $dim
#> [1] 2 2
#> 
#> $dimnames
#> $dimnames[[1]]
#> [1] "foo" "bar"
#> 
#> $dimnames[[2]]
#> NULL

row.names(x) <- NULL
attributes(x)
#> $dim
#> [1] 2 2
#> 
#> $dimnames
#> $dimnames[[1]]
#> NULL
#> 
#> $dimnames[[2]]
#> NULL
```

<sup>Created on 2020-08-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by DavisVaughan** [comment]
If we made this change, we'd get the following results, which I'm not sure I like because it feels a little less consistent than the current behavior.

```r
x <- matrix(1:4, 2)

row.names(x) <- c("foo", "bar")

dimnames(vec_set_names(x, NULL))
# NULL

colnames(x) <- c("c1", "c2")

dimnames(vec_set_names(x, NULL))
# [[1]]
# NULL
# 
# [[2]]
# [1] "c1" "c2"
```

**Comment by lionel-** [comment]
I don't think we need consistency with `row.names<-`?

I was thinking the loop should be fairly quick, most of the time there's only 2 or 3 dimensions. It doesn't seem like it would pose a performance issue.

**Comment by lionel-** [comment]
> If we made this change, we'd get the following results, which I'm not sure I like because it feels a little less consistent (in the return value) than the current behavior.

Since `matrix(1:4, 2)` has NULL `dimnames()`, the output you show seems like the right behaviour.

**Comment by lionel-** [comment]
I don't think it's a big deal, it would mostly simplifies unit tests. So if you're not comfortable with this we can close.
