### ISSUE TITLE
vctrs not available on CRAN

### ISSUE THREAD

**Issue by pieterjanvc** [r-lib/vctrs#1240]
Hello,

Through a [post](https://community.rstudio.com/t/helping-with-installation-of-tidyverse-package/78466/2) at the RStudio Community Forum I found out that the vctrs package in not available anymore on CRAN. Is this intentional, or an error? It leads to issues when users try to install Tidyverse because it's a dependency.

PJ

**Comment by Jojolafin** [comment]
I am facing the same issues.

> install.packages("dplyr")
also installing the dependency ‘vctrs’

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/vctrs_0.3.4.zip'
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/vctrs_0.3.4.zip': HTTP status was '404 Not Found'

my R version:

R version 4.0.2 (2020-06-22) -- "Taking Off Again"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

**Comment by pieterjanvc** [comment]
Please read the [post](https://community.rstudio.com/t/helping-with-installation-of-tidyverse-package/78466) at the RStudio Community Forum for updates on how to bypass the issue before it gets fixed.

**Comment by lionel-** [comment]
See https://github.com/r-lib/vctrs/issues/1234#issuecomment-685686347

```r
install.packages("vctrs", repos = "https://packagemanager.rstudio.com/cran/latest")
```
