### ISSUE TITLE
License s3_register with unlicense

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#1254]
https://choosealicense.com/licenses/unlicense/ — to make it very clear that it's fine to copy and paste the source code into your package.  I think this just needs a comment in the code and new section in the documentation that emphasises that we expect you to copy and paste into your package, and the function is licensed to make that as easy as possible.

**Comment by maxheld83** [comment]
IANAL, but there appear to be [some problems](https://softwareengineering.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense) with the unlicense; the [FSF](https://www.gnu.org/licenses/license-list.en.html#Unlicense) and [Fedora Project](https://fedoraproject.org/wiki/Licensing/Unlicense) recommend using [CC0](https://creativecommons.org/publicdomain/zero/1.0/) instead.

Unlicense is in PR #1254, happy to update with CC0.
