### ISSUE TITLE
Re-license as MIT

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#1259]
I have reviewed all non-RStudio [contributors](https://github.com/r-lib/vctrs/graphs/contributors). I think the following contribution[s] are significant enough to merit a potential copyright claim:
    
* [x] [those made](https://github.com/r-lib/vctrs/commits?author=yutannihilation) by @yutannihilation  
* [x] [those made](https://github.com/r-lib/vctrs/commits?author=808sAndBR) by @808sAndBR  
* [x] [those made](https://github.com/r-lib/vctrs/commits?author=echasnovski) by @echasnovski  

@yutannihilation, @808sAndBR, @echasnovski, would you permit us to relicense vctrs with the MIT license? This is part of a general effort to make the licensing across r-lib and tidyverse as simple and consistent as possible. If so, please comment "I agree" below.

**Comment by echasnovski** [comment]
I agree.

(Actually, I was surprised that it wasn't MIT.)

**Comment by yutannihilation** [comment]
I agree.

**Comment by 808sAndBR** [comment]
I agree.

**Comment by hadley** [comment]
Thanks all!
