### ISSUE TITLE
Request: add a proxy method for ts objects

### ISSUE THREAD

**Issue by TylerGrantSmith** [r-lib/vctrs#1264]
I am not sure if this is something best handled by `vctrs`, but I was looking at some `tibble` output and noticed that `ts` columns display the type and traced the `format` code down to `vec_slice` being called on the `ts` object, which defaults to using stats:::`[.ts` which has the unfortunate side-effect of returning a vector of the underlying type.

``` r
tibble::tibble(x = ts())
#> # A tibble: 1 x 1
#>   x    
#>   <lgl>
#> 1 NA
tibble::tibble(x = ts(1))
#> # A tibble: 1 x 1
#>       x
#>   <dbl>
#> 1     1
str(vctrs::vec_slice(ts(1),1))
#>  num 1
```
In the case where the column is an `mts` object, it seems like the stats:::`[.ts` method isn't called and an expected result gets returned:

``` r
vctrs::vec_slice(ts(matrix(c(1,1),ncol = 2)), 1)
#> Time Series:
#> Start = 1 
#> End = 1 
#> Frequency = 1 
#>   Series 1 Series 2
#> 1        1        1
```

**Comment by lionel-** [comment]
Sorry that's not on the agenda right now :(
