### ISSUE TITLE
Unexpected behavior of names with vctrs_vctr objects

### ISSUE THREAD

**Issue by TylerGrantSmith** [r-lib/vctrs#1268]
I'm not sure if this belongs here or in the `dplyr` or `tibble` repos, but I am posting here because ultimately it is the opinionated behavior of names assignment to `vctrs_vctr` objects that causes the problem. 

Is the following expected behavior?

``` r
library(magrittr)
x <- tibble::tibble(a = c(1, NA), b = c(1, 2))
# error because `names<-.vctrs_vctr` requires all names be != "" and not NA
x %>% dplyr::group_nest(a) %>% tibble::deframe()
#> Error: If any elements are named, all elements must be named.
# what I expect
x %>% dplyr::group_nest(a) %>% dplyr::mutate(data = as.list(data)) %>% tibble::deframe()
#> $`1`
#> # A tibble: 1 x 1
#>       b
#>   <dbl>
#> 1     1
#> 
#> $<NA>
#> # A tibble: 1 x 1
#>       b
#>   <dbl>
#> 1     2
# what I expect
x %>% tidyr::nest(data = -a) %>% tibble::deframe()
#> $`1`
#> # A tibble: 1 x 1
#>       b
#>   <dbl>
#> 1     1
#> 
#> $<NA>
#> # A tibble: 1 x 1
#>       b
#>   <dbl>
#> 1     2
```

<sup>Created on 2020-09-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
Personally I think we should lift this restriction. We'll revisit for the next non-patch version of vctrs (a few months down the line).

**Comment by DavisVaughan** [comment]
I think disallowing `NA_character_` as a name is still a good idea - we never allow it to be a valid name anywhere else in the tidyverse AFAIK

I do think we should allow `""` as a name, which is what https://github.com/r-lib/vctrs/pull/784 does

**Comment by DavisVaughan** [comment]
More motivation to not allow `NA_character_` as a name https://github.com/r-lib/vctrs/issues/780#issuecomment-590985524

**Comment by lionel-** [comment]
I was thinking about `""`. We should also consider whether `NA` should be an error or should be converted to `""` silently.
