### ISSUE TITLE
vec_rbind doesn't use .ptype for type coercion?

### ISSUE THREAD

**Issue by mmuurr** [r-lib/vctrs#1273]
Was reading this issue (https://github.com/tidyverse/dplyr/issues/4281) and saw @romainfrancois's example, which doesn't seem to be working for me (using the most recent vctrs release):
```R
library(dplyr)
library(vctrs)
mtcars_char <- mtcars %>% mutate(mpg = as.character(mpg))
vec_rbind(mtcars, mtcars_char, .ptype = mtcars)
```
Is this behavior implemented in vctrs yet? With v0.3.4, I get this output for the example above:
```
 Error: Can't convert `$mpg` <character> to match type of `$mpg` <double>.
 Run `rlang::last_error()` to see where the error occurred.
```
Or perhaps the previously-mentioned behavior in that issue was rolled-back?

<details><summary>Session Info:</summary>
<pre>
 R version 3.6.3 (2020-02-29)
 Platform: x86_64-apple-darwin19.4.0 (64-bit)
 Running under: macOS Catalina 10.15.3

 Matrix products: default
 BLAS/LAPACK: /usr/local/Cellar/openblas/0.3.10_1/lib/libopenblasp-r0.3.10.dylib

 locale:
 [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

 attached base packages:
 [1] stats     graphics  grDevices datasets  utils     methods   base

 other attached packages:
 [1] vctrs_0.3.4 dplyr_1.0.0

 loaded via a namespace (and not attached):
  [1] crayon_1.3.4     R6_2.4.1         lifecycle_0.2.0  magrittr_1.5     pillar_1.4.6     rlang_0.4.7
  [7] renv_0.11.0      generics_0.0.2   ellipsis_0.3.1   tools_3.6.3      glue_1.4.1       purrr_0.3.4
 [13] compiler_3.6.3   pkgconfig_2.0.3  tidyselect_1.1.0 tibble_3.0.3
</pre>
</details>

**Comment by lionel-** [comment]
In the tidyverse coercions between character and numeric are disallowed. Using `as.integer()` instead of `as.character()` fixes the common type error.

**Comment by mmuurr** [comment]
@lionel- Is there documentation somewhere on these rules? E.g. what's allowed, and in which direction? As an example, if you invert the `.ptype` argument above (i.e. `.ptype = mtcars_char` and thus try to coerce a `double` to a `character`), an error is still raised. (Which is surprising to me, since floating-points can always be represented by strings _somehow_, though perhaps we need explicit formatting?)

**Comment by lionel-** [comment]
There is some documentation in https://vctrs.r-lib.org/reference/faq-compatibility-types.html

> Which is surprising to me, since floating-points can always be represented by strings somehow, though perhaps we need explicit formatting?

They represent different sorts of data. Turning a number into a string is a deparsing/serialising operation rather than a coercion.
