### ISSUE TITLE
Reconsider a `vec_proxy_complete()` proxy

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#1276]
In #1250 I mentioned that a `vec_proxy_complete()` proxy would ease implementation of `df_detect_complete()`. The current implementation of `df_detect_complete()` is rather complicated because we can't use `vec_proxy_equal()`. We can't use it because we want to special case classes like rcrds that have a df equality proxy to ensure that they are only considered "incomplete" if ALL values in a row are missing. This is at odds with what `df_detect_complete()` normally does with data frames, which is to consider them incomplete if ANY values in a row are missing. This keeps us from using `vec_proxy_equal()` because that flattens df-cols, so we lose the distinction between columns that came from a rcrd, and columns that came from a normal data frame.

https://github.com/r-lib/vctrs/pull/1250#discussion_r487110134

As it turns out, `df_detect_complete()` isn't the only place where we use the idea of "competeness". It is also used in this `p_df_is_missing()` function that is used by `vec_match(na_equal = FALSE)` and `vec_in(na_equal = FALSE)`.

https://github.com/r-lib/vctrs/blob/0263587907dcf2236d715cf6746a7e816caea244/src/dictionary.c#L102-L116

This function would be more properly called `p_df_is_incomplete()`, as it early exits at the first missing value. This gives us this `vec_match()` behavior, where we return `NA` if any `needle` row value is missing, which I _think_ we want?

``` r
library(vctrs)

df <- data_frame(x = 1, y = c(2, NA))
df
#>   x  y
#> 1 1  2
#> 2 1 NA

vec_match(df, df, na_equal = FALSE)
#> [1]  1 NA
```

However, it suffers from the same problem that `df_detect_complete()` had to work around with rcrd types. If a rcrd col has any `NA` value in a particular row, that entire row is considered incomplete, which we don't want:

```r
library(vctrs)

# row 1 is missing, row 2 is not
rcrd <- new_rcrd(list(a = c(NA, 1), b = c(NA, NA)))

df <- data_frame(x = 1:2, y = rcrd)

# flattens df-cols, but now we can't tell that cols `a` and `b` must be jointly
# missing to be considered incomplete
vec_proxy_equal(df)
#>   x  a  b
#> 1 1 NA NA
#> 2 2  1 NA

# says that both rows are missing, which isn't right
vec_match(df, df, na_equal = FALSE)
#> [1] NA NA

# alternative proxy that defaults to `vec_proxy_equal()`,
# but allows customization for things like rcrds
vec_proxy_complete.vctrs_rcrd <- function(x) {
  proxy <- vector(length = vec_size(x))
  incomplete <- vec_equal_na(x)
  proxy[incomplete] <- NA
  proxy
}

df2 <- df
df2$y <- vec_proxy_complete.vctrs_rcrd(df2$y)

vec_match(df2, df2, na_equal = FALSE)
#> [1] NA  2
```

One of two things could solve this:

1. It is possible `vec_match()` should work off missingness rather than completeness (as it currently attempts to do). In this case, we just need to change `p_df_is_missing()` to only return `true` if the entire row is missing

2. A `vec_proxy_complete()` proxy could be used, which would let us flatten data frames and still have correct results since we can write a custom method for vctrs_rcrd. This would also simplify `df_detect_complete()` greatly

**Comment by lionel-** [comment]
We should try our best to avoid adding new proxies to the public API. I still think we can just condition on whether the input vector inherits from data.frame. We could have an internal helper function that does this special-casing, if it helps.

```r
vec_proxy_complete <- function(x) {
  if (inherits(x, "data.frame")) {
    ... 
  } else {
    ...
  }
}
```

Conceptually this would just preprocess the proxy in an additional step. It avoids a customisation point and relies on the current heuristic instead (record proxies of non-data-frame types are missing if the whole row is missing, otherwise they are complete). It could be extended to support matrices and arrays.

**Comment by DavisVaughan** [comment]
Possibly something like this would work:

``` r
library(vctrs)

vec_proxy_complete <- function(x) {
  if (is.data.frame(x)) {
    return(df_proxy_complete(x))
  }
  
  proxy <- vec_proxy_equal(x)
  
  # Arrays have stopgap data frame proxies,
  # but their completeness rules match data frames
  if (vctrs:::has_dim(x)) {
    return(proxy)
  }
  
  # i.e. vctrs_rcrd, special case with a heuristic that these
  # rows are "complete" if any column in that row has a non-missing value
  if (is.data.frame(proxy)) {
    incomplete <- vec_equal_na(proxy)
    proxy <- logical(vec_size(proxy))
    proxy <- vec_assign(proxy, incomplete, NA)
  }
  
  proxy
}

df_proxy_complete <- function(x) {
  x[] <- lapply(x, vec_proxy_complete)
  x <- .Call(vctrs:::vctrs_df_flatten, x)
  # also proxy unwrap
  x
}

rcrd <- new_rcrd(list(a = c(NA, 1), b = c(NA, NA)))
dfcol <- data_frame(c = 1:2, d = 3:4)

df <- data_frame(x = 1:2, y = rcrd, z = dfcol)

vec_proxy_complete(rcrd)
#> [1]    NA FALSE
vec_proxy_complete(df)
#>   x     y c d
#> 1 1    NA 1 3
#> 2 2 FALSE 2 4
```

<sup>Created on 2020-10-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
