### ISSUE TITLE
Unclear instructions on roxygen2 method documentation in S3 vector vignette

### ISSUE THREAD

**Issue by joeroe** [r-lib/vctrs#1287]
The "Other helpers" section in the current version of the S3 vector vignette (https://vctrs.r-lib.org/articles/s3-vector.html#other-helpers-1) says:

> The exact same roxygen2 treatment is needed for vec_cast(), which yields:

And the following code block includes:

```r
#' @method vec_cast.double pizza_percent
#' @export
vec_cast.double.pizza_percent <- function(x, to, ...) vec_data(x)
```

Reading this I was confused about what the "same roxygen2 treatment" referred to, and whether the `@method` tag was needed since it is only mentioned for that one function. But presumably these two lines are just left over from 29373a2383cea9d17637469a2ebea5af33e813bd, which removed all other mentions of that tag?

**Comment by lionel-** [comment]
oops this documentation seems outdated. Nowadays you can just use `#' @export` like any other S3 methods.

**Comment by joeroe** [comment]
Does that apply to all methods? I ask because, using vctrs 0.3.4, I was unable to get double dispatch working with vec_arith unless I added `@method` tags, so perhaps some documentation is still needed there? Just using `#' @export` worked fine for vec_ptype2, vec_cast, and vec_math.

**Comment by DavisVaughan** [comment]
You are correct, vec-arith currently still works the old way where you have to use `@method`. In the future that will likely change to also just being able to `@export` it
