### ISSUE TITLE
Should vctrs export vec_arith.integer() and vec_arith.double() generics?

### ISSUE THREAD

**Issue by davidchall** [r-lib/vctrs#1288]
According to the "S3 vectors" vignette section on `vec_arith()` ([see here](https://vctrs.r-lib.org/articles/s3-vector.html#meter-class-1)):
> To support both doubles and integers as operands, we dispatch over numeric here instead of double.

I see that vctrs exports the `vec_arith.numeric()` generic for this purpose. However, if you want different behavior for doubles and integers, then I think you'd need generics for `vec_arith.double()` and `vec_arith.integer()`.

I could just define these generics in my own package, but since these are base types I wanted to check if they should exist in vctrs instead? (Also please let me know if I've misunderstood something about how `vec_arith()` is intended to be used.) 

Thanks!

**Comment by davidchall** [comment]
To be explicit, locally I've been using:

```r
#' @export vec_arith.integer
#' @method vec_arith integer
#' @export
vec_arith.integer <- function(op, x, y, ...) UseMethod("vec_arith.integer", y)

#' @method vec_arith.integer default
#' @export
vec_arith.integer.default <- function(op, x, y, ...) vec_arith.numeric(op, x, y)
```

@DavisVaughan - I just noticed that you have a related PR (https://github.com/r-lib/vctrs/pull/1241). There you mention you "don't think we want to export `vec_arith.integer` or `vec_arith.double`". When you have some time, would you be willing to elaborate? (it seems very relevant to what I'm trying to achieve). Thanks!

**Comment by DavisVaughan** [comment]
@davidchall `vec_arith()` is due for an overhaul that will make the way you register methods for it more like `vec_ptype2()` and `vec_cast()` (i.e. you should only need to use `@export`).

When that happens, you'll be able to do `vec_arith.integer.mytype` even if we don't export `vec_arith.integer`. That is what my comment was about in #1241 

For now, I think that you should just use `vec_arith.numeric`, switching internally on `integer` vs `double`. I can't make any promises on how quickly we will be able to get to the `vec_arith` overhaul

**Comment by davidchall** [comment]
Gotcha - that makes a lot of sense now!

And thanks for the advice about moving the branching logic into `vec_arith.numeric` 👍
