### ISSUE TITLE
na_equal = FALSE not respected in presence of non-ASCII strings?

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#1291]
``` r
df1 <- tibble::tibble(x = c(NA, "e"))
key <- vctrs::vec_group_loc(df1)
vctrs::vec_match(key$key, df1, na_equal = FALSE)
#> [1] NA  2

df1 <- tibble::tibble(x = c(NA, "é"))
key <- vctrs::vec_group_loc(df1)
vctrs::vec_match(key$key, df1, na_equal = FALSE)
#> [1] 1 2
```

<sup>Created on 2020-11-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

From https://github.com/tidyverse/dplyr/issues/5568

**Comment by DavisVaughan** [comment]
This looks fixed in the dev version!

``` r
df1 <- tibble::tibble(x = c(NA, "e"))
key <- vctrs::vec_group_loc(df1)
vctrs::vec_match(key$key, df1, na_equal = FALSE)
#> [1] NA  2

df1 <- tibble::tibble(x = c(NA, "é"))
key <- vctrs::vec_group_loc(df1)
vctrs::vec_match(key$key, df1, na_equal = FALSE)
#> [1] NA  2
```

<sup>Created on 2020-11-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

Probably something to do with the switch to `vctrs:::vec_normalize_encoding()`

Worth adding this as a test case though, ill do that.

**Comment by DavisVaughan** [comment]
For some reason the old `obj_maybe_translate_encoding()` was turning `NA_character_` into `"NA"`.

``` r
x <- c(NA, "é")
x
#> [1] NA  "é"

vctrs:::obj_maybe_translate_encoding(x)
#> [1] "NA" "é"
```

<sup>Created on 2020-11-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

The new `vec_normalize_encoding()` doesn't do that:

```r
x <- c(NA, "é")

Encoding(x)
#> [1] "unknown" "UTF-8"

vctrs:::vec_normalize_encoding(x)
#> [1] NA  "é"

y <- x
y <- iconv(y, "UTF-8", "latin1")

Encoding(y)
#> [1] "unknown" "latin1"

vctrs:::vec_normalize_encoding(y)
#> [1] NA  "é"
```
