### ISSUE TITLE
failure when combining vctrs with a quosure attribute

### ISSUE THREAD

**Issue by moodymudskipper** [r-lib/vctrs#1308]
See reprex below. The error mentions incompatible attributes, the provided link explains that this happens when attributes are different, but they're identical here.

``` r
new_foo <- function(x = character(), attr1 = rlang::new_quosure(quote(expr = ))) {
  vctrs::new_vctr(x, attr1 = attr1, class = "foo")
}
c(new_foo("a"), new_foo("b"))
#> Error: Can't combine `..1` <foo> and `..2` <foo>.
#> x Some attributes are incompatible.
#> i The author of the class should implement vctrs methods.
#> i See <https://vctrs.r-lib.org/reference/faq-error-incompatible-attributes.html>.
```

The same issue comes up if I use a non empty formula as the attribute.

If I store the expression and the environment in separate arguments or store both in a list it works fine.

``` r
new_foo <- function(x = character(), attr1 = quote(expr = ), env = .GlobalEnv) {
  vctrs::new_vctr(x, attr1 = attr1, env = env, class = "foo")
}
c(new_foo("a"), new_foo("b"))
#> <foo[2]>
#> [1] a b
```

**Comment by lionel-** [comment]
I am not sure what is causing this error since the quosures appear to be identical, but this will be low priority to fix. The default coercion method only works for identical attributes, so this error is to be expected as soon as you'll be storing different environments in attributes. In general, the first thing to do when creating a class is to implement self-coercion methods.

**Comment by moodymudskipper** [comment]
I understand. It's one of these things that's not hard to work around, but quite hard to debug. But my use case is probably very unusual so low priority makes sense.

**Comment by DavisVaughan** [comment]
> I am not sure what is causing this error since the quosures appear to be identical

I don't think they are identical. The expression to create `attr1` (`rlang::new_quosure(quote(expr = ))`) will be evaluated in the function env of `new_foo()`, so the quosure environments that get captured are different.

```r
new_foo <- function(x = character(), attr1 = rlang::new_quosure(quote(expr = ))) {
  vctrs::new_vctr(x, attr1 = attr1, class = "foo")
}

x <- new_foo()
y <- new_foo()

# environments are different
attr(x, "attr1")
#> <quosure>
#> expr: ^
#> env:  0x7ff8eb82cbf8
attr(y, "attr1")
#> <quosure>
#> expr: ^
#> env:  0x7ff8db943288

vctrs::vec_ptype2(x, x)
#> <foo[0]>

vctrs::vec_ptype2(x, y)
#> Error: Can't combine <foo> and <foo>.
#> x Some attributes are incompatible.
#> ℹ The author of the class should implement vctrs methods.
#> ℹ See <https://vctrs.r-lib.org/reference/faq-error-incompatible-attributes.html>.
```

I'm with @lionel- that generally you'll want to implement coercion methods pretty soon after creating a custom vctrs class.

**Comment by lionel-** [comment]
oh yes, good catch @DavisVaughan!
