### ISSUE TITLE
Error installing vctrs_0.3.6 in fastR due to undefined symbol STDVEC_DATAPTR

### ISSUE THREAD

**Issue by hsselman** [r-lib/vctrs#1310]
I posted an issue for this also with fastr (from GraalVM): https://github.com/oracle/fastr/issues/174

fastR is another implementation of R suitable to be used in GraalVM. GraalVM is a polyglot SDK to call for example on R or Python code from Java or Scala. 

I saw a similar issue with the installation of vctrs here: https://github.com/tidyverse/dplyr/issues/4448 (that was wrongly posted to dplyr). 

For the details of the error I encourage to read the issue on fastr: https://github.com/oracle/fastr/issues/174
If needed, I can copy-paste the same story here. 

Thanks in advance!

**Comment by lionel-** [comment]
I think fastr needs to implement support for ALTREP.

**Comment by hsselman** [comment]
Thanks for the direction for fastr to look in!
