### ISSUE TITLE
remove zeallot usage from vignettes, examples

### ISSUE THREAD

**Issue by maxheld83** [r-lib/vctrs#1313]
TL,DR: I'm volunteering to remove all `%<-%` usage from user-facing (examples, vignette) code.

Some of the vignette code chunks make use of the `%<-%` operator from [zeallot](https://github.com/r-lib/zeallot).

For example:

https://github.com/r-lib/vctrs/blob/41f841e1a86684cf6a5a56ad8c7747aaa5a781bc/vignettes/s3-vector.Rmd#L488-L500

This is very succinct, but it might confuse people trying to learn vctrs (it did trip me a up a bit):
- It's easy enough to forget the `library(zeallot)` at the beginning of the vignette.
- The zeallot operator may (as yet?) be unfamiliar for many.
- It's usage is orthogonal to vctrs, but this may not be readily apparent.

So, I was wondering whether it might make sense to remove it, and be a bit more verbose, to reduce the cognitive load for learners.

Happy to go through it and make a PR.

(this is somewhat related to #671, which moved the zeallot dependency to suggest; potentially, after this, it could be removed entirely).

(I ❤️ `%<-%`).

**Comment by lionel-** [comment]
Thanks for the suggestion. The alternative is a lot of unpacking or leave it packed and having to use `!!!`. Arguably the vignette is clearer without these extra operations. Let's leave it as is for now and revisit in the future.
