### ISSUE TITLE
Consider allowing `$` field access to record types

### ISSUE THREAD

**Issue by tzakharko** [r-lib/vctrs#1319]
The `rcrd` types are interesting as they mimic vector behavior but have internal components (fields). One of the design choices was to disallow the use of the idiomatic `$` operator for component access, relying on a custom `field()` access function instead. I am wondering whether the team would be open to reconsidering this decision and making `x$a` a synonym to `field(x, "a")`

Here are some motivating points:

1. `$` is an idiomatic way to access components of an aggregate type in R, one would expect it to "just work"

2.  `$` is not defined for atomic vectors in R, which means that implementing it for a subtype of vectors (`rcrds`) will not break any existing assumptions. There is already a precedent for this: `list()` which is a special type of a vector that supports `$` 

3. In another words, implementing `$` for `rcrd` will not change anything about it vector-like behavior, while not implementing `$` breaks assumptions one intuitively has about aggregate types in R

4. Having different accessor functions can make refactoring more complicated 

5. `field()` is not ergonomic and overly verbose if your code makes heavy use of `rcrds`

**Comment by lionel-** [comment]
I think it'd be inconsistent to have `$` index along a different dimension than `[`.

**Comment by lionel-** [comment]
Especially since rcrd vectors will be allowed to have names in the future. When (or if) this happens `$` will index rowwise.

**Comment by tzakharko** [comment]
> I think it'd be inconsistent to have `$` index along a different dimension than `[`.

Isn't there already a precedence for this with `data.frame()`? But yes, I understand your point... 

> Especially since rcrd vectors will be allowed to have names in the future. When (or if) this happens `$` will index rowwise.

Wouldn't that actually make the behavior incompatible with base R atomic vectors? Named atomic vectors cannot be indexed with `$`

One problem with R is that it is, well, messy, and a lot of the language hangs on some loosely defined (and frequently violated) conventions.  I always understood `$` an operator to access a component of an aggregate record, that's the only semantics that makes sense to me when I look at the behavior or lists and data frames. I think what makes this more confusing is the fact that lists in R can fulfill the role of both records and heterogeneous arrays.

Is `$` already used in `vctrs` somewhere and if yes, what is it's semantics?

**Comment by lionel-** [comment]
> Isn't there already a precedence for this with data.frame()?

No, `[` with a single argument indexes along columns, cosistently with `$`.

> Wouldn't that actually make the behavior incompatible with base R atomic vectors? Named atomic vectors cannot be indexed with $, you need to use [ or [[ with the name.

oh yes of course. It'd still make sense for record lists though.

**Comment by lionel-** [comment]
By the way, atomic vectors (and atomic records once they support names) can be indexed by name with `[[`, so that'd make it even weirder for `[[` and `$` to return different things:

```r
c(a = 1, b = 2)[["b"]]
```

Thanks for the suggestion though!
