### ISSUE TITLE
Row-binding date-arrays fails

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#1329]
``` r
x <- Sys.Date()
dim(x) <- 1
vctrs::vec_rbind(data.frame(x), data.frame(x))
#> Error: `vec_cast.Date.Date()` is implemented at C level.
#> This R function is purely indicative and should never be called.
```

<sup>Created on 2021-03-03 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

From https://github.com/tidyverse/dplyr/issues/5779

**Comment by DavisVaughan** [comment]
This has come up one other time, in tidyverse/dplyr#5525

I am pretty sure I'm of the camp that this should continue to not be supported, since Date, POSIXct, and factor were not designed to be matrices/arrays. For example, the print method doesn't respect `dim`, and `c/rbind()` strip the class. I show those examples here along with a link to a factor matrix SO question https://github.com/tidyverse/dplyr/issues/5525#issuecomment-690386782

This is probably the same underlying issue as https://github.com/r-lib/vctrs/issues/1290

In all cases, we could at least throw a more informative error message if we somehow saw `dim` on a Date, POSIXct, or factor

**Comment by hadley** [comment]
We should figure out how people are getting these things — if they're setting `dim()` themselves, I'm fine with just an error, but if it's some base R function we might consider stripping the dims with a warning.

**Comment by DavisVaughan** [comment]
Sounds good

#5525, at least, was manual setting of `dim()`

> I do not even remember why I had added that dimension statement in the code that made me stumble over the error message - it isn't needed and gone by now.

**Comment by romainfrancois** [comment]
Copying https://github.com/tidyverse/dplyr/issues/5844 from @cboettig

`bind_rows()` can unexpected fail with an opaque error when given data.frames containing a Date column that has been created from an array.  Here's the reprex:

``` r
time <- array(1:3)
time <- as.Date(time, origin=Sys.Date())
M <- data.frame(time = time)
dplyr::bind_rows(M,M)
#> Error: `vec_cast.Date.Date()` is implemented at C level.
#> This R function is purely indicative and should never be called.
```

<sup>Created on 2021-04-08 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

Note that array-structures are often returned by scientific data formats like netcdf (from `ncdf4::ncvar_get`), and after coercion via `as.Date()` (or `lubridate::as_date()`  appear to the user as perfectly valid `Date` class vectors, but are left with a hanging additional attribute, `dim`, on the vector.  It appears to be the presence of this extra attribute that causes the panic and the opaque and seemingly unrelated error that can be very difficult  to debug.  

Note also that `rbind` works fine in the above example.

**Comment by DavisVaughan** [comment]
tidyverse/dplyr#5779 uses data from this repo https://github.com/NOAA-EDAB/neus-atlantis/, which also seems to use {ncdf4} a lot, so I bet it is the same underlying issue. We should figure out why that package is returning dates as arrays

**Comment by lindsayplatt** [comment]
I just ran into this and am also using datetimes extracted from a NetCDF file using `ncdf4`. It seems like the temporary solution is to just strip out the `dim` attribute for the time vector _**before**_ it gets put into a dataframe, unless `ncdf4` updates its pattern. This works and doesn't seem to break anything that I am doing:

```r
time <- array(1:3)
dim(time) <- NULL # ADD THIS!
time2 <- as.Date(time, origin=Sys.Date())
M <- data.frame(time = time)
dplyr::bind_rows(M,M)
```

**Comment by lionel-** [comment]
@hadley @DavisVaughan To fix this and #1290, I think it'd be easier to just broadcast the shape attributes if any. Here is what this entails: https://github.com/r-lib/vctrs/commit/f432c332735859ad49172c0fb58b36dbdd9f5958.

With this change we get:

```r
x <- Sys.time() + c(1, 1e6)
dim(x) <- c(1, 2)
out <- vec_c(x, x)

out
#> [1] "2022-09-14 15:23:44 CEST" "2022-09-14 15:23:44 CEST"
#> [3] "2022-09-26 05:10:23 CEST" "2022-09-26 05:10:23 CEST"

dim(out)
#> [1] 2 2
```

**Comment by hadley** [comment]
If the fix is easy, I'm in favour of it. I assume we already get nice errors if the dimensions aren't compatbile?

**Comment by lionel-** [comment]
yup:

```r
y <- Sys.time() + 1:3
dim(y) <- c(1, 3)
vec_c(x, y)
#> Error:
#> ! Can't combine `..1` <datetime<local>> and `..2` <datetime<local>>.
#> ✖ Incompatible sizes 2 and 3 along axis 2.
```
