### ISSUE TITLE
Use `...` not `i` in `[[<-.vctrs_vctr`

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#133]
Currently, you are using 

```
`[[<-.vctrs_vctr`(x, i, value)
```

I propose that this would work "better"

```
`[[<-.vctrs_vctr`(x, ..., value) 
```

My use case is in extending `vctrs_vctr` with an array class on top of it, `vctrs_rray`. I need to be able to do:

```
x[[1, 1, 1]] <- 4
```

but right now I can't because only `i` is passed through. I would bypass it with my own `[[<-.vctrs_rray` but I am not sure what it should do, as calling `NextMethod()` will send me straight into `[[<-.vctrs_vctr`.

I altered the `vctrs` code to use `...` rather than `i` and no tests break, so that's encouraging.

For whatever reason, `factor`s do this:

```
> args(`[[<-.factor`)
function (x, ..., value) 
NULL
```

**Comment by hadley** [comment]
Sure. Want to do a PR?
