### ISSUE TITLE
other pkgs "break up" vctrs records

### ISSUE THREAD

**Issue by maxheld83** [r-lib/vctrs#1333]
I've come across two instances where other packages seem to not "know" about records, and treat them as their underlying data structure (a list), which causes problems.

- purrr with reprex: https://github.com/tidyverse/purrr/issues/819
- testthat with reprex: https://github.com/r-lib/testthat/issues/1349

Before I potentially cause more noise in more pkgs, I wanted to make sure whether this is 

1. actually a problem in these *other* pkgs
2. a problem in vctrs
3. just a fundamental design constraint I was too dumb to see

**Comment by lionel-** [comment]
It is (1). purrr's lack of support for vctrs is a known limitation and on the long term todo list. The layer of compatibility with base R has limits so ultimately packages need to be adapted to be fully compatible with vctrs, e.g. its notion of atomic vectors.
