### ISSUE TITLE
Extending a vctrs base class and `vec_cast`

### ISSUE THREAD

**Issue by jtlandis** [r-lib/vctrs#1338]
I recently started learning about the `vctrs` package and promptly began to try and make complicated classes with this package.

My question is more for the case of when a user, or maybe a developer, may want to extend a vector class created by `new_vctr`. Suppose `"Foo"` is our base class for which we define methods for `vec_cast` and the class `"Bar"` and `"Baz"` are essentially `"Foo"` classes but distinct in some way. One motivation why a developer would do this is to adhere to DRY (Don't Repeat Yourself), e.i. why write 4 `vec_cast` methods (.Bar.Bar,  .Bar.Baz, .Baz.Bar, .Baz.Baz), when theoretically you could just write one `vec_cast.Foo.Foo`, especially if they will all be handled the same way?

It seems though that you cannot force `vec_cast.Foo.Foo` when calling `vec_cast(bar(10), foo())`. See below.

``` r
library(vctrs)

foo <- function(x = double()) new_vctr(x, class = "Foo")

bar <- function(x = double()) {
  f <- foo(x)
  structure(f, class = c("Bar", class(f)))
}
baz <- function(x = double()) {
  f <- foo(x)
  structure(f, class = c("Baz", class(f)))
}
a <- foo(10)
b <- bar(10)
c <- baz(10)
class(a)
#> [1] "Foo"        "vctrs_vctr"
class(b)
#> [1] "Bar"        "Foo"        "vctrs_vctr"
class(c)
#> [1] "Baz"        "Foo"        "vctrs_vctr"

vec_cast.Foo.Foo <- function(x, to, ...) x

vec_cast(a, foo())
#> <Foo[1]>
#> [1] 10
vec_cast(b, foo())
#> Error: Can't convert <Bar> to <Foo>.
vec_cast(c, foo())
#> Error: Can't convert <Baz> to <Foo>.
```

The work-around for me is to explicitly call `UseMethod("vec_cast", to)` in a new function I call `vec_cast2`

``` r
#`vec_cast.Foo` is usually not needed, but helpful for this example
vec_cast.Foo <- function(x, to, ...) UseMethod("vec_cast.Foo")
vec_cast2 <- function(x, to, ...) UseMethod("vec_cast", to)

vec_cast2(a, foo())
#> <Foo[1]>
#> [1] 10
vec_cast2(b, foo())
#> <Bar[1]>
#> [1] 10
vec_cast2(c, foo())
#> <Baz[1]>
#> [1] 10
```

<sup>Created on 2021-03-15 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

I'm assuming this is more of a feature and not a bug but I'm looking for a way to get the `vec_cast2` behavior.

I've noticed that `vec_cast` is defined as follows. It handles these things at the C level, but only really checks if the first class listed has a method defined.

```r
vec_cast <- function (x, to, ..., x_arg = "", to_arg = "") 
{
    if (!missing(...)) {
        check_ptype2_dots_empty(...)
    }
    return(.Call(vctrs_cast, x, to, x_arg, to_arg))
    UseMethod("vec_cast", to)
}
 ```

When is `UseMethod("vec_cast", to)` ever called in `vec_cast` in place of the C call?

**Comment by lionel-** [comment]
The coercion hierarchy is not necessarily the same as the S3 class hierarchy, so it is not inherited. There are some cases where inheritance would be desirable and we would like to solve this in the long term. In most cases though, repeating yourself with explicit coercion methods is the appropriate thing to do.

More info at https://vctrs.r-lib.org/reference/theory-faq-coercion.html

**Comment by jtlandis** [comment]
So my initial assumption was correct. I still really like the motivation behind the `vctrs` package and will probably use it going forward for any simple S3 classes I make. However, if I am making a class that will be inherited by many other classes, I think it would be best to move to S4 for the time being.

Thanks for the reply!
