### ISSUE TITLE
Handling error message 'x' must be a time-series object

### ISSUE THREAD

**Issue by PeishanR** [r-lib/vctrs#1356]
Hi there, 

I encounter this error message when generating a plot with xts dataset named "test_xts". 
The test_xts is transferred from a data frame with sales column with integer values and datetime column in "POSIXct" "POSIXt" format.

`s2_xts <- xts(s2, order.by=s2$datetime)`
`test_xts <- s2_xts["2020010108/2020013121"]`
`plot(test_xts$sales)`
Error in plot.xts(test_xts$sales) : 'x' must be a time-series object

I was unable to comprehend the root cause of this error message because the plot function went fine with the testing codes below.
`number <- rnorm(10)`
`dates <- seq(as.Date("2021-04-01"), length=10, by="days")`
`try_xts <- xts(number, order.by = dates)`
`plot.xts(try_xts)`

Then I tried to isolate the time index and the sales column from the xts object and compose them as a new xts object. 
It works this time with the plot function! 
`test_dates <- index(test_xts)`
`test_tags <- as.numeric(test_xts$sales)`
`train_xts <- xts(test_tags , order.by=test_dates)`
`plot(train_xts)`

It's not handy to have to isolate the time index with target columns and compose a new xts object. 
So I am very curious where could have gone wrong with the dataset transformation(dataframe to xts) and how I can refine it.
Does anyone have any clues?

**Comment by DavisVaughan** [comment]
This seems to be an xts issue, not a vctrs issue. Did you mean to post the issue here? https://github.com/joshuaulrich/xts
