### ISSUE TITLE
vec_equal() with tagged NA values

### ISSUE THREAD

**Issue by dusadrian** [r-lib/vctrs#1360]
The `vec_equal()` function has some C implementations to compare values i n`vctrs_equal` or to compare with an NA value in `vctrs_equal_na`.

Since package `haven` allows defining multiple types of NAs using `tagged_na()`, I wonder if package `vctrs` could check for such an equality as well.

Something like a `vctrs_equal_tagged_na` C function, similar (or even imported) from `is_tagged_na_` in package `haven` but adapted to the specifics in package `vctrs`.

Perhaps even consider moving that function from package `haven` to package `vctrs`? It seems better placed here, since package `haven` uses `vctrs` classes anyways.

**Comment by hadley** [comment]
This is out of scope for vctrs. Tagged NAs are something to allow haven to important SAS/Stata missings so they can be transformed to something that R understands; the intent is not to provide a complete framework for the analysis of tagged NAs.

**Comment by dusadrian** [comment]
I understand, but it's a pity. Having multiple (even concurrent) ways to check for vector equality helps less making R more attractive to people using other software.

Something like this in Stata:
```
use somedata
sum(V6) if V150 == .d
```

is the equivalent of a considerably more cumbersome R expression:
```r
with(subset(somedata, is_tagged_na(V150, 'd')), sum(V6, na.rm = TRUE)

# or

attach(somedata)
sum(V6[is_tagged_na(V150, 'd')], na.rm = TRUE)
```
