### ISSUE TITLE
%0% on NULL works. Should it? Is this supported long-term?

### ISSUE THREAD

**Issue by mmuurr** [r-lib/vctrs#1367]
[Docs for %0%](https://vctrs.r-lib.org/reference/op-empty-default.html) specifically talk about empty vectors, illustrating with the _typed_ `integer(0)`. This also works for `NULL` (as it is zero-length), but is there any expectation that this behavior might change in the future?

I ask because unlike most vctrs functions, `%0%` does type conversion (e.g. `integer(0) %0% "foo"` returns type character, not integer).

Since rlang's `%||%` type-converts NULL (but not zero-length _typed_ vectors), I wonder if there's room for a catch-all zero-length operator that converts _any_ zero-length object (typed or not) to some output. I'd suggest `%|||%` as it is kind of becomes more and more liberal as more `|` characters are added (if you consider replacing NA as a related task _in spirit_):
```
%|%    ## replace NA **within an existing vector** is a type-safe manner, i.e. it never replaces the vector itself
%0%    ## replace empty typed vectors, but perhaps not NULL? -- unfortunately could be a breaking change :-/
%||%   ## replace NULL, but not empty typed vectors
%|||%  ## replace any length-0 object
```

**Comment by lionel-** [comment]
That's because the size of `NULL` is 0

```r
vec_size(NULL)
#> [1] 0
```

Might need a FAQ page on the size of `NULL`.

If you need a length check, you'll need to implement it in your package. I often use a `%|0|%` util with a `length()` condition but it might be confusing to have two different kinds of empty-or operators in rlang and vctrs.

**Comment by mmuurr** [comment]
Yup, totally aware that `length(NULL) == 0`. I was mostly just curious if this behavior is 'officially' intended/supported moving-forward for NULLs . The wording on the man page raises the spectre of possibly checking for length-0 **and** being a vector, "Default value for empty **vectors**", so my defensive-programming Spidey-Sense was activated :-)

Other vctrs and rlang functions do not consider NULL a 'vctr' ... consider, e.g.,
```r
vctrs::vec_is(NULL, NULL, 0) # FALSE
rlang::is_vector(NULL) # FALSE
```

I like the `%|0|%` idea, too, but if `%0%` is (and will continue to be) agnostic to the first arg actually being a vector, then I suppose another operator isn't needed.

`%0%` and `%||%` are so closely related (and both so useful) that perhaps they should be (re)exported from both vctrs and rlang?

**Comment by lionel-** [comment]
> Yup, totally aware that length(NULL) == 0. 

vctrs's `%|0|%` uses `vec_size()`, not `length()`.

> I like the %|0|% idea, too, but if %0% is (and will continue to be) agnostic to the first arg actually being a vector, then I suppose another operator isn't needed.

The main difference will be with types like data frames where `length()` and `vec_size()` have different results.

> %0% and %||% are so closely related (and both so useful) that perhaps they should be (re)exported from both vctrs and rlang?

`%0%` can't be reexported from rlang since it uses a vctrs operation.

**Comment by lionel-** [comment]
I think this suggests that exporting `%0%` of any kind is not such a good idea because the semantics are not explicit.

**Comment by lionel-** [comment]
The documentation already mentions the semantics:

```
#' Use this inline operator when you need to provide a default value for
#' empty (as defined by [vec_is_empty()]) vectors.
```
