### ISSUE TITLE
alternative to as.character(df[1,]

### ISSUE THREAD

**Issue by jjesusfilho** [r-lib/vctrs#138]
If I want to make a vector from a dataframe (tibble) row in R base I would do this way:

```
df<-tibble::tibble(x="var1",y="var2",z="var3",w="var4")

names<-as.character(df[1,]) ## or:
names<-unname(unlist(df[1,])

```
Is there an alternative in the package vectrs to this operation, or it is out its scope?

**Comment by hadley** [comment]
There’s no alternative because I don’t think you should convert a data frame into a character vector. Instead extra the column with `[[` and then convert that.
