### ISSUE TITLE
Memory leak of `strings_posixt`.

### ISSUE THREAD

**Issue by Akirathan** [r-lib/vctrs#1384]
There is a typo in the assignment into `strings` on this line:
https://github.com/r-lib/vctrs/blob/52157b7cc172105404b59d7c4d85802ed79be0f0/src/utils.c#L1670

Instead of `SET_STRING_ELT(strings, strings_posixlt)` there should be `SET_STRING_ELT(strings, strings_posixt)`.

On FastR, this typo causes memory issues as `strings_posixt` is unprotected and not referenced from any other object, therefore, it is eligible for garbage collection. On GNU-R, I am not able to reproduce this issue even with `gctorture()` - it seems that GNU-R has a different policy for garbage-collecting CHARSXP objects.

**Comment by lionel-** [comment]
Thanks! I'm guessing the string doesn't get GC'd in GNU R because it's protected via another character vector (e.g. a class vector)?

**Comment by Akirathan** [comment]
It is not protected by any vector in GNU-R. The thing is that in GNU-R, all CHARSXPs are put inside a hash table, and they are not immediately released to the garbage collector even with `gctorture()` - as far as I can tell from looking into `memory.c : RunGenCollect`.

For example, in the following snippet (run with `gctorture()`), `first_vec` gets garbage-collected and so the result will be `list(2L,2L)`, as expected, because `first_vec` will be effectively replaced by `second_vec` in the memory:
```C
SEXP func() {
    SEXP first_vec = ScalarInteger(1);
    // After ScalarInteger(2) statement, first_vec is collected.
    SEXP second_vec = ScalarInteger(2);
    return list2(first_vec, second_vec);
}
```

But for CHARSXPs this is not the case:
```C
SEXP func() {
    SEXP char_sxp = mkChar("Foo");
    // After ScalarInteger statement, char_sxp should be collected as it is not referenced from anywhere.
    SEXP vec = ScalarInteger(42);
    return list2(char_sxp, vec);
}
```
This will return `list(CHARSXP("Foo"), 42L)`, but should fail because `char_sxp` should be collected.
