### ISSUE TITLE
Add function `df_unchop()`?

### ISSUE THREAD

**Issue by mgirlich** [r-lib/vctrs#1390]
I recently created a [PR in `tidyr`](https://github.com/tidyverse/tidyr/pull/1126) to improve the performance of `unchop()`. I saw that in an old PR @lionel- and @DavisVaughan already worked on its performance. There you mentioned in a comment
[tidyr: improve unchop performance](https://github.com/tidyverse/tidyr/pull/888#issuecomment-608091104) that `df_unchop()` respectively `df_unchop_info()` would make a nice addition for `vctrs`.

I think this would be a nice addition but I couldn't find an exisiting issue on it. Is this still something you consider adding to `vctrs`?

`unchop()` has an argument `keep_empty = c(TRUE, FALSE)`. It is used to specify whether rows of `NULL` should be kept or not. This is currently handled directly in `unchop()` but I think it would make sense to have this in `df_unchop_info()`.

Example from `tidyr`

```r
df <- tibble(
  y = list(
    NULL,
    tibble(a = 1, b = 2),
    tibble(a = 1:3, b = 3:1)
  )
)

df_unchop_info(df, ptype = NULL, keep_empty = FALSE)
#> # A tibble: 4 x 2
#>     loc val$y$a val$$b
#>   <int>   <dbl>  <dbl>
#> 1     2       1      2
#> 2     3       1      3
#> 3     3       2      2
#> 4     3       3      1

df_unchop_info(df, ptype = NULL, keep_empty = TRUE)
#> # A tibble: 5 x 2
#>     loc val$y$a val$$b
#>   <int>   <dbl>  <dbl>
#> 1     1      NA     NA
#> 2     2       1      2
#> 3     3       1      3
#> 4     3       2      2
#> 5     3       3      1
```

**Comment by DavisVaughan** [comment]
I think we will keep this in tidyr for now, see also https://github.com/tidyverse/tidyr/pull/1140
