### ISSUE TITLE
Add `keep` argument to `vec_rep()` and `vec_rep_each()`

### ISSUE THREAD

**Issue by mgirlich** [r-lib/vctrs#1393]
I'm not sure whether this is a common use case but I found this the following pattern in `tidyr`

```r
y <- vec_rep(x, n)
vec_slice(y, lgl_vector)
```

and the same for `vec_rep_each()`. It would be a bit nicer and more efficient to combine this into a single operation

```r
vec_rep(x, n, keep = lgl_vector)
```

where `lgl_vector` is of size `vec_size(x) * n`. Maybe it could instead also be a negative integer vector (though the name should then probably rather be something like `drop`).

**Comment by DavisVaughan** [comment]
I'm not sure I've ever seen this pattern in the wild personally. I'm inclined to just leave it as a separate slice after the rep call

**Comment by DavisVaughan** [comment]
I think leaving this as a separate call is the correct thing to do
