### ISSUE TITLE
Add `list_compact()`

### ISSUE THREAD

**Issue by mgirlich** [r-lib/vctrs#1395]
When dealing with lists it is often necessary to remove `NULL` elements. While `purrr::compact(x)` does the job nicely it is pretty slow. I think something like `list_compact()` would be a great addition to `vctrs`.

It might make sense to allow the user to control whether only `NULL` should be removed and/or other empty elements, e.g.

```r
drop_null <- function(x) {
  vec_slice(x, !vapply(x, is.null, logical(1)))
}

vctrs_compact <- function(x) {
  vec_slice(x, list_sizes(x) != 0)
}

l <- list(a = NULL, b = integer(), c = 1L)
# only remove `NULL`
drop_null(l)

# remove empty elements
vctrs_compact(l)
```

## Benchmarks

``` r
library(purrr)
library(vctrs)

vctrs_compact <- function(x) {
  vec_slice(x, list_sizes(x) != 0)
}

# bigger lists
n1 <- 1e3
l <- vec_rep(list(1, NULL, 2), n1)

bench::mark(
  purrr = compact(l),
  vctrs = vctrs_compact(l)
)
#> # A tibble: 2 x 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 purrr        7.23ms   8.02ms      124.   161.5KB    24.3 
#> 2 vctrs       90.47µs 116.08µs     8048.    51.6KB     6.29

# tight loops
l2 <- vec_rep(list(vec_rep(list(1, NULL, 2), 10L)), 1e3)
bench::mark(
  purrr = lapply(l2, compact),
  vctrs = lapply(l2, vctrs_compact)
)
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 2 x 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 purrr       107.5ms 110.77ms      8.80     211KB    19.4 
#> 2 vctrs        2.98ms   3.35ms    281.       211KB     9.98
```

<sup>Created on 2021-06-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by lionel-** [comment]
I think this sort of high level features is out of scope for vctrs, at least currently. In the next non-patch versions we'll focus on finishing genericity and sorting issues.

**Comment by hadley** [comment]
Where should this live then?

**Comment by lionel-** [comment]
The backend for `purrr::compact()` would be `vctrs::list_compact()`, like the backend for `purrr::flatten()` would be `vctrs::vec_flatten()` or `vctrs::list_flatten()`. I think the feature makes sense, I closed the issue because we postponed purrr backends to the longer term roadmap the last time we worked on them.

I see in the linked issue that it might be needed now for tidyr.
