### ISSUE TITLE
Type stable [<- for base classes

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#140]
i.e. ensures that the type of `x` does not change. 

Needed for https://github.com/tidyverse/purrr/pull/579

**Comment by krlmlr** [comment]
I don't see how to do this for `[<-`, but we could change `vec_slice<-()` . Currently: 

``` r
x <- 2:6
vctrs::vec_slice(x, 2:4) <- "foo"
x
#> [1] "2"   "foo" "foo" "foo" "6"
```

<sup>Created on 2019-02-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by krlmlr** [comment]
I'm not sure casting is the right operation here:

``` r
library(vctrs)
x <- 2:6
vctrs::vec_slice(x, 2:4) <- vec_cast("3", vec_type(x))
x
#> [1] 2 3 3 3 6
```

<sup>Created on 2019-02-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

I'd say we still throw an error here. We'd also throw an error if `vec_type2(x, value)` return anything different than `vec_type(x)`. (Subset assignment never changes the data type.?) Do we need a new `vec_coerce()` ?

**Comment by hadley** [comment]
Alternatively we just do `vec_assert()`. We could always relax it later if that turns out to be too painful.

**Comment by hadley** [comment]
No, that's going to be too strict — it's going to make it painful to change (e.g.) dates or factors.

**Comment by lionel-** [comment]
I think we also need `vec_is()` for recursion into containers. Without it we can't figure out what's a leave.

**Comment by lionel-** [comment]
Distinguishing coercion and casting we have:

```r
vec_coerce <- function(x, to) {
  vec_cast(x, vec_type2(x, to))
}

x <- 1:6
i <- 2:4

y <- "10"
vec_slice(x, i) <- vec_coerce(y, x)
#> Error: No common type for <character> and <integer>.

y <- 10
vec_slice(x, i) <- vec_coerce(y, x)
```

**Comment by krlmlr** [comment]
I don't think `[<-` should change the underlying type. Going with the cast for now, we can revisit later.

**Comment by lionel-** [comment]
I'm working on casting @krlmlr.

**Comment by lionel-** [comment]
@hadley suggested a third option: casting `value` to the type of `x`, but only if `x` and `value` have a common type. Maybe it's safer to just `vec_assert()` for now, until we figure out the correct way.

**Comment by krlmlr** [comment]
We also should look at the interplay between `vec_slice<-()` and `[<-()`. Currently, the former calls the latter.

What if we made `vec_slice<-()` very strict (i.e., `value` must be the same type), and `[<-()` closer to the behavior of base R (casting to a common subtype)?

**Comment by lionel-** [comment]
I'm wondering whether we should call `vec_slice()` from `[`. This way we consistently preserve attributes.

**Comment by lionel-** [comment]
I.e. I _think_ it's better for `vec_slice()` / `[` and their assign variants to have consistent behaviour.

**Comment by krlmlr** [comment]
Consistent, yes, but `vec_slice()` still can be stricter than `[`? (Basically, because we can't influence the behavior of `[` for types we don't control?)

**Comment by lionel-** [comment]
I think our types should have strict `[` just like tibble implements a stricter interface than data.frame.

**Comment by lionel-** [comment]
Also it makes the vctrs API simpler if `vec_slice()` and `[` are synonyms in practice.

**Comment by krlmlr** [comment]
They can't be synonyms.

**Comment by krlmlr** [comment]
Unless we implement `vec_slice()` to be lax for bare vectors, do we want that?

**Comment by lionel-** [comment]
What do you mean by lax?

**Comment by krlmlr** [comment]
``` r
x <- 2:6
vctrs::vec_slice(x, 2:4) <- "foo"
x
#> [1] "2"   "foo" "foo" "foo" "6"
```

<sup>Created on 2019-03-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by krlmlr** [comment]
This was the original request.

I'll come up with examples that show current behavior of `vec_slice<-()` and `[<-()`, then we can discuss about how we want it to be.

**Comment by lionel-** [comment]
ah yes you're right, this should fail.

**Comment by lionel-** [comment]
I think this is a better formulation: `vec_slice()` and `vec_slice<-` should be stricter than `[` and `[<-` with base types, but have consistent behaviour for our own types.

**Comment by krlmlr** [comment]
Thinking about it, I'm not sure what the call chain should look like.

- `[<-()` is a generic that "does the right thing", also for objects with dimension
- `vec_slice<-()` currently isn't generic and probably shouldn't be
- `vec_slice<-()` currently relies on `[<-()` for objects with dimension (and also for simple vectors)

If `[<-()` forwards to `vec_slice()`, we get endless recursion -- tried that. If we move all the checking logic from `vec_slice<-()` to `[<-()`, we lose strictness for base and foreign types. If we extract the checking logic and call it in both `vec_slice<-()` and `[<-()`, we do the same work twice for our own types.

Can we somehow call the "bare" version of `[<-()`? Or do we implement our own C version of the slice assignment that works for one-dimensional vectors?

**Comment by lionel-** [comment]
I've been wondering whether the genericity in vctrs could be handled with just `vec_restore()` + `vec_data()` (removes attributes except dims and names) and `vec_proxy()` (may preserve attributes, should return either atomic vectors or records/dataframes, it's a noop for most classes).

This way `vec_slice()` doesn't need to be generic, it'd just slice the `vec_proxy()`, producing fresh data, and `vec_restore()` the class at the end.

Similarly `vec_slice<-` could operate on the unclassed `vec_data()` with `[<-` and `vec_restore()` would restore attributes. Then there is no issue calling `vec_slice<-` from `[<-`.

**Comment by krlmlr** [comment]
I like that idea, will try (and also mind your open PR).

I have prepared a survey of the current behavior of sliced assignment: http://rpubs.com/krlmlr/vctrs-140-sliced-assign . The code compares `dput()` output between `[<-()` and `vec_slice<-()`, a comment before every comparison shows my assessment. Does this look reasonable? Is anything missing?

**Comment by krlmlr** [comment]
Unfortunately, `vec_data()` currently doesn't preserve dimensions (#245).

**Comment by krlmlr** [comment]
We also need to think about `x[] <- value` .

**Comment by lionel-** [comment]
@krlmlr I've now started work on slice-assign.
