### ISSUE TITLE
Fast path for `vec_assign(x, integer())`?

### ISSUE THREAD

**Issue by mgirlich** [r-lib/vctrs#1408]
Similarly to #1400 I think it would make sense to have a fast path for `vec_assign(x, integer())`

The motivation is also similar: e.g. when using `vec_assign()` in a `coalesce()` like fashion `vec_assign(x, is.na(x), 1L)`.

## Benchmark

``` r
library(rlang)
library(vctrs)

x <- 0L + 1:10e6

bench::mark(
  vec_assign = {vec_assign(x, integer(), integer())},
  check = FALSE
)
#> # A tibble: 1 x 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 vec_assign    5.1ms   5.53ms      165.    38.2MB     172.
```

<sup>Created on 2021-06-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by lionel-** [comment]
Thanks for looking into this but we've decided early exits like this are not worth the complications.
