### ISSUE TITLE
Add `allow_null` arg to `vec_assert()`

### ISSUE THREAD

**Issue by markfairbanks** [r-lib/vctrs#1410]
One of the most common uses I have for `vec_assert()` is to do type checking on function arguments. Would it be possible to add an `allow_null` argument?

A very common default for arguments is `NULL`, and I find myself using this pattern quite frequently:

```r
foo <- function(x = NULL) {
  if (!is.null(x)) {
    vec_assert(x, character())
  }
  x
}
```

**Comment by lionel-** [comment]
hmm I think checking for `NULL` on the outside is a better approach compared to adding an argument.

**Comment by markfairbanks** [comment]
Gotcha, I'll keep using that approach then 👍
