### ISSUE TITLE
Allow splicing quosures in `vctrs::data_frame()`

### ISSUE THREAD

**Issue by markfairbanks** [r-lib/vctrs#1412]
Not sure this is out of scope for `vctrs`, but should `vctrs::data_frame()` be able to splice quosures?

``` r
library(vctrs)
library(rlang)

create_df <- function(...) {
  dots <- enquos(...)
  data_frame(!!!dots)
}

create_df(x = 1, y = 2)
#> Error: Input must be a vector, not a <quosure> object.
```

**Comment by lionel-** [comment]
Nope because it doesn't defuse its arguments. `data_frame()` is a standard evaluation function. If you have quosures or expressions, you'll have to evaluate them manually.
