### ISSUE TITLE
Avoid eagerly evaluating arg in vec_as_subscript() and other functions 

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#1417]
``` r
library(vctrs)

vec_as_subscript(1, arg = { print("oof"); deparse(quote(i)) })
#> [1] "oof"
#> [1] 1
```

<sup>Created on 2021-07-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

The `deparse()` call is slow, it should be run only if there is an actual error.

**Comment by DavisVaughan** [comment]
Duplicate of https://github.com/r-lib/vctrs/issues/1150?

**Comment by krlmlr** [comment]
Yep.
