### ISSUE TITLE
vec_as_location(missing = "error") and logical NA

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#1420]
Should this fail?

``` r
vctrs::vec_as_location(NA, 3, missing = "error")
#> [1] NA NA NA
```

<sup>Created on 2021-07-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0.9000)</sup>

**Comment by DavisVaughan** [comment]
Hmm, probably. That would mean this should fail too:

``` r
vctrs::vec_as_location(NA_character_, 2, missing = "error", names = c("x", "y"))
#> [1] NA
```

`lgl_as_location()` and `chr_as_location()` don't check `missing` right now:
https://github.com/r-lib/vctrs/blob/81e32472a575a212539bdc9f6b8447e429635f29/src/subscript-loc.c#L219
https://github.com/r-lib/vctrs/blob/81e32472a575a212539bdc9f6b8447e429635f29/src/subscript-loc.c#L278
