### ISSUE TITLE
Allow list splicing in `data_frame()`

### ISSUE THREAD

**Issue by markfairbanks** [r-lib/vctrs#1421]
Might be out of scope for vctrs, but should something like this be possible?

``` r
library(vctrs)

val_list <- list(1, 2, 3)

data_frame(vals = c(!!!val_list))
#> Error in !val_list: invalid argument type
```

**Comment by DavisVaughan** [comment]
I think you are probably better off with using `vec_unchop()` ahead of time, for reasons similar to #1412 - i.e. `data_frame()` is a standard evaluation function and doesn't defuse its arguments

``` r
library(vctrs)

val_list <- list(1, 2, 3)

data_frame(vals = vec_unchop(val_list))
#>   vals
#> 1    1
#> 2    2
#> 3    3
```

<sup>Created on 2021-08-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0.9000)</sup>

**Comment by markfairbanks** [comment]
Gotcha, makes sense
