### ISSUE TITLE
`vec_cast_common()` support for `raw`

### ISSUE THREAD

**Issue by coolbutuseless** [r-lib/vctrs#1443]
Should `vec_cast_common()` work with `raw` values? 

I would have expected the following to promote the raw to integer as the lowest "common" type, but instead it throws an error.

```
> vec_cast_common(1L, raw(1L))
Error in `stop_vctrs()` at vctrs/R/conditions.R:69:2: 
Can't combine `..1` <integer> and `..2` <raw>.
```

**Comment by lionel-** [comment]
I don't think so, raw vectors are not part of the numeric tower and they are not user facing.
