### ISSUE TITLE
How to hide list_of header?

### ISSUE THREAD

**Issue by briatte** [r-lib/vctrs#1444]
Apologies if this is a trivial question, but how can I hide the header of a `vctrs_list_of` object while printing it?

An example of such a header for a 2-element `list_of` object is shown below:

```r
tibble::tibble(x = c("one", "two"), y = 1:2) %>% 
    dplyr::group_by(x) %>% 
    dplyr::group_split()
```
```
<list_of<
  tbl_df<
    x: character
    y: integer
  >
>[2]>
[[1]]
# A tibble: 1 x 2
  x         y
  <chr> <int>
1 one       1

[[2]]
# A tibble: 1 x 2
  x         y
  <chr> <int>
1 two       2
```

The part that I am trying to hide is

```
<list_of<
  tbl_df<
    x: character
    y: integer
  >
>[2]>
```

My best guess is that the answer will have to do with `obj_print_header`, but I am struggling with how to use it properly.

**Comment by DavisVaughan** [comment]
Generally, you can't, since it provides valuable information about the type. Why would you like to hide it? If you don't care about it being a list-of anymore you can call `as.list()` to turn it into a bare list again if it bothers you.

**Comment by briatte** [comment]
> Why would you like to hide it?

I am trying to show a lot of information on screen, and would value the option to showing one more list item in the space currently taken by the header.

**Comment by DavisVaughan** [comment]
We appreciate the issue, but aren't planning on changing the print method to list-of at this time
