### ISSUE TITLE
Should we handle more easy cases in `vec_cast_switch_native()`?

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#1451]
We could handle list-list, complex-complex, and raw-raw types here, since they are all no-ops? I think that would really help combining lots of lists together, since that currently dispatches to `vec_cast.list.list()`

https://github.com/r-lib/vctrs/blob/acd304b6cc70dda47e7b928806ec55bc3403fa2f/src/cast.c#L93-L97

**Comment by lionel-** [comment]
Makes sense. I wonder why we didn't do that right away for the list-list case.
