### ISSUE TITLE
Should `vec_equal_na(NULL)` return `logical(0)`?

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#1494]
Like `is.na(NULL)`

Found when running tidyr revdeps after upgrading `replace_na.default()` to be:

```r
function(data, replace = NA, ...) {
  check_replacement(replace, "data")
  missing <- vec_equal_na(data)
  vec_assign(data, missing, replace, x_arg = "data", value_arg = "replace")
}
```

Someone had done `replace_na(NULL, "x")` and that errors now.

`vec_assign(NULL, i, value)` already returns `NULL`, so this would compose with that well (even though I think the revdep package has an actual issue)

**Comment by lionel-** [comment]
Agreed, that makes sense since `NULL` has a size and is in general supported in the vector generics.
