### ISSUE TITLE
Accessing, testing for and rationalizing names

### ISSUE THREAD

**Issue by jennybc** [r-lib/vctrs#15]
There's a set of name-handling functions that recur in many a `utils.R` file. They would seem to fit nicely here.

Some specific examples:

`names2()` from [purrr](https://github.com/hadley/purrr/blob/a7afcca128ab9e44bb544086b1465d44c2931fb1/R/utils.R#L132-L134) or [tibble](https://github.com/hadley/tibble/blob/6d2bb0826ca8256d457e9b210a30e12101afd6fc/R/utils.r#L1-L8)

`has_names()` from [purrr](https://github.com/hadley/purrr/blob/a7afcca128ab9e44bb544086b1465d44c2931fb1/R/utils.R#L197-L204) or [httr](https://github.com/hadley/httr/blob/1fc659856602f60ff75eb01903513244e3491ec2/R/utils.r#L21-L27)

`named()` and `unnamed()` from [httr](https://github.com/hadley/httr/blob/1fc659856602f60ff75eb01903513244e3491ec2/R/utils.r#L18-L19)

**Comment by jennybc** [comment]
Have also recently needed something to completely strip names when they are uniformly empty strings. This is an odd way in which the names of a list reflect its evolution vs. its current state.

``` r
library(magrittr)
a <- list(one = 1, "hi")
names(a2 <- a[2])
#> [1] ""
names(a3 <- list("hi"))
#> NULL
jsonlite::toJSON(a2)
#> {"1":["hi"]}
jsonlite::toJSON(a3)
#> [["hi"]]

## as already suggested above
has_name <- function(x) {
  nms <- names(x)
  if (is.null(nms)) {
    rep_len(FALSE, length(x))
  } else {
    !(is.na(nms) | nms == "")
  }
}
cleanse_names <- function(x) {
  if (all(!has_name(x))) {
    names(x) <- NULL
  }
  x
}
a2 %>% cleanse_names() %>% jsonlite::toJSON()
#> [["hi"]]
a3 %>% cleanse_names() %>% jsonlite::toJSON()
#> [["hi"]]
```

**Comment by hadley** [comment]
I think these now live in rlang, which feels like the right place to me.
