### ISSUE TITLE
Release vctrs 0.1.1

### ISSUE THREAD

**Issue by javierluraschi** [r-lib/vctrs#150]
@hadley when is `vctrs` planned to be updated in CRAN?

I'm trying to figure out when https://github.com/r-lib/vctrs/pull/122 will hit CRAN since the R `arrow` bindings make use of this feature. Otherwise, we could disable this for the first CRAN release and update once `vctrs` gets updated.

**Comment by hadley** [comment]
I don't have near future plans. Maybe after rstudio::conf?

**Comment by hadley** [comment]
We're planning on a release prior to useR
