### ISSUE TITLE
Do `vec_group_loc()` and `vec_split()` offer group ordering guarantees?

### ISSUE THREAD

**Issue by tzakharko** [r-lib/vctrs#1505]
Is it guaranteed that the groups produced by these functions are ordered by the first occurrence of the respective key? The documentation only offers this guarantee for `vec_group_id()`, but I was not able to find similar statements for the actual splitting functions. It does seem like this is how these functions currently work, but I am wondering whether this is an implementation detail or a guaranteed behaviour that one can rely on going forward. 

The reason why I am asking is that I frequently have to split vectors based on integer group ids similar to what `vec_group_id()` returns. Knowing that splitting functions will not permute the group order would allows me to simplify the code, as I am currently inserting `match()` to make sure that groups are correctly ordered.

**Comment by DavisVaughan** [comment]
Yes they order by first appearance
