### ISSUE TITLE
`vec_assign()` when assigning into an unspecified column

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#1514]
I think this idea has come up a few times, but I can't figure out where. Most recently it appeared here https://github.com/tidyverse/tidyr/issues/1317

When assigning into an unspecified vector (most commonly, a vector of all logical `NA`), should the LHS be cast to the RHS?

Tibble makes an exception for this already in `tibble:::vectbl_assign()`

``` r
library(vctrs)
library(tibble)

x <- c(NA, NA)

vctrs:::is_unspecified(x)
#> [1] TRUE

# Not allowed
vec_assign(x, 1L, 1.5)
#> Error:
#> ! Can't convert from <double> to <logical> due to loss of precision.
#> • Locations: 1

# Tibble makes an exception
df <- tibble(x = x)

# Casts unspecified column to RHS
df[1, 1] <- 1

df
#> # A tibble: 2 × 1
#>       x
#>   <dbl>
#> 1     1
#> 2    NA
```

Here is `vectbl_assign()`, which basically checks for `is_unspecified(x)` if it is unspecified it will replace it with `vec_init(value, vec_size(x))`.

``` r
tibble:::vectbl_assign
#> function (x, i, value) 
#> {
#>     if (is.logical(value)) {
#>         if (.Call("tibble_need_coerce", value)) {
#>             value <- vec_slice(x, NA_integer_)
#>         }
#>     }
#>     else {
#>         if (.Call("tibble_need_coerce", x)) {
#>             d <- dim(x)
#>             dn <- dimnames(x)
#>             x <- vec_slice(value, rep(NA_integer_, length(x)))
#>             dim(x) <- d
#>             dimnames(x) <- dn
#>         }
#>     }
#>     vec_assign(x, i, value)
#> }
#> <bytecode: 0x7fd45ce8cc08>
#> <environment: namespace:tibble>
```

If we also did something like this, I think it would be _slightly_ different, because `tibble_need_coerce` considers `logical(0)` as unspecified, but we haven't been doing that.

**Comment by DavisVaughan** [comment]
It also affects the case of `vec_assign(NA, 1L, 0)`, where `0` is cast to `FALSE` in the current behavior.

It we changed this so the LHS is cast to the type of the RHS in this case, we'd get `0` as the result.

**Comment by lionel-** [comment]
I think this is https://github.com/r-lib/vctrs/issues/1172
