### ISSUE TITLE
vec_restore.default() alters size and type

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#153]
According to the docs:

> A `vec_restore()` method can assume that `x` has the correct type (although the length may be different) but all attributes have been lost and need to be restored.

This would lead me to believe that `x` can have a different size than `to`, which is the case when using `vec_restore()` with 1D vectors, but with matrices/arrays this isn't the case because all attributes of `to` are copied to `x`, including the `dim` (which embeds the size).

``` r
library(vctrs)

x <- matrix(1:5)

# dummy function to demonstrate losing attributes
# - type is the same (but attributes are needed)
# - size is now different
c_level_manip <- function(x) {
  vec_data(x)[1:2]
}

# I think this should work
vec_restore(c_level_manip(x), x)
#> Error in attributes(x) <- attributes(to): dims [product 5] do not match the length of object [2]

# special case the `dim` attribute
# pull size from x
# pull shape from to
vec_restore.default <- function(x, to) {
  restore_attr <- attributes(to)
  
  if ("dim" %in% names(restore_attr)) {
    restore_attr$dim <- c(vec_size(x), vctrs:::shape(to))
  }
  
  attributes(x) <- restore_attr
  x
}

vec_restore(vec_data(x)[1:2], x)
#>      [,1]
#> [1,]    1
#> [2,]    2
```

<sup>Created on 2019-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

Size is implicitly ignored with vectors:

``` r
library(vctrs)

ex <- factor(c("a", "a", "b"))

vec_restore(vec_data(ex[1]), ex)
#> [1] a
#> Levels: a b
```

<sup>Created on 2019-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

Update) This also would affect dimnames and general names. This is more difficult as the order or the rows would matter here when "restoring" names, but generally I think it isn't vctrs's job to restore names/dimnames so maybe they could just be removed.

``` r
library(vctrs)
x <- 1:5
names(x) <- letters[1:5]
vec_restore(vec_data(x[1:2]), x)
#> Error in attributes(x) <- attributes(to): 'names' attribute [5] must be the same length as the vector [2]
```

<sup>Created on 2019-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by hadley** [comment]
I'm pretty sure your analysis is correct (I'm don't have vctrs in front-of-mind, so I can't be absolutely sure).

**Comment by yutannihilation** [comment]
#179 might be a related problem to this. IMHO, `dim` or `row.names` should be allowed to be provided as arguments.

**Comment by lionel-** [comment]
My current thinking is:

* `vec_restore()` should always get `x` as raw data. This avoids infloops when using vctrs primitives with `x` (still dangerous to query `to` with vctrs).

* vctrs takes cares of restoring all core vectorised attributes, such as names, dim, and dimnames. `x` will have the correct attributes after slicing, and before `vec_restore()` is called.

WDYT Davis?

**Comment by lionel-** [comment]
I think https://github.com/r-lib/vctrs/pull/242 fixes this issue by the way.

**Comment by DavisVaughan** [comment]
Just want to document that I think `vec_restore()`'s default should also keep the dimnames of `x`. https://github.com/r-lib/vctrs/blob/master/src/cast.c#L292

I think this means `vec_slice()` also has to "restore" dimnames correctly whenever a 2D+ implementation of `vec_slice()` is created (i.e. `slice_names()` should also handle dimnames).
