### ISSUE TITLE
vec_size with proxy

### ISSUE THREAD

**Issue by milosradon** [r-lib/vctrs#1539]
I was expecting that by default the size of a vctr is equal to the size of its proxy. However, in the following example the length of the proxy is returned.

```r
require(vctrs)

# myclass method
vec_proxy.myclass = function(x, ...) {
  new_rcrd(list(A = seq_along(x)), class = "myclass_rcrd")
}

# myclass vector
a <- new_vctr(integer(10L), class = "myclass")


vec_size(a)
# 1
vec_size(vec_proxy(a))
# 10
```

Is this desired behaviour?

**Comment by DavisVaughan** [comment]
The proxy method isn't recursive, so we currently consider the result of `vec_proxy()` to be a "base" like type where `length()` would work on it (with the exception of data frames where we take the number of rows).

So the rcrd that is being returned from `vec_proxy()` is treated like a list, which has length 1 (i.e. the A element).

You could use a data frame as the proxy? But I'm not entirely sure what you are trying to do here with such a simple vctr class.

``` r
require(vctrs)
#> Loading required package: vctrs

# myclass method
vec_proxy.myclass = function(x, ...) {
  new_data_frame(list(A = seq_along(x)))
}

# myclass vector
a <- new_vctr(integer(10L), class = "myclass")

vec_size(a)
#> [1] 10
```

<sup>Created on 2022-02-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by lionel-** [comment]
Agreed, I'd use a data frame as proxy. We should probably document in `?vec_proxy` that it should return one of the fundamental vctrs types (base vectors and data frames).

**Comment by milosradon** [comment]
Thank you! Yes, a note in `?vec_proxy` would clear that up.

@DavisVaughan My problem is not with that simple vctr class but arises from the fact that `data.table` would not accept a `vctrs_rcrd` vector as a column, in general. I was considering to use an atomic `vctrs_vctr` (always accepted by `data.table`) that has a `vctrs_rcrd` proxy. 

Using `list_of` would solve the issue, however, the solution would generate other problems (list-columns do not have all functionalities). I will try to come up with an implementation using the data.frame proxy approach.

**Comment by DavisVaughan** [comment]
Do you (in theory) have more than one `field`? Where would you store the 2nd field in a vctrs-vctr type?

**Comment by milosradon** [comment]
Looks like I brought that up for the post's anniversary :-) Exactly, this would be much appreciated.

If `x` is atomic and inherits from `vctrs_vctr`, my initial experimental implementation would store its `rcrd` proxy as an attribute. 
(Along the lines of
```r
x_proxy <- rep(as.POSIXlt(Sys.time()), 5L)
x <- as.character(x_proxy)
setattr(x, "proxy", x_proxy)
tbl <- data.table(A = 1:5, B = x)
tbl 
```
)
On the attribute no restrictions are imposed (in particular not on the number of fields). But one has to make sure it does not get lost and it is always up to date.

In the end, I decided not to use `rcrd`s (or `data.frame`s) at all. Instead, an integer encoding is used.

**Comment by lionel-** [comment]
> We should probably document in ?vec_proxy that it should return one of the fundamental vctrs types (base vectors and data frames).

Ah this is already mentioned in the section Proxying.
