### ISSUE TITLE
ANSI escape codes showing in hosted vignette

### ISSUE THREAD

**Issue by TimTaylor** [r-lib/vctrs#1548]
The hosted [pillar vignette](https://vctrs.r-lib.org/articles/pillar.html) seems to be displaying the ANSI escape codes.

**Comment by lionel-** [comment]
Should this be transferred to r-lib/pkgdown @hadley?

**Comment by hadley** [comment]
I think you probably need to change

```R
knitr::opts_chunk$set(collapse = TRUE, comment = pillar::style_subtle("#>"))
```

to 

```R
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
```
