### ISSUE TITLE
`vec_cast()` with `stats::ts` objects

### ISSUE THREAD

**Issue by hughjonesd** [r-lib/vctrs#1564]
This works:

```r
vec_cast(1.0, 1L)
```

This doesn't
```r
vec_cast(ts(1.0), ts(1L))
```

Both time series have the same start, end and frequency, so it feels as if they should be compatible (if integers and doubles are).

**Comment by lionel-** [comment]
We currently don't fully support `ts` objects in vctrs, only as part of the fallback mechanism.
