### ISSUE TITLE
`vec_as_names()` message seems slow

### ISSUE THREAD

**Issue by markfairbanks** [r-lib/vctrs#1566]
Not sure if this is expected, but `quiet = FALSE` seems slow to me in `vec_as_names()`.

``` r
library(vctrs)

names <- c("a", "", "", "")

bench::mark(
  quiet_false = vec_as_names(names, repair = "unique", quiet = FALSE),
  quiet_true = vec_as_names(names, repair = "unique", quiet = TRUE),
  check = FALSE, iterations = 30
)
#> New names:
#> • `` -> `...2`
#> • `` -> `...3`
#> • `` -> `...4`
#> # A tibble: 2 × 6
#>   expression       min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>  <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 quiet_false  65.85ms   67.4ms      14.8     844KB     34.6
#> 2 quiet_true    6.19µs   6.74µs  130447.         0B      0
```

When not using `{reprex}` my laptop was taking 180ms vs. 6.99μs. The `{reprex}` result seems better but still slower than I would have expected. (Not sure why there's a difference between non-reprex and reprex 🤷‍♂️)

**Comment by lionel-** [comment]
Thanks for the report. We are aware of this but fixing this is not a priority at the moment. FYI the slowness comes from `rlang::names_inform_repair()`.
