### ISSUE TITLE
Allow `.name_repair = "minimal"`?

### ISSUE THREAD

**Issue by lionel-** [r-lib/vctrs#1567]
Would be useful for ggplot.

**Comment by lionel-** [comment]
Investigate:

```r
vec_rbind(x = 1:3, y = 4:6, .name_repair = function(x) c("a", "a", "a"))
#> New names:
#> • `` -> `...1`
#> • `` -> `...2`
#> • `` -> `...3`
#> New names:
#> • `` -> `...1`
#> • `` -> `...2`
#> • `` -> `...3`
#>   ...1 ...2 ...3
#> 1    1    2    3
#> 2    4    5    6
```

**Comment by DavisVaughan** [comment]
I think the unique name repair happens in `as_df_row()` and ignores the `.name_repair` input. My guess is that it happens here:

https://github.com/r-lib/vctrs/blob/6bfe08c945476b3fd6c5fd9a01340a1f404dd199/src/bind.c#L322

**Comment by lionel-** [comment]
Yeah that would have been my guess as well. Are you working on a fix?
