### ISSUE TITLE
How to test if vector is `unspecified()`?

### ISSUE THREAD

**Issue by mgirlich** [r-lib/vctrs#1574]
`vec_is()` always returns `FALSE`. Is this intended behaviour?

``` r
library(vctrs)

x <- unspecified()
vec_is(x, x)
#> [1] FALSE
```

<sup>Created on 2022-06-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

There is an unexported function `is_unspecified()`. Probably it would make sense to export it?

**Comment by lionel-** [comment]
`vec_is()` is mostly experimental at the moment. And unspecified vectors are more of an internal type. What do you use them for?

**Comment by lionel-** [comment]
Closing for now but we can keep discussing the role and usage of unspecified outside of vctrs.
