### ISSUE TITLE
What should `vec_equal_na()` return with data frames with N rows and 0 cols?

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#1585]
It currently returns `TRUE` for each of the `N` rows, implying it is "missing". Maybe this is right? Hard to say.

We need to ensure `vec_any_missing()` is aligned with it, and that both get the 0 row, 0 col case right, which I think should definitely be `FALSE` for `vec_any_missing()` (because `vec_any_missing(integer())` and friends returns `FALSE`).

``` r
library(vctrs)

# 0 rows, 0 cols
df <- data_frame(.size = 0)
vec_equal_na(df)
#> logical(0)
vec_any_missing(df)
#> [1] FALSE

# N rows, 0 cols (What to return here?)
df <- data_frame(.size = 5)
vec_equal_na(df)
#> [1] TRUE TRUE TRUE TRUE TRUE
vec_any_missing(df)
#> [1] FALSE

# The `vec_equal()` page says `vec_equal_na()` preserves this invariant, so
# maybe vec_any_missing(df) should return `TRUE` with N rows, 0 cols.
# (This could just mean that `vec_equal()` is wrong too?)
vec_equal(df, vec_init(df), na_equal = TRUE)
#> [1] TRUE TRUE TRUE TRUE TRUE
```

**Comment by DavisVaughan** [comment]
I think the `vec_equal()` and `vec_equal_na()` behavior is right. For data frames, I think `vec_equal_na(df)` and `vec_equal(df)` mean: "For each row, return `TRUE` for that row if ALL values in that row are missing/equal". So it implies usage of `all()` on each row. When there are 0 columns, that means doing `all(logical()) == TRUE` for each row, matching what `vec_equal_na()` is giving.

And then `vec_any_missing(df)` should have the invariant of `vec_any_missing(df) == any(vec_equal_na(df))`, giving us `TRUE` as well.

So all in all it should do something like this.

``` r
library(vctrs)
library(purrr)

df_equal_na <- function(x) {
  # Replace each column with its equal-na value
  x[] <- map(x, vec_equal_na)
  
  # We are going to work 1 row at a time
  rows <- vec_chop(x)
  
  # Unchop each row into a logical vector of length `n_col`
  rows <- map(rows, ~vec_unchop(unclass(.x), ptype = logical()))
  
  # We apply `all()` to each row vector
  # i.e. "all row values must be missing for the row to be missing"
  map_lgl(rows, all)
}

df_any_missing <- function(x) {
  any(df_equal_na(x))
}

# 0 rows means size 0 result, so `logical()`
df_equal_na(data_frame())
#> logical(0)

# any(logical()) == FALSE
df_any_missing(data_frame())
#> [1] FALSE

# When looked at rowwise, a row with 0 cols is a vector of length 0,
# so that means we apply `all(logical())` on each row, getting `TRUE` for each row
df_equal_na(data_frame(.size = 5))
#> [1] TRUE TRUE TRUE TRUE TRUE

# any(c(TRUE, TRUE, TRUE, TRUE, TRUE)) == TRUE
df_any_missing(data_frame(.size = 5))
#> [1] TRUE
```

**Comment by lionel-** [comment]
This is a bit of an uncomfortable part of vctrs because we need to think about invariants both across rows and cols, instead of just across rows. Part of me wants `df_any_missing()` to return `FALSE` for empty data frames, but these zero-col data frames are not really empty and I like your reasoning.
