### ISSUE TITLE
rename vec_count 

### ISSUE THREAD

**Issue by petermeissner** [r-lib/vctrs#159]
I think. while `vec_count()` does have its purpose and is a nice feature the naming is a little misleading. 

The common term for operations like those done by `vec_count()` is tabulation: the counting of the number of occurances of keys within the data (vector).

I suggest: `vec_tab()` or `vec_tabulate()` or even `vec_key_count()` if *count* really has to be part of the name.

**Comment by krlmlr** [comment]
It's very similar to `dplyr::count()`, though.

**Comment by petermeissner** [comment]
Yeah, it is (still not the best name, I think, but consistent).
