### ISSUE TITLE
Lossy cast error messages differ depending on usage of `conditionMessage()` vs `cnd_message()`

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#1592]
``` r
library(vctrs)
library(rlang)

cnd <- catch_cnd(vec_cast(1.5, integer()))

# Partial message??
conditionMessage(cnd)
#> [1] "Can't convert `1.5` <double> to <integer>."

# Full message
cnd_message(cnd)
#> [1] "Can't convert from `1.5` <double> to <integer> due to loss of precision.\n• Locations: 1"
```

The general problem is that we have a `conditionMessage.vctrs_error_cast_lossy()` method that is being called instead of `conditionMessage.rlang_error()` (which would then call `cnd_message()`).

I think that we should remove this `conditionMessage()` method and let the `cnd_header()` and `cnd_body()` methods that we have defined for `vctrs_error_cast_lossy` handle this instead.

The `conditionMessage()` method was added here, back before the cast and type errors followed the same code paths. We also might not have known exactly how the rlang errors were going to work at that point.
https://github.com/r-lib/vctrs/commit/9b0acba8ecb10020de3c9f987f3a118db93f0b21

This issues seems to have appeared in the 0.3.8 -> 0.4.0 transition, which merged the cast and type error paths.

I notice it when writing snapshot tests. Interactively `vec_cast(1.5, integer())` throws the full error, but when `expect_snapshot()` wraps it it will show the partial error, because `expect_snapshot()` uses `conditionMessage()`

**Comment by lionel-** [comment]
> I think that we should remove this conditionMessage() method and let the cnd_header() and cnd_body() methods that we have defined for vctrs_error_cast_lossy handle this instead.

Yes exactly.
