### ISSUE TITLE
Use `arg` and `call` in `num_as_location()` argument checking

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#1601]
i.e.

```R
   if (is.object(i) || !(is_integer(i) || is_double(i))) {
        abort("`i` must be a numeric vector.")
    }
```

**Comment by hadley** [comment]
Oh maybe I'm supposed to use `vec_as_subscript()` here?

**Comment by lionel-** [comment]
Good question. This depends on how we interpret this `num_` prefix:

1. Does `num_` means you should have checked for the type beforehand, and supplying something else is an internal error?

2. Does `num_` implies we're checking the type for you?

It could make sense to go with (2).

**Comment by DavisVaughan** [comment]
I think of it as 1 tbh, like `list_sizes()` and other `list_*()` funs
