### ISSUE TITLE
Rethink casting for factor and ordered

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#161]
- [x] Should be able to cast ordered to factor
- [ ] Common type of factor and ordered should be factor
- [ ] Common type of ordered and ordered should be factor (!), perhaps with warning

**Comment by hadley** [comment]
Current behaviour:

``` r
library(vctrs)

f <- factor("a")
o <- ordered("b")

vec_c(f, o)
#> Error: No common type for `..1` <factor<127a2>> and `..2` <ordered<ddf10>>.
vec_c(o, o)
#> [1] b b
#> Levels: b
```

<sup>Created on 2020-04-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DavisVaughan** [comment]
Not sure if the second example is a typo, but that one is an ordered factor, it just doesn't have >1 levels so you wouldn't know just from the print method. Helpful!

``` r
library(vctrs)

o <- ordered("b")

vec_c(o, o)
#> [1] b b
#> Levels: b

class(vec_c(o, o))
#> [1] "ordered" "factor"
```

<sup>Created on 2020-04-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
We have now settled on the current behaviour:

- factor and ordered are never coercible
- ordered are coercible if they have the exact same set of levels
