### ISSUE TITLE
`num_as_location()` should check oob consecutiveness before filtering out zeros

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#1613]
I don't think this should work

``` r
# OOB extension check should happen before zeros are filtered
num_as_location(c(0L, 4L, 5L, 0L, 6L, 0L), 5L, zero = "remove", oob = "extend")
#> [1] 4 5 6
```

**Comment by DavisVaughan** [comment]
Oh actually this one is probably fine. For some reason I thought the oob extension had to happen at the end of the vector, but it is just saying it has to be consecutive past `5`, but it can appear anywhere

**Comment by lionel-** [comment]
yup I agree.
