### ISSUE TITLE
Explicit error when trying to create a nested record

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#165]
- [ ] records inside records
- [ ] data frames inside records

**Comment by krlmlr** [comment]
Then we should return an error here:

``` r
library(vctrs)
fields(new_rcrd(list(a = iris)))
#> [1] "a"
```

<sup>Created on 2019-01-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by hadley** [comment]
I don't think we need to do anything with this for now. It's unlikely that people will hit this problem, and we have higher priority needs.

**Comment by zachary-foster** [comment]
I made a record class with 3 record classes inside it and it seems to work fine. Are nested records supported now or should I rethink my design? If not, is there plans to support nested records in the future? Thanks!

**Comment by lionel-** [comment]
This is likely to work properly nowadays because of internal changes. The proxy of records are data frames and data frames are the recursive type in vctrs. I think it makes sense to allow nested records.

**Comment by zachary-foster** [comment]
Great, thanks!

**Comment by krlmlr** [comment]
If it works, fine! Do we have tests?
