### ISSUE TITLE
Internal error: comparing to complex

### ISSUE THREAD

**Issue by TimTaylor** [r-lib/vctrs#1655]
``` r
vctrs::vec_compare(1,1i)
#> Error in `vctrs::vec_compare()`:
#> ! Unsupported vctrs type `complex`.
#> ℹ In file 'type-info.c' at line 177.
#> ℹ This is an internal error in the vctrs package, please report it to the package authors.

#> Backtrace:
#>     ▆
#>  1. ├─vctrs::vec_compare(1, 0+1i)
#>  2. └─rlang:::stop_internal_c_lib(...)
#>  3.   └─rlang::abort(message, call = call, .internal = TRUE, .frame = frame)
```

<sup>Created on 2022-09-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by DavisVaughan** [comment]
We haven't supported comparison for complex types, as there is no meaningful way to compare them (in the sense of complex vectors). I still think this is the right decision for complex in general.

If this is in reference to https://github.com/DavisVaughan/ivs/issues/26, then this is a case where you are using complex as a _container_ for a more complex data type. It is possible that in that case we could define complex comparison as: compare reals, then break ties by comparing imaginaries.

But for now I suggest doing:

``` r
library(vctrs)

x <- new_vctr(
  complex(real = c(1, 2, 2), imaginary = c(2, 1, 1)), 
  class = "my_complex_type"
)
y <- new_vctr(
  complex(real = c(1, 1, 2), imaginary = c(2, 1, 2)), 
  class = "my_complex_type"
)

vec_proxy_compare.my_complex_type <- function(x, ...) {
  vctrs::data_frame(real = Re(x), imag = Im(x))
}

x
#> <my_complex_type[3]>
#> [1] 1+2i 2+1i 2+1i
y
#> <my_complex_type[3]>
#> [1] 1+2i 1+1i 2+2i
vec_compare(x, y)
#> [1]  0  1 -1
```

<sup>Created on 2022-09-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by TimTaylor** [comment]
Related - but only as I was curious what `vec_compare()` would say if I gave it a complex number. Definitely correct to error IMO  but I was expecting an error message such as `complex numbers are not comparable` and not the additional info points:
```
#> ℹ In file 'type-info.c' at line 177.
#> ℹ This is an internal error in the vctrs package, please report it to the package authors.
```

**Comment by DavisVaughan** [comment]
Yea it probably shouldn't be an internal error
