### ISSUE TITLE
`vec_shape_broadcast()` evaluation error

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#1666]
With dev vctrs installed

```r
> slider::slide_sum(array(1:4, dim = c(2, 2)), before = 1)
Error in shape_broadcast(x = x, to = to, x_arg = x_arg, to_arg = to_arg,  : 
  could not find function "shape_broadcast"
```

I'm fairly certain this is because slider directly calls a number of vctrs C callables, like these:
https://github.com/DavisVaughan/slider/blob/main/src/slider-vctrs-private.c

But when the R implementation of `shape_broadcast` is looked up in `vec_shape_broadcast()`, `vctrs_eval_mask5()` ends up using `r_peek_frame()` as the environment to look `shape_broadcast()` up in.
https://github.com/r-lib/vctrs/blob/cd18ecbcccdef0cf05a9cb8975777d988c85108a/src/utils.c#L65

But if I understand correctly, this is where `.Call()` is called from, which is the slider namespace, not the vctrs one.

I'm not sure if `vctrs_eval_mask_n()` should always use the vctrs namespace or if this is just a special case where we need to hard code something to use the vctrs namespace.

**Comment by lionel-** [comment]
It's nice to use the caller-env so that the calls form a continuous branch in the backtrace tree.
I think we can fix this by calling `vctrs:::shape_broadcast()`.

oh but with `eval_mask()`, we'll never have a continuous backtrace to begin with... So yeah, we may as well evaluate in the vctrs namespace.

**Comment by DavisVaughan** [comment]
Does this walk back this idea? https://github.com/r-lib/vctrs/issues/701

**Comment by lionel-** [comment]
Yes but also no because we were evaluating in a child of the caller frame anyway.
