### ISSUE TITLE
merge fails when vctrs integer or numeric is matched against base numeric or integer.

### ISSUE THREAD

**Issue by bergsmat** [r-lib/vctrs#1669]
Hi, and thanks for a great package!

I have implemented a vctrs class 'dvec' in the CRAN package 'yamlet'.  I think I have a complete set of coercion functions for base types.  Yet I can't get matches when I merge, say, a numeric 'dvec' with an equivalent integer, and vice versa (see NA resulting from the 3rd and 4th left joins in the reprex).  Is this behavior expected?  I followed the issue down to ```vctrs_match```, which seems to be a C++ call.

``` r
suppressMessages(library(dplyr))
suppressMessages(library(yamlet))

# coercible
c(1, 1L, as_dvec(1), as_dvec(1L))
#> [1] 1 1 1 1

left_join( # ok
  data.frame(ID = as_dvec(1)),
  data.frame(ID = 1, TIME = 0)
)
#> Joining, by = "ID"
#>   ID TIME
#> 1  1    0

left_join( # ok
  data.frame(ID = as_dvec(1L)),
  data.frame(ID = 1L, TIME = 0)
)
#> Joining, by = "ID"
#>   ID TIME
#> 1  1    0

left_join( # no match
  data.frame(ID = as_dvec(1L)),
  data.frame(ID = 1, TIME = 0)
)
#> Joining, by = "ID"
#>   ID TIME
#> 1  1   NA

left_join( # no match
  data.frame(ID = as_dvec(1)),
  data.frame(ID = 1L, TIME = 0)
)
#> Joining, by = "ID"
#>   ID TIME
#> 1  1   NA
```

<sup>Created on 2022-09-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by DavisVaughan** [comment]
I think your ptype2 and cast rules are a little off, I've tried to demonstrate that here:

``` r
library(vctrs)
library(yamlet)

# <dvec<int>> + <dbl> = <dvec<int>>
# seems wrong, should probably be <dvec<dbl>>
ptype <- vec_ptype2(as_dvec(1L), 1)
str(ptype)
#>  'dvec' int(0)

# try casting both inputs to the <dvec<int>> common type:
# - <dvec<int>> -> <dvec<int>>
# - <dbl> -> <dvec<dbl>> (wrong, should be <dvec<int>>)
# This won't work, both result types need to be the exact same
str(vec_cast_common(as_dvec(1L), 1, .to = ptype))
#> List of 2
#>  $ : 'dvec' int 1
#>  $ : 'dvec' num 1
```

<sup>Created on 2022-09-17 with [reprex v2.0.2.9000](https://reprex.tidyverse.org)</sup>

**Comment by DavisVaughan** [comment]
I'm convinced this isn't a vctrs issue though, so I'm going to close on our end

**Comment by bergsmat** [comment]
@DavisVaughan Thank you for identifying the expectations above!  They led directly to a systematic solution.
