### ISSUE TITLE
vec_order_base() function not found 

### ISSUE THREAD

**Issue by esraagithub** [r-lib/vctrs#1696]
hello
 i installed version 0.4.1.9
 i got this massage while executing library(tidyverse)

Error: package or namespace load failed for ‘tidyverse’:
 .onLoad failed in loadNamespace() for 'dplyr', details:
  call: import_from(name, "vctrs")
  error: No such 'vctrs' function: `vec_order_base()'

**Comment by lionel-** [comment]
You are using a dev version of vctrs. Are you also using a dev version of dplyr? If so you might need to update to the latest dplyr dev version.

**Comment by DavisVaughan** [comment]
Yea very likely you just need to do `pak::pak("tidyverse/dplyr")` and restart R
