### ISSUE TITLE
A better summary

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#17]
Data frame, and grouped_df methods

select() semantics

Return tibble. One row per var, then break into groups. Col of types. List col of summaries. 

Logical gives number of T/F/NA.

Integer/numeric min-[Q1 [median] Q3]-max NA:  Inf?: [].  Extract out common multiple 10³ x 1-[5 [10] 11]-20

For date/time, just display range. Need to special case if min & max on same day (do it by year/month/day/hour/minute ?). 

Factors to give compact freq table. In one line. How?? (print method based on width?)

Characters give summary of length (1-20 chars). Encoding?. Number of empty & missing.

For unknown type, use obj_sum

https://github.com/holman/spark

**Comment by randomgambit** [comment]
Hi there @hadley @sfiske, for what it's worth here are my thoughts on the matter. 

Just a bit of background about me. I am an econ Phd working at a very large organisation and essentially doing academic research. I use `r`, `python` and `stata` every day and I try to hit a top journal in my finance/econ field.

As I mentioned @sfirke some time ago (https://github.com/sfirke/janitor/issues/84), I think a nice summary function is missing in the `tidyverse` and that is really problematic. 

For tabulation and crosstabulation, fortunately, there is `janitor` (see also https://github.com/matthieugomez/statar), but for a proper state-of-the-art summary stats of the columns of my dataframe, I am alone in the wild. 

To be honest, I think many good ideas can come from `stata`. This software was built for researchers and contains many routines that are the starting point of any serious empirical work: quickly examining the patterns in the data, the missing values, etc.

We should be able to use a `tidyverse`-proof summary function that intelligently understands the type of the columns, and prints an output that is relevant for that type. So, following up on @hadley, here are my remarks:

1. Logical gives number of T/F/NA, **yes, but also percentages!**
2. Integer/numeric min-[Q1 [median] Q3]-max NA: Inf?: []. Extract out common multiple 10³ x 1-[5 [10] 11]-20. **we should be able to feed the percentiles directly if we need (say p10 p20 and p95). I dont see the benefits of extracting the common multiple.**
3. For date/time, just display range. Need to special case if min & max on same day (do it by year/month/day/hour/minute ?) **Quite the opposite, I think a nice summary stat function for `datetime` variable can add a lot of value. For instance something similar to Stata's `tsreport` (http://www.stata.com/manuals13/tstsreport.pdf) that reports time gaps in a dataset would be very useful.**
4. Factors to give compact freq table. just use `janitor` hehehe
5. Characters give summary of length (1-20 chars). Encoding?. Number of empty & missing. **Maybe also most common string?**
6. what about panel data? Have a look at `xtsum` in stata that gives a nice `within` , `between` and `overall` variation of a variable that is key in any OLS setting (http://www.stata.com/manuals13/xtxtsum.pdf)

In any case, keep up the good work!
Thanks

**Comment by hadley** [comment]
I now think that is out of scope for vctrs, and would be better off in its own package (e.g. https://github.com/ropensci/skimr)
