### ISSUE TITLE
usethis-like function to create boilerplate code

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#170]
perhaps with RStudio add-in?

- [ ] construction
- [ ] validation
- [ ] casting
- [ ] coercion
- [ ] `as_()` and `is_()`
- [ ] `setOldClass()`
- [ ] tests (with a separate function?)

**Comment by jennybc** [comment]
Tests?

**Comment by krlmlr** [comment]
Would that be another function -- `use_vctr(name)` and `use_vctr_test(name = active_file_name())` ?

**Comment by jennybc** [comment]
I'm not sure. I just want to put register the fact that there may be some standard test-able behaviours that could be scaffolded with an eventual template for vctrs S3 boilerplate.

**Comment by hadley** [comment]
I think we can close this now, since the amount of boilerplate will dramatically decrease once #985 is implemented
