### ISSUE TITLE
vec_slice<-() should not add names

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#171]
Currently, can assign a named slice to an unnamed vector. This should be an error.

Related to #140?

``` r
library(vctrs)

a <- new_vctr(1:3)
vec_slice(a, "x") <- 4L
a
#> <vctrs_vctr[4]>
#>       x 
#> 1 2 3 4

new_vctr(c(1:3, a = 4))
#> Error: If any elements of `.data` are named, all must be named
```

<sup>Created on 2019-01-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by krlmlr** [comment]
@hadley: How do we ensure that all vectors are either named everywhere or unnamed, even after updates?

**Comment by hadley** [comment]
We should only allow slicing with a character vector if the vector has names?
