### ISSUE TITLE
Expose more re: `"unique_quiet"` and `"universal_quiet"`

### ISSUE THREAD

**Issue by jennybc** [r-lib/vctrs#1713]
From the side conversation in #1703

I'm going to make it more clear which _other_ functions, besides `vec_as_names()` and `vec_names2()`, can make use of the new strings.

First, I gathered a some data on which options are presented for the repair arg of various functions:

```
  fcn            arg_nm       repair_vals                                                                 
   <chr>          <chr>        <chr>                                                                       
 1 data_frame     .name_repair check_unique | unique | universal | minimal                                 
 2 df_list        .name_repair check_unique | unique | universal | minimal                                 
 3 list_unchop    name_repair  minimal | unique | check_unique | universal                                 
 4 vec_c          .name_repair minimal | unique | check_unique | universal                                 
 5 vec_interleave .name_repair minimal | unique | check_unique | universal                                 
 6 vec_unchop     name_repair  minimal | unique | check_unique | universal                                 
 7 vec_as_names   repair       minimal | unique | universal | check_unique | unique_quiet | universal_quiet
 8 vec_names2     repair       minimal | unique | universal | check_unique | unique_quiet | universal_quiet
 9 vec_rbind      .name_repair unique | universal | check_unique                                           
10 vec_cbind      .name_repair unique | universal | check_unique | minimal    
```

Can @lionel- or @DavisVaughan confirm that the existing differences re: which strings appear and in which order are intentional? In which I case I should presumably preserve those differences. If any of it is an accident of history, maybe this is a good occasion to standardize.

**Comment by jennybc** [comment]
I propose a simplification: everything should literally or morally inherit the docs in `vec_as_names()`. What I mean by "morally": inherit from `vec_c()` which has the very brief "How to repair names, see `repair` options in `vec_as_names()`".

And then, assuming the signature differences are intentional, the definitive docs for repair should gain a sentence indicating that the signature of each function indicates which strings are allowed (or recommended?).

**Comment by lionel-** [comment]
> Can @lionel- or @DavisVaughan confirm that the existing differences re: which strings appear and in which order are intentional

At least the default item (position 1) is intentional. I'm not sure regarding the orders of the remaining items but I would probably preserve them.

> I propose a simplification: everything should literally or morally inherit the docs in vec_as_names(). What I mean by "morally": inherit from vec_c() which has the very brief "How to repair names, see repair options in vec_as_names()".
> 
> And then, assuming the signature differences are intentional, the definitive docs for repair should gain a sentence indicating that the signature of each function indicates which strings are allowed (or recommended?).

I'm slightly worried this might be a bit confusing, but it seems like the simplicity this brings is worth it. If a different topic is needed to be able to provide the most relevant information to `vec_as_names()` callers, the documentation could live in `?vctrs::args_name_repair`, similarly to e.g. `?rlang::args_error_context`.
