### ISSUE TITLE
vec_slice error - reporting as requested

### ISSUE THREAD

**Issue by b11235** [r-lib/vctrs#1718]
i was trying to run code from https://www.anycodings.com/1questions/1125956/how-to-use-accumulate-function-to-calculate-2-intertwining-variables. I assume this code worked at some point, but I have no evidence of that.

code is:
library(tidyverse, warn.conflicts = F)

ddf <- structure(list(Scenario = c(0, 1, 1, 1, 1, 1, 1, 1, 1, 1),
                     SlNo = c(NA, 1L, 5L, 9L, 13L, 17L, 21L, 25L, 29L, 33L),
                     A = c(NA, 14, 1, 17, 10, 9, 14, 14, 4),
                     B = c(NA, 19, 13, 20, 7, 16, 12, 18, 15, 17),
                     C = c(4, 0, 0, 0, 0, 0, 0, 0, 0, 0),
                     E = c(6, 0, 0, 0, 0, 0, 0, 0, 0, 0)),
                row.names = c(NA, -10L),
                class = c("tbl_df", "tbl", "data.frame"))

df[1:4] %>%
  filter(Scenario != 0) %>%
  mutate(new = accumulate(B, 
                          .init = tibble(C = 4, E = 6),
                          ~ tibble(C = (1 -0.5)* .x$C + 5 + .y + .x$E,
                                   E = 0.5 * .x$C + 5 + .x$E + 2 * .y - 50
                                   )
                          )[-1]
         ) %>% 

I received the following error:
Error in `vec_slice()`:
! Column `A` (size 9) must match the data frame (size 10).
ℹ In file slice.c at line 188.
ℹ This is an internal error that was detected in the vctrs package.
  Please report it at <https://github.com/r-lib/vctrs/issues> with a [reprex](https://https://tidyverse.org/help/) and the full backtrace.
Backtrace:
     ▆
  1. ├─tidyr::unnest_wider(...)
  2. │ └─base::is.data.frame(data)
  3. ├─dplyr::mutate(...)
  4. ├─dplyr::filter(df[1:4], Scenario != 0)
  5. ├─dplyr:::filter.data.frame(df[1:4], Scenario != 0)
  6. │ ├─dplyr::dplyr_row_slice(.data, loc, preserve = .preserve)
  7. │ └─dplyr:::dplyr_row_slice.data.frame(.data, loc, preserve = .preserve)
  8. │   ├─dplyr::dplyr_reconstruct(vec_slice(data, i), data)
  9. │   │ └─dplyr:::dplyr_new_data_frame(data)
 10. │   │   ├─row.names %||% .row_names_info(x, type = 0L)
 11. │   │   └─base::.row_names_info(x, type = 0L)
 12. │   └─vctrs::vec_slice(data, i)
 13. └─rlang:::stop_internal_c_lib(...)
 14.   └─rlang::abort(message, call = call, .internal = TRUE, .frame = frame)
 Error in vec_slice(data, i) :
16.
stop(fallback)
15.
signal_abort(cnd, .file)
14.
abort(message, call = call, .internal = TRUE, .frame = frame)
13.
stop_internal_c_lib(file = file, line = line, call = call, message = message, 
frame = frame)
12.
vec_slice(data, i)
11.
.row_names_info(x, type = 0L)
10.
row.names %||% .row_names_info(x, type = 0L)
9.
dplyr_new_data_frame(data)
8.
dplyr_reconstruct(vec_slice(data, i), data)
7.
dplyr_row_slice.data.frame(.data, loc, preserve = .preserve)
6.
dplyr_row_slice(.data, loc, preserve = .preserve)
5.
filter.data.frame(df[1:4], Scenario != 0)
4.
filter(df[1:4], Scenario != 0)
3.
mutate(filter(df[1:4], Scenario != 0), new = accumulate(B, .init = tibble(C = 4, 
E = 6), ~tibble(C = (1 - 0.5) * .x$C + 5 + .y + .x$E, E = 0.5 * 
.x$C + 5 + .x$E + 2 * .y - 50))[-1])
2.
is.data.frame(data)
1.
unnest_wider(mutate(filter(df[1:4], Scenario != 0), new = accumulate(B, 
.init = tibble(C = 4, E = 6), ~tibble(C = (1 - 0.5) * .x$C + 
5 + .y + .x$E, E = 0.5 * .x$C + 5 + .x$E + 2 * .y - 50))[-1]), 
new)

**Comment by b11235** [comment]
from reprex:

``` r
df <- structure(list(Scenario = c(0, 1, 1, 1, 1, 1, 1, 1, 1, 1),
                     SlNo = c(NA, 1L, 5L, 9L, 13L, 17L, 21L, 25L, 29L, 33L),
                     A = c(NA, 14, 1, 17, 10, 9, 14, 14, 4),
                     B = c(NA, 19, 13, 20, 7, 16, 12, 18, 15, 17),
                     C = c(4, 0, 0, 0, 0, 0, 0, 0, 0, 0),
                     E = c(6, 0, 0, 0, 0, 0, 0, 0, 0, 0)),
                row.names = c(NA, -10L),
                class = c("tbl_df", "tbl", "data.frame"))

df[1:4] |>
  filter(Scenario != 0) |>
  mutate(new = accumulate(B, 
                          .init = tibble(C = 4, E = 6),
                          ~ tibble(C = (1 -0.5)* .x$C + 5 + .y + .x$E,
                                   E = 0.5 * .x$C + 5 + .x$E + 2 * .y - 50
                                   )
                          )[-1]
         ) |> unnest_wider(new)
#> Error in unnest_wider(mutate(filter(df[1:4], Scenario != 0), new = accumulate(B, : could not find function "unnest_wider"
```

<sup>Created on 2022-10-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by lionel-** [comment]
Thanks for the report. The problem is that the data frame is not constructed correctly. The column A doesn't have the right size:

```r
> lengths(ddf)
Scenario     SlNo        A        B        C        E 
      10       10        9       10       10       10 
```

So this is not a problem in vctrs but in the way this data frame has been constructed from raw data. If it had been constructed using a proper constructor (such as `data.frame()`), the data would have been validated earlier before the vctrs call.

I believe this "anycoding" site is stealing contents from Stackoverflow. Here is the original URL in case you'd like to report there: https://stackoverflow.com/questions/68259139/how-to-use-accumulate-function-to-calculate-2-intertwining-variables

**Comment by lionel-** [comment]
No worries!
