### ISSUE TITLE
This is an internal error that was detected in the vctrs package.

### ISSUE THREAD

**Issue by Helia-sudo** [r-lib/vctrs#1745]
├─dplyr::bind_rows(df2, df2_n)
 2. │ ├─dplyr:::fix_call(vec_rbind(!!!dots, .names_to = .id))
 3. │ │ └─base::withCallingHandlers(...)
 4. │ └─vctrs::vec_rbind(!!!dots, .names_to = .id)
 5. │   └─vctrs (local) `<fn>`()
 6. │     └─vctrs::vec_proxy(x = x)
 7. │       └─vctrs:::date_validate(x)
 8. └─rlang:::stop_internal_c_lib(...)
 9.   └─rlang::abort(message, call = call, .internal = TRUE, .frame = frame)

**Comment by DavisVaughan** [comment]
Closing until we get more information
