### ISSUE TITLE
Support indirect vectors

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#177]
via `vec_islice()` and the following invariants:

```r
identical(vec_size(vec_islice(x, i)), vec_size(vec_slice(x, i)))
identical(vec_materialize(vec_islice(x, i)), vec_slice(x, i))

identical(vec_slice(vec_islice(x, i1), i2), vec_islice(x, i1[i2]))

cache <- new_cache()
identical(vec_islice(tbl, i), tibble(!!!map(tbl, vec_islice, i, cache)))
```

The cache memoizes results of index subsetting operations `i1[i2]`, in case we're islicing indirect vectors: we don't want to store multiple identical index vectors.

Implementation could be a wrapper around arbitrary vector classes:

```r
new_deferred <- function(vctr, i) {
  structure(list(vctr), i = i, class = c("vctrs_deferred", "vctrs_vctr"))
}

indexes <- function(x) attr(x, "i")
full <- function(x) x[[1L]]

vec_islice <- function(x, i, cache) {
  if (is_deferred(x)) {
    ii <- cache$get(indexes(x), i)
    if (is.null(ii)) {
      ii <- indexes(x)[i]
      cache$set(indexes(x), i, ii)
    }
    new_deferred(full(x), ii)
  } else {
    new_deferred(x, i)
  }
}

vec_slice_deferred <- function(x, i) {
  # Perhaps also need cache
  vec_slice(full(x), indexes(x)[i])
}
```

This might be easier to implement if we restrict the scope of vector types we support, i.e., we assume all vectors are one of:

- atomic vectors
- matrices, arrays
- records of **atomic** vectors (#165)

**Comment by hadley** [comment]
This is out of scope for vctrs currently.
