### ISSUE TITLE
no package called 'vctrs' error when package not yet installed & cannot remove prior install

### ISSUE THREAD

**Issue by RickPack** [r-lib/vctrs#1789]
As communicated at https://github.com/r-lib/vctrs/issues/1234 and https://github.com/The-Strategy-Unit/707_covid_outpatients_data_pulling/issues/1, I am getting this error when I use `devtools::install_github('r-lib/vctrs')` prior to installing the package:
`there is no package called 'vctrs'`
 
Correction: Installing from CRAN was not sufficient for install / updating through Github. I see the following even with a fresh load of R:
`ERROR: cannot remove earlier installation, is it in use?`

> (.packages())
[1] "stats"     "graphics"  "grDevices" "utils"     "datasets"  "methods"  
[7] "base"

**Comment by lionel-** [comment]
This looks like a user / admin question so you might have better luck on a forum as we're not experts.

Can you please check that

- You don't have any RStudio / R session running at all - it's not sufficient to merely use a fresh session if another sessions runs alongside
- `sessionInfo()` only shows base packages in fresh sessions - your RProfile might load packages
- There is no LOCK files in your library folders (see `.libPaths()`)
- Try installing packages with pak
- Try starting over by removing all packages

**Comment by RickPack** [comment]
Thank you, @lionel. You helped me solve the problem. The devtools package had a dependency on vctrs that was causing the deletion of the package folder to trigger an error. Why R could not remove the earlier installation remains a mystery.

**Comment by lionel-** [comment]
Thanks for letting us know!

I think this problem would have been avoided by using `pak::pak()` (see https://pak.r-lib.org/) or `remotes::install_github()`
