### ISSUE TITLE
vec_slice() cannot slice 0-column data.frames properly

### ISSUE THREAD

**Issue by yutannihilation** [r-lib/vctrs#179]
``` r
library(vctrs)
library(tibble)

vec_slice(tibble(.rows = 3), 1:3)
#> # A tibble: 0 x 0

vec_slice(tibble(x = tibble(.rows = 3)), 1:3)
#> Error: Positive column indexes in `[` must match number of columns:
#> * `.data` has 0 columns
#> * Position 1 equals 1
#> * Position 2 equals 2
#> * Position 3 equals 3
#> Backtrace:
#>     █
#>  1. └─vctrs::vec_slice(tibble(x = tibble(.rows = 3)), 1:3)
#>  2.   └─base::lapply(x, `[`, i)
#>  3.     ├─base:::FUN(X[[i]], ...)
#>  4.     └─tibble:::`[.tbl_df`(X[[i]], ...)
#>  5.       └─tibble:::check_names_df(i, x)
#>  6.         └─tibble:::check_names_df_numeric(j, x)
```

<sup>Created on 2019-01-31 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by yutannihilation** [comment]
It seems rownames are lost here:

https://github.com/r-lib/vctrs/blob/ed62f1efedd118c8e0cdeb7416ccd197546e575a/R/size.R#L108-L109

**Comment by yutannihilation** [comment]
To fix this, I feel we have to provide the expected length to `vec_restore()`. Otherwise it cannot know what length the result is supposed to be.

``` r
library(vctrs)

x <- tibble::tibble(.rows = 3)
out <- lapply(x, vec_slice, 1)

# the expected length is 1, but neither of out nor x know it here
vec_restore(out, x)
#> # A tibble: 0 x 0
```

<sup>Created on 2019-02-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Does this looks OK...? if so, I'll make a PR.

```r
vec_restore <- function (x, to, ...) {
    UseMethod("vec_restore", to)
}

vec_restore.data.frame <- function (x, to, n = NULL, ...) {
  ...
  attr_to[["row.names"]] <- .set_row_names(n %||% df_length(x))
  ...
}
```

**Comment by hadley** [comment]
I think if you have to supply arguments, it's a sign that you shouldn't be using `vec_restore()` — I think I may have used `vec_restore()` in places (like here) where it's not actually suitable.

**Comment by yutannihilation** [comment]
Hmm..., thanks, I agree it's a bad sign. But, I don't think I "shouldn't be using `vec_restore()`," because `vec_restore()` is still useful (as long as it doesn't raise errors) for restoring classes and attributes except for rownames.

Probably, we can add rownames again after `vec_restore()`. Or, do you think it's better to remove `vec_restore()` here?

**Comment by hadley** [comment]
The more I think about it, the more I think this use of `vec_restore()` is inappropriate — this clause is just a hack around the slowness of `[.data.frame` and there's no guarantee that it will work with other data frame subclasses. 

I'm not sure what we should do here given that `[.tibble` is much more efficient, so there's no need for the hack. I suspect we should be testing `identical(class(x), "data.frame")` and then calling `new_data_frame()` on the output of the `lapply()`. 

Alternatively, this might be resolved by #124, where we'll make `vec_slice` generic, so it would make more sense to provide our own specialised implementation of row-subsetting a data frame.

**Comment by yutannihilation** [comment]
Thanks, given the current `vec_slice()` is just a hack for speed, that's convincing. Then I'll just wait for other discussions.

**Comment by hadley** [comment]
Oh please leave this one open; it was way more info.

**Comment by yutannihilation** [comment]
Ah, sorry. Sure.

**Comment by hadley** [comment]
It turns out that the fixes needed for the newly focussed #199, also ended up fixing this issue. I _think_ this is correct because I was just too aggressively throwing away the row names attribute (throwing the baby out with the bath water), but I'd appreciate it if you'd take a look at the patch and see if it makes sense to you too.

**Comment by yutannihilation** [comment]
@hadley Sorry, I don't think this is "fixed." The second one below no more raises an error, but the result seems still incorrect; the dimensions should be 3 x 0, and 3 x 1.

``` r
library(vctrs)
library(tibble)

packageDescription("vctrs")["GithubSHA1"]
#> $GithubSHA1
#> [1] "3b80a81418d0f8037f86e875e80e5a73b2744485"

vec_slice(tibble(.rows = 3), 1:3)
#> # A tibble: 0 x 0

vec_slice(tibble(x = tibble(.rows = 3)), 1:3)
#> # A tibble: 0 x 1
#> # ... with 1 variable: x <lgl>
```

<sup>Created on 2019-02-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by hadley** [comment]
Ok, that's actually reassuring to me 😄

**Comment by hadley** [comment]
Ok, I am now pretty sure I have fixed it properly — it's sort of a hack on top of a hack, but if we're going to coerce into a list to avoid expensive `[.data.frame` calls, then we also need to create the correct `row.names` attribute. In the future, we'll resolve this more rigorously by implementing `vec_slice()` in C, and more carefully figuring out what we need to do when `x` is a data.frame vs. a data frame subclass.

**Comment by yutannihilation** [comment]
Confirmed the fix, thanks!
