### ISSUE TITLE
Error merging datasets

### ISSUE THREAD

**Issue by meg8803** [r-lib/vctrs#1797]
Backtrace:
    ▆
 1. ├─dplyr::inner_join(regSeasonCompact, TourneySeedOrdinal)
 2. ├─dplyr:::inner_join.data.frame(regSeasonCompact, TourneySeedOrdinal)
 3. │ └─dplyr:::join_mutate(...)
 4. │   └─dplyr:::join_rows(...)
 5. │     └─dplyr:::dplyr_locate_matches(...)
 6. │       ├─base::withCallingHandlers(...)
 7. │       └─vctrs::vec_locate_matches(...)
 8. └─rlang:::stop_internal_c_lib(...)
 9.   └─rlang::abort(message, call = call, .internal = TRUE, .frame = frame)

**Comment by DavisVaughan** [comment]
Thanks, we will need a full reprex (https://reprex.tidyverse.org/articles/learn-reprex.html) to be able to help you with this

**Comment by DavisVaughan** [comment]
Closing until we get more information
