### ISSUE TITLE
Error in `vctrs::vec_locate_matches()`:

### ISSUE THREAD

**Issue by grobenorc** [r-lib/vctrs#1798]
Backtrace:
     ▆
  1. ├─... %>% ...
  2. ├─dplyr::mutate(...)
  3. ├─dplyr::left_join(., data, tab_drivers, by = "driverId")
  4. ├─dplyr:::left_join.data.frame(., data, tab_drivers, by = "driverId")
  5. │ └─dplyr:::join_mutate(...)
  6. │   └─dplyr:::join_rows(...)
  7. │     └─dplyr:::dplyr_locate_matches(...)
  8. │       ├─base::withCallingHandlers(...)
  9. │       └─vctrs::vec_locate_matches(...)
 10. └─rlang:::stop_internal_c_lib(...)
 11.   └─rlang::abort(message, call = call, .internal = TRUE, .frame = frame)

**Comment by DavisVaughan** [comment]
Thanks, we will need a full reprex (https://reprex.tidyverse.org/articles/learn-reprex.html) to be able to help you with this

**Comment by DavisVaughan** [comment]
Closing until we get more information
