### ISSUE TITLE
Not precise documentation of `vec_duplicate_any()`

### ISSUE THREAD

**Issue by echasnovski** [r-lib/vctrs#180]
In description of `vec_duplicate_any()` (in [these lines](https://github.com/r-lib/vctrs/blob/0715639f700370ed07147000ed9b5a1e0ce06c33/R/dictionary.R#L78)) it is described as doing "the same way as `anyDuplicated()`". However, as I recently found out myself, `anyDuplicated()` doesn't return single logical value but rather "an integer or real vector of length one with value the 1-based index of the first duplicate if any, otherwise 0".

Reprex:
``` r
vctrs::vec_duplicate_any(c(1, 2, 1))
#> [1] TRUE
anyDuplicated(c(1, 2, 1))
#> [1] 3
```

<sup>Created on 2019-02-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by hadley** [comment]
Oh wow, that's not what I thought `anyDuplicated()` did!
