### ISSUE TITLE
fasstr Date Validate error

### ISSUE THREAD

**Issue by Rpaq** [r-lib/vctrs#1802]
I am wanting to pull information from 2 gauge stations using fasstr and I get this message: 

**Station number: 07GB003**

Error in `date_validate()`:
! Corrupt `Date` with unknown type logical.
ℹ In file 'type-date-time.c' at line 344.
ℹ Install the winch package to get additional debugging info the next time you get this error.
ℹ This is an internal error that was detected in the vctrs package.
  Please report it at <https://github.com/r-lib/vctrs/issues> with a reprex (<https://https://tidyverse.org/help/>) and the full backtrace.
Backtrace:
     ▆
  1. ├─fasstr::calc_annual_lowflows(station_number = "07GB003", roll_days = 7)
  2. │ ├─base::`$<-`(`*tmp*`, "MIN_DATE", value = `<date>`)
  3. │ ├─dplyr:::`$<-.grouped_df`(`*tmp*`, "MIN_DATE", value = `<date>`)
  4. │ ├─base::NextMethod()
  5. │ └─tibble:::`$<-.tbl_df`(`*tmp*`, "MIN_DATE", value = `<date>`)
  6. │   └─tibble:::tbl_subassign(...)
  7. │     └─tibble:::vectbl_recycle_rhs_rows(...)
  8. │       ├─base::withCallingHandlers(...)
  9. │       └─vctrs::vec_recycle(value[[j]], nrow)
 10. │         └─vctrs (local) `<fn>`()
 11. │           └─vctrs::vec_proxy(x = x)
 12. │             └─vctrs:::date_validate(x)
 13. └─rlang:::stop_internal_c_lib(...)
 14.   └─rlang::abort(message, call = call, .internal = TRUE, .frame = frame)

**Station number: 07GB001**

Error in `date_validate()`:
! Corrupt `Date` with unknown type logical.
ℹ In file 'type-date-time.c' at line 344.
ℹ Install the winch package to get additional debugging info the next time you get this error.
ℹ This is an internal error that was detected in the vctrs package.
  Please report it at <https://github.com/r-lib/vctrs/issues> with a reprex (<https://https://tidyverse.org/help/>) and the full backtrace.
Backtrace:
     ▆
  1. ├─fasstr::calc_annual_lowflows(station_number = "07GB001", roll_days = 7)
  2. │ ├─base::`$<-`(`*tmp*`, "MIN_DATE", value = `<date>`)
  3. │ ├─dplyr:::`$<-.grouped_df`(`*tmp*`, "MIN_DATE", value = `<date>`)
  4. │ ├─base::NextMethod()
  5. │ └─tibble:::`$<-.tbl_df`(`*tmp*`, "MIN_DATE", value = `<date>`)
  6. │   └─tibble:::tbl_subassign(...)
  7. │     └─tibble:::vectbl_recycle_rhs_rows(...)
  8. │       ├─base::withCallingHandlers(...)
  9. │       └─vctrs::vec_recycle(value[[j]], nrow)
 10. │         └─vctrs (local) `<fn>`()
 11. │           └─vctrs::vec_proxy(x = x)
 12. │             └─vctrs:::date_validate(x)
 13. └─rlang:::stop_internal_c_lib(...)
 14.   └─rlang::abort(message, call = call, .internal = TRUE, .frame = frame)

**Comment by DavisVaughan** [comment]
Closing in favor of https://github.com/bcgov/fasstr/issues/93
