### ISSUE TITLE
Error in `vec_slice()`:

### ISSUE THREAD

**Issue by Bece-Er** [r-lib/vctrs#1804]
Error in `vec_slice()`:
! Column `after` (size 59) must match the data frame (size 30).
ℹ In file slice.c at line 188.
ℹ Install the winch package to get additional debugging info the next time you get this error.
ℹ This is an internal error that was detected in the vctrs package.
  Please report it at <https://github.com/r-lib/vctrs/issues> with a reprex and the full backtrace.
Backtrace:
    ▆
 1. ├─df %>% track(clean_vorgaben, "Vorgaben")
 2. ├─global track(., clean_vorgaben, "Vorgaben")
 3. │ └─rec %>% ...
 4. ├─dplyr::left_join(...)
 5. ├─dplyr:::left_join.data.frame(...)
 6. │ └─dplyr:::join_mutate(...)
 7. │   └─vctrs::vec_slice(y_out, y_slicer)
 8. └─rlang:::stop_internal_c_lib(...)
 9.   └─rlang::abort(message, call = call, .internal = TRUE, .frame = frame)

reprex:

I have a data frame:

        entry_key          Vorgaben
1          1               0,00 .. 99,00 g/l
2          2                0,00 .. 9,99 g/l
3          3               0,00 .. 99,99 g/l
4          4               7,00 .. 13,00 g/l
5          5                2,10 .. 3,90 g/l
6          6               0,00 .. 99,00 g/l
7         22               0,00 .. 99,00 g/l
8         23                0,00 .. 9,99 g/l
9         24               0,00 .. 99,99 g/l
10        25               7,00 .. 13,00 g/l

library(stringr)
library(tidyverse)

df<-list(df)

track <- function(df,fun,...){
  
  cnames <- colnames(df[[1]])
  args <- list()
  args <- append(args,list(...))
  columns <- str_flatten(unique(unlist(args))[unique(unlist(args)) %in% colnames(df[[1]])],collapse=", ")
  
  rec <- df[[1]] %>% select(entry_key,colnames(df[[1]])[colnames(df[[1]]) %in% args]) %>%
    unite("before",-entry_key,sep=", ") %>%
    mutate(columns=columns)
  
  df[[1]] <- df[[1]] %>% 
    fun(...)
  
  new.cols <- colnames(df[[1]])[!(colnames(df[[1]])) %in% cnames]
  
  rec <- rec %>%
    left_join(df[[1]] %>% 
                select(entry_key,
                       all_of(cnames[cnames %in% args]),
              all_of(new.cols)) %>%
    unite("after",all_of(cnames[cnames %in% args]),sep=", "))
    
  if(length(new.cols>0)){
    rec <- rec %>%
      pivot_longer(cols=new.cols,names_to = "new_colname",values_to = "new_colvalue")
  }
  
  rec <- rec %>%
    mutate(function_code=str_squish(deparse1(fun)))
  
  df[['rec']] <- rbind(df[['rec']],rec)
  df
}

clean_vorgaben <- function(df,col){
    
    df <- df %>%
      mutate({{col}}:=str_replace_all(.[[col]],pattern = "\\.\\.","to")) %>%
      mutate({{col}}:=do.call(comma_to_dots,list(df,col)))
    df
  }

comma_to_dots <- function(df,col){
  df<-df %>%
    mutate({{col}}:=str_replace_all(.[[col]],pattern = ",","\\."))
  df
  }

df <- list(

The error message above was produced and reproduced with the following line:

df2 <- df %>% 
track(clean_vorgaben,"Vorgaben")

**Comment by DavisVaughan** [comment]
Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

You can install reprex by running (you may already have it, though, if you have the tidyverse package installed):
```r
install.packages("reprex")
```

Thanks
