### ISSUE TITLE
Indicate that `vec_assert()` is not encouraged

### ISSUE THREAD

**Issue by billdenney** [r-lib/vctrs#1812]
"And we don't encourage using `vec_assert()` now because of the difficulties of `ptype`, so I don't think we need to spend much time here"

_Originally posted by @DavisVaughan in https://github.com/r-lib/vctrs/issues/1157#issuecomment-1458205654_

I was recently trying to use `vctrs` for the first time and was following the vignette on how to do it (https://vctrs.r-lib.org/articles/s3-vector.html).  I encountered issues with `vec_assert()` while doing so due to `ptype` trouble.  It would be helpful if the discouragement from `vec_assert()` were mentioned in the vignette.  It is currently used many times in the examples.

**Comment by DavisVaughan** [comment]
It has been removed from the dev version already https://vctrs.r-lib.org/dev/articles/s3-vector.html and is now silently soft deprecated and removed from all documentation on pkgdown

**Comment by billdenney** [comment]
Thanks!
