### ISSUE TITLE
Error when using the full_join function

### ISSUE THREAD

**Issue by NilosmitaBanerjee1** [r-lib/vctrs#1825]
Hi, 

I have been getting an error when using the full_join function. Below is the error message that is produced.

Error in `vctrs::vec_locate_matches()`:
! Match procedure results in an allocation larger than 2^31-1 elements. Attempted allocation size was 35932020505.
ℹ In file match.c at line 2411.
ℹ Install the winch package to get additional debugging info the next time you get this error.
ℹ This is an internal error that was detected in the vctrs package.
  Please report it at <https://github.com/r-lib/vctrs/issues> with a reprex (<https://https://tidyverse.org/help/>) and the full backtrace.
Backtrace:
     ▆
  1. ├─rounds.df %>% full_join(addiction_score.df)
  2. ├─dplyr::full_join(., addiction_score.df)
  3. ├─dplyr:::full_join.data.frame(., addiction_score.df)
  4. │ └─dplyr:::join_mutate(...)
  5. │   └─dplyr:::join_rows(...)
  6. │     └─dplyr:::dplyr_locate_matches(...)
  7. │       ├─base::withCallingHandlers(...)
  8. │       └─vctrs::vec_locate_matches(...)
  9. └─rlang:::stop_internal_c_lib(...)
 10.   └─rlang::abort(message, call = call, .internal = TRUE, .frame = frame)

**Comment by DavisVaughan** [comment]
It also looks like you are trying to return a 35 billion row result from the join, which seems unlikely to work very well in practice
