### ISSUE TITLE
Error in `vctrs::vec_locate_matches()`:

### ISSUE THREAD

**Issue by nk061** [r-lib/vctrs#1841]
### Any tips? 

Error in `vctrs::vec_locate_matches()`:
! Match procedure results in an allocation larger than 2^31-1 elements. Attempted allocation size was 18389337369.
ℹ In file match.c at line 2644.
ℹ This is an internal error that was detected in the vctrs package.
  Please report it at <https://github.com/r-lib/vctrs/issues> with a reprex (<https://tidyverse.org/help/>) and the full backtrace.
Traceback:

1. df_sleep %>% select(person_id, sleep_date, minute_in_bed) %>% 
 .     left_join(hr_exp, by = "person_id") %>% na.omit()
2. na.omit(.)
3. left_join(., hr_exp, by = "person_id")
4. left_join.data.frame(., hr_exp, by = "person_id")
5. join_mutate(x = x, y = y, by = by, type = "left", suffix = suffix, 
 .     na_matches = na_matches, keep = keep, multiple = multiple, 
 .     unmatched = unmatched, relationship = relationship, user_env = caller_env())
6. join_rows(x_key = x_key, y_key = y_key, type = type, na_matches = na_matches, 
 .     condition = condition, filter = filter, cross = cross, multiple = multiple, 
 .     unmatched = unmatched, relationship = relationship, error_call = error_call, 
 .     user_env = user_env)
7. dplyr_locate_matches(needles = x_key, haystack = y_key, condition = condition, 
 .     filter = filter, incomplete = incomplete, no_match = no_match, 
 .     remaining = remaining, multiple = multiple, relationship = relationship, 
 .     needles_arg = "x", haystack_arg = "y", error_call = error_call)
8. withCallingHandlers(vctrs::vec_locate_matches(needles = needles, 
 .     haystack = haystack, condition = condition, filter = filter, 
 .     incomplete = incomplete, no_match = no_match, remaining = remaining, 
 .     multiple = multiple, relationship = relationship, needles_arg = needles_arg, 
 .     haystack_arg = haystack_arg, nan_distinct = TRUE), vctrs_error_incompatible_type = function(cnd) {
 .     abort("`join_cast_common()` should have handled this.", .internal = TRUE)
 . }, vctrs_error_matches_nothing = function(cnd) {
 .     rethrow_error_join_matches_nothing(cnd, error_call)
 . }, vctrs_error_matches_incomplete = function(cnd) {
 .     rethrow_error_join_matches_incomplete(cnd, error_call)
 . }, vctrs_error_matches_remaining = function(cnd) {
 .     rethrow_error_join_matches_remaining(cnd, error_call)
 . }, vctrs_error_matches_relationship_one_to_one = function(cnd) {
 .     rethrow_error_join_relationship_one_to_one(cnd, error_call)
 . }, vctrs_error_matches_relationship_one_to_many = function(cnd) {
 .     rethrow_error_join_relationship_one_to_many(cnd, error_call)
 . }, vctrs_error_matches_relationship_many_to_one = function(cnd) {
 .     rethrow_error_join_relationship_many_to_one(cnd, error_call)
 . }, vctrs_warning_matches_relationship_many_to_many = function(cnd) {
 .     rethrow_warning_join_relationship_many_to_many(cnd, error_call)
 . }, vctrs_error_matches_multiple = function(cnd) {
 .     rethrow_error_join_matches_multiple(cnd, error_call)
 . }, vctrs_warning_matches_multiple = function(cnd) {
 .     rethrow_warning_join_matches_multiple(cnd, error_call)
 . })
9. vctrs::vec_locate_matches(needles = needles, haystack = haystack, 
 .     condition = condition, filter = filter, incomplete = incomplete, 
 .     no_match = no_match, remaining = remaining, multiple = multiple, 
 .     relationship = relationship, needles_arg = needles_arg, haystack_arg = haystack_arg, 
 .     nan_distinct = TRUE)
10. stop_internal_c_lib(file = file, line = line, call = call, message = message, 
  .     frame = frame)
11. abort(message, call = call, .internal = TRUE, .frame = frame)
12. signal_abort(cnd, .file)

**Comment by DavisVaughan** [comment]
Yea it looks like your result would have 18 billion rows? Unfortunately that is quite large for R. Are you by chance missing a `by` variable? If not maybe you can process it in chunks. Otherwise I dont think there is much we can do for you 😞

**Comment by nk061** [comment]
Thank you for the response! Each dataset has 18+ million rows so not very surprised at the large number... 

The `by` variable is the participant id! I am going to try and add another variable in that argument, maybe `group_by` in the line before joining, and see if it will help? 
Thank you, anyway!!

**Comment by DavisVaughan** [comment]
Is it possible they should also be joined on `sleep_date`? Going from 18 million to 18 billion sounds like there could be some mistake in the join, but im not sure

**Comment by nk061** [comment]
That worked!!!! 
here is my code for joining: 
`hr_sleep <- df_sleep %>%
    group_by(person_id) %>% 
    select(person_id, date, minute_in_bed) %>%
    left_join(hr_exp, by = c("person_id", "date")) %>% na.omit()`

Adding date helped a lot, I think the 18billion df had way too many NA values. 
Thank you so much for your help!! :)
