### ISSUE TITLE
vec_equal_na / vec_detect_missing and NA

### ISSUE THREAD

**Issue by ilikegitlab** [r-lib/vctrs#1843]
coalesce broke in my code since NA for list is now NULL. Although I can see where this coming from, lost of other R code (as.list(vector) in my case) is not converting NA to null, so its quite unfortunate. NA in lists are a real thing that people might want to check for (and coalesce). Would be great to get that functionality back.

**Comment by DavisVaughan** [comment]
We have been pretty happy with `NULL` as the missing value for lists and don't see that changing, so I think you'll need to come up with another solution. `dplyr::case_match()` may help.
