### ISSUE TITLE
internal error that was detected in the vctrs package.

### ISSUE THREAD

**Issue by antonellacolque** [r-lib/vctrs#1844]
Hello 
I am getting this error when running a specific code in R 
It indicates me to submit the issue here with the backtrace. Please see as follow:

Error in `vctrs::vec_locate_matches()`:
! Match procedure results in an allocation larger than 2^31-1 elements. Attempted allocation size was 6975758324.
ℹ In file match.c at line 2648.
ℹ This is an internal error that was detected in the vctrs package.
  Please report it at <https://github.com/r-lib/vctrs/issues> with a reprex and the full backtrace.
Backtrace:
     ▆
  1. ├─... %>% purrr::reduce(left_join)
  2. ├─purrr::reduce(., left_join)
  3. │ └─purrr:::reduce_impl(.x, .f, ..., .init = .init, .dir = .dir)
  4. │   ├─dplyr (local) fn(out, elt, ...)
  5. │   └─dplyr:::left_join.data.frame(out, elt, ...)
  6. │     └─dplyr:::join_mutate(...)
  7. │       └─dplyr:::join_rows(...)
  8. │         └─dplyr:::dplyr_locate_matches(...)
  9. │           ├─base::withCallingHandlers(...)
 10. │           └─vctrs::vec_locate_matches(...)
 11. └─rlang:::stop_internal_c_lib(...)
 12.   └─rlang::abort(message, call = call, .internal = TRUE, .frame = frame)
There were 50 or more warnings (use warnings() to see the first 50)

Any help will be gladly appreciated 
Best
Antonella

**Comment by DavisVaughan** [comment]
It looks like you are trying to do a join that would result in 6.9 billion rows

You likely have an improperly specified `by` argument in the join. Typically this means you are missing at least one key column

**Comment by antonellacolque** [comment]
Hi Davis
Thanks for your fast reply.
I am trying to reproduce a code from a publication:(https://github.com/glew8/PA_ModelAccuracy/blob/main/resampling_AS2.R)

And yes, I can see in my R session that I get multiple lines of 
Joining with `by = join_by(locus_tag)` 
Joining with `by = join_by(locus_tag)` 
Joining with `by = join_by(locus_tag)` 
....

But I cannot see an error in the code from the above mentioned git hub -in terms of misplacing a "by"- ..

**Comment by DavisVaughan** [comment]
I'm not entirely sure, but it looks like you probably don't want `reduce(left_join)` at all. It looks like you probably want `bind_rows()` instead since each data frame looks like it will have the same columns?
