### ISSUE TITLE
This is an internal error that was detected in the vctrs package.

### ISSUE THREAD

**Issue by mhakeem112** [r-lib/vctrs#1860]
This is an internal error that was detected in the vctrs package.
  Please report it at <https://github.com/r-lib/vctrs/issues> with a reprex and the full backtrace.
Backtrace:
    ▆
 1. ├─dplyr::full_join(df_Crime_Data, df_Call_For_Service, by = "GRID")
 2. ├─dplyr:::full_join.data.frame(...)
 3. │ └─dplyr:::join_mutate(...)
 4. │   └─dplyr:::join_rows(...)
 5. │     └─dplyr:::dplyr_locate_matches(...)
 6. │       ├─base::withCallingHandlers(...)
 7. │       └─vctrs::vec_locate_matches(...)
 8. └─rlang:::stop_internal_c_lib(...)
 9.   └─rlang::abort(message, call = call, .internal = TRUE, .frame = frame)

**Comment by DavisVaughan** [comment]
Probably related to https://github.com/r-lib/vctrs/issues/1845
