### ISSUE TITLE
Crash on bind_rows with integer duration in seconds

### ISSUE THREAD

**Issue by davidlub** [r-lib/vctrs#1862]
<html>
<body>

> x = dseconds(as.integer(1)) 
> df = data.frame(x) 
> bind_rows(df) 

Error in `vec_rbind()`: ! `proxy` of type `double` incompatible with `value` proxy of type `integer`. 
ℹ In file slice-assign.c at line 160. 
ℹ This is an internal error that was detected in the vctrs package.   
Please report it at <https://github.com/r-lib/vctrs/issues> with a reprex and the full backtrace. Backtrace:     
1. ├─dplyr::bind_rows(df)  
2. │ └─vctrs::vec_rbind(!!!dots, .names_to = .id, .error_call = current_env())  
4. └─rlang:::stop_internal_c_lib(...)  
5. └─rlang::abort(message, call = call, .internal = TRUE, .frame = frame) 
> R.version                _                                 
platform       x86_64-w64-mingw32                
arch           x86_64                            
os             mingw32                           
crt            ucrt                              
system         x86_64, mingw32                   
status                                           
major          4                                 
minor          3.1                               
year           2023                              
month          06                                
day            16                                
svn rev        84548                             
language       R                                 
version.string R version 4.3.1 (2023-06-16 ucrt) 
nickname       Beagle Scouts
--
 
> | >
>

</body>
</html>

**Comment by DavisVaughan** [comment]
Tracking in https://github.com/tidyverse/lubridate/issues/1131
