### ISSUE TITLE
Error in `vctrs::vec_locate_matches()`

### ISSUE THREAD

**Issue by mkaschner** [r-lib/vctrs#1874]
! Match procedure results in an allocation larger than 2^31-1 elements. Attempted allocation size was 151994151045.
ℹ In file match.c at line 2648.
ℹ This is an internal error that was detected in the vctrs package.

Backtrace:
    ▆
 1. ├─dplyr::full_join(...)
 2. ├─dplyr:::full_join.data.frame(...)
 3. │ └─dplyr:::join_mutate(...)
 4. │   └─dplyr:::join_rows(...)
 5. │     └─dplyr:::dplyr_locate_matches(...)
 6. │       ├─base::withCallingHandlers(...)
 7. │       └─vctrs::vec_locate_matches(...)
 8. └─rlang:::stop_internal_c_lib(...)
 9.   └─rlang::abort(message, call = call, .internal = TRUE, .frame = frame)

**Comment by DavisVaughan** [comment]
Your join would result in over 151 billion rows, you almost definitely have forgotten to specify a primary key in the `by` argument to your joins
