### ISSUE TITLE
Should the recycling rules really be `@internal`?

### ISSUE THREAD

**Issue by jennybc** [r-lib/vctrs#1877]
I came to vctrs looking for vctrs recycling rules and a help topic exists, but it's marked internal and therefore somewhat hard to find.

https://github.com/r-lib/vctrs/blob/8bbd8c4a69a9b3e2c42aa752c5339f949562af96/R/recycle.R#L70

I gather this is intentional (https://github.com/r-lib/vctrs/pull/1580/commits/88fd9b6646996c5e75e21889a39362b5c2f4b185), but that seems to sort of contradict other signals that suggest this topic is meant to be user-facing.

**Comment by jennybc** [comment]
Here's the page we're talking about: https://vctrs.r-lib.org/reference/vector_recycling_rules.html

**Comment by DavisVaughan** [comment]
It has since proved fairly useful to share, so it seems reasonable to make it external and give it a dedicated bullet in the pkgdown reference page
