### ISSUE TITLE
vctrs objects loose names when apply is used on them

### ISSUE THREAD

**Issue by thomasp85** [r-lib/vctrs#1914]
It appears vctrs objects will throw away their names when mapped over, in contrast to how names generally behaves with mapping (the names is transferred to the result)

```r
names(lapply(vctrs::new_vctr(list(a = 1, b = 2)), identity))
#> NULL
names(lapply(list(a = 1, b = 2), identity))
#> [1] "a" "b"
```

This is due to `as.list()` throwing away the names

**Comment by DavisVaughan** [comment]
I think this is actually a duplicate of https://github.com/r-lib/vctrs/issues/1416
