### ISSUE TITLE
Return multiple duplicated/unique results

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#197]
When you work with duplicated values you often need to know: 

* if there are any duplicates
* a list of duplicates for each unique value
* the position of the unique values

It would be useful if one function returned all these things to avoid creating the hash multiple times.

**Comment by jjesusfilho** [comment]
> When you work with duplicated values you often need to know:
> 
> * if there are any duplicates
> * a list of duplicates for each unique value
> * the position of the unique values
> 
> It would be useful if one function returned all these things to avoid creating the hash multiple times.

Is there a function to return your second question: "a list of duplicates for each unique value"?

**Comment by lionel-** [comment]
```r
v <- c("a","b","c","a","a","b")
vec_split(v, v)
#>   key     val
#> 1   a a, a, a
#> 2   b    b, b
#> 3   c       c
```
