### ISSUE TITLE
Should vec_proxy_compare() have a fallback?

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#210]
It would be nice to be able to sort data frames containing list columns. Should `vec_proxy_compare()` return `seq_along(x)`? Or should it return `NULL`, and then failures would be communicated downstream?

**Comment by hadley** [comment]
This is needed for (e.g.) `tidyr::crossing()` and `nesting()` because (for historical reasons) these sort all columns.

**Comment by DavisVaughan** [comment]
For sorting list columns we have changed usage `vec_proxy_compare(relax = TRUE)` to instead use `vec_proxy_order()`. This "orders" list column elements by first appearance, which seemed reasonable.
