### ISSUE TITLE
Terminology in stability vignette

### ISSUE THREAD

**Issue by ijlyttle** [r-lib/vctrs#214]
In the **Examples** near the beginning, you refer to *size-stability*, then switch for a while to *length-stability*. 

https://github.com/r-lib/vctrs/blob/de2eef17e1bfa64a5f8715fe28e1e535ceab27f7/vignettes/stability.Rmd#L74

https://github.com/r-lib/vctrs/blob/de2eef17e1bfa64a5f8715fe28e1e535ceab27f7/vignettes/stability.Rmd#L90

Do you intend to use different terms here? 

If not, I'll be happy to make a PR: presumably to refer only to *size-stability* in these examples.

**Comment by hadley** [comment]
Yes, it's deliberate — it's a weaker condition than size stability

**Comment by ijlyttle** [comment]
Thanks!
