### ISSUE TITLE
Vectorized isTRUE() and friends

### ISSUE THREAD

**Issue by jennybc** [r-lib/vctrs#23]
Vectorized `isTRUE()` would be really helpful. And lots of people define `isFALSE()` in package utils. And then it's a slippery slope ...

``` r
x <- c(TRUE, NA, FALSE)
is_true <- Vectorize(isTRUE)
is_false <- Vectorize(function(x) identical(x, FALSE))
is_not_true <- function(x) !is_true(x)
is_not_false <- function(x) !is_false(x)
is_true(x)
#> [1]  TRUE FALSE FALSE
is_false(x)
#> [1] FALSE FALSE  TRUE
is_not_true(x)
#> [1] FALSE  TRUE  TRUE
is_not_false(x)
#> [1]  TRUE  TRUE FALSE
```

**Comment by patperry** [comment]
Coincidentally, I just learned this idiom for vectorized `isTRUE` and friends from the source for `as.matrix.data.frame`:

```r
x <- c(TRUE, NA, FALSE)
x %in% TRUE
#> [1]  TRUE FALSE FALSE
x %in% FALSE
#> [1] FALSE FALSE  TRUE
!x %in% TRUE
#> [1] FALSE  TRUE  TRUE
!x %in% FALSE
#> [1]  TRUE  TRUE FALSE
```

**Comment by jennybc** [comment]
Reminded of this issue for first time in long time.

It looks like `isFALSE()` is coming to R in 3.5.

**Comment by hadley** [comment]
This feels like it might just be part of #22 - i.e. your vectorised `isTRUE` would just be `equal(x, TRUE)` (for some definition of equal) because it would use the hashing/`%in%` definition of equality where `NA == TRUE` is false.
