### ISSUE TITLE
vec_slice() strictness for character indices

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#244]
Do we want to allow `vec_slice()` with character `NA` index to return a typed `NA`, for consistency? Missing names should still produce an error.

``` r
library(vctrs)
x <- setNames(1:3, c("one", "two", "three"))

x[NA_character_]
#> <NA> 
#>   NA
vec_slice(x, NA_character_)
#> Error: Can't index non-existing elements.

x["four"]
#> <NA> 
#>   NA
vec_slice(x, "four")
#> Error: Can't index non-existing elements.

x[NA_integer_]
#> <NA> 
#>   NA
vec_slice(x, NA_integer_)
#> <NA> 
#>   NA
```

<sup>Created on 2019-03-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

I have surveyed behavior for slicing and sliced assignment for all corner cases I could think of (in #243), haven't found anything else suspicious: http://rpubs.com/krlmlr/vctrs-sliced-index-corner-cases.

**Comment by lionel-** [comment]
I think that makes sense.
