### ISSUE TITLE
Provide implementation for vec_data(), preserving shape and vec_names

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#245]
Invariants: 

```r
identical(vec_names(vec_data(x)), vec_names(x))
identical(vec_dim(vec_data(x)), vec_dim(x))
```

The documentation currently states that names are preserved. The names of a vector can also be row names (of a data frame or matrix).

Ideally, an ALTREP implementation would avoid copying.

``` r
library(vctrs)

x <- diag(2)
rownames(x) <- letters[1:2]
colnames(x) <- LETTERS[1:2]

vctrs:::vec_names(x)
#> [1] "a" "b"

x
#>   A B
#> a 1 0
#> b 0 1

vec_data(x)
#> [1] 1 0 0 1
```

<sup>Created on 2019-03-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by hadley** [comment]
Yes, I think that’s correct.

**Comment by lionel-** [comment]
Agreed that `vec_data()` should preserve all core vectorised attributes (names, dim, dimnames). See also https://github.com/r-lib/vctrs/issues/153.

I'm not sure we should do the ALTREP in vctrs, R 3.6 will do it for us I think.

**Comment by krlmlr** [comment]
Got it. I'll start with an R implementation then, we can assess the problem later.

**Comment by hadley** [comment]
@DavisVaughan does this make sense to you to?

**Comment by DavisVaughan** [comment]
I think the two invariants mentioned in the first comment currently hold for matrices/arrays. After this issue was opened, `vec_data()` was altered to keep the dim/dimnames. I don't know what `vec_names()` is supposed to be returning though.

``` r
library(rray)
library(vctrs)

x <- matrix(1, dimnames = list("row", "col"))

# this is null?
vctrs:::vec_names(x)
#> NULL

# it matches base R, but what do we want it to do?
names(x)
#> NULL

dimnames(x)
#> [[1]]
#> [1] "row"
#> 
#> [[2]]
#> [1] "col"

# vec_data() currently keeps shape / dimname
vec_data(x)
#>     col
#> row   1

# which is very helpful for me in rray
x_rray <- as_rray(x)
vec_data(x_rray)
#>     col
#> row   1
```

<sup>Created on 2019-05-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by DavisVaughan** [comment]
I'm fairly certain this looks incorrect, which is used in `vec_names()` and I think is giving the wrong answer. I'll take a closer look and see if I can PR 
https://github.com/r-lib/vctrs/blob/c6c9c85f0152fb3275a1788c5174895b43b62dde/src/size.c#L7
