### ISSUE TITLE
Do we need/have an equivalent for x[] <- value?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#246]
Required when we start forwarding `[<-()` to `vec_slice()` .

``` r
library(vctrs)

x <- 1:3
x[] <- 4L

x <- 1:3
vec_slice(x, ) <- 4L
#> Error in vec_size(i): argument "i" is missing, with no default
```

<sup>Created on 2019-03-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by lionel-** [comment]
It feels like a recycle + cast operation.

**Comment by hadley** [comment]
Isn't this just a default value for `i`?

**Comment by krlmlr** [comment]
`vec_slice<-()` calls `vec_as_index()` which has `maybe_missing(i)` -- do we want to change this to an explicit `NULL` (also for `vec_slice()`) ?

**Comment by hadley** [comment]
Yeah, I think an explicit `NULL` makes sense here.
