### ISSUE TITLE
vec_rbind() doesn't handle NA correctly

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#255]
``` r
library(vctrs)
vec_rbind(NA, data.frame(x = 1))
#> New names:
#>  -> ..1
#>   ..1  x
#> 1  NA NA
#> 2  NA  1
```

<sup>Created on 2019-03-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

It should return `data.frame(x = c(NA, 1))`

**Comment by lionel-** [comment]
It seems that the names repair rules should be independent of the type. What mechanism are you envisioning?

Or should we treat unnamed vectors positionally? This would be more efficient than repairing names for each input.

**Comment by hadley** [comment]
An `NA` should be equivalent to an `unspecified()` which shouldn't affect the common type and should be able to be cast to `data.frame(x = integer())`
