### ISSUE TITLE
How strict should `vec_assert()` be with factors?

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#261]
I think this is a broader question around what exactly `vctrs:::is_same_type()` should do, but consider the case of validating that a user provided a factor as the `outcome` to a tree-based model (as they would be required to do).

``` r
library(vctrs)

# I think I want this to pass
vec_assert(iris$Species, factor())
#> `iris$Species` must be <fctr>, not <fctr>.

# Because there's no way i could know the levels ahead of time,
# just that its a factor
vec_assert(iris$Species, factor(levels = c("setosa", "versicolor", "virginica")))

# I suppose I could use this
outcome <- vec_cast(iris$Species, factor())

# But it doesn't give as good of an error message
# when there is an issue
vec_cast(iris$Sepal.Length, factor())
#> Can't cast <double> to <factor<>>


# (on a separate note)
# I see how is_same_type() lets me do this, but is it right?
vec_assert(iris$Species, integer())
```

<sup>Created on 2019-03-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by DavisVaughan** [comment]
I also think that this should extend to data frames with factor columns.

``` r
library(vctrs)

species <- iris[, "Species", drop = FALSE]

# should pass
df_ptype_partial <- data.frame(Species = factor())
vec_assert(species, df_ptype_partial)
#> `species` must be <df[,1]>, not <df[,1]>.

# all good
df_ptype_full <- data.frame(Species = factor(levels = c("setosa", "versicolor", "virginica")))
vec_assert(species, df_ptype_full)
```

I _think_ that a factor without levels specified could be a partial type for a factor. And maybe I'm asking that `vec_assert()` should let that partial type count as being the same as the full type.

**Comment by hadley** [comment]
This is partly #198/#257 and partly #106

**Comment by DavisVaughan** [comment]
👍 I agree completely. The combination of those would solve this.

**Comment by lionel-** [comment]
> ```
> # (on a separate note)
> # I see how is_same_type() lets me do this, but is it right?
> vec_assert(iris$Species, integer())
> ```

I agree this isn't right. I'll revert to `identical(x, ptype)`.
