### ISSUE TITLE
Lazily generate label in vec_assert

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#263]
Currently `arg %||% as_label(substitute(x))` appears to take about 25% of the run time when the assertion passes

``` r
library(vctrs)
library(rlang)

label1 <- function(x, arg = NULL) {
  arg %||% as_label(substitute(x))
}
label2 <- function(x, arg = NULL) {
  delayedAssign("label", arg %||% as_label(substitute(x)))
  10
}

x <- 1:10

bench::mark(
  vctrs::vec_assert(x, integer(), size = 10),
  label1(x),
  label2(x),
  check = FALSE
)[1:6]
#> # A tibble: 3 x 6
#>   expression                         min    mean  median      max `itr/sec`
#>   <chr>                         <bch:tm> <bch:t> <bch:t> <bch:tm>     <dbl>
#> 1 vctrs::vec_assert(x, integer…   43.3µs 54.51µs 48.03µs 228.47µs    18345.
#> 2 label1(x)                       11.7µs 15.75µs 13.53µs  19.72ms    63489.
#> 3 label2(x)                        1.4µs  1.99µs  1.62µs   2.15ms   502699.
```

<sup>Created on 2019-03-31 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

It's probably worth worrying about the performance so we can use this as a standard tool for making assertions about argument types across the tidyverse.

**Comment by hadley** [comment]
(I also wonder if we should assert that `type` is size 0 in order to avoid a call to `vec_ptype()`)

**Comment by lionel-** [comment]
> (I also wonder if we should assert that type is size 0 in order to avoid a call to vec_ptype())

This will require a proxy dispatch in any case in order to get the size. Maybe we should take the proxy to get a core vector type and then we can call `vec_size()` and `vec_type()` more cheaply (dispatch is avoided with core types). If size is 0, we don't call `vec_type()` and return early.

**Comment by lionel-** [comment]
> Currently arg %||% as_label(substitute(x)) appears to take about 25% of the run time

Right, labellisation/deparsing is the slowest part of tidy eval. At some point it should be rewritten for efficiency.

**Comment by lionel-** [comment]
Three improvements, the first two already on master and the third one is at #264.

- Lazy label.
- Take the proxy only once in `vec_assert()`.
- Rewrite `vec_type()` in C.

With a bare integer:

```
# A tibble: 4 x 6
  expression              min     mean   median      max `itr/sec`
  <bch:expr>         <bch:tm> <bch:tm> <bch:tm> <bch:tm>     <dbl>
1 Before               33.8µs   44.1µs   40.9µs    253µs    22685.
2 Lazy arg             20.1µs     26µs     24µs    158µs    38481.
3 One proxy dispatch   20.8µs   26.4µs   24.8µs    148µs    37901.
4 C vec_type()           11µs   14.6µs   13.8µs    108µs    68614.
```

With an S3 list (which requires S3 dispatch to `vec_proxy()` method):

```
# A tibble: 4 x 6
  expression              min     mean   median      max `itr/sec`
  <bch:expr>         <bch:tm> <bch:tm> <bch:tm> <bch:tm>     <dbl>
1 Before               43.4µs   54.3µs   50.2µs    225µs    18421.
2 Lazy arg             28.9µs   35.9µs   33.6µs    154µs    27843.
3 One proxy dispatch   21.9µs   27.7µs   25.9µs    140µs    36106.
4 C vec_type()         13.2µs   17.5µs   16.2µs    117µs    57211.
```

**Comment by lionel-** [comment]
> Take the proxy only once in vec_assert()

Actually it isn't right to take the proxy in `vec_assert()`, we don't want to compare the proxy but the whole type itself. Different types might have the same proxy. I'll write failing tests and fix.

**Comment by hadley** [comment]
Those numbers look great ~20µs is only going to make a difference in very tight loops.
