### ISSUE TITLE
Is `[.vctrs_vctr` too restrictive for objects with shape?

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#269]
If you create a new vctr class that acts like a matrix and try and subset it, you immediately hit problems with `[.vctrs_vctr` only allowing `i` through.

``` r
library(vctrs)

new_2d <- function(.data, dim) {
  vctrs::new_vctr(.data, dim = dim, class = "vctrs_2d")
}

x <- new_2d(c(1, 2), dim = c(2L, 1L))

# works
x[1]
#> <vctrs_2d[1]>
#>      [,1]
#> [1,] 1

# nope
x[, 1]
#> `...` is not empty.
#> These dots only exist for technical reasons and should be empty.

# nope
x[1, 1]
#> `...` is not empty.
#> These dots only exist for technical reasons and should be empty.


# What _should_ it return?
# should it just pass on to 
# the matrix method and drop dimensions?
# (i.e. we say that the underlying class
# controls whether dims are dropped or not)
y <- matrix(1:2)
y[, 1]
#> [1] 1 2

# or should it return this?
y[, 1, drop = FALSE]
#>      [,1]
#> [1,]    1
#> [2,]    2

# same question here I guess
y[1, 1]
#> [1] 1
```

If you do pass everything on to the underlying class, I think it might be good to think through what these return:

```r
x[1] # might call `vec_slice_native()` and drop dims
x[1,] # might call underlying method and not drop dims
```

On a similar note, `[<-.vctrs_vctr` should allow more than just `i` through as well. But I don't think the fix is as simple as just replacing `i` with `...` there.

**Comment by lionel-** [comment]
That's temporary, our `[` methods need to be a little more complicated and directly fall back to ``base::`[` `` when a shape is detected. Eventually we'll have native slicing for shaped objects too.
