### ISSUE TITLE
`vec_c()` fails if only some arguments are named

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#271]
``` r
library(vctrs)

y <- 1
names(y) <- "a"

# fails because it expects
# `1` to have names
vec_c(y, 1)
#> Error in names[pos:(pos + n - 1)] <- outer_names(names(args)[[i]], vec_names(args[[i]]), : replacement has length zero

# this is ok
z <- 2
names(z) <- "b"
vec_c(y, z)
#> a b 
#> 1 2
```

<sup>Created on 2019-04-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by DavisVaughan** [comment]
Hmm maybe this is expected? I patched the names assignment in the error there to just use `""` for the unnamed inputs, which works nicely for base R objects. But as soon as I use something like:

```
a <- rray(1, dim_names = list("x"))
vec_c(a, 2)
```

I get an error from `vctrs:::names<-.vctrs_vctr` complaining about "if any elements are named, all must be named". This makes me think maybe an error was the intention from the beginning so you can't get into a state of having partially filled names (even if the error message isn't great).

**Comment by hadley** [comment]
Yeah, this should be an error, but it needs to be more informative. I'm not sure if it's worth patching the R implementation, or waiting until this is reimplemented inC.

**Comment by hadley** [comment]
Minimal reprex:

``` r
vctrs::vec_c(c(a = 1), 1)
#> Error in vctrs::vec_c(c(a = 1), 1): Internal error in `vec_assign()`: `value` should have been recycled to fit `x`.
```

<sup>Created on 2019-06-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by lionel-** [comment]
oops, Davis just pinged me that you discussed about making it an error.

This really surprises me. I think it often happens that I'm combining named and unnamed vectors, especially lists. I suggest not making it an error.

**Comment by lionel-** [comment]
Surely this will cause issues when flattening data structures etc. And this won't simplify vector code because we still need to assume some elements might be unnamed. Is there an advantage to having this restriction?

**Comment by lionel-** [comment]
Maybe we need a `.name_repair` argument that could take a `"check_named"` value? The default value would be `"none"`. IIRC we also talked about a `"unnamed"` option to ignore the names for efficiency.

**Comment by hadley** [comment]
I don't feel too strongly about it, so we can leave your behaviour and see if it bugs me.
