### ISSUE TITLE
Rename allow_lossy_cast() to with_allow_lossy_cast()

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#279]
for consistency with {withr} functions. Can we implement a scoped version by calling the `.addCondHands()` internal ourselves?

**Comment by lionel-** [comment]
I don't like `with_allow_`. But I agree a scoped version would be useful.

> Can we implement a scoped version by calling the .addCondHands() internal ourselves?

That wouldn't be compatible with other R implementations. I think we'd first need to get this feature in base R, then we can come up with a compat.

**Comment by lionel-** [comment]
Maybe `with_lossy_cast()` is better?

**Comment by hadley** [comment]
I think the existing name is fine
