### ISSUE TITLE
Consider bringing back warn_lossy_cast()

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#280]
In {hms} I'd like to introduce a warning when characters can't be parsed as `hms()`. I don't like to make this an error because I'd like to give downstream maintainers a chance to adapt seamlessly. I think this scenario will occur very frequently as vector classes are lifted to use {vctrs}.

This can be as simple as adding an optional argument to `maybe_lossy_cast()`. Then, `warn_lossy_cast()` could forward to `maybe_lossy_cast()` and be marked soft-deprecated.

Also, there are quite a few instances of `warn_lossy_cast` floating around on GitHub: https://github.com/search?q=warn_lossy_cast&type=Code.

Currently I'm rolling my own version of `warn_lossy_cast()`.

**Comment by lionel-** [comment]
> Also, there are quite a few instances of warn_lossy_cast floating around on GitHub:

I just see the "probably" package, and one expectation that will break no matter what in the typeR package.

Good point regarding transition.

I just worry that maintainers will keep the warning forever and we'll end up with a confusing mix of warnings and errors. How about making those lifecycle warnings with an example of how to use `allow_lossy_cast()`?

```r
allow_lossy_cast(maybe_lossy_cast(...), .lifecycle_warning = TRUE)
```

**Comment by hadley** [comment]
I think vctrs is sufficiently experimental we don’t need to worry unduly about backward compatibility

**Comment by krlmlr** [comment]
Let's ignore backward compatibility then. How do we add stricter behavior to existing classes without breaking their backward compatibility?

**Comment by lionel-** [comment]
> How do we add stricter behavior to existing classes without breaking their backward compatibility?

What do you think about https://github.com/r-lib/vctrs/issues/280#issuecomment-480561637

**Comment by krlmlr** [comment]
A lifecycle warning looks reasonable.
