### ISSUE TITLE
What should `vec_slice(x, i) <- NULL` do?

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#285]
In the spirit of having good error messages for edge cases, what should this do? Is this a no-op or an error?

``` r
library(vctrs)
x <- 1:5
vec_slice(x, 1L) <- NULL
#> Error in x[i] <- value: replacement has length zero
```

**Comment by hadley** [comment]
I think the RHS should be recycled to the same length as the index.

**Comment by hadley** [comment]
Slightly fully reprex:

``` r
library(vctrs)
x <- 1:5
vec_slice(x, 1L) <- NULL
#> Error in `vec_slice<-`(`*tmp*`, 1L, value = NULL): Internal error in `vec_assign()`: `value` should have been recycled to fit `x`.
vec_slice(x, 1L) <- integer()
#> Error: Incompatible lengths: 0, 1
```

<sup>Created on 2019-06-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

I think this could be a clear error message.

**Comment by hadley** [comment]
@DavisVaughan do you want to try a doing a PR for this?

**Comment by DavisVaughan** [comment]
Sure:
- Do both of those need better messages, or do you like the internal error and just want to fix the `<- integer()` case? 
- Do you want it to say something like `value cannot be recycled to fit x`?

**Comment by hadley** [comment]
I think incompatible lengths is fine, it's the internal error that needs something like "Can't slice assign with `NULL`"
