### ISSUE TITLE
Inconsistent behavior of `vec_rbind()` with 0-length input

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#286]
I don't think these first two are quite right. They break this invariant:

```r
vec_size(vec_rbind(x, y)) == vec_size(x) + vec_size(y)
```

``` r
library(vctrs)

# not right?
vec_rbind(integer(), 1)
#> New names:
#>  -> ..1
#>   ..1
#> 1  NA
#> 2   1

# not right?
vec_rbind(integer(), data.frame(x = 1))
#>    x
#> 1 NA
#> 2  1

# this seems right
vec_rbind(integer(), integer())
#> data frame with 0 columns and 0 rows
```

Should the result just have 1 row, with `integer()` just being used to help determine the output container type?

**Comment by lionel-** [comment]
Yes I think so.

**Comment by lionel-** [comment]
Actually I think empty rows should be ignored entirely because there's no reason to think the type information applies to a particular column. I see three options regarding which columns the row could coerce with:

1. The first column
1. All columns
1. No columns

Option 1 seems ad hoc. Option 2 would represent a weird case of recycling of empty vectors to full size. Option 3 seems to make the most sense because an empty row doesn't convey information about position or name.

What do you think @hadley @DavisVaughan?

**Comment by DavisVaughan** [comment]
I agree with you. In `vec_rbind()` I think we should ignore inputs that have 0 columns.

``` r
library(vctrs)

# this should have no effect on the column types
# because...well it doesn't have any columns
# to match up against
vctrs:::as_df_row(numeric())
#> data frame with 0 columns and 1 row

# so this...
vec_rbind(numeric(), data.frame(x = 1L, y = 2L))
#>    x  y
#> 1 NA NA
#> 2  1  2

# ...should really be
data.frame(x = 1L, y = 2L)
#>   x y
#> 1 1 2

# on the other hand, when there is 1 col and 0 rows
# the column information should be used to determine the type.
# this result is correct (notice x became numeric)
str(
  vec_rbind(
    data.frame(x = numeric()), 
    data.frame(x = 1L, y = 2L)
  )
)
#> 'data.frame':    1 obs. of  2 variables:
#>  $ x: num 1
#>  $ y: int 2
```

<sup>Created on 2019-06-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by DavisVaughan** [comment]
Actually, on second thought I am not sure that is right either because the invariant stated at the very beginning is broken.

I now think that `as_df_row(numeric())` should create a data frame with 0 columns and 0 rows. That will be ignored.

But the current behavior of the example with `new_data_frame(n = 2L)` seems correct, actually. The types come from the inputs that actually have columns, but the number of rows comes from all of the inputs. So those 2 rows should count and should just be filled in with `NA`, as is done.

**Comment by lionel-** [comment]
From another perspective, to be consistent with `vec_cbind()` we'd need to return a zero-col data frame with as many rows as inputs.

```r
vctrs::vec_cbind(a = 1:3, b = integer())
#> [1] a b
#> <0 rows> (or 0-length row.names)
```

**Comment by DavisVaughan** [comment]
I have constructed a framework that convinces me that the current behavior is actually correct.

The shorter story is that: 

With `vec_rbind(integer(), 1)` we use `as_df_row()` on both inputs, which results in two data frames with dimensions defined by `(1 row | no cols)` and `(1 row | ..1)`. Then we rbind them together, meaning we add the rows so we should get `(2 rows | ..1)` and we do.

With `vec_rbind(integer(), integer())`, the behavior in the reprex above was wrong at the time, but has since been corrected at some point. What should happen is: use `as_df_row()` on both inputs, which results in `(1 row | no cols)` and `(1 row | no cols)`. Then rbind them to get `(2 rows | no cols)`. This is what happens currently:

``` r
vctrs::vec_rbind(integer(), integer())
#> data frame with 0 columns and 2 rows
```

Below is the full set of syntax I made to define these operations, with rbind and cbind examples.

<details>

``` r
library(vctrs)

# forcing data framedness on 1D objects
# - as_df_col -> ncol = 1,      nrow = length
# - as_df_row -> ncol = length, nrow = 1

# syntax:
# (#rows | colname1, colname2)
# special case:
# (#rows | .) <- no columns

# when we cbind, we recycle rows
# when we rbind, we sum # of rows

# (0 | .)
# (1 | z)
# _______ (recycle rows)
# (0 | z)
vec_cbind(
  new_data_frame(n = 0L),
  data.frame(z = 1)
)
#> [1] z
#> <0 rows> (or 0-length row.names)

# (3 | .)
# (1 | z)
# _______ (recycle rows)
# (3 | z)
vec_cbind(
  vctrs:::new_data_frame(n = 3L),
  data.frame(z = 1)
)
#>   z
#> 1 1
#> 2 1
#> 3 1

# this correctly errors cant recycle 3 and 2
# (3 | .)
# (2 | .)
# _______ (recycle rows)
# (ERROR | .)
vec_cbind(
  vctrs:::new_data_frame(n = 3L),
  vctrs:::new_data_frame(n = 2L)
)
#> No common size for `..1`, size 3, and `..2`, size 2.

# (0 | x, y)
# (1 | z)
# _______ (recycle rows)
# (0 | x, y, z)
vec_cbind(
  data.frame(x = numeric(), y = integer()),
  data.frame(z = 1)
)
#> [1] x y z
#> <0 rows> (or 0-length row.names)

# (0)
# (1 | z)
# _______ as_df_col
# (0 | ..1)
# (1 | z)
# _______ (recycle rows)
# (0 | ..1, z)
vec_cbind(
  numeric(),
  data.frame(z = 1)
)
#> New names:
#> * `` -> ...1
#> [1] ...1 z   
#> <0 rows> (or 0-length row.names)

# (0 | x, y)
# (1 | z)
# _______ (sum # of rows)
# (1 | x, y, z)
vec_rbind(
  data.frame(x = numeric(), y = integer()),
  data.frame(z = 1)
)
#>    x  y z
#> 1 NA NA 1

# (0)
# (1 | z)
# _______ as_df_row
# (1 | .)
# (1 | z)
# _______ (sum # of rows)
# (2, z)
vec_rbind(
  numeric(),
  data.frame(z = 1)
)
#>    z
#> 1 NA
#> 2  1

# (0)
# (1)
# _______ as_df_row
# (1 | .)
# (1 | ..1)
# _______ (sum # of rows)
# (2 | ..1)
vec_rbind(
  numeric(),
  1
)
#> New names:
#> * `` -> ...1
#>   ...1
#> 1   NA
#> 2    1

# (0)
# (0)
# _______ as_df_row
# (1 | .)
# (1 | .)
# _______ (sum # of rows)
# (2 | .)
vec_rbind(
  integer(), 
  integer()
)
#> data frame with 0 columns and 2 rows
```

<sup>Created on 2019-06-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

</details>

**Comment by lionel-** [comment]
Agreed that the current behaviour is correct. We just need more tests and better invariants in the documentation.
