### ISSUE TITLE
[FR] Better c() for named vectors

### ISSUE THREAD

**Issue by yutannihilation** [r-lib/vctrs#30]
As reported in https://github.com/hadley/dplyr/issues/2284, `c()` behaves very tricky for named vectors. We need better `c()`.

```r
x <- "φ"
names(x) <- "φ"

Encoding(names(x))
#> [1] "unknown"

Encoding(names(c(x)))
#> [1] "UTF-8"
```

**Comment by hadley** [comment]
Looks like this is fixed with `vec_c()`:

``` r
library(vctrs)

x <- "φ"
names(x) <- "φ"

Encoding(names(x))
#> [1] "unknown"
Encoding(names(vec_c(x)))
#> [1] "unknown"
```

Created on 2018-08-09 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by yutannihilation** [comment]
Cool!
