### ISSUE TITLE
vec_na(NULL, n) should return unspecified(n)

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#301]
To preserve the invariant that `vec_size(vec_na(x, n))` is `n`

An error might also be acceptable, but the current behaviour is definitely wrong.

**Comment by lionel-** [comment]
Probably best to take the conservative route and make it an error, now that `vec_size(NULL)` is also an error. Also consistent with `vec_init()` without argument being an error.

**Comment by lionel-** [comment]
@hadley This change causes a failure in dev tidyr: https://travis-ci.org/tidyverse/tidyr/jobs/550781919#L1126

**Comment by hadley** [comment]
Yup, I'll fix next week
