### ISSUE TITLE
`vec_type2()` with a `NULL` input doesn't return a 0-size result

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#307]
This is a consistency thing that I thought should be pointed out. `vec_type2()` has an early exit if `x` or `y` is `NULL`, but it returns the input unchanged rather than returning the 0-size type. This doesn't really affect anything downstream, but I just thought it was worth mentioning.

``` r

library(vctrs)

vec_type(1:5)
#> integer(0)

vec_type2(1:5, NULL)
#> [1] 1 2 3 4 5

vec_type_common(1:5, NULL)
#> integer(0)
```

The early exit is here, I think.

https://github.com/r-lib/vctrs/blob/d9fd8f444ce632d72b7acef32771532e560b4254/src/type2.c#L32

**Comment by lionel-** [comment]
I'm not sure there should be any expectation on the size of a prototype.

**Comment by DavisVaughan** [comment]
That's fine, I just wanted to check that that was the case. Feel free to close if you think there is nothing to be done.

**Comment by lionel-** [comment]
One advantage of always slicing to 0 size is that it makes unit testing easier.
