### ISSUE TITLE
`vec_compare(<type>, NULL)` throws an error

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#308]
Should this error?

``` r
vctrs::vec_compare(1:5, NULL)
#> Error: `x` and `y` must have same types and lengths
```

I think `integer(0)` might be an appropriate result, since that is what this does:

``` r
vctrs::vec_compare(NULL, NULL)
#> integer(0)
```

This error means that comparison operations between vctrs and `NULL` error, unlike base R, which I think gives an intuitive result:

``` r
vctrs:::new_hidden(1) > NULL
#> Error: `x` and `y` must have same types and lengths

1 > NULL
#> logical(0)
```

If it returned `integer(0)`, then the comparison operator would work since this operation powers `>.vctrs_vctr`:

``` r
integer(0) > 0
#> logical(0)
```

However, returning `integer(0)` would break an invariant of `vec_size_common(x, y) == vec_size(vec_compare(x, y))` so maybe it should be an error after all.

The current error is here at the C level. Since `vec_compare()` calls `vec_recycle_common()` and `vec_cast_common()` before this, I don't see how this error could ever be reached except in this 1 case with `NULL`. Maybe it could be improved some if that was the case?
https://github.com/r-lib/vctrs/blob/master/src/compare.c#L125

**Comment by lionel-** [comment]
> However, returning integer(0) would break an invariant of vec_size_common(x, y) == vec_size(vec_compare(x, y)) so maybe it should be an error after all.

I think the common size with a `NULL` should be zero. However I'm not familiar with this part of vctrs yet so that might not be practical.

**Comment by DavisVaughan** [comment]
I agree! Here are my thoughts:

``` r
library(vctrs)

# i think this should be 0
vec_size_common(NULL)
#> NULL

# this is NULL
vec_size_common()
#> NULL

# i think this is 0
vec_size_common(1, NULL)
#> [1] 1
```

I think all you'd have to do is remove the `compact()` from `vec_size_common()`

**Comment by hadley** [comment]
NULL should be treated as the absence of an input, definitely not as a zero length vector. I think we need a fallback for when all inputs are NULL, not to change existing behaviour otherwise.

**Comment by DavisVaughan** [comment]
Should `vec_size_common(NULL) == vec_size(NULL)`?

I imagine those two cases should be consistent?

In `vec_size()` there is this note, and from that I got that both should then equal `0`:

```
#' vec_size(NULL) == 0
#' # Because vec_size(vec_c(NULL, x)) ==
#' #   vec_size(NULL) + vec_size(x) ==
#' #   vec_size(x)
```

If that is the case, then I'd imagine that `vec_size_common() == 0` as well. I got there because if `NULL` is treated as the absense of input, `vec_size_common() == vec_size_common(NULL)`

**Comment by lionel-** [comment]
> NULL should be treated as the absence of an input, definitely not as a zero length vector. 

Ah that makes sense!

> Should vec_size_common(NULL) == vec_size(NULL)?

Maybe `vec_size_common()` = `vec_size_common(NULL)` = `vec_size2(NULL, NULL)` = 1.

`vec_size2()` doesn't exist, but `vec_size_common()` is a reducing operation, so thinking about it in terms of identity on absence of inputs makes sense as well.

**Comment by DavisVaughan** [comment]
I _think_ this issue has been resolved since we handled the `vec_size(NULL)` issue elsewhere and `vec_compare(1:5, NULL)` should be an error since `NULL` is treated as the absence of input. I'll let someone else close though in case they have other thoughts

**Comment by hadley** [comment]
The current behaviour seems correct to me:

```R
vctrs::vec_compare(integer(), NULL)
#> Error: `y` must be a vector, not NULL
```

And we've discussed the size stuff elsewhere
