### ISSUE TITLE
Reconsider vec_ptype_abbr() for factor and complex

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#323]
After switching to `vec_ptype_abbr()` in {pillar}, two downstream packages now fail their checks. This is mostly due to the change from `"fct"` to `"fctr"` and `"cpl"` to `"cplx"` .

`type_sum()` moved *away* from `"fctr"` and `"cplx"` just over a year ago: https://github.com/r-lib/pillar/pull/80, suggested in https://github.com/r-lib/pillar/issues/71. It feels inconsistent that now `vec_ptype_abbr()` returns `"fctr"` and `"cplx"` .

@lionel- @hadley: Can we please move to `"fct"` and `"cpl"` here to save quite a few headaches downstream?

Thanks to @nacnudus for pointing this out: https://github.com/nacnudus/unpivotr/issues/24#issuecomment-490627895.

**Comment by hadley** [comment]
Yeah, that's fine with me. Want to do a PR?
