### ISSUE TITLE
Can't install 0.1.0.9003 because of issue with rlang_is_splice_box

### ISSUE THREAD

**Issue by mattle24** [r-lib/vctrs#331]
I'm trying to install the 0.1.0.9003 version of `vctrs` so I can install the dev version of `tidyr`. However, when I try to install `vctrs` 0.1.0.9003 using Windows 10 and R 3.6.0  I get this error: 

```
Error: package or namespace load failed for 'vctrs':
 .onLoad failed in loadNamespace() for 'vctrs', details:
  call: fun(libname, pkgname)
  error: function 'rlang_is_splice_box' not provided by package 'rlang'
Error: loading failed
Execution halted
ERROR: loading failed for 'x64'
```

I can install `vctrs` 0.1.0 from CRAN without issue.

**Comment by lionel-** [comment]
Did you use `remotes::install_github()`? It should automatically pull in the dev version of rlang.

**Comment by mattle24** [comment]
Didn't realize I needed a newer version of rlang, thanks @lionel-!

**Comment by ogorodriguez** [comment]
Hello, I am having the same issue. Could you please provide the complete code used to have the install.  Thanks. Did you use `remotes::install.github()` separately on tidyr, or on vctrs, or on rlang?

**Comment by ogorodriguez** [comment]
This is the error I am getting even after repeated installs of rlang in dev version...
`
remotes::install_github("r-lib/vctrs")`

`Error: package or namespace load failed for 'vctrs':
 .onLoad failed in loadNamespace() for 'vctrs', details:
  call: fun(libname, pkgname)
  error: function 'rlang_is_splice_box' not provided by package 'rlang'
Error: loading failed
Execution halted
ERROR: loading failed for 'x64'
* removing 'C:/Users/.../Documents/R/win-library/3.4/vctrs'
* restoring previous 'C:/Users/.../Documents/R/win-library/3.4/vctrs'
Error: (converted from warning) running command '"C:/PROGRA~1/R/R-34~1.2/bin/x64/R" CMD INSTALL -l "C:\Users\...\Documents\R\win-library\3.4" "C:/Users/...E~3/AppData/Local/Temp/RtmpU3P4NF/file487432754cc4/vctrs_0.1.0.9003.tar.gz"' had status 1`

Any help on this issue will be highly appreaciated.

**Comment by lionel-** [comment]
Please shut down all your R and RStudio sessions. Then start a new one, make sure that rlang is not loaded by consulting `sessionInfo()` (it could be loaded automatically via your RProfile if you load tidyverse packages).

And only then `remotes::install_github("r-lib/rlang")`.

When you install packages with compiled code on Windows, be extra careful with the output. When R can't update the DLL, it doesn't fail and instead issues a warning and leaves your installation broken. This doesn't happen on Linux or macOS because files already in use can still be overwritten on those platforms.

**Comment by ogorodriguez** [comment]
Thanks for the prompt reply.  I was able to install rlang following your instructions.  Now I can go on and install vctrs with the proper version to then install the dev version of tidyr?  When I try to install tidyr it is asking me to install version `vctrs (0.1.0 -> d90ff1059...) [GitHub]`.  

Here is the full code:
`devtools::install_github("tidyverse/tidyr")
Downloading GitHub repo tidyverse/tidyr@master
These packages have more recent versions available.
Which would you like to update?

1:   vctrs (0.1.0 -> d90ff1059...) [GitHub]

Enter one or more numbers separated by spaces, or an empty line to cancel
1: `

**Comment by lionel-** [comment]
Yes tidyr depends on the development version of vctrs.

**Comment by ogorodriguez** [comment]
Ok.  Could you tell me how should I proceed in this case?  Should I follow the prompt and type 1, or should I use remotes::install.github() to get vctrs, and then install dev tidyr.  Thanks a lot for this help, but I have been going through this for a week.

**Comment by lionel-** [comment]
Sorry about that. To be extra safe you could repeat the same procedure with vctrs, close all the sessions and install with `remotes::install_github("r-lib/vctrs")`.

I believe that closing the sessions and doing `remotes::install_github("r-lib/tidyr")`, and selecting `1` at the prompt should work though.

@gaborcsardi is working on https://github.com/r-lib/pak to make package installations much less painful for Windows users by the way.

**Comment by ogorodriguez** [comment]
Hello @lionel- Thanks a lot.  I was able to get the dev version of tidyr! following your indications.  Will give pak a try in the future.  

big hug!

**Comment by chalg** [comment]
Wow, having the same issue, some really good pointers in here!
