### ISSUE TITLE
Question) Proper use of `vec_restore()`

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#340]
I'm sorry this is a bit long, no rush on a response.

I have a question about the proper usage of `vec_restore()`, specifically inside of comparison and arithmetic operations. First, I'll describe my original intent.

In rray, I have a `>` method that compares objects with broadcasting. Because that idea might be useful in general, I have exposed `rray_greater()` which is the underlying engine powering that function. That way, a user could explicitly compare two base R arrays with broadcasting.

The question I have is about the return value. My original thoughts were that _`rray_greater()` should return an array if only given base R objects, and an rray if any input is an rray._

* First, is that would you would expect to happen too? Alternatively, since 99% of the time it will be called with `>` where one of the inputs is guaranteed to be an rray, it could _always_ return an rray (or a base R array if you think comparison operators should always return low level base R objects).

* Second, if the original behavior is what you would expect to happen (being able to return an array or rray), how would one implement this correctly? Currently, I do something roughly like:

```
rray_greater <- function(x, y) {
  
  # because the C impl expects x and y to have the same type
  args <- vec_cast_common(x, y)
  
  # compare with broadcasting
  res <- rray__greater_c_impl(args[[1]], args[[2]])
  
  # restore to either rray or array
  vec_restore(res, vec_type2(x, y))
}
```

However, I feel that this is an incorrect use of `vec_restore()`, and only works because I am getting lucky. I would like to have confirmation on that. I feel that way because `vec_type2(x, y)` could have a common type of an rray of doubles. `res` is _always_ a logical, so then I'd be "restoring" to an rray of doubles. My `vec_restore()` method kind of glosses over the "inner type" and just sees that I should be restoring to an rray class, and all is well, but I feel like that is incorrect. FWIW, vctrs allows this with base R objects, which is why `rray_greater()` also works when comparing two base R arrays:

``` r
library(vctrs)
vec_restore(x = matrix(TRUE), to = matrix(1))
#>      [,1]
#> [1,] TRUE
```

But not with `vctrs_vctr` classes:

``` r
library(vctrs)
vec_restore(new_vctr(matrix(TRUE)), new_vctr(matrix(1)))
#> Can't cast <vctrs_vctr> to <vctrs_vctr>

# because of 
vctrs:::vec_restore.vctrs_vctr
#> function (x, to, ..., i = NULL) 
#> {
#>     if (typeof(x) != typeof(to)) {
#>         stop_incompatible_cast(x, to)
#>     }
#>     NextMethod()
#> }
#> <bytecode: 0x7ffa81be9d40>
#> <environment: namespace:vctrs>
```

So I guess my main question is: If I should allow the flexible return type, how should it be implemented using vctrs functions?

**Comment by lionel-** [comment]
I think the problem is that there is no concept of `vector_of<>` in vctrs. It seems reasonable to always return the same type from `rray_greater()`, though my first impression is to agree that more genericity would be nice.

**Comment by DavisVaughan** [comment]
> I think the problem is that there is no concept of `vector_of<>` in vctrs

Currently I subclass my rray's based on their "inner type", so it looks like `c("vctrs_rray_int", "vctrs_rray", "vctrs_vctr")`. It doesn't help me much here, but I thought it was worth mentioning. It makes my `vec_cast()` methods really clean because I know exactly what to do with `vec_cast.vctrs_rray_int.vctrs_rray_dbl` as opposed to just `vec_cast.vctrs_rray.vctrs_rray`.

> though my first impression is to agree that more genericity would be nice

Yea and I'm also _trying_ to think about the fact that if rray was ever extended, it might make sense that comparing `<rray>` and `<extended-rray>` should return `<extended-rray>`. So keeping that extensibility would be nice.

**Comment by hadley** [comment]
Why wouldn't you use `vec_cast(res, vec_type2(x, y))`?  You'd normally only use `vec_restore()` if you'd used `vec_proxy()` earlier.

**Comment by lionel-** [comment]
@hadley IIUC this would cast to the correct container type but to the wrong containee type, which should be logical.

**Comment by DavisVaughan** [comment]
Correct, `vec_type2(x, y)` might return a `vctrs_rray_dbl`, but `res` is always a logical. So `vec_cast(res, vec_type2(x, y))` would request that I cast to an rray (which would be correct) but would also coerce to double (which would be incorrect).

**Comment by hadley** [comment]
Oooh of course, it's a logical matrix. I wonder if we are missing something like `vec_cast_container()`. We're using `vec_restore()` in that sense when we pass stuff to internal functions that lose attributes.

**Comment by DavisVaughan** [comment]
I think that sounds like it would be helpful.

**Comment by DavisVaughan** [comment]
This is incomplete but works for my use cases, it essentially replaced all of my calls to `vec_restore()`. https://github.com/DavisVaughan/rray/blob/cast-container/R/cast-container.R

**Comment by lionel-** [comment]
I noticed we also need the container type in `vec_cbind()`. In this case, it's enough to just remove all columns from the data frame. Empty data frames are always coercible to each together so the casting looks like this:

- Take container type for all elements
- Find their common type
- Cast to common type

Perhaps we just need a new `vec_container_type()` generic? For data frames, the default method would strip columns and for arrays, it'd return an array of `<unspecified>`. Then you just need to find the common type of the logical matrix and the unspecified inputs, and cast to that.

This seems extensible because `vec_container_type()` could also return a partial type for more complex cases.

**Comment by lionel-** [comment]
hmm actually we can't derive an rray from `vctrs_unspecified` (and using inheritance here doesn't seem appropriate anyway). So maybe rrays should return a partial type?

**Comment by DavisVaughan** [comment]
Closing because this is generally outdated and we should rethink the whole thing if this comes up again
