### ISSUE TITLE
Performance) `new_vctr()` overhead

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#341]
Currently, with R < 3.6.0, `new_vctr()` makes 4 copies every time it is called. Since this should be a really cheap function, I was hoping we could do something about this. As is, it's really killing my rray performance.

There are two main issues, both stem from the fact that `attributes(x) <- list(...)` creates two copies when there are attributes to set. See my examples below:

``` r
x <- 1:50000 + 0L
garbarge <- capture.output(profmem::profmem(attributes(x) <- NULL))

# set to nothing (same as setting to NULL)
x <- 1:50000 + 0L
profmem::profmem(attributes(x) <- list())
#> Rprofmem memory profiling of:
#> attributes(x) <- list()
#> 
#> Memory allocations:
#>        what  bytes      calls
#> 1     alloc 200048 <internal>
#> total       200048

# set attributes. Agh! Two copies!
x <- 1:50000 + 0L
profmem::profmem(attributes(x) <- list(stuff = "hi"))
#> Rprofmem memory profiling of:
#> attributes(x) <- list(stuff = "hi")
#> 
#> Memory allocations:
#>        what  bytes      calls
#> 1     alloc 200048 <internal>
#> 2     alloc 200048 <internal>
#> total       400096

# Clever way to call it, which only copies once
x <- 1:50000 + 0L
profmem::profmem(x <- `attributes<-`(x, value = list(stuff = "hi")))
#> Rprofmem memory profiling of:
#> x <- `attributes<-`(x, value = list(stuff = "hi"))
#> 
#> Memory allocations:
#> Number of 'new page' entries not displayed: 1
#>        what  bytes      calls
#> 2     alloc 200048 <internal>
#> total       200048
```

Based on the above results, I have two suggestions.

1) `validate_attr()` should validate and return names, but not set them. It will simply pass them on to `structure()`, ~which always removes all attributes from `.Data` before adding new ones.~ (not true, see the Update below)

2) We should wrap `structure()` so we have a version that does the exact same thing, except it sets attributes using `attributes<-(.Data, value = c(attributes(.Data), attrib))` since that only makes 1 copy, as seen above. Maybe call it `vec_structure_shim()`.

To be as forward compatible as possible, I think it would make sense to create this `vec_structure_shim()` in `.onLoad()`. If the version is >= 3.6.0, we can just use base R's provided `structure()`, which has fixed the double copy issue, and with ALTREP often makes 0 copies until needed. Otherwise, we use our shim.

PS: For the interested, I believe this `attributes<-()` double copy behavior might have been some kind of bug that was just fixed. There was a time between 3.5.3 and 3.6.0 where this was what `structure()` did, which leads me to believe that even after they had ALTREP parts in place, it was still making a copy because of some compiler bug. 
https://github.com/wch/r-source/commit/8d332d420f83c4343cf2e1a5694faeffc9de599e#diff-7eda0a571a9f91eb3be4d1627b8d4c2aL37

Here is a before/after performance comparison:

``` r
x <- 1:500000 + 0L
dim = c(5000L, 100L)

bench::mark(
  new_vctr(x, dim = dim),
  new_vctr2(x, dim = dim)
)
#> # A tibble: 2 x 10
#>   expression   min     mean   median    max `itr/sec` mem_alloc  n_gc n_itr
#>   <chr>      <bch> <bch:tm> <bch:tm> <bch:>     <dbl> <bch:byt> <dbl> <int>
#> 1 new_vctr(… 706µs   1.77ms   1.11ms 5.56ms      565.    7.65MB    43   152
#> 2 new_vctr2… 135µs 484.16µs 279.96µs 1.22ms     2065.    1.96MB    39   801
#> # … with 1 more variable: total_time <bch:tm>
```

Update) `structure()` does not actually remove existing attributes from `.Data`, but maybe this is ok? Otherwise I don't see a way to add _only_ the attributes in `...` without either rewriting `structure()` or making a second copy with `attributes(x) <- NULL`

**Comment by DavisVaughan** [comment]
This behavior is a bit interesting because with data frames / lists, the inner elements don't get double copied, only the container itself. So you get interesting (but expected) results like this:

``` r
x <- factor(rep(letters[1:3], each = 1000))
df <- data.frame(x = x)

profmem::profmem(attributes(df) <- list(stuff = "hi"))
#> Rprofmem memory profiling of:
#> attributes(df) <- list(stuff = "hi")
#> 
#> Memory allocations:
#>       what bytes calls
#> total          0

profmem::profmem(attributes(x) <- list(stuff = "hi"))
#> Rprofmem memory profiling of:
#> attributes(x) <- list(stuff = "hi")
#> 
#> Memory allocations:
#>        what bytes      calls
#> 1     alloc 12048 <internal>
#> 2     alloc 12048 <internal>
#> total       24096

xx <- rlang::new_list(10000000)
profmem::profmem(attributes(xx) <- list(stuff = "hi"))
#> Rprofmem memory profiling of:
#> attributes(xx) <- list(stuff = "hi")
#> 
#> Memory allocations:
#>        what     bytes      calls
#> 1     alloc  80000048 <internal>
#> 2     alloc  80000048 <internal>
#> total       160000096
```

**Comment by DavisVaughan** [comment]
Oooh we could also use this trick in `vec_data()` which also makes two copies every time it is called, which also hurts. It would at least drop it down to 1 copy in R < 3.6.0.

``` r
library(vctrs)
x <- 1:5000 + 0L
profmem::profmem(vec_data(x))
#> Rprofmem memory profiling of:
#> vec_data(x)
#> 
#> Memory allocations:
#>        what bytes      calls
#> 1     alloc 20048 vec_data()
#> 2     alloc 20048 vec_data()
#> total       40096
```

<sup>Created on 2019-05-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by juangomezduaso** [comment]
As the goal of removing existing attributes and setting new ones can be achieved in one go:

``` r
x <- 1:50000 + 0L
attributes(x) <- list(stuff = "hi")
x<-`attributes<-`(x, list(stuff=NULL, newstuff="hello"))
attributes(x)                  
#> $newstuff
#> [1] "hello"
```

<sup>Created on 2019-05-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

 perhaps the dots passed to structure() in new_vctrs() could be arranged to write and delete in one call

**Comment by hadley** [comment]
Rather than hacking around with `attributes<-`, I think it would be better to write a small C helper (which we’d only use in older versions of R)

**Comment by DavisVaughan** [comment]
Unfortunately `do_attributesgets()` is complicated enough that replicating it's behavior completely would be a bit of work. 

I don't think `attributes<-` is exposed at the C level (`do_attributesgets()` uses both `SET_ATTRIB()` and `Rf_setAttrib()`, which are exposed, but individually don't do enough).

https://github.com/wch/r-source/blob/27da0eac8bb84677002febcf12e6d61bb7358d89/src/main/attrib.c#L1289

**Comment by hadley** [comment]
I don’t think we need to replicate it exactly because we’re overriding the existing attributes, and we can already assume that the names are unique.
