### ISSUE TITLE
Provide legacy naming function

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#359]
From https://github.com/tidyverse/tidyr/issues/641#issuecomment-496583453 (note that the default arguments are slightly different from those in readxl)

```R
legacy_repair <- function(nms, prefix = "V", sep = "") {
  if (length(nms) == 0) return(character())
  blank <- nms == ""
  nms[!blank] <- make.unique(nms[!blank], sep = sep)
  new_nms <- setdiff(paste(prefix, seq_along(nms), sep = sep), nms)
  nms[blank] <- new_nms[seq_len(sum(blank))]
  nms
}
```

**Comment by lionel-** [comment]
Does it make sense to provide it in a dated compat- file rather than as an exported function?

**Comment by hadley** [comment]
I think it will be easier to export it.
