### ISSUE TITLE
Should equality and hashing be consistent?

### ISSUE THREAD

**Issue by lionel-** [r-lib/vctrs#364]
Currently hashes ignore attributes, even for list components. This is not consistent with `vec_equal()`:

```r
vec_hash(list(mtcars))
#> [1] 80 e5 8c e3

vec_hash(list(tibble::as_tibble(mtcars)))
#> [1] 80 e5 8c e3

vec_equal(list(mtcars), list(tibble::as_tibble(mtcars)))
#> [1] FALSE
```

**Comment by hadley** [comment]
I think `vec_equal(x, y)` has to imply that `vec_equal(vec_hash(x), vec_hash(y))`, but the opposite is not true: `vec_equal(vec_hash(x), vec_hash(y))` does not imply that `vec_equal(x, y)`.

**Comment by lionel-** [comment]
What is an example of the opposite not being true?

Note that objects are coerced before hashing, which should ensure congruent attributes for the vector parts, so that really only concerns list components. To me it seems sloppy not to compare these as wholes and I expect it will cause problems down the line. For instance when comparing elements of list-cols, it seems model fit objects should be fully hashed rather than treated as ordinary vectors.

**Comment by hadley** [comment]
Hash collisions!

**Comment by hadley** [comment]
I think of hash comparison as being a performance optimisation, so ignoring attributes seems like a reasonable trade-off to me. But I admit I have not fully though the consequences through for non-vector types, and it's totally possible it makes sense to also hash attributes there.

**Comment by lionel-** [comment]
ah of course!

So to take the example above, though these objects have the same hash, they won't compare equal and will occupy a different place in the dictionary.

What I had in mind is to hash attributes in `hash_object()`, so the overhead should only concern lists components, not other vectors. This should improve speed in case of many similar objects since we'll have much fewer collisions.

**Comment by hadley** [comment]
Yeah, that makes sense to me (although I would probably save it for the next release unless you have a pressing use case)

**Comment by lionel-** [comment]
No pressing use case since the current behaviour is correct. This only took a few minutes to implement though, I'll send a PR now so this issue is out of the way.
