### ISSUE TITLE
Create an empty Date vector

### ISSUE THREAD

**Issue by amarchin** [r-lib/vctrs#37]
Sometimes it is useful to create empty vectors using commands like `integer()`, `character()`, etc.

Very often I use Date vectors created with the `ymd` function from `lubridate` but I am not able to create empty Date vectors (maybe there is a way to do taht but I don't know the trick).

Could be this package the right place in which expose this feature?

**Comment by amarchin** [comment]
I figured out a way to do that

```r
as.Date(x = integer(0), origin = "1970-01-01")
```

Maybe a more user-friendly API is still useful :)

**Comment by hadley** [comment]
I think that function belongs in lubridate. It's possible that vctrs will generally export some helpers to construct base classes, but I'm not sure it's the right place.

**Comment by asrguru** [comment]
Just saw this, as I was looking into this same question - thought you might find my lubridate answer interesting, even though this is closed -
`empty_date_vector <- as_datetime(vector(mode="integer", length = some_needed_length))`

I imagine this would work with as_date as well ...
