### ISSUE TITLE
Better name for vec_na()

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#372]
Not immediately obvious what it's supposed to do

**Comment by DavisVaughan** [comment]
More along the lines of `vec_template()`?

**Comment by jennybc** [comment]
`vec_init()`?

**Comment by hadley** [comment]
`vec_new()` or `vec_create()` could be options too

**Comment by DavisVaughan** [comment]
Did we come up with a solution? I think this should be done this release. I am fond of `vec_init()` now. In particular I am thinking of the case where you would `vec_init()` an empty version of a vector and then fill it in with results using `vec_assign()` or something similar

**Comment by lionel-** [comment]
I like `vec_init()` too, it has a good synergy with loop idioms as you mention.

**Comment by hadley** [comment]
I'm good with `vec_init()`
