### ISSUE TITLE
Potentially rethink `vec_size(NULL) = error`

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#373]
@hadley depending on what is decided here, this might be a tidyr bug.

Modified from this tidyr issue:
https://github.com/tidyverse/tidyr/issues/646

What should this return? It seems natural here that `unchop()` should be using `vec_size()` (through `vec_is_empty()`) as it currently is (mapping over a list, checking the size of each element).

To me it seems that `vec_size(NULL)` really should have been `0`, so the idea of mapping over a list and checking the size of each element works without issue.

``` r
library(tidyr)
df1 <- tibble(
  id = 1:3,
  data = list(
    tibble(a = 1, b = 2), 
    NULL, 
    tibble(a = 3, b = 4)
  )
)

df1 %>% unchop(data)
#> # A tibble: 2 x 2
#>      id data$a    $b
#>   <int>  <dbl> <dbl>
#> 1     1      1     2
#> 2     3      3     4

df1 %>% unchop(data, keep_empty = TRUE)
#> Error: The size of `NULL` is not defined.
```

A similar bug is going to happen to me in rray. I map over the dim names list and check the size of each element. Each element can be either `NULL` or a character vector and I have previously been expecting the `NULL` elements to have size 0.

Or maybe it also needs an `absent` argument?

**Comment by hadley** [comment]
Or we could special case `vec_is_empty()`? 🤔

**Comment by DavisVaughan** [comment]
That would be fine too. I use the actual lengths in rray (not just whether or not it is empty), but I can refactor around it easily.

**Comment by lionel-** [comment]
Special-casing `vec_is_empty()` would muddy its semantics I think.

I'm starting to think that the path of least resistance is to have `vec_size(NULL) == 0L`. And then the `.absent` argument can default to 0 too for consistency. It seems it would be more practical, and can be justified this way: a size measures how much space an element takes, and absent elements don't take up space. The most common purpose of `vec_size()` is for assembling inputs together and compute a total size, an operation for which 0 is the identity.

When a different value is required, e.g. for `vec_recycle()`, the inputs can be preprocessed or `vec_size_common(.absent = na_int)` can be used.

**Comment by hadley** [comment]
So `vec_size(NULL) == 0` and `vec_size_common(x, NULL)` equals `vec_size(x)` and we'll just document that `NULL` gets special handling?  I think that seems reasonable.
