### ISSUE TITLE
Export `vec_as_index()`

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#381]
@lionel- I believe you mentioned you were planning on exporting this, correct? I use it in rray (although I use it over any dimension, not just the 1st dimension, which requires a bit of a hack).

**Comment by lionel-** [comment]
What would be an interface that wouldn't require you to use a hack? Possibly for a second function.

**Comment by DavisVaughan** [comment]
Just to explain how I use it first, the user can of course do `x[...]` with row/col/etc indexing.

So I pass along `x` and `...` to `rray_as_index(x, ...)`.

It iterates over `...` and passes each index along to `vec_as_index()`. 

The main hack is that `x` in `vec_as_index()` has to have the correct _size_ and optionally has to have the names attached. So when I want to validate the column index, I have to create a dummy proxy that has the length of the number of columns, and optionally attach the column names to it.
https://github.com/DavisVaughan/rray/blob/2a203b09fc5e09792d332935ae33f631a70c58f9/R/subset.R#L156

I was going to suggest that rather than `x` you just accept `size` / `n`. That works in all cases except for `chr_as_index()` where you have to rip the names off of `x`. Maybe `vec_as_index(i, n, names)` with `names` being optional and only used if `i` is character? Not sure exactly how that would work, but that would be a solution for me because then you don't have to create the proxy, and you really just pass in the required information to check `i`.

**Comment by DavisVaughan** [comment]
`vec_index()` could maybe use `vec_names()` to get the names from `x` and pass them on to `vec_as_index()`. It would have the correct behavior of passing along `NULL` if there are no names, and this would still be an error if `i` is character.
