### ISSUE TITLE
Question: vec_math not working if vec_proxy is defined

### ISSUE THREAD

**Issue by earowang** [r-lib/vctrs#393]
This is more of a question, because my understanding about `vec_proxy` may not be correct.

I've defined a new class `my_rle`, a named list.

``` r
library(vctrs)
my_new_rle <- function(x = list(lengths = integer(), values = integer())) {
  new_vctr(x, class = "my_rle")
}

my_rle <- function(x) {
  my_new_rle(rle(x))
}

length.my_rle <- function(x) { # for size display
  length(x$values)
}

(x <- my_rle(c(rep(1, 3), rep(3, 2), rep(10, 10))))
#> <my_rle[3]>
#>  lengths   values 
#> 3, 2, 10 1, 3, 10
```

I'd like `sum()` over the `lengths` of `my_rle`. This works fine until I've defined `vec_proxy`.

```r
vec_math.my_rle <- function(fun, x, ...) {
  vec_math_base(fun, x$lengths, ...)
}
sum(x)
#> [1] 15
x[2:3]
#> Error: Can't index beyond the end of a vector.
#> The vector has length 2 and you've tried to subset element 3.
```

I'd also like subsetting `my_rle` like a vector which goes beyond the list length 2. In this case, I need to define `vec_proxy`.

```r
vec_proxy.my_rle <- function(x) {
  new_data_frame(unclass(x))
}

x[2:3]
#> <my_rle[2]>
#> lengths  values 
#>   2, 10   3, 10
```

The subsetting works as expected, but `sum()` no longer works. I `browser()` through `vec_restore`, and found that `i` takes 3 `NA`s in the second iteration, which triggers the error.

```r
sum(x)
#> Error in vec_c(...): Internal error in `vec_assign()`: `value` should have been recycled to fit `x`.

vec_restore.my_rle <- function(x, to, ..., i = NULL) {
  my_new_rle(x)
}
x[2:3]
#> <my_rle[2]>
#> lengths  values 
#>   2, 10   3, 10
sum(x)
#> Error in vec_c(...): Internal error in `vec_assign()`: `value` should have been recycled to fit `x`.
```

I don't quite understand how `vec_math` is linked with `vec_proxy`. Could you help with that? Thanks.

Related to #332 

<sup>Created on 2019-06-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
As suggested in #442, I think this class should be implemented as a record vector.
