### ISSUE TITLE
Flattening, squashing and unpacking

### ISSUE THREAD

**Issue by earowang** [r-lib/vctrs#395]
I'm wondering if it's worth implementing a type-stable equivalent of `unlist()`, particularly useful for a homogenous `list_of`. Currently we have to use `do.call()` to preserve the class in base R.

``` r
unlist(list(Sys.Date(), Sys.Date() - 1))
#> [1] 18055 18054

do.call("c", list(Sys.Date(), Sys.Date() - 1))
#> [1] "2019-06-08" "2019-06-07"
```

<sup>Created on 2019-06-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DavisVaughan** [comment]
I think this is similar to #183, also makes me wonder if `vec_simplify()` needs to be recursive in some way

**Comment by hadley** [comment]
The vctrs equivalent of `unlist(x)` is `vec_x(!!!x)`

**Comment by earowang** [comment]
You mean `vec_c()`? But can be recursive?

**Comment by hadley** [comment]
Oh you want recursive flattening? I think that's usually a sign that something is wrong with your design.

**Comment by earowang** [comment]
I don’t need recursive flattening for the package, vec_c() is good enough.
Just curious bc unlist() has recursive option.

**Comment by lionel-** [comment]
@hadley I think it can also be a sign that something is wrong with the data, which might be outside the analyst control. It might make sense to provide the equivalent of `rlang::squash()`.

**Comment by lionel-** [comment]
Also discussed in tidyverse/purrr#575.

**Comment by vspinu** [comment]
Recursive flattening is very useful with hierarchical datastructures (json, xml). `unlist`'s type inference is a crazy design. A simple workaround is to insert a symbol dummy before the unlist:

```R

unlist2 <- function(x, recursive = TRUE, use.names = TRUE) {
  x <- as.list(x)
  x[["..DUMMY.."]] <- as.name("..DUMMY..")
  out <- unlist(x, recursive = recursive, use.names = use.names)
  out[["..DUMMY.."]] <- NULL
  out
}

```
