### ISSUE TITLE
Handle row names

### ISSUE THREAD

**Issue by lionel-** [r-lib/vctrs#397]
For instance in `vec_slice()`:

```r
vec_slice(mtcars, 1)
#>   mpg cyl disp  hp drat   wt  qsec vs am gear carb
#> 1  21   6  160 110  3.9 2.62 16.46  0  1    4    4
```

@hadley Perhaps this should make it into 0.2.0? Supporting it later on might be disruptive if unit tests in downstream deps make incidental assumptions about row names.

**Comment by lionel-** [comment]
Would be great to support names in record classes as well. Row names would be the best fit to implement this, but then we need our own `data.frame` subclass that allows duplicated row names.

**Comment by hadley** [comment]
Yeah, I think we should add `rowname` support in `vec_slice()` and consider where else it's needed.

For records, I think we can just use a specially named column like `.name`.
