### ISSUE TITLE
Use classed error conditions everywhere

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#401]
From C code, this probably means a call back to R to call `signalCondition()` . Does rlang have a C API for this?

**Comment by lionel-** [comment]
We're already throwing classed errors from C, but I rather just do it case by case than everywhere. What errors from names.c do you need to be structured?

**Comment by krlmlr** [comment]
#408 should be rewritten in C, the errors thrown from there should be throwable from C.

**Comment by hadley** [comment]
This is in progress
