### ISSUE TITLE
Evaluate arguments lazily in vec_as_names()

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#410]
The names can be expensive to compute for tibbles. In the example below, I'd expect `n()` and `names()` to be called only if necessary.

``` r
library(vctrs)

n <- function() {
  message("n")
  3L
}
names <- function() {
  message("names")
  letters[1:3]
}

vec_as_index(1L, n(), names())
#> n
#> names
#> [1] 1
vec_as_index(TRUE, n(), names())
#> n
#> names
#> [1] 1 2 3
vec_as_index("a", n(), names())
#> n
#> names
#> [1] 1
```

<sup>Created on 2019-06-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by krlmlr** [comment]
This is of very little relevance right now, as I need to provide compat code in tibble. Maybe in tibble 3.0.0?

**Comment by lionel-** [comment]
How come the names are expensive to compute by the way? Is this for row names?

**Comment by krlmlr** [comment]
Yes, at some point I thought this is a problem, but it's probably not. Closing for now.
