### ISSUE TITLE
`vec_type2()` and grouped data frames

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#417]
I think this is somewhat related to #211, but I'd be curious to collect thoughts on what this should return. I imagine this one is easy. The second result should be a grouped data frame with all of the grouping columns of `grouped_starwars` maintained? I'm also not sure where the implementation of that `vec_type2()` method will live. Should vctrs "know" about grouped data frames?

``` r
library(vctrs)
library(dplyr, warn.conflicts = FALSE)

grouped_starwars <- starwars %>% group_by(eye_color)

vec_type2(starwars, starwars)
#> # A tibble: 0 x 13
#> # … with 13 variables: name <chr>, height <int>, mass <dbl>,
#> #   hair_color <chr>, skin_color <chr>, eye_color <chr>, birth_year <dbl>,
#> #   gender <chr>, homeworld <chr>, species <chr>, films <list>,
#> #   vehicles <list>, starships <list>

vec_type2(starwars, grouped_starwars)
#>  [1] name       height     mass       hair_color skin_color eye_color 
#>  [7] birth_year gender     homeworld  species    films      vehicles  
#> [13] starships 
#> <0 rows> (or 0-length row.names)
```

<sup>Created on 2019-06-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by lionel-** [comment]
I think this should be dealt with in dplyr. Tibble methods will probably live in the tibble repo as well.

**Comment by hadley** [comment]
Can you move to dplyr please?

**Comment by DavisVaughan** [comment]
sure
