### ISSUE TITLE
Feature request: obj_print_size() for displaying dimensions

### ISSUE THREAD

**Issue by earowang** [r-lib/vctrs#442]
The recent change in `obj_print_header()` where `length()` is replaced by `vec_size()` makes it impossible to customise the dimension for the purpose of displaying.

``` r
library(vctrs)
library(dplyr, warn.conflicts = FALSE)

my_new_rle <- function(x = list(lengths = integer(), values = integer())) {
  new_vctr(x, class = "my_rle")
}

my_rle <- function(x) {
  my_new_rle(rle(x))
}
```

Previously,  defining `length()` provides a way for displaying the size.

```r
length.my_rle <- function(x) { # previously used for size display
  length(x$values)
}
```

Now, I need to define `obj_print_header()` to get the size properly displayed.

```r
obj_print_header.my_rle <- function(x) {
  cat(paste0(vec_ptype_full(x), "<", length(x), ">"))
  invisible(x)
}

x <- c(rep(1, 3), rep(3, 2), rep(10, 10))
my_rle(x)
#> my_rle<3> lengths   values 
#> 3, 2, 10 1, 3, 10
```

However, `vctrs_list_of` currently displays `vec_size()` instead of `length()`. This is not that informative for this `my_rle` class, because it's always a list of two elements. It would be more informative to show the number of runs. I understand `vec_size()` is more robust. Is it possible to provide `obj_print_size()` method for the displaying purpose?

```r
tbl <- tibble(x = rep(x, times = 3), group = rep(letters[1:3], each = 15))

tbl %>% 
  group_by(group) %>% 
  summarise(x_rle = list_of(my_rle(x)))
#> # A tibble: 3 x 2
#>   group          x_rle
#>   <chr> <list<my_rle>>
#> 1 a                [2]
#> 2 b                [2]
#> 3 c                [2]
```

<sup>Created on 2019-06-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
Is it possible you need to make your RLE class a record type with lengths and values fields? If `vec_size()` doesn't return the actual length of your vector, there is a problem with the class design.

**Comment by earowang** [comment]
Now I think the RLE class is more appropriate to be a record type. Thanks for that. But now `vec_size()` returns the desired lengths, but the display of `vctrs_list_of` doesn't update.

``` r
library(vctrs)
library(dplyr, warn.conflicts = FALSE)

my_new_rle <- function(x = list(lengths = integer(), values = integer())) {
  new_rcrd(x, class = "my_rle")
}

my_rle <- function(x) {
  my_new_rle(unclass(rle(x)))
}

x <- c(rep(1, 3), rep(3, 2), rep(10, 10))
vec_size(my_rle(x))
#> [1] 3

tbl <- tibble(x = rep(x, times = 3), group = rep(letters[1:3], each = 15))

tbl_rle <- tbl %>% 
  group_by(group) %>% 
  summarise(x_rle = list_of(my_rle(x))) %>% 
  print()
#> # A tibble: 3 x 2
#>   group          x_rle
#>   <chr> <list<my_rle>>
#> 1 a                [2]
#> 2 b                [2]
#> 3 c                [2]
tbl_rle$x_rle
#> <list_of<my_rle>[3]>
#> [[1]]
#> <vctrs_rcrd[3]>
#> `format.vctrs_rcrd()` not implemented.
```

<sup>Created on 2019-06-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
You need to implement a format method, see the S3 vignette: https://vctrs.r-lib.org/articles/s3-vector.html#rational-class
