### ISSUE TITLE
Should `vec_init()` be a primitive customisation point?

### ISSUE THREAD

**Issue by lionel-** [r-lib/vctrs#445]
Relying on `x[NA_integer_]` to get missing values limits compatibility with foreign classes such as integer64.

**Comment by hadley** [comment]
I would've thought that was a fundamental property of vector classes, and if you don't implement it, you'll have problems else where (e.g. `x[x > 0]` will return the wrong thing when `x` contains missing value; although maybe that's a sign we should be using a logical missing?)

**Comment by lionel-** [comment]
hmm this doesn't work with integer64 either, the class is definitely broken on this front:

```r
x <- bit64::as.integer64(1:5)
x[[1]][NA]
#> integer64
#> [1] 9218868437227407266
```

**Comment by lionel-** [comment]
@joehl Would you accept a patch to fix this?

**Comment by jtbates** [comment]
It was patched [last year](https://r-forge.r-project.org/scm/viewvc.php?view=rev&root=ff&sortby=log&sortdir=down&revision=176), but hasn't been released to CRAN yet.

tidyverse/tidyr#758

**Comment by DavisVaughan** [comment]
I think we can close this? I imagine that `x[NA_integer_]` should work with all vectors, and we've worked around the integer64 case for now

**Comment by lionel-** [comment]
Agreed.
