### ISSUE TITLE
argument name antipattern

### ISSUE THREAD

**Issue by barryrowlingson** [r-lib/vctrs#45]
Having special names for some arguments when the other arguments are absorbed into everything else is an antipattern because the function can't tell between the argument as a special argument or as an unspecial named argument. Example:
```
vec_c(1, 2, .type = integer())
#> [1] 1 2
```

`vec_c` supports named vectors, so `vec_c(a=1, b=2, .type=integer())` is valid, but `vec_c(.print=1, .type=2, .screen=3)` fails because the `.type` argument is treated specially.

The arguments for this antipattern are:

- The low probability of having an argument with that name is very low  - but that probability is non-zero and increases linearly with the amount of usage. When it hits it generates massive surprise.
- Names starting with a dot are well-known as "special" and are documented - but this relies on people being introduced to the documentation at first usage.

The existence of specially-named arguments when there is a possibility of misinterpretation is an irregularity which seems incongruous with everything else being tidy.

You could write `vec_c` to return a function, and then pass the type argument as a further argument:

```
vec_c(a=1, .type=99, type=23)()  # returns c(a=1,.type=99, type=23)
vec_c(a=1, .type=99, type=23)(type=integer()) # as above but integer type.
```

This approach has the advantage that the argument no-longer needs to be "dotted".

**Comment by lionel-** [comment]
With tidy dots it is easy to circumvent argument matching:

```
# Wrap and splice
vec_c(!!!list(.print = 1, .type = 2, .screen = 3))

# Or use the := operator
vec_c(.print = 1, .type := 2, .screen = 3)
```

See `?rlang::list2`.

**Comment by hadley** [comment]
I agree that using dot-prefixed arguments is suboptimal, but I think it's the least-worst solution. Returning a function has the substantial downside that the most common usage (not supplying the type) requires additional syntax (an additional pair of parentheses).

**Comment by hadley** [comment]
@barryrowlingson if you're interested in continuing to discuss this, a better place might be https://github.com/tidyverse/principles/ (since it affects the whole tidyverse, not just vctrs)
