### ISSUE TITLE
Lossy cast from NA_integer_ to logical()?

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#451]
Is this a lossy cast?

``` r
vctrs::vec_cast(NA_integer_, logical())
#> Lossy cast from `x` <integer> to `to` <logical>.
#> Locations: 1
```

<sup>Created on 2019-06-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I attempted to do `vec_cast(c(NA, 1L), logical())` and was surprised to see an error.

**Comment by hadley** [comment]
Oh, we probably forgot to check for NAs in that branch. It should be an easy fix if you want to take it.

**Comment by DavisVaughan** [comment]
- Not checked in int as logical conversion: https://github.com/r-lib/vctrs/blob/a8924ec0191caf9ce2dbe274d8b1ca4c14315fbc/src/cast.c#L29
- Checked in dbl as logical conversion, but early lossy return takes precedence and we never get here https://github.com/r-lib/vctrs/blob/a8924ec0191caf9ce2dbe274d8b1ca4c14315fbc/src/cast.c#L52
- Not checked in character to logical conversion
- Corresponding R level casts need to be updated too
