### ISSUE TITLE
`check_unique` name repair isn't returning visibly somewhere

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#452]
``` r
vctrs::vec_cbind(x = 1, .name_repair = "unique")
#>   x
#> 1 1

vctrs::vec_cbind(x = 1, .name_repair = "check_unique")

x <- vctrs::vec_cbind(x = 1, .name_repair = "check_unique")
x
#>   x
#> 1 1
```

<sup>Created on 2019-06-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by DavisVaughan** [comment]
Does `invisible()`ness propagate somehow? 😮 

If you change this to actually return `names` it works https://github.com/r-lib/vctrs/blob/fbcbab14b7815d9fdb7c628af547666a843a5780/R/names.R#L225

**Comment by lionel-** [comment]
It propagates through `.External2()`, so we need an explicit `Rf_eval()` to reset it when we call back R from an external2 routine.
