### ISSUE TITLE
Should `vec_recycle()` throw a classed error?

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#471]
`vec_recycle()` throws a standard error when the sizes are incompatible.
https://github.com/r-lib/vctrs/blob/010f3a22d574b398a28d0b9e27447c04e77912a4/src/size.c#L182

There is a spot in `tibble` where it would be nice to catch this specific error and rethrow it with a tibble specific error message (currently `vec_recycle_common()` is being called there but it will be changed to `vec_recycle()`). 
https://github.com/tidyverse/tibble/commit/7728a8b1c8e9ce0d7c881bc6fc64ead7b34572e4#diff-540c0e3edd23d1e0767808051997d469R238

I'm not quite sure what to call that error message. We have `stop_incompatible_size()` but that is for comparing between two vectors.

**Comment by DavisVaughan** [comment]
Can possibly use the same custom error here:
https://github.com/r-lib/vctrs/blob/da4c2bae73e27b51b31e8eeb0420f6f8c2f7271c/R/shape.R#L32

**Comment by hadley** [comment]
`stop_unrecyclable()` ?

**Comment by lionel-** [comment]
`stop_recycle_incompatible_size()`, throwing a `"rlib_error_recycle_incompatible_size"`?

I think it's better to be more verbose with lots of categories, because that makes it much easier to come up with names that are overall consistent.

**Comment by krlmlr** [comment]
On it.

**Comment by krlmlr** [comment]
Maybe `stop_incompatible_recycle()` ?
