### ISSUE TITLE
`vec_assert()` with partial objects

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#477]
Currently, the way that partial objects are handled results in this error:

``` r
library(vctrs)

# works great
vec_assert(factor("x"), partial_factor())

# not informative
vec_assert(1, partial_factor())
#> `y` must be a vector, not a `vctrs_partial_factor/vctrs_partial/vctrs_sclr`
#> object

# same problem with partial frames
vec_assert(1, partial_frame())
#> `y` must be a vector, not a `vctrs_partial_frame/vctrs_partial/vctrs_sclr`
#> object
```

This makes the assertion a bit problematic (even though partial objects seem to be working everywhere else).

Along the way `vec_assert(partial_factor())` is eventually called, and `vec_is_vector()` returns false on this partial object, so we get the `stop_scalar_type()` error.

Maybe `stop_incompatible_type()` needs to `vec_ptype_finalise()` partial objects?

```r
> rlang::last_error()
<error>
message: `y` must be a vector, not a `vctrs_partial_frame/vctrs_partial/vctrs_sclr` object
class:   `vctrs_error_scalar_type`
backtrace:
  1. vctrs::vec_assert(1, partial_frame())
 10. vctrs:::vec_ptype2.double.default(...) R/type-bare.R:19:21
 11. vctrs::vec_default_ptype2(x, y, x_arg = x_arg, y_arg = y_arg) R/type-bare.R:124:2
 12. vctrs::stop_incompatible_type(x, y, x_arg = x_arg, y_arg = y_arg) R/type2.R:63:2
 13. vctrs::vec_assert(y) R/conditions.R:72:2
 14. vctrs:::stop_scalar_type(x, arg) R/assert.R:36:4
 15. vctrs:::stop_vctrs(msg, "vctrs_error_scalar_type", actual = x) R/conditions.R:367:2
Call `rlang::last_trace()` to see the full backtrace
```

**Comment by mgirlich** [comment]
I also stumbled across the error `Error: C stack usage  7971296 is too close to the limit` when executing the following code

```r
library(vctrs)
library(tibble)

vec_assert(
  tibble(a = 1),
  partial_frame(a = 1)
)
```

and I also found an issue with `vec_rbind()` for `tibble` and `partial_frame()` that might be connected:

``` r
library(vctrs)
library(tibble)
#> 
#> Attaching package: 'tibble'
#> The following object is masked from 'package:vctrs':
#> 
#>     data_frame

vec_rbind(
  data.frame(x = 1),
  .ptype = partial_frame(x = double())
)
#>   x
#> 1 1

vec_rbind(
  tibble(x = 1),
  .ptype = partial_frame(x = double())
)
#> Error: Input must be a vector, not a `vctrs_partial_frame/vctrs_partial/vctrs_sclr` object.
```

<sup>Created on 2021-01-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

But I wasn't even sure whether `partial_frame()` and `tibble()` are supposed to work together.

**Comment by lionel-** [comment]
I wouldn't use `partial_frame()` as it's an experimental feature and its implementation poses challenges that are low priority to investigate at the moment.

**Comment by mgirlich** [comment]
okay, good to know. Would be great to also mark it as experimental in the documentation.

**Comment by lionel-** [comment]
oops sorry about that. Now done, thanks! https://github.com/r-lib/vctrs/commit/41f841e1a86684cf6a5a56ad8c7747aaa5a781bc

**Comment by lionel-** [comment]
Closing this as we won't continue working on the partial type idea for a while.
