### ISSUE TITLE
Partial types

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#48]
It would be useful to supply the type of _some_ columns in a data frame, or to specify that you wanted a factor without specifying the levels.

This requires some sort of "partial" type, which `find_type()` would handle specially

**Comment by jennybc** [comment]
I want to say "Amen!": this is something that both readr and readxl allow (and, I think, people really use) and it would be nice to make available in more circumstances.

**Comment by hadley** [comment]
It now occurs to me that the way to implement this is as a new vector type. Then it would be straightforward to implement custom coercing and casting semantics using the existing framework.

**Comment by hadley** [comment]
This would also be nice if we implemented a `vec_assert()` function - then you could assert that a data frame input had at least the columns that you needed (while not caring about any extras) .

**Comment by hadley** [comment]
Some experiments checked in to local partial branch
