### ISSUE TITLE
vec_cbind returns wrong ptype

### ISSUE THREAD

**Issue by atusy** [r-lib/vctrs#481]
Before `vec_cbind` is implemented by C,
`vec_cbind(grouped_df, data.frame)` returned `tbl_df`.

However, from b7f4518, it is returning `data.frame` and causing `tdiyr:::nest.grouped_df` also returning `data.frame`.

This change is causing messy printing of nested data frame because of using `print.data.frame` instead of `print.tbl` (https://github.com/tidyverse/tidyr/issues/675).

## vctrs 0.2.0

``` r
library(dplyr, warn.conflicts = FALSE)
library(vctrs)
packageVersion("vctrs")
#> [1] '0.2.0'
d1 <- tibble(x=1:3)
d2 <- data.frame(y = 1:3)
vec_cbind(d1, d2) %>% class
#> [1] "tbl_df"     "tbl"        "data.frame"
vec_cbind(group_by(d1, x), d2) %>% class
#> [1] "data.frame"
```

<sup>Created on 2019-07-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

## vctrs 0.1.0

``` r
library(dplyr, warn.conflicts = FALSE)
library(vctrs)
packageVersion("vctrs")
#> [1] '0.1.0'
d1 <- tibble(x=1:3)
d2 <- data.frame(y = 1:3)
vec_cbind(d1, d2) %>% class
#> [1] "tbl_df"     "tbl"        "data.frame"
vec_cbind(group_by(d1, x), d2) %>% class
#> [1] "tbl_df"     "tbl"        "data.frame"
```

<sup>Created on 2019-07-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
Thanks for spotting this. Simpler reprex:

```r
class(vec_ptype2(group_by(mtcars, cyl), mtcars))
#> [1] "data.frame"
```

**Comment by DavisVaughan** [comment]
See also https://github.com/tidyverse/tidyr/issues/649
