### ISSUE TITLE
'vec_dim' is not an exported object from 'namespace:vctrs'

### ISSUE THREAD

**Issue by galileukim** [r-lib/vctrs#487]
The function dplyr::glimpse relies on exported vctrs::vec_dim, which is missing in version 0.2.0, but available for 0.1.0.

**Comment by lionel-** [comment]
Please update tibble to the latest version:

```r
install.packages("tibble")
```

**Comment by galileukim** [comment]
Thank you for the response. Despite updating the package tibble, the same error continues when using glimpse. This may be OS specific: I am using Ubuntu 18.04 and the same command works fine in MacOS.

**Comment by lionel-** [comment]
What is your `sessionInfo()` after `library(dplyr)` on a fresh session please?

**Comment by MeganBeckett** [comment]
Hi there, I'm getting the exact same error on a server running Ubuntu 18.04. 

R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.8.3

loaded via a namespace (and not attached):
 [1] tidyselect_0.2.5 compiler_3.6.0   magrittr_1.5     assertthat_0.2.1
 [5] R6_2.4.0         pillar_1.4.2     glue_1.3.1       tibble_2.1.3    
 [9] crayon_1.3.4     Rcpp_1.0.1       pkgconfig_2.0.2  rlang_0.4.0     
[13] purrr_0.3.2

**Comment by lionel-** [comment]
That is strange. Could you provide the `traceback()` after you get the error please.

**Comment by DavisVaughan** [comment]
I'm curious as to why it doesn't look like vctrs is loaded via namespace. As lionel said, a full reprex + traceback would be great.

FWIW here is a fresh rstudio cloud session with a similar (but not exact) setup and it seems to work fine.

<details>

```r
# install.packages("dplyr")

library(dplyr)

glimpse(mtcars)
#> Observations: 32
#> Variables: 11
#> $ mpg  <dbl> 21.0, 21.0, 22.8, 21.4, 18.7, 18.1, 14.3, 24.4, 22.8, 19.2,…
#> $ cyl  <dbl> 6, 6, 4, 6, 8, 6, 8, 4, 4, 6, 6, 8, 8, 8, 8, 8, 8, 4, 4, 4,…
#> $ disp <dbl> 160.0, 160.0, 108.0, 258.0, 360.0, 225.0, 360.0, 146.7, 140…
#> $ hp   <dbl> 110, 110, 93, 110, 175, 105, 245, 62, 95, 123, 123, 180, 18…
#> $ drat <dbl> 3.90, 3.90, 3.85, 3.08, 3.15, 2.76, 3.21, 3.69, 3.92, 3.92,…
#> $ wt   <dbl> 2.620, 2.875, 2.320, 3.215, 3.440, 3.460, 3.570, 3.190, 3.1…
#> $ qsec <dbl> 16.46, 17.02, 18.61, 19.44, 17.02, 20.22, 15.84, 20.00, 22.…
#> $ vs   <dbl> 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,…
#> $ am   <dbl> 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,…
#> $ gear <dbl> 4, 4, 4, 3, 3, 3, 3, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 4, 4, 4,…
#> $ carb <dbl> 4, 4, 1, 1, 2, 1, 4, 2, 2, 4, 4, 3, 3, 3, 4, 4, 4, 1, 2, 1,…

sessionInfo()
#> R version 3.6.0 (2019-04-26)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 16.04.5 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/atlas-base/atlas/libblas.so.3.0
#> LAPACK: /usr/lib/atlas-base/atlas/liblapack.so.3.0
#> 
#> locale:
#>  [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
#>  [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
#>  [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
#> [10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] dplyr_0.8.3
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.1       knitr_1.23       magrittr_1.5     tidyselect_0.2.5
#>  [5] R6_2.4.0         rlang_0.4.0      fansi_0.4.0      stringr_1.4.0   
#>  [9] highr_0.8        tools_3.6.0      xfun_0.8         utf8_1.1.4      
#> [13] cli_1.1.0        htmltools_0.3.6  yaml_2.2.0       assertthat_0.2.1
#> [17] digest_0.6.20    tibble_2.1.3     crayon_1.3.4     purrr_0.3.2     
#> [21] vctrs_0.2.0      zeallot_0.1.0    glue_1.3.1       evaluate_0.14   
#> [25] rmarkdown_1.14   stringi_1.4.3    compiler_3.6.0   pillar_1.4.2    
#> [29] backports_1.1.4  pkgconfig_2.0.2
```

</details>

**Comment by galileukim** [comment]
> What is your `sessionInfo()` after `library(dplyr)` on a fresh session please?

R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] dplyr_0.8.3

loaded via a namespace (and not attached):
 [1] tidyselect_0.2.5 compiler_3.6.1   magrittr_1.5    
 [4] assertthat_0.2.1 R6_2.4.0         tools_3.6.1     
 [7] pillar_1.4.1     glue_1.3.1       rstudioapi_0.10 
[10] tibble_2.1.3     crayon_1.3.4     Rcpp_1.0.1      
[13] pkgconfig_2.0.2  rlang_0.4.0      purrr_0.3.2

**Comment by lionel-** [comment]
And a `traceback()` after the error has been triggered please.

**Comment by DavisVaughan** [comment]
@galileukim you seem to have pillar 1.4.1, and a quick check shows that it uses `vec_dim()`. Could you try `install.packages("pillar")`, restart R, and try again? 

A `traceback()` would be still be helpful as well to confirm.

**Comment by MeganBeckett** [comment]
Ok thanks. This is happening in a shiny app that I've got on a server, so just trying to figure out how to debug or see a traceback. Works fine locally with the same setup, but not on the server. 

Here is the result from the log file for the app:

```
Listening on http://127.0.0.1:36821
Warning: Error in : 'vec_dim' is not an exported object from 'namespace:vctrs'
  125: stop
  124: getExportedValue
  123: ::
  122: dim_desc
  120: size_sum
  118: FUN
  117: vapply
  116: map_mold
  115: map_chr
  114: obj_sum.list
  111: pillar_shaft.list
  109: lapply
  108: map
  107: colonnade_get_width
  106: pillar::squeeze
  105: format.trunc_mat
  103: format.tbl
   98: print.tbl
   96: renderUI [/srv/shiny-server/breakfast-shift/app.R#193]
   95: func
   82: origRenderFunc
   81: output$select_team
    1: runApp
Warning: Error in UseMethod: no applicable method for 'inner_join' applied to an object of class "NULL"
  110: inner_join
  109: function_list[[i]]
  108: freduce
  107: _fseq
  106: eval
  105: eval
  103: %>%
  102: exprFunc [/srv/shiny-server/breakfast-shift/app.R#246]
  101: widgetFunc
  100: func
   87: origRenderFunc
   86: renderFunc
   82: origRenderFunc
   81: output$table
    1: runApp
```

**Comment by galileukim** [comment]
> @galileukim you seem to have pillar 1.4.1, and a quick check shows that it uses `vec_dim()`. Could you try `install.packages("pillar")`, restart R, and try again?
> 
> A `traceback()` would be still be helpful as well to confirm.

Seems like installing the latest version of pillar solved the problem. Here's a `traceback()` from the bug prior to reinstalling `pillar`.

21: stop(gettextf("'%s' is not an exported object from 'namespace:%s'", 
        name, getNamespaceName(ns)), call. = FALSE, domain = NA)
20: getExportedValue(pkg, name)
19: vctrs::vec_dim
18: dim_desc(x)
17: paste0(" [", dim_desc(x), "]")
16: size_sum(x)
15: paste0(type_sum(x), size_sum(x))
14: obj_sum.default(x)
13: obj_sum(x)
12: tbl_sum.default(x)
11: tbl_sum(x)
10: glimpse.data.frame(.)
9: glimpse(.)
8: function_list[[k]](value)
7: withVisible(function_list[[k]](value))
6: freduce(value, `_function_list`)
5: `_fseq`(`_lhs`)
4: eval(quote(`_fseq`(`_lhs`)), env, env)
3: eval(quote(`_fseq`(`_lhs`)), env, env)
2: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
1: school %>% glimpse

**Comment by lionel-** [comment]
@MeganBeckett It looks like the server needs to update pillar/tibble.

In any case we'll re-include `vec_dim()` in vctrs shortly to soften the transition.

**Comment by DavisVaughan** [comment]
@MeganBeckett from your session info it looks like you had pillar 1.4.2 which should contain the fix, but the traceback suggests you might actually have 1.4.1 loaded in the shiny app server? I say that because I see `dim_desc` there. 

Yea as lionel just said (as I was typing this) can you update pillar too?

**Comment by MeganBeckett** [comment]
Yes yes! That worked. :tada: I updated `pillar`. Thanks so much! :smile:

**Comment by donojazz** [comment]
I had the exact same problem.  Error code was 'vec_dim' is not an exported object from 'namespace:vctrs'.  My only action was to update my pillar package to 1.4.2 and refresh tidyverse package.  Worked fine.  Will these dependent packages like pillar/tibble automatically update, or should I automatically update ALL packages in my R instance?

**Comment by lionel-** [comment]
It is recommended to update all your packages at once.

**Comment by donojazz** [comment]
Thanks
