### ISSUE TITLE
Hash test results are not endian-neutral

### ISSUE THREAD

**Issue by QuLogic** [r-lib/vctrs#492]
Building vctrs 0.2.0 across [various arches](https://koji.fedoraproject.org/koji/taskinfo?taskID=36317857) works everywhere except [s390x](https://koji.fedoraproject.org/koji/taskinfo?taskID=36317896), which is a big-endian architecture. The error occurs in a check of hashes from some stored known value:

>   1. Failure: hashes are consistent from run to run (@test-hash.R#61) 

I did not investigate too deeply where the endian-ness comes into play. But since hashes are supposed to be fast-ish, you may not want to implement byte-swapping. I could provide the big-endian hash results instead.

**Comment by lionel-** [comment]
Thanks for reporting this. We could also just skip the test if `Sys.info()[["machine"]]` is not `"x86_64"`.

**Comment by QuLogic** [comment]
That might be a bit much, as it seems to work on any other little-endian machine. Maybe just skip on s390x and ppc64 (those are the two I know of)?

**Comment by QuLogic** [comment]
Looking at the output, it looks like it's mostly just the result that's byte swapped. So that's actually less problematic than I thought as I expected swapped inputs might have caused completely different hash outputs.

```
x[2]: " [1] 51 4e 28 b7 00 00 00 00 6d 3c 65 a0"
y[2]: " [1] b7 28 4e 51 00 00 00 00 a0 65 3c 6d"

x[5]: "  [1] 51 4e 28 b7 30 f4 c3 06 85 f0 b4 27 24 9c b2 85 cc 0d 53 cd 5c eb 4d 08 18"
y[5]: "  [1] b7 28 4e 51 06 c3 f4 30 27 b4 f0 85 85 b2 9c 24 cd 53 0d cc 08 4d eb 5c c4"

x[6]: " [26] c9 ae c4 49 39 65 0b c2 7c 29 13 e9 25 04 90 93 a0 fe 04 7c 88 ad 73 95 bb"
y[6]: " [26] ae c9 18 0b 65 39 49 13 29 7c c2 90 04 25 e9 04 fe a0 93 73 ad 88 7c 92 7d"

x[7]: " [51] 7d 92 bf eb d3 f1 cc 1a d8 45 55 25 53 bc d8 d0 9e e8 d6 04 53 17 e1 f1 55"
y[7]: " [51] bb 95 f1 d3 eb bf 45 d8 1a cc bc 53 25 55 e8 9e d0 d8 17 53 04 d6 14 55 f1"

x[8]: " [76] 14 d2 4b 09 21 ea 12 61 65 78 4b f1 36 d1 b8 3c 8c bb c4 e9 ef 7f 73 d7 3a"
y[8]: " [76] e1 21 09 4b d2 65 61 12 ea 36 f1 4b 78 8c 3c b8 d1 ef e9 c4 bb 3a d7 73 7f"
```
