### ISSUE TITLE
Performance for hashing of tibble with factors

### ISSUE THREAD

**Issue by romainfrancois** [r-lib/vctrs#498]
I'm using `vctrs::vec_duplicate_split()` for https://github.com/tidyverse/dplyr/pull/4504 and there seems to be a performance loss when hashing a tibble with a factor column, however performance looks good when hashing the factor itself: 

``` r
library(dplyr, warn.conflicts = FALSE)

n <- 1e5
d1 <- tibble(x = sample(2000, n, TRUE))
d2 <- mutate(d1, x = as.factor(x))

vec_duplicate_split <- vctrs:::vec_duplicate_split

# performance are comparable bertween int vectors and factors
bench::mark(
  int = vec_duplicate_split(d1$x) ,
  fac = vec_duplicate_split(d2$x)
)
#> # A tibble: 2 x 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 int          2.52ms   3.68ms      281.    2.77MB     14.1
#> 2 fac          3.25ms   4.42ms      236.    3.15MB     14.4

# but not with tibble with them as a single column
bench::mark(
  int = vec_duplicate_split(d1) ,
  fac = vec_duplicate_split(d2)
)
#> Warning: Some expressions had a GC in every iteration; so filtering is
#> disabled.
#> # A tibble: 2 x 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 int          14.4ms   15.7ms     62.0     2.77MB     2.00
#> 2 fac         685.8ms  685.8ms      1.46    2.77MB    23.3
```

<sup>Created on 2019-07-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by lionel-** [comment]
It seems for factors the number of allocations grows linearly with `n`:

```r
> n <- 1e4
> d1 <- tibble(x = sample(2000, n, TRUE))
> d2 <- mutate(d1, x = as.factor(x))

> profmem::profmem(vec_duplicate_split(d1)) 
Rprofmem memory profiling of:
vec_duplicate_split(d1)

Memory allocations:
Number of 'new page' entries not displayed: 5
       what  bytes                            calls
1     alloc  65592 vec_duplicate_split() -> .Call()
2     alloc  40056 vec_duplicate_split() -> .Call()
3     alloc  65584 vec_duplicate_split() -> .Call()
4     alloc  65584 vec_duplicate_split() -> .Call()
5     alloc  40048 vec_duplicate_split() -> .Call()
6     alloc   8008 vec_duplicate_split() -> .Call()
7     alloc  15960 vec_duplicate_split() -> .Call()
8     alloc   8008 vec_duplicate_split() -> .Call()
total       308840                                 


> profmem::profmem(vec_duplicate_split(d2)) 
Rprofmem memory profiling of:
vec_duplicate_split(d2)

Memory allocations:
Number of 'new page' entries not displayed: 3950
       what  bytes                            calls
4     alloc  65592 vec_duplicate_split() -> .Call()
6     alloc  40056 vec_duplicate_split() -> .Call()
7     alloc  65584 vec_duplicate_split() -> .Call()
8     alloc  65584 vec_duplicate_split() -> .Call()
9     alloc  40048 vec_duplicate_split() -> .Call()
10    alloc  40048 vec_duplicate_split() -> .Call()
3957  alloc   8008 vec_duplicate_split() -> .Call()
3958  alloc  15960 vec_duplicate_split() -> .Call()
3959  alloc   8008 vec_duplicate_split() -> .Call()
total       348888                                 
```

For `d1`: Number of 'new page' entries not displayed: 5
For `d2`: Number of 'new page' entries not displayed: 3950

**Comment by DavisVaughan** [comment]
I've tracked the slowness to be coming from:

 `dict_hash_scalar -> dict_hash_with -> equal_scalar -> df_equal_scalar`

In `df_equal_scalar()` there are two calls to the C level `vec_proxy_equal()`. This dispatches back to the R level `vec_proxy_equal()` if the column is S3, which is probably what takes so long.

This explains why the data frame version is slow, but not the factor version directly. When just doing `vec_duplicate_split(d2$x)`, when `equal_scalar()` is called it will fall through to `int_equal_scalar()` which never calls that `vec_proxy_equal()`

**Comment by lionel-** [comment]
There is only one column though. Oh but we might be comparing row by row? Then that's one dispatch per row. We probably need to take the proxies recursively in the data frame case, before storing the data structures in the dictionary.

**Comment by DavisVaughan** [comment]
Also just noting that I'm fairly certain we have the same performance issue with `vec_equal(d2, d2)` and `vec_duplicate_detect(d2)`

**Comment by lionel-** [comment]
I'm working on a fix in dictionary.c and equal.c.

**Comment by lionel-** [comment]
It feels like `vec_proxy()`, `vec_proxy_equal()` and `vec_proxy_compare()` should take proxies recursively in the case of data frames. This would be simpler, though maybe less efficient in some cases? Then we need to restore recursively as well. I'll leave that out of the fix though, as this would be a major change.
