### ISSUE TITLE
check_unique error should list duplicated variables

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#501]
``` r
vctrs::vec_as_names(c("x", "x", "y"), repair = "check_unique")
#> Names must be unique.
```

<sup>Created on 2019-07-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DavisVaughan** [comment]
``` r
vctrs::vec_as_names(c("x", "x", "y"), repair = "check_unique")
#> Error: Names must be unique.
#> x These names are duplicated:
#>   * "x" at locations 1 and 2.
```

<sup>Created on 2020-04-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Closed by https://github.com/r-lib/vctrs/pull/898
