### ISSUE TITLE
Massive speedup when `vec_slice()`ing using `[` (factors/dates)

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#504]
I'll try and do a PR for this tomorrow. I think performance here can be greatly improved by not constructing the call with the objects directly, but instead by using symbols.

https://github.com/r-lib/vctrs/blob/c9fb8834fc8b586b1ed0215667fe8c57e5e33f11/src/slice.c#L253

So something like:

```
      SEXP call = PROTECT_N(Rf_lang3(fns_bracket, syms_x, syms_i), &nprot);
      SEXP env = PROTECT_N(r_new_environment(R_GlobalEnv, 2), &nprot);
      Rf_defineVar(syms_i, index, env);
      Rf_defineVar(syms_x, x, env);
      out = PROTECT_N(Rf_eval(call, env), &nprot);
```

This gives us:

``` r
library(vctrs)

x <- factor(rep(letters, 10000))

# before
bench::mark(vec_slice(x, 1L))
#> # A tibble: 1 x 6
#>   expression            min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 vec_slice(x, 1L)   96.2µs    227µs     3651.    1.01MB     74.0

# after
bench::mark(vec_slice(x, 1L))
#> # A tibble: 1 x 6
#>   expression            min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 vec_slice(x, 1L)   9.42µs   10.8µs    89540.    17.1KB     89.6
```

**Comment by lionel-** [comment]
This looks similar to `dispatch()` code in utils.c.

It'd be helpful to identify the source of duplication in base R so the slowdown with constructed calls can be fixed. Is this with R 3.6? It should be able to duplicate atomic vectors shallowly.

**Comment by lionel-** [comment]
The duplication is in `NextMethod()`, I'll send a patch: https://github.com/wch/r-source/blob/ec6faae1911207f1cb9b2cf259238598dc1ffe17/src/main/objects.c#L697

**Comment by DavisVaughan** [comment]
It does look similar to the dispatch code, but I wouldn't want to use that directly. I want to create the call once, and `Rf_eval()` many times (where `index` changes from iteration to iteration, effectively changing the call). _Maybe_ it would be worth extracting out the logic that just constructs the call and defines vars by reference in an environment that a user could pass in.
