### ISSUE TITLE
vctrs:::data_frame can produce data.frame without column names.  test-compare.R uses it to make [illegal] data.frame.

### ISSUE THREAD

**Issue by BillDunlap** [r-lib/vctrs#521]
If the caller does not tag all arguments, vctrs:::data_frame will produce an object of class "data.frame" without column names, which goes against the model of data.frames.  It is private to getNamespace("vctrs") so that would be ok (but dangerous).  The only call to it in the R and src directories supplies the name, but the tests are full of calls to it without the tags.  E.g., 

vctrs/tests/testthat/test-compare.R:  expect_equal(vec_order(data_frame(list(10, 2, 1))), 1:3)

It would be nice if it produced a valid data.frame so that functions that depend on data.frames having names worked.

I see the public vctrs::new_data_frame can also make a data.frame without names.  Should this be allowed?

**Comment by lionel-** [comment]
`data_frame()` is a private bare bones constructor, convenient for unit tests.

`new_data_frame()` does not check names on purpose because unnamed data frames are actually part of the model of data frames in base R. See this comment:

```r
  # names() should always be a character vector, but we can't enforce that
  # because as.data.frame() returns a data frame with NULL names to indicate
  # that outer names should be used
  if (length(x) == 0) {
    names(x) <- character()
  }
```

**Comment by lionel-** [comment]
In general, we need to construct malformed data frames to make sure we support them, since they do appear in the wild.

**Comment by BillDunlap** [comment]
OK, but ?vctrs::new_data_frame says
     A ‘data.frame’ ‘data.frame()’ is a list with "row.names"
     attribute. Each element of the list must be named, and of the same
     length.
and goes on to state that the equal-lengths part is the caller's
responsibility.

A fair bit of data.frame code in base fails if there are no column names.
E.g.,

> library(vctrs)
> x <- new_data_frame(list(11:13, 21:23))
> x["Sum12"] <- x[1] + x[2]
> str(x)
'data.frame':   3 obs. of  2 variables:
 $ Sum12: int  11 12 13
 $ NA   : int  21 22 23
and
> x <- new_data_frame(list(11:13, 21:23))
> x[,"AnotherSumColumn"] <- x[,1] + x[,2]
> str(x)
'data.frame':   3 obs. of  3 variables:
 $ AnotherSumColumn: int  11 12 13
 $ NA              : int  21 22 23
 $ NA.1            : int  32 34 36
