### ISSUE TITLE
Discussion) "Details attributes"

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#529]
It will likely be the case that a custom class will be created where:

- A custom attribute will be added, but should not be considered in `vec_is()`
- That attribute might be vectorized (`vec_size(<attr>) == vec_size(x)`) and should be sliced along with `x`

The best example we can currently come up with of something like this that exists in base R is POSIXlt names, but I know there are other situations where this will arise.

``` r
library(vctrs)
library(rlang)

x <- set_names(as.POSIXlt(new_datetime(c(0, 1))), c("a", "b"))
x
#>                         a                         b 
#> "1969-12-31 19:00:00 EST" "1969-12-31 19:00:01 EST"

names(x)
#> [1] "a" "b"

# names are on `year`
names(unclass(x)$year)
#> [1] "a" "b"
```

Currently, you could not try and recreate this with `vctrs_rcrd`, as you cannot add names to a `vctrs_rcrd` class. The names slot is taken up by the names of the rcrd list, and the `names.vctrs_rcrd` function just returns `NULL`.

---

I would like to propose the addition of a general vectorized "details attribute" called `vctrs_details`. This is:
- A data frame
- `vec_size(attr(x, "vctrs_details")) == vec_size(x)`

__"Details attributes"__ in general are attributes that should not be considered when calling `vec_is()` or `vec_equal()`. They are meta data about the values, and not part of the type. There are two proposed ways of declaring details attributes:
- Add a normal attribute with a `.` prefix on the name.
- Add a vectorized attribute as a column in `vctrs_details`.

Here is a rough look at how you'd implement `POSIXlt`-ish names with `vctrs_rcrd`:

``` r
library(vctrs)

my_rcrd <- new_rcrd(
  list(year = 1991:1995, month = 1:5, day = 11:15), 
  vctrs_details = data.frame(names = letters[1:5], stringsAsFactors = FALSE),
  class = "my_rcrd"
)

attributes(my_rcrd)
#> $names
#> [1] "year"  "month" "day"  
#> 
#> $vctrs_details
#>   names
#> 1     a
#> 2     b
#> 3     c
#> 4     d
#> 5     e
#> 
#> $class
#> [1] "my_rcrd"    "vctrs_rcrd" "vctrs_vctr"

names.my_rcrd <- function(x) {
  attr(x, "vctrs_details")$names
}

format.my_rcrd <- function(x, ...) {
  paste(field(x, "year"), field(x, "month"), field(x, "day"), sep = "-")
}

my_rcrd
#> <my_rcrd[5]>
#>         a         b         c         d         e 
#> 1991-1-11 1992-2-12 1993-3-13 1994-4-14 1995-5-15
```

`vec_slice()` would understand how to slice the `vctrs_details` data frame, if it exists, which would allow downstream developers to create new vectorized details arguments and have them be sliced correctly automatically.

---

I think this is a general feature, and it not one specific to `vctrs_rcrd` classes. Here is a breakdown of how I think these could be used:

| # data attributes  | # vectorized details attributes | What |
| ----------------| ---------------------------- | ----- |
| 1  | 0  | `vctrs_vctr` |
| 1  | >0  | `vctrs_vctr` + use `vctrs_details` |
| >1  | 0  | `vctrs_rcrd` |
| >1  | >0  | `vctrs_rcrd` + use `vctrs_details` |

The key thing to note here is that if you have a `vctrs_vctr` and you want to add some kind of additional vectorized information, you have to decide if it is another "data" attribute, in which case you should create a `vctrs_rcrd`, or a "details" attribute, in which case you'd use `vctrs_details`.

--- 

As a final note, I had the question of whether or not `names` of a `vctrs_vctr` should or should not be included in this `vctrs_details` df. Even though it is a "vectorized detail argument" Lionel and I think it is special enough to be treated separately. Same with rownames of an array, which are too tightly integrated with the rest of the dimnames to make any kind of change here.

**Comment by hadley** [comment]
Why not just adopt the convention that any field or attribute starting with `.` is "details" and shouldn't be included in the detail equality comparison?

**Comment by DavisVaughan** [comment]
That's in there too (CTRL+F for "Add a normal attribute with", its a bit hidden), but you still need "details" that are vectorized to be sliced by `vec_slice()` correctly, and that is where this comes in.

**Comment by hadley** [comment]
I meant like this:

```R
my_rcrd <- new_rcrd(
  list(.names = letters[1:5], year = 1991:1995, month = 1:5, day = 11:15), 
  class = "my_rcrd"
)
```

**Comment by lionel-** [comment]
I like this idea, it would be nicely consistent with non-vectorised details attributes (attributes starting with `.`), and overall simpler. Then we can't have vectorised detail attributes for `vctrs_vctr`, but forcing the class implementor to use a record proxy in that case makes things simpler.

**Comment by DavisVaughan** [comment]
Gotcha, so the table looks more like this:

| # data attributes  | # vectorized details attributes | What |
| ----------------| ---------------------------- | ----- |
| 1  | 0  | `vctrs_vctr` |
| 1  | >0  | `vctrs_rcrd` 1 data element, >0 `.` prefixed elements |
| >1  | 0  | `vctrs_rcrd` >1 data elements |
| >1  | >0  | `vctrs_rcrd` >1 data elements, >0 `.` prefixed elements |

I think that makes sense!

> Then we can't have vectorised detail attributes for vctrs_vctr

Yea I think this is the only drawback, but this model seems much simpler so it would be worth it to require the record class in this case.

**Comment by DavisVaughan** [comment]
Two more thoughts:

What goes in the `.names` column when the POSIXlt-ish object has no names? Does that column even exist?

What happens when you `vec_assign()` into an object that has this `.names` column? Say you update element 2 in the rcrd object, so row 2 in that data frame proxy. Unless there is some special handling built in, it will overwrite the 2nd element in the `.names` column, which I think is incorrect. When you `vec_assign()` into `x` I'm pretty sure `x` keeps it's original names.

**Comment by lionel-** [comment]
Closing because, as @DavisVaughan noted on Slack, this can be solved by omitting the detail fields from a `vec_proxy_equal()` method.

**Comment by DavisVaughan** [comment]
For names in particular, clock took the same approach as POSIXlt, it puts names on the first field (at least 1 field is always required) and they show up in `vec_proxy()` so they get sliced.

This has worked fairly well and is potentially how we could deal with names in rcrd classes going forward

``` r
library(clock)

x <- year_month_day(2019, 11:12)
names(x) <- c("a", "b")

names(x)
#> [1] "a" "b"

vctrs::vec_proxy(x)$year
#>    a    b 
#> 2019 2019
```

<sup>Created on 2022-09-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
