### ISSUE TITLE
vec_size() takes a "long time" for POSIXlt

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#535]
``` r
library(vctrs)

ct <- new_datetime(0)
lt <- as.POSIXlt(ct)

bench::mark(
  vec_size(ct),
  vec_size(lt)
)
#> # A tibble: 2 x 6
#>   expression        min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 vec_size(ct)    727ns    944ns  1013283.     6.3KB    101. 
#> 2 vec_size(lt)   18.6µs   21.8µs    42695.    29.5KB     25.6
```

Discovered while repeatedly calling `vec_restore(x, to, R_NilValue)` where `x` was a list holding a POSIXlt and `to` was a data frame. Because no size was passed in, it goes through `df_raw_size(x)`, which in this case calls `vec_size()` on the first element of the list (the POSIXlt). Totally crippled performance 😬 . Luckily I am able to pre-compute the size ahead of time to fix it for my use case.

The main "issue" is that `vec_size()` needs the proxy:
https://github.com/r-lib/vctrs/blob/f736b2353d248820847a09b808cb7370ab8fc2f6/src/size.c#L47

and `vec_proxy.POSIXlt` calls `new_data_frame()`, which is quite slow:

``` r
library(vctrs)

ct <- new_datetime(0)
lt <- as.POSIXlt(ct)

# imitate vec_proxy.POSIXlt
vctrs:::vec_proxy.POSIXlt
#> function(x, ...) {
#>   new_data_frame(unclass(x))
#> }
#> <bytecode: 0x7f99f69716f8>
#> <environment: namespace:vctrs>

# no problem here:
bench::mark(unclass(lt))
#> # A tibble: 1 x 6
#>   expression       min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>  <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 unclass(lt)    308ns    373ns  2350164.        0B     235.

lt_unclassed <- unclass(lt)

# ouch
bench::mark(new_data_frame(lt_unclassed))
#> # A tibble: 1 x 6
#>   expression                       min  median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                   <bch:t> <bch:t>     <dbl> <bch:byt>    <dbl>
#> 1 new_data_frame(lt_unclassed)  14.9µs  17.6µs    52643.    24.8KB     15.8
```

Perhaps there is no solution, since we have to get the full proxy, but this is definitely something to be aware of when liberally using `vec_size()` and expecting it to have negligible speed impacts.

**Comment by lionel-** [comment]
We haven't implemented native handling for dates and factors yet.

**Comment by DavisVaughan** [comment]
Ah, I knew we'd do Date/POSIXct but I didn't know we'd have native handling for POSIXlt too

**Comment by lionel-** [comment]
In general we'll need to identify this kind of speed bottlenecks and make customisation points, so that any class can be made efficient with some effort. Making all base classes efficient would probably get us most of the way there.
