### ISSUE TITLE
`vec_is_na()` / `vec_are_na()`

### ISSUE THREAD

**Issue by lionel-** [r-lib/vctrs#538]
Needed for detecting missing elements when input is potentially a tibble. Cf https://github.com/lionel-/recode/commit/c4e6b9b

```r
vec_are_na <- function(x) {
  vec_equal(x, vec_init(x, vec_size(x)), na_equal = TRUE)
}
```

Probably needs a fast native implementation.

Do we want to follow the rlang experiment with vectorised predicates, and use `are` instead of `is`? I think a good rule is that any `is_` function must be usable as an `if ()` condition, i.e. only return a single `TRUE` or `FALSE`, never a missing value or a length > 1 vector. Also it should never throw, use a prefix if it requires a particular type, e.g. `quo_is_missing()` throws if input is not a quosure.

**Comment by DavisVaughan** [comment]
This is `vec_equal_na()` right?

**Comment by lionel-** [comment]
yup
