### ISSUE TITLE
Promotion from raw to integer

### ISSUE THREAD

**Issue by romainfrancois** [r-lib/vctrs#546]
``` r
library(vctrs)

vec_c(as.raw(1:3), 1:3)
#> No common type for `..1` <raw> and `..2` <integer>.
vec_c(as.raw(1:3), 1:3, .ptype = integer())
#> Can't cast <raw> to <integer>.
vec_ptype2(raw(), integer())
#> No common type for `x` <raw> and `y` <integer>.
```

... which in turns breaks a test in dplyr:  https://github.com/tidyverse/dplyr/blob/9c3b417ba8e5f35ad1b959e90ae292b414456b92/tests/testthat/test-mutate.r#L772

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(a = 1:4, g = c(1, 1, 2, 2))
df %>% group_by(g) %>% mutate(b = if (all(a < 3)) as.raw(a) else a)
#> No common type for `..1` <raw> and `..2` <integer>.
```

**Comment by hadley** [comment]
Are we sure we want to continue to support this? It's probably not that important either way, but raw <-> integer seems like it's different enough to require an explicit cast.

**Comment by romainfrancois** [comment]
I guess it depends on the use case, e.g. I've seen raw vectors used as rgb components. 

I can update the dplyr test though. An expression that sometimes return raw and sometimes integers is not really likely to happen anyway. 

If we wanted explicit cast, would we cast within the expression for each group ? e.g. 

```
mutate(x = vec_cast(something(), to = integer()))
```

**Comment by hadley** [comment]
Or just `as.integer()`
