### ISSUE TITLE
Impute indexes with vec_as_index(NULL)

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#547]
Currently:

``` r
vctrs::vec_as_index(NULL, 3)
#> `n` must be a vector with type <integer>.
#> Instead, it has type <double>.
```

<sup>Created on 2019-08-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Ideally:

``` r
vctrs::vec_as_index(NULL, 3)
#> [1] 1 2 3
```

<sup>Would have been created on 2019-08-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This would allow for an easier implementation of (and definition of invariants for) `[.tbl_df` .

**Comment by hadley** [comment]
Yeah, we should probably relax this so it's easier for user-facing code to use.

**Comment by krlmlr** [comment]
There are two issues:

1. Passing a double as `n` (in my reprex); this is not a priority.
2. Converting `NULL` to `seq_len(n)`; this is the spirit of the issue (but detailed wrong in the reprex).

Correct reprex:

``` r
vctrs::vec_as_index(NULL, 3L)
#> integer(0)
```

<sup>Created on 2019-08-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Ideal behavior (for tibble):

``` r
vctrs::vec_as_index(NULL, 3L)
#> [1] 1 2 3
```

<sup>Created on 2019-08-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

@lionel-: I remember a discussion about this, and that we resolved to treating `NULL` synonymous to a length-0 vector (and not as a missing argument as in my proposal). I'd argue the proposed behavior makes more sense for `vec_as_index()`. Would you reconsider?

**Comment by krlmlr** [comment]
tibble is using a more efficient code path if `i` or `j` are missing.
