### ISSUE TITLE
Rename unknown to anything

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#55]
And finish consideration of casting

**Comment by hadley** [comment]
And figure out why this is failing:

```R
vec_c(factor("x"), rep(NA, 10))
```

**Comment by hadley** [comment]
And add `vctrs_` prefix to class name

**Comment by lionel-** [comment]
> Rename unknown to anything

Or to `whatever()`?

**Comment by hadley** [comment]
`whatever()` now feels a bit too casual to me

**Comment by hadley** [comment]
NB: `anything()` is a partial type
