### ISSUE TITLE
vec_restore() and corrupted tibbles

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#552]
Should `vec_restore()` refuse to operate here, or perhaps pad?

``` r
x <- vctrs::vec_restore(
  structure(list(a = 1, b = 2:3), row.names = 1:2), 
  tibble::tibble(a = 1:2, b = 2:3)
)
x$a
#> [1] 1
```

<sup>Created on 2019-08-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The problem arises with `vec_slice()`:

``` r
x <- structure(list(a = 1, b = 2:3), row.names = 1:2, class = "data.frame")
unclass(vctrs::vec_slice(x, 2))
#> $a
#> [1] 2.652495e-315
#> 
#> $b
#> [1] 3
#> 
#> attr(,"row.names")
#> [1] 1
```

<sup>Created on 2019-08-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by krlmlr** [comment]
Same problem with `new_data_frame()`, I suspect it's not the responsibility of `vec_restore()` to validate.

``` r
library(vctrs)

x <- new_data_frame(list(a = 1, b = 2:3), n = 2L)
x$a
#> [1] 1
vec_slice(x, 2)
#>              a b
#> 1 4.51753e-314 3
```

<sup>Created on 2020-07-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
I'm not concerned about `vec_restore()` but I think the data frame method for `vec_slice()` should check the column size. We normally validate the subscript beforehand but for data frames this is validated against the theoretical size of the data frame, not the actual sizes of the columns. I think I see where to add this check so I'll send a PR shortly.

**Comment by antoine-sachet** [comment]
I just wanted to say thanks. Updating `vctr` broke some of our code ("Columns must match the data frame size.") without apparent reason. It took me a while to track down the issue. Turns out we had had a massive bug for months. So thank you both :+1:

**Comment by krlmlr** [comment]
Thanks for the heads up, very much appreciated!
