### ISSUE TITLE
expression() should be treated as a vector?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#559]
``` r
x <- expression()
y <- expression(1, 2 + 3)
length(x)
#> [1] 0
length(y)
#> [1] 2
y[[2]]
#> 2 + 3
vctrs::vec_is(x)
#> [1] FALSE
vctrs::vec_is(y)
#> [1] FALSE
```

<sup>Created on 2019-09-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Use case: {bench} package (and perhaps others) store expressions in tibbles, which now require `vec_is()` for the columns. CC @jimhester.

**Comment by lionel-** [comment]
I think it was deliberate, though it should probably be easy to add support. If I'm not missing anything, the only advantage of expression vectors over lists of calls is that the former carries srcrefs?

**Comment by jimhester** [comment]
I can actually change it in bench to just be a list of calls. There is no actual need for it to be an expression.

**Comment by krlmlr** [comment]
It's not only bench. What would it take to add vctrs support? (I'm not sure what the advantages of the `"expression"` class are.)

**Comment by krlmlr** [comment]
Also:

``` r
vctrs::vec_is(rlang::quos())
#> [1] FALSE
```

<sup>Created on 2019-09-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
Good point, `quos()` should normally return a `<list_of<quosure>>` but the ctor is in vctrs. As a workaround we should add a delayed S3 method for `vec_proxy()` in rlang, I opened an issue at https://github.com/r-lib/rlang/issues/831.

**Comment by lionel-** [comment]
Closing for now.
