### ISSUE TITLE
Extendable record vectors?

### ISSUE THREAD

**Issue by mabafaba** [r-lib/vctrs#562]
I’ve been trying to make a record type vector class that serves as the basis of a number of subclasses. Is that supported by vctrs (and if not, should it)? At the moment it seems that one would have to duplicate all the methods instead of extending from one vctrs vector class to another

**Comment by lionel-** [comment]
Can you provide a small example please? Quick suggestion: creating your own constructor that allows subclassing:

```r
new_myclass <- function(data, subclass = NULL) {
  new_rcrd(data, class = c(subclass, "myclass"))
}
```

**Comment by mabafaba** [comment]
Ha of course this works. Sorry should have gone on github. Thanks a lot!!
