### ISSUE TITLE
vec_c( <complex>, NA)

### ISSUE THREAD

**Issue by romainfrancois** [r-lib/vctrs#564]
``` r
library(vctrs)

vec_c(2 + 1i, NA)
#> No common type for `..1` <complex> and `..2` <vctrs_unspecified>.
```

<sup>Created on 2019-09-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by romainfrancois** [comment]
Also : 

``` r
vctrs::vec_c(1, 1+1i)
#> Error: No common type for `..1` <double> and `..2` <complex>.
```

<sup>Created on 2019-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

related to https://github.com/tidyverse/dplyr/issues/4614

**Comment by yogat3ch** [comment]
> A similar issue is happening when using `bind_rows()` with a column of periods on dplyr_0.8.99.9000:
> 
> ```r
>   test <- list()
> test$a <- data.frame(a = rep(lubridate::now(), 10), p = rep(lubridate::hm("0:30"), 10))
> test$b <- data.frame(a = rep(lubridate::now(), 10), p = rep(lubridate::hm("0:50"), 10))
> 
> dplyr::bind_rows(test)
> #> Error: No common type for `a$p` <Period> and `b$p` <Period>.
> ```
> 
> Created on 2019-12-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by DavisVaughan** [comment]
Looks like this would be taken care of with https://github.com/tidyverse/lubridate/issues/721
