### ISSUE TITLE
vignette: need to @importFrom vctrs vec_cast vec_ptype vec_ptype2

### ISSUE THREAD

**Issue by mabafaba** [r-lib/vctrs#566]
Should we add to the [namespace section of the s3-vector Vignette](https://github.com/r-lib/vctrs/blob/5f2297161c87b2f07ba8d4cc7df905239964806c/vignettes/s3-vector.Rmd#L952) documentation that one also needs 
```{r}
#' @importFrom vctrs vec_cast
#' @importFrom vctrs vec_ptype
#' @importFrom vctrs vec_ptype2
```
to prevent R CMD "check"  warnings _"object 'vec_cast' not found whilst loading namespace"_ ? (or maybe I'm doing something else wrong..)
Happy to make a pull request if anyone has a recommendation where best to put those imports (I've put it on top of one of the new_myvectorclass() function for now?)

**Comment by jennybc** [comment]
The S3 vectors vignette just gained a lot of material re: how to define your own class within a package in 32892dd0056970b38b9908f61f14610c6068b40e. There we offer the default advice to import the vctrs namespace (not a good general practice, but is a good option in this case).
