### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#57]
`vec_c()`, `vec_rbind()`, and `vec_cbind()` need to create error messages that make it easier to determine the source of the error, even when nested.

e.g. how can we do better here?

``` r
library(vctrs)

vec_c(1, 2, vec_c(3, vec_c(4, "x")))
#> Error: No common type for double and character
```

**Comment by njtierney** [comment]
My first (and probably not very good) thought: Perhaps it could print back some kind of AST of the vector:

```
> lobstr::ast(c(1,2, c(1, c(4, "x"))))
█─c 
├─1 
├─2 
└─█─c 
  ├─1 
  └─█─c 
    ├─4 
    └─"x" {"character provided in a majority numeric vector"}
```

And then provide an error message / cross at the location where there is an error?

That said, this print / error warning wouldn't scale.

**Comment by hadley** [comment]
Hmmm, interesting idea. I think the idea of some tree like display might be useful.

Although I can't quite imagine how the tree would look in cases like this:

```R
df1 <- data.frame(a = 1)
df1$b <- data.frame(b = 2)
df1$b$c <- data.frame(c = 3)
df1$b$c$d <- data.frame(d = 3)

df2 <- data.frame(a = 1)
df2$b <- data.frame(b = 2)
df2$b$c <- data.frame(c = 3)
df2$b$c$d <- data.frame(d = "x")

vctrs::vec_rbind(df1, df2)
#>  Error: No common type for double and factor<5a425> 
```

**Comment by njtierney** [comment]
I think that the trees idea is kinda neat, but I'm not sure how useful it would be in implementation, it would need a pretty special print method, I think. Maybe there's some kind of scope for a reduced print method for `ast` similar to how `tibble` reduces the printing of rows for `data.frame`s.

I'm not sure what the tree would look like in that case either, although I must say that the `vctr` error message is better than base `rbind` and `dplyr::bind_rows`

``` r
df1 <- data.frame(a = 1)
df1$b <- data.frame(b = 2)
df1$b$c <- data.frame(c = 3)
df1$b$c$d <- data.frame(d = 3)

df2 <- data.frame(a = 1)
df2$b <- data.frame(b = 2)
df2$b$c <- data.frame(c = 3)
df2$b$c$d <- data.frame(d = "x")

rbind(df1,df2)
#> Warning: non-unique value when setting 'row.names': '1'
#> Error in `.rowNamesDF<-`(x, value = value): duplicate 'row.names' are not allowed
dplyr::bind_rows(df1, df2)
#> Error in bind_rows_(x, .id): Argument 2 can't be a list containing data frames
```

Created on 2018-08-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.0.9000).

Is it possible to identify the number of things that are one class vs another, and perhaps provide a message around that?

Perhaps something like:

```
vctrs::vec_rbind(df1, df2)
#>  Error: No common type for double (7 provided) and factor (1 provided)
```

**Comment by krlmlr** [comment]
Can we change `vec_ptype()` so that it prints intermediate types until an error occurs, and also shows more detail for records and such? Then, the error message could instruct the user to call `vec_ptype()` .

``` r
vctrs::vec_ptype(0:1, 2, "a")
#> Error: incompatible types
#> 0. (           , <integer>    ) = <integer>
#> 1. ( <integer> , <double>     ) = <double> 
#> 2. ( <double>  , <character>  ) = <error>
```

<sup>Created on 2019-01-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

``` r
library(vctrs)
vec_ptype(new_rcrd(list(a = 1)), new_rcrd(list(a = 1)), new_rcrd(list(a = "a")))
#> Prototype: <vctrs_rcrd[a]>
#> 0. (                 , <vctrs_rcrd[a]> ) = <vctrs_rcrd[a]>
#> 1. ( <vctrs_rcrd[a]> , <vctrs_rcrd[a]> ) = <vctrs_rcrd[a]>
#> 2. ( <vctrs_rcrd[a]> , <vctrs_rcrd[a]> ) = <vctrs_rcrd[a]>
#> fields("a")
#>   Error: incompatible type
#>   0. (          , <double>    ) = <double>
#>   1. ( <double> , <double>    ) = <double>
#>   2. ( <double> , <character> ) = <error>
```

<sup>Created on 2019-01-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by DavisVaughan** [comment]
Better error messages in data frame casts would definitely be nice. It would be great to know the column where this issue came from, if possible.

``` r
suppressPackageStartupMessages({
  library(vctrs)
  library(dplyr)
})
#> Warning: package 'dplyr' was built under R version 3.5.2

options(rlang__backtrace_on_error = "none")

iris2 <- mutate(iris, Species = 1)

vec_cast(iris2, iris)
#> Error: Can't cast <double> to <factor<12d60>>
```

<sup>Created on 2019-02-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by lionel-** [comment]
Check consistency of `vec_assert()` messages.
