### ISSUE TITLE
`vec_is_coercible()`

### ISSUE THREAD

**Issue by lionel-** [r-lib/vctrs#571]
Currently requires a `tryCatch()`:

```r
vec_is_coercible <- function(x, to, ..., x_arg = "x", to_arg = "to") {
  tryCatch(
    vctrs_error_incompatible_type = function(...) FALSE,
    {
      vctrs::vec_ptype2(x, to, ..., x_arg = x_arg, y_arg = to_arg)
      TRUE
    }
  )
}
```

Do we want to change `vec_ptype2()` to communicate non-coercibility via a sentinel rather than an error? `tryCatch()` is currently slow and causes complex backtraces, but that might get better in future versions of R, depending on https://github.com/lionel-/r-source/pull/22 being accepted (local handlers probably won't be exposed to users, but `tryCatch()` might be rewritten to use them).

**Comment by DavisVaughan** [comment]
Since we control the dispatch now, one idea is to implement this at the C level and return `FALSE` if our dispatch lookup doesn't find any methods. Should be fast

**Comment by lionel-** [comment]
This wouldn't work in the general case because dispatch on class is not indicative of a common type.

**Comment by hadley** [comment]
What do we need this function for?

**Comment by lionel-** [comment]
We use it (or something similar) in `vec_as_location()` to figure out the domain of a type (coercible to character, logical, or integer).

**Comment by lionel-** [comment]
Another use case: falling back to deparsing or chopping when there is no common type. Currently requires a try-catch as well.

It is probably possible to switch to a sentinel approach with a period of deprecation of the throwing functions. Also since we encouraged vec-default-ptype2 instead of throwing directly, this may not be as large a breaking change.

**Comment by lionel-** [comment]
The `tryCatch()` pattern is sufficient for this rare operation, so it seems we don't need to export a function for it yet.
