### ISSUE TITLE
"vctrs_list_of" of p_type character(0) give unexpected output with `as.character()`

### ISSUE THREAD

**Issue by moodymudskipper** [r-lib/vctrs#573]
See https://github.com/tidyverse/tidyr/issues/737 for example that prompted the issue : 

``` r
library(vctrs)
x <- structure(list("Norway", "Spain", "USA"), 
               ptype = character(0), 
               class = c("vctrs_list_of", "vctrs_vctr"))

as.character(x)
#> [1] "<chr>" "<chr>" "<chr>"
```

I expected:

```
as.character(x)
#> [1] "Norway" "Spain"  "USA"
```

**Comment by lionel-** [comment]
That is deliberate. The semantics you describe can't work because the character vectors might be length > 1.

**Comment by moodymudskipper** [comment]
Could it fail then ? What is the use of a vector of `"<chr>"` ? In my linked example `pivot_wider()` is creating new columns, only one of them has elements with length > 1, so I tried to use `as.character()`, which would work on a standard list of length 1 elements, and I got this unexpected result silently, it's not consistent with how other *tidyverse* functions work yet and might break some code at some point if they use *vctrs* too.

The fix is to use `unlist()` rather than `as.character()`, it might be suggested in the error message.

**Comment by lionel-** [comment]
It can't fail because `as.character()` (which as a generic doesn't have well defined semantics) is used in many places to serialise objects as text. One place is in `print.data.frame` IIRC, another is in the RStudio object veiewer.

**Comment by DavisVaughan** [comment]
If the list really only has length one elements I think you can also use `vec_casr(x, character ())`
