### ISSUE TITLE
Offer unique name repair that doesn't change the name of the first occurrence?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#576]
A less invasive form of `"unique"` name repair, perhaps called `"minique"`. Useful for tibble:

``` r
tibble::tibble(a = 1, a = 1, .name_repair = "unique")
#> New names:
#> * a -> a...1
#> * a -> a...2
#> # A tibble: 1 x 2
#>   a...1 a...2
#>   <dbl> <dbl>
#> 1     1     1
tibble::tibble(a = 1)[c(1, 1)]
#> New names:
#> * a -> a...2
#> # A tibble: 1 x 2
#>       a a...2
#>   <dbl> <dbl>
#> 1     1     1
```

<sup>Created on 2019-09-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
My first feeling is that we should avoid having variants of name repair, otherwise users will have a hard time predicting the behaviour.

cc @jennybc

**Comment by krlmlr** [comment]
Sure we can roll our own name repair strategy in tibble. But this will lead to a lot of code duplication I'm afraid. What would be a good compromise?

**Comment by jennybc** [comment]
What's the new info or need in tibble that make this variant of unique-ifying necessary now?

**Comment by jennybc** [comment]
Without knowing the context, I'd say the proposal basically contradicts one our rationales for the current strategy:

In 3.5.1 of [principles.tidyverse.org](https://principles.tidyverse.org/names-attribute.html#unique-names), we say:

> There are many ways to make names unique. We append a suffix of the form `...j` to any name that is a duplicate or `""` or `...`, where `j` is the position. Why?
>
>   * An absolute position `j` is more helpful than numbering within the elements that share a name. Context: troubleshooting data import with lots of columns and dysfunctional names.
>   * We hypothesize that it’s better have a “level playing field” when repairing names, i.e. if `foo` appears twice, both instances get repaired, not just the second occurrence.

And I still feel pretty good about both of those points.

**Comment by krlmlr** [comment]
Compare:

``` r
data.frame(a = 1)[c(1, 1)]
#>   a a.1
#> 1 1   1
tibble::tibble(a = 1)[c(1, 1)]
#> # A tibble: 1 x 2
#>       a     a
#>   <dbl> <dbl>
#> 1     1     1
```

<sup>Created on 2019-09-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I feel that subsetting shouldn't unnecessarily change column names. If we repair, I think we should repair using `...#` . That's the motivation for this issue.

We agreed with @hadley to declare this as "undefined behavior" and keep the column names unchanged, as in the current tibble implementation. No action needed for now.

**Comment by lionel-** [comment]
> Sure we can roll our own name repair strategy in tibble.

(Just a note that I don't think it'd have been a good idea to introduce a new strategy in tibble, the goal is to be consistent across packages.)

**Comment by jennybc** [comment]
This form of subsetting, `tibble::tibble(a = 1)[c(1, 1)]` feels like a pretty special case. More often, we are selecting or rearranging existing columns. I suppose that it is technically subsetting, but it's adding a variable = changing the shape of the object. So I don't think it's too surprising that the name repair strategies seen elsewhere are in play.

**Comment by krlmlr** [comment]
I don't mind using the "minimal" strategy for now. The "unique" strategy feels disruptive. We're declaring this as undefined behavior, this allows us to change later.

Are you suggesting to implement differently?

**Comment by jennybc** [comment]
I think @lionel- and I were both sort of alarmed or puzzled by this statement: 

> Sure we can roll our own name repair strategy in tibble. But this will lead to a lot of code duplication I'm afraid.

And hence wanted more discussion to understand where this is coming from.

**Comment by krlmlr** [comment]
Does the following property make sense:

```r
identical(df[c(j1, j2)][j1], df[j1])
```

? Essentially this means that extending the index vector never alters existing column names. If we stick to this, we can't use the "unique" strategy.

I hear your concerns about introducing a new repair strategy, and I agree we should rather not, unless we find a very compelling reason.

**Comment by jennybc** [comment]
Without some practical motivation or set of concrete user issues, I don’t really see what’s gained by adding another strategy. And there is some cost, in terms of complexity and something else to name and document well.

**Comment by DavisVaughan** [comment]
I like the "symmetry" (I guess?) we get with the current unique name repair. I find it pretty easy to explain. Notice how the only thing that changes is the `%>%` part, and the same pattern is applied for `i` and `j` when they are equal. 

I don't think it would be quite as "simple" with the other pattern where you have a special rule for the first duplicate value (leave unchanged) vs the second duplicate value and on (add `...#`).

```r
# When i != j

df[c(i, j)][1] == df[i]

df[c(i, j)][2] == df[j]

# When i == j

df[c(i, j)][1] == df[i] %>% set_names(glue("{names(df[i])}...1"))

df[c(i, j)][2] == df[j] %>% set_names(glue("{names(df[j])}...2"))
```

We can kind of try this out right now with `vec_cbind()`

``` r
library(magrittr)
library(rlang)
library(vctrs)
library(glue)

x <- data.frame(a = 1)
y <- data.frame(b = 1)

df <- vec_cbind(x, y)

# When i != j

i <- 1L
j <- 2L

vec_equal(vec_cbind(df[i], df[j])[1], df[i])
#> [1] TRUE

vec_equal(vec_cbind(df[i], df[j])[2], df[j])
#> [1] TRUE

# When i == j

i <- 1L
j <- 1L

vec_equal(vec_cbind(df[i], df[j])[1], df[i] %>% set_names(glue("{names(df[i])}...1"))) 
#> New names:
#> * a -> a...1
#> * a -> a...2
#> [1] TRUE

vec_equal(vec_cbind(df[i], df[j])[2], df[j] %>% set_names(glue("{names(df[j])}...2"))) 
#> New names:
#> * a -> a...1
#> * a -> a...2
#> [1] TRUE
```

I'm also not sure we should get too much inspiration from base R regarding what to repair. For example, we already diverge strongly with `vec_cbind()`

``` r
x <- data.frame(a = 1)

cbind(x, x)
#>   a a
#> 1 1 1

vctrs::vec_cbind(x, x)
#> New names:
#> * a -> a...1
#> * a -> a...2
#>   a...1 a...2
#> 1     1     1
```

Oh maybe this is a nice invariant for tibble to strive for as well, which would advocate for the current unique name repair scheme:

```r
vec_cbind(df[i], df[j]) == df[c(i, j)]
```

**Comment by lionel-** [comment]
One thing that is unclear is when should we proceed with a user request that creates _new_  [^1] duplicates by repairing the names, and when should we make it an error.

* In tidyselect we have recently decided to make it an error.
* In `vec_cbind()` we proceed and repair.
* In tibble with repeated indices we proceed and ignore.

Could we agree that ignoring the duplicates is not good and that we should at least repair? That would narrow the options to two cases.

[^1] What to do when we see _existing_ duplicate names in the input tibbles is a different issue though, and it seems we are converging towards the principle of ignoring those as much as feasible.

**Comment by jennybc** [comment]
I think it comes down to whether this invariant ("the following property" above) is suggested by what makes real world usage more pleasant and predictable. Or could it be characterized as "elegant invariants for the sake of elegant invariants"?

I agree it is appealing on its own. But I think what we currently do is more useful in real world data analytic situations and that should be regarded as more important. In many places, we give people the flexibility to specify a name repair function and they can use `make.unique()` if they prefer that. I believe it has the quality you are talking about.

**Comment by krlmlr** [comment]
I've submitted https://github.com/tidyverse/tibble/issues/656, let's discuss there.
