### ISSUE TITLE
Allow integerish indexes in vec_as_index()

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#577]
Does this need to be an error?

``` r
vctrs::vec_as_index(1:3, 3)
#> `n` must be a vector with type <integer>.
#> Instead, it has type <double>.
```

<sup>Created on 2019-09-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
We should `vec_coercible_cast()`.

**Comment by lionel-** [comment]
vctrs doesn't support long vectors at the moment.

**Comment by krlmlr** [comment]
long vctrs :rofl:

Do you mind a test that is `skip()`ped?

**Comment by lionel-** [comment]
Maybe open a "Long vectors support" issue and file the test there?
