### ISSUE TITLE
vec_as_index() improvements

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#578]
Lessons learned from tibble.

1. Should `vec_slice()` be allowed to extend the vector?

    We should keep the following invariant: `` `vec_slice<-`(x, i, value)`` is the same as `` `vec_slice<-`(x, vec_as_index(i, vec_size(x), names2(x)), value)`` . 

2. Do we need `vec_as_scalar_index()` ? This would have the same semantics as `vec_as_index()` but only support positive scalar numerics and scalar names.

3. Do we really need both the `n` and the `names` argument to `vec_as_index()` and `vec_as_position()`? Can we allow a character vector as the `n` argument?

To be continued.

**Comment by lionel-** [comment]
> Do we need vec_as_index_scalar() ?

Can you elaborate please.

**Comment by hadley** [comment]
`[[` has different arguments to `[`:

* A logical vector doesn't make sense
* Numeric and character vectors must have length 1
* Numeric vectors must be positive

**Comment by DavisVaughan** [comment]
This can probably be closed? We have `vec_as_location2()` now, and I think having both `n` and `names` isn't that bad.

I doubt we want `vec_slice()` to be able to extend a vector, but I'm not sure

**Comment by lionel-** [comment]
Yes this API should be in a better state now.
