### ISSUE TITLE
Build warning: cast from pointer to integer of different size

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#583]
Another Windows warning building on arch i386 only:

```
hash.c: In function 'hash_char':
hash.c:45:21: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   return hash_int64((int64_t) x);
```

I think this is why in other places we use `intptr_t` rather than `int64_t`.

(I'll fix this tomorrow too)

**Comment by lionel-** [comment]
> I think this is why in other places we use intptr_t rather than int64_t.

We need to cast to a fixed width type at some point. We may need a compile-time branch to detect 32 bit pointers and take a `uint32_t` path in that case. Also it'd be nice to use unsigned types consistently.
