### ISSUE TITLE
A clarification on `vec_match()` with attributes

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#599]
What is the correct behavior of `vec_match()` when attributes are involved? Consider a few base R examples:

- When the names are on the outermost vector, they are ignored.
- When the names are on the inner elements of a list, they are important since R calls `as.character()` on the inputs when they are lists.

``` r
x <- c(x_nm = 1)
y <- c(y_nm = 1)

match(x, y)
#> [1] 1

match(list(x), list(y))
#> [1] NA

as.character(list(x))
#> [1] "c(x_nm = 1)"

as.character(list(y))
#> [1] "c(y_nm = 1)"
```

Notice this has inconsistent behavior though. Consider what happens with characters. Notice how the `as.character()` call doesn't retain the names, so things look equal.

``` r
x <- c(x_nm = "1")
y <- c(y_nm = "1")

match(x, y)
#> [1] 1

match(list(x), list(y))
#> [1] 1

as.character(list(x))
#> [1] "1"

as.character(list(y))
#> [1] "1"
```

With other attributes, they are ignored (as far as i can tell) when converting to character.

``` r
x <- 1
x_attr <- structure(1, stuff = 1)

match(x, x_attr)
#> [1] 1

match(list(x), list(x_attr))
#> [1] 1

as.character(list(x))
#> [1] "1"

as.character(list(x_attr))
#> [1] "1"
```

What should `vec_match()` do? There are really two questions:

- Should names and attributes be ignored with this? My gut reaction is yes.

```r
vec_match(c(x_nm = 1), c(y_nm = 1))
#> [1] 1
```

- Should names and attributes be ignored in the nested version? My gut reaction is no.

```r
vec_match(list(c(x_nm = 1)), list(c(y_nm = 1)))
#> [1] NA
```

Similar questions arise with `vec_equal()` on these same examples.

**Comment by DavisVaughan** [comment]
There might be nothing to do, as I think `vec_match()` is already doing the behavior I am proposing. But it might be worth adding a few more tests specifically about these edge cases to document the differences.

There is currently one bug with `vec_match()` and characters with different encodings, but I figured it out and its an easy fix. This is currently broken according to what I think `vec_match()` should be doing:

``` r
library(vctrs)

string <- "\u00B0C"

utf8 <- iconv(string, from = Encoding(string), to = "UTF-8")
latin1 <- iconv(string, from = Encoding(string), to = "latin1")

utf8_attr <- structure(utf8, stuff = 1)

# correct
vec_match(utf8_attr, latin1)
#> [1] 1

# should be NA (attributes were dropped)
vec_match(list(latin1), list(utf8_attr))
#> [1] 1
```

**Comment by hadley** [comment]
Yeah, that sounds correct to me.

**Comment by lionel-** [comment]
Conceptually equality comparisons are done on the proxy data after coercion to the common type. Names and attributes are not part of the proxy data (though the proxy might have attributes for convenience).

When comparing list elements, the proxy is not taken and the comparison is wholistic. We should ignore details attributes though.
