### ISSUE TITLE
Rolling functions from RcppRoll

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#6]

**Comment by eddelbuettel** [comment]
Look at [roll](https://cloud.r-project.org/web/packages/roll/index.html) instead -- a newer and more powerful variant.  On GH [over here](https://github.com/jjf234/roll).

**Comment by dandermotj** [comment]
It would be nice to have a similar interface to `purrr::map` for flexibility. I have a very simple (and fragile) version of `roll` that does this [here](https://github.com/dandermotj/mmr/blob/master/R/roll.R). 

``` r
roll <- function(x, .f, ..., width = 10, extend = FALSE) {

  .f <- as_function(.f, ...)

  idxs <- if(extend) {
    map(seq(1, length(x) - width + 1), ~ seq(1, .x + width - 1))
  } else {
    map(seq(1, length(x) - width + 1), ~ seq(.x, .x + width - 1))
 }

  map_dbl(idxs, ~ .f(x[.x]))
}

roll(1:20, mean, width = 5)
# [1]  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18
roll(1:20, ~ sum(.x) / length(.x), width = 5)
# [1]  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18
```

This interface works well for simple extensions like computing rolling means, variances, ect, but I'm not sure how well this would work for things like rolling linear models and such.

**Comment by hadley** [comment]
@dandermotj please discuss that over at purrr - we will be implementing specific high performance methods here.

**Comment by hadley** [comment]
Closed in favour of roll package.
