### ISSUE TITLE
Working with the `vec_assign_impl()` callable

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#625]
So in {slide} I use `vec_assign_impl(clone = false)` for building up my output container, which works great for the most part. But it doesn’t capture the case where the output container is a matrix / we don’t have a proxy method, because in those cases we fall back to `vec_assign_fallback()` earlier in `vec_assign()`, not in `vec_assign_impl()`
https://github.com/r-lib/vctrs/blob/8d12bfc0e29e056966e0549af619253253752a64/src/slice-assign.c#L46

This means that tests like these fail for me in `slide_vec()`, where the output container could be a matrix
https://github.com/DavisVaughan/slide/blob/a070c3025a88904348b302a7a77d2cfad0d52aa0/tests/testthat/test-slide-vec.R#L106

I see two possible solutions:

- We move this check into `vec_assign_impl()`, but that seems odd because if I set `clone = false` and we do have to fallback, because I’m not sure if it would work right (would it clone anyways?).
- I have to do this check myself in {slide}. That means I would need `vec_proxy_info()` and `vec_assign_fallback()` callables. And I guess I’d have to know how to work with the return value of a `struct vctrs_proxy_info` in slide.

**Comment by DavisVaughan** [comment]
One consequence of the way this currently works is that we can't assign into a data frame with a matrix column.

``` r
library(vctrs)
library(tibble)

df <- tibble(x = 1:2, y = matrix(1:4, nrow = 2))
df
#> # A tibble: 2 x 2
#>       x y[,1]  [,2]
#>   <int> <int> <int>
#> 1     1     1     3
#> 2     2     2     4

vec_slice(df, 2) <- df[1,]
#> Error in `vec_slice<-`(`*tmp*`, 2, value = structure(list(x = 1L, y = structure(c(1L, : Internal error in `vec_assign()`: `value` should have been recycled to fit `x`.
```

<sup>Created on 2019-10-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This is because `df_assign()` uses `vec_assign_impl()`, bypassing the fallback which should be called.

https://github.com/r-lib/vctrs/blob/142a257e4dbad97df4923ee72767b4df7a192d45/src/slice-assign.c#L239

**Comment by lionel-** [comment]
Ideally vec-slice-impl would know how to slice arrays, and the fallback would only be used for OO objects.
