### ISSUE TITLE
Dictionary functions should proxy inputs recursively

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#630]
I can bomb RStudio with this while in the vctrs project:

```r
devtools::load_all()
vec_unique_loc(data.frame(x = tuple(1:3, 1:3)))
```

There are two problems, both have to do with recursively proxying `x`.

---

The first problem is that we recursively call `vec_proxy_equal()` here
https://github.com/r-lib/vctrs/blob/2cce0f8c422e130cb270d95416724d107cc415e1/src/dictionary.c#L36

But we don't actually set `x` back to the proxied value. So when we `hash_fill()` it doesn't use the right version
https://github.com/r-lib/vctrs/blob/2cce0f8c422e130cb270d95416724d107cc415e1/src/dictionary.c#L61

It bombs because we try and pass along a df size of `3` here, but because the tuple is implemented as a list it only has a size of `2` when it hasn't been proxied (proxying it gives a data frame of size 3). It very much has to do with the FIXME note at the below link.
https://github.com/r-lib/vctrs/blob/2cce0f8c422e130cb270d95416724d107cc415e1/src/hash.c#L296

---

Second, it turns out that `obj_maybe_translate_encoding()` has essentially the same problem. It assumes we have recursively proxied and tries to pass along the data frame size when checking if any column need translation.
https://github.com/r-lib/vctrs/blob/2cce0f8c422e130cb270d95416724d107cc415e1/src/translate.c#L127

---

I think the best solution that fixes both problems is to recursively proxy in `vec_unique_loc()` and the other dictionary functions, rather than just calling `vec_proxy_equal()` once. There is no overhead in doing this since `init_dict()` does it anyways.

https://github.com/r-lib/vctrs/blob/2cce0f8c422e130cb270d95416724d107cc415e1/src/dictionary.c#L117

We could also recursively call `vec_proxy_equal()` in both `df_hash_fill()` and `obj_maybe_translate_encoding()`, which might be more robust if we use them elsewhere, but has the disadvantage that we'd be doing it twice.

**Comment by lionel-** [comment]
Should we call `hash_fill()` on the proxied structure rather than the input vector?
