### ISSUE TITLE
Make C level `vec_proxy_equal()` recursive by default

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#641]
See https://github.com/r-lib/vctrs/pull/636#pullrequestreview-307867127

It is not currently used non-recursively anywhere anymore, so we might not even need `vec_proxy_equal_shallow()`.

**Comment by lionel-** [comment]
It seems like the R level `vec_proxy()` should also be recursive. And then restoration as well.

**Comment by lionel-** [comment]
E.g. there might be a grouped-df column whose group indices need to be restored after slicing.

**Comment by lionel-** [comment]
oops `vec_proxy()` cannot be recursive because `vec_restore()` cannot be recursive. We can't restore recursively since the number of columns or their contents might change.

It's possible vec-proxy and vec-proxy-equal are in fact unrelated concepts.

**Comment by lionel-** [comment]
`vec_proxy_compare()` also needs some clean up

```r
test <- new_data_frame(n = 2L)
test$x <- new_data_frame(list(y = matrix(1:2, 2)))
vec_proxy_compare(test)
#>   V1
#> 1  1
#> 2  2

test$x <- tibble::tibble(y = matrix(1:2, 2))
vec_proxy_compare(test)
#> Error: No common type for `..1$y` <data.frame<V1:integer>> and `..2$y` <integer[,1]>.
```
