### ISSUE TITLE
list proxies behave differently than vectors with vec_init()

### ISSUE THREAD

**Issue by mjskay** [r-lib/vctrs#647]
Not sure if this is a bug or not (and seems possibly related to #445), but I discovered while developing a custom type that if you use a list as a proxy it will break `vec_init()`. I discovered this because I couldn't use `tidyr::pivot_wider()` with the type due to the usage of `vec_init()` inside `pivot_wider_spec()`. I assumed from the documentation of `vec_proxy()` that using a list as a proxy would be fine, but it seems to require a bit more care than I thought.

The actual type I'm developing is more complex than this example, but here is a reprex of a simple (and frankly kind of silly) type that just wraps around an internal vector as its first element:

``` r
library(tidyr)
library(vctrs)

new_a1 <- function(x) {
  new_vctr(list(x), class = "a1")
}

vec_proxy.a1 = function(x) {
  field(x, 1)
}

vec_restore.a1 = function(x, ...) {
  new_a1(x)
}

length.a1 = function(x, ...) {
  length(field(x, 1))
}

x1 = new_a1(c(1,2))
d1 = tibble(g = c("a", "b"), x = x1)
d1
#> # A tibble: 2 x 2
#>   g         x
#>   <chr>  <a1>
#> 1 a         1
#> 2 b         2
pivot_wider(d1, names_from = g, values_from = x)
#> # A tibble: 1 x 2
#>       a     b
#>    <a1>  <a1>
#> 1     1     2
```

<sup>Created on 2019-11-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I had assumed a similar type that uses a list as a proxy instead would also work, and for the most part it does --- except `pivot_wider` choked on it:

``` r
library(tidyr)
library(vctrs)

new_a2 <- function(x) {
  new_vctr(list(x), class = "a2")
}

vec_proxy.a2 = function(x) {
  as.list(field(x, 1))
}

vec_restore.a2 = function(x, ...) {
  new_a2(unlist(x))
}

length.a2 = function(x, ...) {
  length(field(x, 1))
}

x2 = new_a2(c(1,2))
d2 = tibble(g = c("a", "b"), x = x2)
d2
#> # A tibble: 2 x 2
#>   g         x
#>   <chr>  <a2>
#> 1 a         1
#> 2 b         2
pivot_wider(d2, names_from = g, values_from = x)
#> Error: Can't index beyond the end of a vector.
#> The vector has length 0 and you've tried to subset element 1.
```

<sup>Created on 2019-11-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I tracked the problem down to vec_init. vec_init works correctly on type a1:

```r
> vec_init(x1, 3)
<a1[3]>
[1] NA NA NA
```

But not on type a2:

```r
> vec_init(x2, 3)
<a2[0]>
```

This is because the proxy type for a2 is a list, and `vec_init()` is doing the equivalent of this:

```r
> vec_proxy(x2)[c(NA_integer_, NA_integer_, NA_integer_)]
[[1]]
NULL

[[2]]
NULL

[[3]]
NULL
```

Which after unlist yields `NULL`. A workaround I found was to change `vec_restore()` as follows:

```r
vec_restore.a2 = function(x, ...) {
  if (length(x) > 0) {
    x[sapply(x, is.null)] = NA
  }
  new_a2(unlist(x))
}
```

But I'm not sure if this represents a bigger potential issue, or if the problem should at least be documented for others who want to use lists as proxies.

**Comment by lionel-** [comment]
I think the problem comes from your usage of `unlist()` in the restore method, it seems rather type unsafe.

**Comment by mjskay** [comment]
Ah fair --- that's my bad for switching to unlist for the simplified reprex. The code I'm actually working on is essentially using `rray::rray_bind()` where that unlist happens, and the same issue still crops up. I think the issue comes from the fact that while NULLs are a sensible "missing value" for lists, a lot of functions that do stuff with lists are going to chuck the NULLs rather than treat them as missing values.

I would expect similar issues to crop up for other folks using lists as proxies for a non-list type --- though I'm not sure this use case is common (which is partly why my first instinct was to blow off steam about it on twitter rather than creating an issue; then @hadley asked for more details so I figured I'd make an issue :)). It may be that the type I'm working on could be structured in a better way to avoid this issue altogether. On the other hand, a cautionary note in the docs might save someone else the same trouble somewhere down the road.

**Comment by lionel-** [comment]
Can you maybe use `vec_cast()` in some way to make sure the size constraints are fulfilled?

We'll also have better tooling for container coercions in the future, which might be relevant to your use case.

**Comment by mjskay** [comment]
> Can you maybe use vec_cast() in some way to make sure the size constraints are fulfilled?

Ah cool! Yeah, it looks like `vec_cast` might work if I can sort out the final array dimensions in advance then I can cast directly to it. Still need to evaluate if there are some corner cases but this could work, thanks!

> We'll also have better tooling for container coercions in the future, which might be relevant to your use case.

Look forward to that.

Thanks for the help!

**Comment by lionel-** [comment]
Please let me know if there are other problems.
