### ISSUE TITLE
Consider letting `vec_restore()` take an R_len_t `n` rather than a SEXP

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#650]
A little benchmarking of slide revealed that when using `vec_slice_impl()` in a tight loop we really pay for the allocation of the restoration size here

https://github.com/r-lib/vctrs/blob/5a0e6965ae833c203c73a679f203b36917d8a656/src/slice.c#L269

It looks like it ends up being about 20% of the total time I spent in `vec_slice_impl()` in my loop.

![Screen Shot 2019-11-07 at 5 24 05 PM](https://user-images.githubusercontent.com/19150088/68435006-5c10b400-0188-11ea-8063-8556ebf4cc6e.png)

If `vec_restore()` allowed the restore size to be a `R_len_t` we wouldn't have to do this.

It does feel a bit awkward for this to be a SEXP value. In `vec_chop()` I also would have benefited from this just being a `R_len_t` value (I currently have to manage a SEXP and its pointer to continually update the restore size).

We would have to make a decision about what a missing size should be. Right now we use `R_NilValue` but I'd vote for just using `-1` instead.

**Comment by lionel-** [comment]
Note that you may just be measuring the gc cost rather than the typical cost of the allocation. It might make sense to pass a value though, but we'll need to think about the eventual long vector support.
