### ISSUE TITLE
`vec_equal(list(NULL), list(NULL))` returns `TRUE`

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#653]
This should return `NA` right? Unless `na_equal = TRUE`?

``` r
vctrs::vec_equal(list(NULL), list(NULL))
#> [1] TRUE
```

Problem line:

https://github.com/r-lib/vctrs/blob/673c9f1feb20ab517f99a7ba15f1e1155fdf83c2/src/equal.c#L256

**Comment by hadley** [comment]
Right
