### ISSUE TITLE
Can't slice list-cols with extra classes

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#666]
``` r
library(vctrs)

df <- data.frame(x = 1:2)
df$z <- structure(list(c(2, 5), c(3, 6)), class = c("custom_subclass", "list"))

vec_slice(df, 1)
#> Error: Can't slice a scalar
```

<sup>Created on 2019-11-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I assume this is because we're not using `Rf_inherits(x, "list")` somewhere

**Comment by krlmlr** [comment]
I now see:

``` r
library(vctrs)
z <- structure(list(c(2, 5), c(3, 6)), class = c("custom_subclass", "list"))
vec_slice(z, 1)
#> Error: Expected a vector, not a `custom_subclass/list` object
vec_is(z)
#> [1] FALSE
```

<sup>Created on 2020-01-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
@lionel- is there any chance we can get this into the patch release? It'll help with #723 and generally in getting the tibble dev version on to CRAN.

**Comment by lionel-** [comment]
Sure but I really think we should wait before releasing a vctrs-based tibble.

It's currently using vec-restore, which is not right, it should use vec-cast instead but we need to fix its semantics. Also there are multiple primitives missing from vctrs, like tbl-slice, vec-get, and tbl-get.

**Comment by krlmlr** [comment]
I'm aiming for a release not earlier than mid-February. The earlier we can alert downstream maintainers, the better. This is about making it easy for downstream maintainers to prepare for the tibble release. What can I do to help?

https://github.com/tidyverse/tibble/pull/688 deals with `vec_restore()`. We should look at the vctrs functions used by tibble and ensure they are stable-ish, I agree (https://github.com/tidyverse/tibble/issues/692). We can start using new vctrs functionality as it becomes available?

**Comment by lionel-** [comment]
We talked about coordinated developer releases for vctrs, dplyr, maybe tibble should be part of that.
