### ISSUE TITLE
Keep empty factor levels in `vec_split()`

### ISSUE THREAD

**Issue by lionel-** [r-lib/vctrs#686]
This would be useful for `group_by()`. Maybe add a `drop` parameter?

Keeping empty levels in the output of vec-split would also make the output more predictable. For instance in the following snippet it's unclear whether the output has one or two rows, depending on input data:

```r
direction <- ifelse(rnorm(3) < 0L, 1L, 2L)
direction <- factor(direction, 1:2, c("neg", "pos"))
pos <- vctrs::vec_group_pos(direction)

pos
#>   key     pos
#> 1 neg 1, 2, 3

match(pos$key, "neg")
#> [1] 1

match(pos$key, "pos")
#> [1] NA
```

Maybe the results should also be ordered by level positions, to make numeric indexing of rows possible.

Maybe a small util to slice rows by key would be useful.

```r
key_slice <- function(df, key, key_col = "key") <...>

key_slice(pos, "neg")
#>   key     pos
#> 1 neg 1, 2, 3
```

**Comment by romainfrancois** [comment]
The current implementation in `dplyr` starts from the "existing" groups and adds the "groups that might exist": https://github.com/tidyverse/dplyr/blob/master/src/dplyr.cpp#L270

It's currently recursive C++, but no Rcpp.

**Comment by hadley** [comment]
FWIW `drop` is probably the wrong argument; it's more about whether to use factor levels vs factor labels, and possibly whether the groups are defined by the Cartesian product of individual variables.

**Comment by lionel-** [comment]
Let's revisit if the need resurfaces again.

**Comment by DavisVaughan** [comment]
FWIW I looked at this once or twice and it is extremely hard to do with the way `vec_split()` works

It also works very differently in `tidyr::crossing()` vs in `group_by(.drop = FALSE)`, so having a single vctrs solution wouldn't be able to be applied to both packages, making it less convincing to implement something here
