### ISSUE TITLE
vec_c does not correctly use proxy() for record vectors

### ISSUE THREAD

**Issue by caewok** [r-lib/vctrs#691]
I am trying to implement a record vector in which the values are not necessarily stored in the vector class. Imagine a cached vector or file-based vector. In practice, this means that new_rcrd() is passed a field with some length not equal to the entire vector length. For example, new_rcrd() might have a field with a single vector of length 6, but the vector as a whole might be length 100. Other attributes would be passed to new_rcrd() to assist with reconstructing the whole vector. By calling vec_proxy(), a full-length vector can be reconstructed from the record. Other methods can be added as needed to handle indexing, length, etc.

This works well, with one exception. The function vec_c() does not work unless the .ptype is set to something other than the record vector class. So for example, vec_c(rcrd, rcrd, .ptype = integer()) works, while vec_c(rcrd, rcrd, .ptype = rcrd_class()) does not work and instead throws the error "Internal error in `vec_assign()`: `value` should have been recycled to fit `x`." Note that vec_assign() works fine in all cases when called as a stand-alone function. 

The problem seems to be that vec_c() is erroneously passing a record vector instead of the underlying proxy to vec_assign_impl() if the .ptype is a record vector class. I am not as well-versed in the underlying C code, but I think the key parts are (from vec_c in vctrs/c.c):

```
SEXP out = vec_init(ptype, out_size); # creates an empty record vector
PROTECT_WITH_INDEX(out, &out_pi);
out = vec_proxy(out); # gets the record vector proxy
...
SEXP x = VECTOR_ELT(xs, i); # gets the next element; which here would be a record vector
SEXP elt = PROTECT(vec_cast(x, ptype, args_empty, args_empty)); # casts the record vector to a record vector
...
vec_assign_impl(out, idx, elt, false); # assigns the record vector to the specified index of the record vector proxy. This causes an error, presumably because the elt record vector is erroneously unclassed and thus the length is wrong.
```

If my hunch is correct, then what should happen is that vec_assign_impl() in the above code should only be passed a vec_proxy(), something like:
`vec_assign_impl(out, idx, vec_proxy(elt), false)`

This would help with handling record vectors using vec_c. Thanks!

**Comment by hadley** [comment]
If the fields are different lengths, I don't think you should be using a rcrd, since its fundamental constraint is equal lengths. Could you provide a simple reprex that illustrates what you're trying to do?

**Comment by caewok** [comment]
Sure. This code should illustrate the issue:

```
library(vctrs)
library(fst)
library(data.table)

##### Constructor #####
new_fst_vector <- function(x = logical(), path = tempfile(fileext = ".fst"), col = "vec", compress = 50) {
  len <- length(x)
  hd <- head(x)
  cl <- class(x)

  if(length(x) > 0) { # otherwise, x has no values, so don't create an fst file (cannot write fst with no data)
    # create new fst file
    dt <- data.table::data.table(x)
    colnames(dt) <- col

    fst::write_fst(dt, path = path, compress = compress)
  }

  out <- vctrs::new_rcrd(list(head = hd),
                         path = path,
                         length = len,
                         compress = compress,
                         names = NULL,
                         base_class = cl,
                         col = col,
                         names_fst = NULL,
                         class = "fst_vector")
  out
}

##### Helper function for extraction #####
extract <- function(x, i, ...) {
  if(missing(i)) i <- seq(length(x))
  if(length(x) == 0) return(get(attr(x, "base_class"))())

  if(is.logical(i)) i <- which(i)
  vec <- fst::read_fst(attr(x, "path"), columns = attr(x, "col"), from = min(i), to = max(i))[[1]]
  vec <- vec[i - min(i) + 1]
  vec
}

##### Length #####
length.fst_vector <- function(x) { attr(x, "length") }

##### Proxy for data return #####
vec_proxy.fst_vector <- function(x) { extract(x) }

vec_restore.fst_vector <- function(x, to, ..., i = NULL) {
  if(is.list(x)) {
    stopifnot(length(x) == 1)
    x <- x[[1]]
  }

  new_fst_vector(x, compress = attr(to, "compress"))
}

##### format() #####
format.fst_vector <- function(x, max_n = 5, ...) {
  split_sample_data <- length(x) > max_n & length(x) > 10
  if(split_sample_data) {
    split_indices <- list(1:5, (length(x) - 4):length(x))

    sample_data_head <- extract(x, split_indices[[1]])
    sample_data_tail <- extract(x, split_indices[[2]])

    sample_data <- c(sample_data_head, sample_data_tail)
  } else {
    sample_data <- extract(x)
  }

  formatted_sample_data <- format(sample_data)
  if(length(formatted_sample_data) >= 10) {
    out <- c(formatted_sample_data[1:5], "...", formatted_sample_data[6:10])
  } else {
    out <- c(formatted_sample_data)
  }

  out
}

obj_print_header.fst_vector <- function(x, ...) {
  vctrs:::cat_line("<", vec_ptype_full(x), "[", attr(x, "length"), "]>")
  invisible(x)
}

obj_print_data.fst_vector <- function(x, ...) {
  if(length(x) == 0) return()
  out <- format(x)
  print(out, quote = FALSE)
  invisible(x)
}

vec_ptype_abbr.fst_vector <- function(x, ...) "fstvec"
vec_ptype_full.fst_vector <- function(x, ...) "fst_vector"

##### casting and coercion #####
vec_ptype2.fst_vector <- function(x, y, ...) UseMethod("vec_ptype2.fst_vector", y)
vec_ptype2.fst_vector.default <- function(x, y, ..., x_arg = "x", y_arg = "y") {
  vec_default_ptype2(x, y, x_arg = x_arg, y_arg = y_arg)
}

vec_ptype2.fst_vector.fst_vector <- function(x, y, ...) new_fst_vector()

vec_ptype2.integer.fst_vector <- function(x, y, ...) new_fst_vector()
vec_ptype2.fst_vector.integer <- function(x, y, ...) new_fst_vector()

vec_cast.fst_vector <- function(x, to, ...) UseMethod("vec_cast.fst_vector")
vec_cast.fst_vector.default <- function(x, to, ...) vec_default_cast(x, to)

vec_cast.fst_vector.fst_vector <- function(x, to, ...) x

vec_cast.integer.fst_vector <- function(x, to, ...) vec_cast(extract(x), integer())
vec_cast.fst_vector.integer <- function(x, to, ...) fst_vector(x)


#### Testing vec_c ####
x <- new_fst_vector(1:10)
y <- new_fst_vector(10:20)

x
y

vec_c(x, y, .ptype = integer()) # works
vec_c(x, y, .ptype = new_fst_vector()) # fails: Internal error in `vec_assign()`: `value` should have been recycled to fit `x`.
vec_c(x, y) # fails: Internal error in `vec_assign()`: `value` should have been recycled to fit `x`.

```

**Comment by DavisVaughan** [comment]
I wonder if you're really after something along these lines, where the attributes are really fields. Otherwise, how are attributes reconciled when you add two `fst_vector` together?

``` r
library(vctrs)
library(fst)
library(data.table)
library(tibble)

##### Constructor #####
new_fst_vector <- function(x = logical(), path = tempfile(fileext = ".fst"), col = "vec", compress = 50) {
  len <- length(x)
  hd <- head(x)
  cl <- class(x)
  
  if(length(x) > 0) { # otherwise, x has no values, so don't create an fst file (cannot write fst with no data)
    # create new fst file
    dt <- data.table::data.table(x)
    colnames(dt) <- col
    
    fst::write_fst(dt, path = path, compress = compress)
  }
  
  out <- vctrs::new_rcrd(
    fields = list(
      head = list(hd),
      path = path,
      length = len,
      compress = compress,
      base_class = list(cl),
      col = col
    ),
    class = "fst_vector"
  )

  out
}

x <- new_fst_vector(1:10)
y <- new_fst_vector(10:20)


as_tibble(vec_proxy(x))
#> # A tibble: 1 x 6
#>   head    path                                  length compress base_class col  
#>   <list>  <chr>                                  <int>    <dbl> <list>     <chr>
#> 1 <int [… /var/folders/41/qx_9ygp112nfysdfgxcs…     10       50 <chr [1]>  vec

as_tibble(vec_proxy(y))
#> # A tibble: 1 x 6
#>   head    path                                  length compress base_class col  
#>   <list>  <chr>                                  <int>    <dbl> <list>     <chr>
#> 1 <int [… /var/folders/41/qx_9ygp112nfysdfgxcs…     11       50 <chr [1]>  vec

x_and_y <- vec_c(x, y)

as_tibble(vec_proxy(x_and_y))
#> # A tibble: 2 x 6
#>   head    path                                  length compress base_class col  
#>   <list>  <chr>                                  <int>    <dbl> <list>     <chr>
#> 1 <int [… /var/folders/41/qx_9ygp112nfysdfgxcs…     10       50 <chr [1]>  vec  
#> 2 <int [… /var/folders/41/qx_9ygp112nfysdfgxcs…     11       50 <chr [1]>  vec
```

<sup>Created on 2019-11-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by caewok** [comment]
Davis: 

No, the point is to have the fst_vector class act as a proxy for an underlying vector that is saved elsewhere. From my perspective, the fields could be empty; I only included an entry for the field to comply with vctrs::new_rcrd restrictions. I used the first six elements of the vector for the field because it seemed like it would be useful to be able to see the head() of the vector without pulling the entire vector from the fst file. I cannot simply store the entire vector in the field, as that would defeat the purpose. 

The attributes themselves are just helpers to make certain things easier, and are not critical to the underlying concept. Compress is used by fst in saving the file; it could just as easily be omitted and use the fst default instead. Base_class tells you what the underlying vector class is, but that could be determined by peeking at the fst file. Length is similar; it tells you the length of the underlying vector without pulling fst metadata. And col is just to make it easier to deal with potentially different fst files consistently. The only thing you really need is the file path. You could probably pass the file path as the field instead of using the head() of the vector as the field. 

When combining two fst_vectors, as in c(new_fst_vector(1:10), new_fst_vector(11:20)), the following needs to occur: (1) Pull the underlying vectors into memory and combine into one vector, then save to a new fst file. (In the future, the fst package plans to permit appending, which may make this simpler.) The underlying vectors follow normal casting rules, so combining them is not really an issue, at least in theory. (2) Identify where to save the file. Choices are either overwrite one of the existing file paths from one of the two respective fst_vectors, or create a new file path. The latter is probably better in practice. (3) Update remaining attributes. Length, header, and base class is taken from the combined vector. Compress will need to select one of the two in case of discrepancy or fall back to a default value. So, reconciling the attributes is not a big issue here. 

Thanks for your help here!

**Comment by hadley** [comment]
As I suspected earlier, you don’t have a record type object so you shouldn’t be using a rcrd. You’ll need to implement the entire class structure yourself, starting from `new_vctr()`. We don’t currently have documentation for cases we’re you’re attempting to override size/length so it is going to be hard.

**Comment by caewok** [comment]
I switched to using new_vctr():
```
new_fst_vector <- function(x = logical(), path = tempfile(fileext = ".fst"), col = "vec", compress = 50) {
  len <- length(x)
  hd <- head(x)
  cl <- class(x)

  if(length(x) > 0) { # otherwise, x has no values, so don't create an fst file (cannot write fst with no data)
    # create new fst file
    dt <- data.table::data.table(x)
    colnames(dt) <- col

    fst::write_fst(dt, path = path, compress = compress)
  }

  out <- vctrs::new_vctr(.data = hd,
                         path = path,
                         length = len,
                         compress = compress,
                         names = NULL,
                         base_class = cl,
                         col = col,
                         names_fst = NULL,
                         class = "fst_vector")
  out
}
```

The error remains the same. Like I said, I think vec_c() should be passing the proxy, not the vector itself, when it passes elt here to vec_assign_impl:
`vec_assign_impl(out, idx, elt, false)`

Overriding size/length otherwise works fairly well, by defining a method for vec_proxy, length, vec_restore, and the various `[` selectors.

**Comment by DavisVaughan** [comment]
@caewok I believe you are correct, and that will be fixed here when this PR is merged. 

https://github.com/r-lib/vctrs/pull/690/files#diff-0317dc94677a53b0b3c5efb7d0bc8072R84
