### ISSUE TITLE
Custom names_repair_arg

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#692]
For https://github.com/tidyverse/tidyr/issues/774

**Comment by hadley** [comment]
Is the hint no longer produced by vctrs?  I'd think to see it in `validate_unique()` but `stop_error()` and subclasses don't seem to generate it.

Is this actually made by tibble?

**Comment by hadley** [comment]
Maybe `vec_as_names()` should have a `repair_name` argument that is passed down to `validate_unique()`, and then to `stop_names_cannot_be_empty()`, `stop_names_cannot_be_dot_dot()` and `stop_names_must_be_unique()`. If non "" (non `NULL`?) this would add an info bullet to the condition.

@lionel- if that sounds like basically the right approach, I'm happy to implement it.

**Comment by lionel-** [comment]
It'd pass down `repair_arg` as well? This sounds like the right approach!

**Comment by hadley** [comment]
Sorry, yeah, I meant `repair_arg`. I'll take a stab
