### ISSUE TITLE
Preserve free-floating data.frame attributes where possible?

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#703]
* https://github.com/tidyverse/dplyr/issues/4617
* https://github.com/tidyverse/dplyr/issues/3429

**Comment by lionel-** [comment]
It looks dplyr and tidyr genericity will mostly be handled by `vec_cast()`. Not sure we can preserve attributes in coercing methods.

**Comment by lionel-** [comment]
Maybe this should be transferred to dplyr again, in the context of `dplyr_reconstruct()`?

**Comment by hadley** [comment]
Yeah, probably.

**Comment by lionel-** [comment]
Transferred to https://github.com/tidyverse/dplyr/issues/5132.
