### ISSUE TITLE
Include timezone in vec_ptype_abbr.POSIXt()?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#709]
This would help with tibbles -- if there's not enough horizontal space, the information will be truncated.

**Comment by krlmlr** [comment]
I'll do it in pillar.

**Comment by DavisVaughan** [comment]
This is what I do in clock too, I think it looks pretty nice, and is very useful when you have multiple columns in different zones

``` r
tibble::tibble(x=clock::zoned_time_now("America/New_York"), y = clock::zoned_time_now("UTC"))
#> # A tibble: 1 x 2
#>   x                                   y                                  
#>   <zt<nano><America/New_York>>        <zt<nano><UTC>>                    
#> 1 2021-03-18 08:20:32.625518000-04:00 2021-03-18 12:20:32.626243000+00:00
```

<sup>Created on 2021-03-18 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
