### ISSUE TITLE
Take care of known list classes

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#723]
From tibble's revdepchecks, I see the following S3 classes that wrap a list and are a vector:

Base classes should be fixed in vctrs:

- [x] `"package_version"`

These will need to be fixed in downstream packages, either by implementing vec-proxy or by adding an explicit `"list"` at the end of the vector class.

- [ ] bench: `"bench_expr"`
- [ ] concurve: `"data.frame"` (?????)
- [ ] feasts: `"lst_mdl"`
- [ ] heemod: `"lazy_dots"` (???)
- [x] jstor, textrecipes: `"quosures"`
- [ ] PML: `"trelliscope_panels"`
- [ ] psychmeta: `"ad_int_list"`
- [ ] units: `"mixed_units"`

Related: #666.

**Comment by lionel-** [comment]
I think these should be fixed downstream.

**Comment by krlmlr** [comment]
Can we keep this list here?

**Comment by lionel-** [comment]
Yes, I've also added a "base" section to your post. Reprex for pkg-version:

``` r
vctrs::vec_is(packageVersion("tibble"))
#> [1] FALSE
data.frame(a = packageVersion("tibble"))
#>              a
#> 1 2.99.99.9011
```

<sup>Created on 2020-01-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Required for {pkgsearch}.

**Comment by lionel-** [comment]
Closing now, since tibble has been released.
