### ISSUE TITLE
Consider sorting instead of hashing for uniqueness

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#736]
https://news.ycombinator.com/item?id=21985246

This would allow us to use radix sort of for integer indices, which would help us to match data.table performance when grouping in dplyr.

**Comment by DavisVaughan** [comment]
See https://github.com/r-lib/vctrs/pull/1361#issuecomment-1261016775 for explanation of why we probably don't want switch all of the dictionary functions over to sorting

We did expose `vec_locate_sorted_groups()` (which uses radix ordering) for use in dplyr's `group_by()` https://github.com/tidyverse/dplyr/pull/6297, which was really the original motivation of this issue
