### ISSUE TITLE
Remove `vec_cast.<datelike>.double()` methods

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#741]
Part of 0.3.0, since it is breaking an existing cast method.

It was determined that casting dates/datetimes to and from integer/double is too relaxed here https://github.com/r-lib/vctrs/pull/728#issuecomment-570654648

- `vec_cast.Date.double()`
- `vec_cast.POSIXct.double()`
- `vec_cast.POSIXlt.double()`

Supersedes #728 and #715

**Comment by lionel-** [comment]
Part of #606
