### ISSUE TITLE
Sketch C implementation plan

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#75]
* Function that returns an enum for all types/classes that we want handle internally. Should throw an error if not a vector, and return sentinel type for vectors where we'll need to call the generic. (logical, integer, double, character, list, factor, date, datetime, difftime, duration, period, data frame, other.)

* Function that calls generic if not handled for TYPE_OTHER

* Trial with `.subset2()` and `.subset2<-()`, then use to implement `nth()`, `nth<-` and hence close #38

**Comment by hadley** [comment]
Might be better to start with `vec_cast()` — `nth()` etc can just use `[[`

**Comment by krlmlr** [comment]
Not sure if we need this if we have a way to obtain a C implementation of `vec_slice()` as discussed in https://github.com/r-lib/vctrs/issues/124.

**Comment by hadley** [comment]
Closing since @lionel- is working on it.
