### ISSUE TITLE
Prevent `vec_cast()` methods from being inherited

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#753]
I think this is similar to https://github.com/r-lib/vctrs/pull/742

In rray I have tests for:

```r
test_that("from unknown types", {
  expect_error(vec_cast("chr", rray(1)), class = "vctrs_error_incompatible_cast")
  expect_error(vec_cast(rray(1), "chr"), class = "vctrs_error_incompatible_cast")
})
```

With dev vctrs I get:

``` r
library(rray)
library(vctrs)

vec_cast("chr", rray(1))
#> Error: Can't cast `x` <character> to `to` <rray<dbl>>.

vec_cast(rray(1), "chr")
#> <rray<dbl>[1]>
#> [1] "1"
```

I think that we need `vec_cast.character.double()` to include the same `is.object()` check as `vec_ptype2()` methods for base types. So I imagine it would become something like:

```r
vec_cast.character.double <- function(x, to, ...) {
  if (is.object(x)) {
    vec_default_cast(x, to) # x_arg, y_arg?
  } else {
    x <- vec_coerce_bare(x, "character")
    shape_broadcast(x, to)
  }
}
```

**Comment by DavisVaughan** [comment]
Oh this might have just been because I now need `inherit_base_type = FALSE` in my `new_rray()` constructor

**Comment by lionel-** [comment]
I think you're right.

**Comment by lionel-** [comment]
We now disallow inheritance for base classes: https://github.com/r-lib/vctrs/commit/ac7554a50dc726856084fd5ab92883ae0789d79e

We'll need to finish this issue for the 0.3.0 milestone to avoid introducing too many breaking changes in the patch version.

**Comment by DavisVaughan** [comment]
This can still happen:

```r
library(vctrs)

x <- 1L
class(x) <- c("foo", "integer")

vec_cast(1, x)
#> [1] 1
```

**Comment by lionel-** [comment]
yeah but I didn't want to do this in the patch release because being able to coerce bare types to `vctrs_vctr` is part of the loose semantics that `vec_cast()` currently has and the idea that `vctrs_vctr` implements as much as possible for the user.

**Comment by lionel-** [comment]
For 0.2.2 I only fixed the dispatch paths introduced by `inherit_base_type = TRUE`.

**Comment by hadley** [comment]
Same as #710?
