### ISSUE TITLE
Subsetting with `NULL`

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#755]
Just want to confirm something about `vec_as_location()`. `vec_as_index()` used to allow `NULL`. Is this expected behavior now?

```r
vctrs::vec_as_location(NULL, n = 1)
#> Error: Must subset with a proper subscript vector.
#> x `i` has the wrong type `NULL`.
#> ℹ These indices must be indicators, locations or names.
```

It looks like tibble is working around this, and its breaking some rray tests
https://github.com/tidyverse/tibble/blob/413e6e4ba1eac1a8b5ff3674696da912a36209ed/R/subsetting.R#L172

Confirming CRAN vctrs results:

```r
> vctrs::vec_as_index(NULL, 1L)
integer(0)
```

It looks like the old behavior treats `NULL` like `integer()`. If we were consistent with “`NULL` is a missing argument” then I guess `x[NULL]` should be treated as `x[]`.

We are actually a bit inconsistent in the dev version because this is allowed:

```r
> vctrs::vec_slice(1:2, NULL)
integer(0)
```

^ this happens because `vec_slice()` calls the C version of `vec_as_location()`, but the R version of `vec_as_location()` also goes through `vec_as_subscript()` which is where this is caught.

**Comment by lionel-** [comment]
That seems like an overlook, I'll fix.

**Comment by lionel-** [comment]
cc @krlmlr
