### ISSUE TITLE
Rethink `vec_duplicate_id()` name, and new `vec_duplicate_loc()`

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#763]
We have:

```
vec_duplicate_any()
vec_duplicate_detect()
vec_duplicate_id()
```

```
vec_unique()
vec_unique_loc()
vec_unique_count()
```

`vec_duplicate_id()` returns "an integer vector giving the location of the first occurrence of the value". I no longer think this name is correct, for two reasons:

1. It returns locations, but `vec_duplicate_loc()` isn't the right name (see below).
2. It could be called `vec_unique_id()` and have the same meaning, suggesting that forcing it in with the unique/duplicated functions is wrong altogether.

I suggest soft-deprecating and using `vec_first_loc()` instead. "The location of the first occurrence of the current element in `x`".

---

I think that we could also use `vec_duplicate_loc()`, which to me would be the complement of `vec_unique_loc()`. Where `vec_unique_loc()` returns the locations of the first time a value is seen, I think `vec_duplicate_loc()` would return the locations of the second and subsequent times a value is seen (like `duplicated()`, but with locations).

```r
library(vctrs)

vec_duplicate_loc <- function(x) {
  vec_seq_along(x)[-vec_unique_loc(x)]
}

x <- c(5, 6, 5, 3, 6)

# Location of unique values, in order they appear
vec_unique_loc(x)
#> [1] 1 2 4

# - Location of non-unique values, i.e. the "duplicates".
# - This is like `duplicated()`, returning the loc of the second and subsequent
#   duplicate values
# - Notice how it is the complement of `vec_unique_loc()`
vec_duplicate_loc(x)
#> [1] 3 5


# I feel like `vec_duplicate_id()` and `vec_unique_id()` would be equivalent,
# suggesting that it has the wrong name altogether
vec_unique_id <- vec_duplicate_id

# i.e., both of these "make sense"

# "location of the first occurance of the value"
vec_duplicate_id(x)
#> [1] 1 2 1 4 2
vec_unique_id(x)
#> [1] 1 2 1 4 2

vec_first_loc <- vec_duplicate_id

vec_first_loc(x)
#> [1] 1 2 1 4 2
```

**Comment by DavisVaughan** [comment]
@hadley does this sound okay? The two main changes are:

- `vec_duplicate_id()` is soft deprecated in favor of `vec_first_loc()`
- New `vec_duplicate_loc()` as the complement of `vec_unique_loc()`, for returning the locations of the second and subsequent occurrences of each element in `x`

**Comment by hadley** [comment]
Could you please make a google doc (or similar) that lays out all of the grouping, duplicating, uniquing, ... functions into some sort of 2d grid?

**Comment by DavisVaughan** [comment]
Tracked in our vec-prefixes google sheet
