### ISSUE TITLE
Add "named" for named vectors

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#781]
in `vec_ptype_abbr()` (and perhaps `vec_ptype_full()`), because tibbles now allow named vectors.

Current:

``` r
vctrs::vec_ptype_abbr(c(a = 1))
#> [1] "dbl"
```

<sup>Created on 2020-01-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Desired:

``` r
vctrs::vec_ptype_abbr(c(a = 1))
#> [1] "named dbl"
```

<sup>Created on 2020-01-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
Interesting idea.

**Comment by lionel-** [comment]
Perhaps needs to be a parameter of `vec_ptype_abbr()`? In many cases it isn't relevant whether the vector is named.
