### ISSUE TITLE
Account for new element types in cnd_subscript_element()

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#786]
In {dm} we subset tables. I tried:

``` r
tryCatch(
  vctrs::vec_as_location("A", length(letters), letters),
  vctrs_error_subscript = function(cnd) {
    cnd$subscript_elt <- "table"
    rlang::cnd_signal(cnd)
  }
)
#> Error: Internal error: `cnd$subscript_elt` must be one of `element`, `row`, or `column`.
```

<sup>Created on 2020-01-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This gives me an error at `vctrs:::cnd_subscript_element`.

Would you support arbitrary element names so that we can do `cnd$subscript_elt <- c("table", "tables")` ?

**Comment by lionel-** [comment]
I don't think we should support arbitrary element names because they make it very difficult to generate proper English messages and even more difficult to translate them. But we could maybe consider adding "table".

**Comment by krlmlr** [comment]
Adding "table" would solve my problem, thanks. What else do we need, other than singular and plural forms?

**Comment by lionel-** [comment]
> What else do we need, other than singular and plural forms?

English is easiest, but in general we'd need gender, declensions, etc. I don't think it's possible to have unbounded extensibility for nouns or verbs.
