### ISSUE TITLE
Add recursive and use.names arguments to c.vctrs_vctr()?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#791]
This might help users that are inadvertently using `c(..., recursive = TRUE)` . These arguments are part of the definition of the generic.

**Comment by lionel-** [comment]
I don't think so?

**Comment by hadley** [comment]
It might be worthwhile just to avoid insidious errors? We'd throw an error if `recursive` or `use.names` were supplied, and only in `c.vctrs_vctr`, not in `vec_c()`.

**Comment by lionel-** [comment]
Ah yes, it makes sense to detect it in `c` methods.

**Comment by lionel-** [comment]
(which I now see was your point @krlmlr, I read `vec_c` instead of `c` somehow)
