### ISSUE TITLE
Semantics of functions with as_ prefix

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#792]
In hms, we have:

``` r
hms::as_hms
#> function(x) {
#>   vec_cast(x, new_hms())
#> }
#> <bytecode: 0x5645d60c2bf8>
#> <environment: namespace:hms>
```

<sup>Created on 2020-02-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I wonder if this is the most useful implementation. Should `as_hms()` be a method (again)? The default would remain as is; the method allows overrides that do not implement a coercion/casting but perhaps extraction of hms-like components from a larger object?

Similarly in blob. What's a good place to document this?

**Comment by lionel-** [comment]
`vec_cast()` should have restricted coercions, while `as_` functions can be more liberal.

**Comment by lionel-** [comment]
In general, I think extensible `as_` functions should be single dispatch generics.

**Comment by hadley** [comment]
Maybe this makes sense?

```R
as_hms <- function(x) UseMethod("as_hms")
as_hms.default <- function(x) vec_cast(x, new_hms())
```

?

**Comment by krlmlr** [comment]
I agree with the implementation. Where do we document this pattern?

**Comment by lionel-** [comment]
Let's first implement the pattern before documenting it. This is developing.

**Comment by davidchall** [comment]
@lionel- I'm migrating my package for the upcoming release of vctrs 0.3.0.

In doing so, I found this in the NEWS:

> - `vec_cast()` is now restricted to the same conversions as `vec_ptype2()` methods (#606, #741). This change is motivated by safety and performance:
> ...
>   - When unrestricted conversions are useful, this is generally towards a known type. For example, `glue::glue()` needs to convert arbitrary inputs to the known character type. In this case, using double dispatch instead of a single dispatch generic like `as.character()` is wasteful.

This sounds like I should reserve `vec_cast()` for situations where implicit coercion is desired (i.e. where we also have a `ptype2()` function), and use `as_xxx()` single-dispatch generics to handle explicit casting. This seems to align with recommendations in this issue.

However, in the vignette on S3 vector classes, it suggests writing an `as_xxx()` function that internally uses `vec_cast()`:

https://github.com/r-lib/vctrs/blob/cba3838974f6ab0b2fc2779f97298f63f538b100/vignettes/s3-vector.Rmd#L266-L272

It seems like this would prevent additional (explicit) casting methods. Have I misunderstood something? Or can I follow the advice in this issue?

**Comment by krlmlr** [comment]
This part of the documentation came in as #164 when the desired semantics of `as_()` were not clear. The simplest solution for now seems to be to remove that paragraph from the vignette.

**Comment by lionel-** [comment]
I think we could update it to use @hadley's pattern in https://github.com/r-lib/vctrs/issues/792#issuecomment-590553756.

**Comment by davidchall** [comment]
Thanks so much for the clarification!
