### ISSUE TITLE
Missing cast method: `vec_cast.character.ordered()`

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#794]
We have `vec_cast.character.factor()`

**Comment by DavisVaughan** [comment]
I just realized that `vec_cast.character.factor()` should cover this through inheritance

**Comment by lionel-** [comment]
Since cast should now mirror ptype2, and we're in the process of forbidding ptype2 inheritance, I think cast can't use inheritance either.

**Comment by DavisVaughan** [comment]
Fixed as a part of #963 

```r
> vec_cast(factor(ordered = TRUE), "x")
character(0)
```
