### ISSUE TITLE
vec_cast() with factors and NA levels

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#795]
`factor()` has this interesting `exclude = NA` argument that excludes `NA` values from being set as `levels` by default. This results in _losing_ the `NA` factor level when a user casts to a factor that actually does have NA levels.

``` r
x <- factor(c("x", NA), exclude = NULL)
x
#> [1] x    <NA>
#> Levels: x <NA>

vctrs:::vec_cast.factor.factor(x, x)
#> [1] x    <NA>
#> Levels: x
```

<sup>Created on 2020-02-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

I would argue that if you are casting `to` something with explicit `NA` levels, then those should stick around.

**Comment by lionel-** [comment]
That makes sense. The general stance in vctrs is to fully support the base data structures, e.g. rownames in data frames.
