### ISSUE TITLE
vec_cast() with factors when `to` has no levels

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#796]
The current implementation of `vec_cast.factor.factor()` special cases when `to` has 0 levels, allowing you to do:

``` r
x <- factor(c("x", "y"))
x
#> [1] x y
#> Levels: x y

to <- factor()

vctrs:::vec_cast.factor.factor(x, to)
#> [1] x y
#> Levels: x y
```

<sup>Created on 2020-02-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

I think this is too flexible? This feels like it would actually be the job of casting to a `partial_factor()`, and casting to a `factor()` should be more strict (you get the levels in `to` or die trying). We haven't fully implemented the `partial_factor()` cast methods but we could add them in to support being able to do this.

**Comment by lionel-** [comment]
I think it makes sense to treat empty data frames and empty factors as templates (or partial types). However it's unclear whether this can be a systematic principle in vctrs types, and it might make it hard to perform some specific checking/validation with explicitly empty types. The upside is that it improves the UI, e.g. `vec_is(x, factor())`.

**Comment by DavisVaughan** [comment]
For now we've kept the idea of using factors with no levels as templates
