### ISSUE TITLE
`unspecified()` and scalar ptype2 symmetry is wrong

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#807]
With current master:

``` r
library(vctrs)

foobar <- function(x = list()) structure(x, class = "vctrs_foobar")

vec_ptype2(unspecified(), foobar())
#> list()
#> attr(,"class")
#> [1] "vctrs_foobar"

vec_ptype2(foobar(), unspecified())
#> Error: `x` must be a vector, not a `vctrs_foobar` object
```

<sup>Created on 2020-02-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DavisVaughan** [comment]
`vec_ptype2.vctrs_unspecified()` may need to call `vec_assert()` on `y`

**Comment by romainfrancois** [comment]
Is this the same issue as this ?

``` r
library(vctrs)
library(tibble)
df <- tibble(x = NA)
vec_ptype(df)$x
#> logical(0)
vec_ptype2(df, df)$x
#> <unspecified> [0]
```

<sup>Created on 2020-02-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by lionel-** [comment]
Yes both ptype and ptype2 return will unfinalised prototypes across all columns once Davis' changes are merged.

**Comment by DavisVaughan** [comment]
@romainfrancois with current master, because of #816 

``` r
library(vctrs)
library(tibble)

df <- tibble(x = NA)

vec_ptype(df)$x
#> <unspecified> [0]
vec_ptype2(df, df)$x
#> <unspecified> [0]

vec_ptype_common(df)$x
#> logical(0)
vec_ptype_common(df, df)$x
#> logical(0)
```

<sup>Created on 2020-02-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
