### ISSUE TITLE
Casting `NULL` to `<scalar>` should not be allowed

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#814]
I imagine that we'd want to require that casting involving scalars always fails

``` r
library(vctrs)

vec_cast(NULL, quote(name))
#> NULL

vec_cast(quote(name), NULL)
#> name
```

We can probably call `vec_assert()` in `vec_cast()` before early returning when either `x` or `to` is `NULL`

**Comment by DavisVaughan** [comment]
Should casting with `NULL` and partial types be allowed? That would slightly alter the implementation of how this is fixed

``` r
library(vctrs)

vec_cast(partial_factor(), NULL)
#> partial_factor<
#> 
#> >

vec_cast(NULL, partial_factor())
#> NULL
```

<sup>Created on 2020-02-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
Agreed it makes sense to vec-assert when casting with `NULL`.
