### ISSUE TITLE
Allow `unspecified()` to be shaped

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#818]
This would require adding `shape_match()` to `vec_ptype2.logical.logical()` for the unspecified case, and relaxing `vec_is_unspecified()` to allow non-object, shaped logical vectors that are all `NA` to be considered unspecified

See:
https://github.com/r-lib/vctrs/pull/812#discussion_r378743128

**Comment by DavisVaughan** [comment]
I can't exactly explain why, but I don't think we actually need this.

There is something about unspecified vectors that implies that they shouldn't have any information recorded in them at all, not even the shape.

It hasn't caused us any problems so far, so I'm in favor of closing and revisiting later if we have to

**Comment by lionel-** [comment]
The information they do record is the size. I agree other dimensions are not needed currently. Revisiting later if needed sounds good.
