### ISSUE TITLE
Regression: vec_as_names() seems to ignore `quiet` argument

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#849]
## 0.2.2

``` r
vctrs::vec_as_names(c("a", "a"), repair = "unique")
#> New names:
#> * a -> a...1
#> * a -> a...2
#> [1] "a...1" "a...2"
```

<sup>Created on 2020-02-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

## 0.2.3

``` r
vctrs::vec_as_names(c("a", "a"), repair = "unique")
#> [1] "a...1" "a...2"
```

<sup>Created on 2020-02-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by krlmlr** [comment]
Introduced in 3bacee70. Did we intend to get rid of the messages?

**Comment by lionel-** [comment]
Not intentional. Looks like this is not covered by unit tests in vctrs :/
Will fix, thanks!

**Comment by lionel-** [comment]
0.2.3 caused a warning on Solaris so we can use this as reason for sending a new version right away.

**Comment by DavisVaughan** [comment]
It looks like the Solaris warning is directly related to this. We pass `quiet` through as a SEXP, when it should be a `bool` https://github.com/r-lib/vctrs/blob/6a01418e120a4a371284f05537fb7a819024b465/src/names.c#L49
