### ISSUE TITLE
vec_slice<-() and factors

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#853]
give unexpected results.

``` r
library(vctrs)

y <- factor(c("a", NA), levels = c("a", "b"))
`vec_slice<-`(y, 2, factor("b", levels = "b"))
#> [1] a    <NA>
#> Levels: a b
`vec_slice<-`(y, 1:2, factor("b", levels = "b"))
#> [1] <NA> <NA>
#> Levels: a b
```

<sup>Created on 2020-02-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DavisVaughan** [comment]
This was a problem in 0.2.2 as well, before any factor changes.

This is an interesting case where `vec_restore()` might need to change the actual underlying data, and not just the attributes. When the factor is "restored" back to its original form, it goes from having levels of `c("a", "b")` to having levels of just `"b"`. This means the data needs to be recoded, but right now `vec_restore()` doesn't do that.

The C level `vec_restore()` calls `class_type()`, so maybe we could intercept factors here and call `fct_as_factor()` to recode the underlying data before calling `vec_restore_default()`?

``` r
library(vctrs)
vec_coercible_cast <- vctrs:::vec_coercible_cast

y <- factor(c("a", NA), levels = c("a", "b"))

new <- factor("b", levels = "b")

new_like_y <- vec_coercible_cast(new, y)
new_like_y
#> [1] b
#> Levels: a b

unclass(new_like_y)
#> [1] 2
#> attr(,"levels")
#> [1] "a" "b"

# its a factor, need to fallback in vec_assign()
# first call vec_restore()
vec_restore(new_like_y, new)
#> Error in as.character.factor(x): malformed factor

# the actual data needs to be recoded here to a 1
unclass(vec_restore(new_like_y, new))
#> [1] 2
#> attr(,"levels")
#> [1] "b"
```

<sup>Created on 2020-02-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
@DavisVaughan doesn't that imply that there's a missing coercion somewhere?
