### ISSUE TITLE
Should vec_rbind() put .names_to at start?

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#855]
``` r
vctrs::vec_rbind(x = data.frame(x = 1), y = data.frame(x = 2), .names_to = "id")
#>   x id
#> 1 1  x
#> 2 2  y
```

This would be more consistent with `dplyr::bind_rows()` (i.e. https://github.com/tidyverse/dplyr/issues/4876), `vroom::vroom()`, and `plyr::ldply()`

**Comment by DavisVaughan** [comment]
having the id column first also feels more natural when compared with the new "outer names are row names behavior"

``` r
vctrs::vec_rbind(x = data.frame(x = 1), y = data.frame(x = 2), .names_to = "id")
#>   x id
#> 1 1  x
#> 2 2  y

vctrs::vec_rbind(x = data.frame(x = 1), y = data.frame(x = 2))
#>   x
#> x 1
#> y 2
```

<sup>Created on 2020-02-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
