### ISSUE TITLE
Support double dispatch methods for %in% operator (?)

### ISSUE THREAD

**Issue by davidchall** [r-lib/vctrs#873]
The [`vec_arith()`](https://vctrs.r-lib.org/reference/vec_arith.html) generic provides a double dispatch mechanism for many infix operators. Would it be possible to similarly support the `%in%` infix operator via this generic?

**Comment by lionel-** [comment]
`%in%` is a wrapper around `match()`, so the proper genericity mechanism is through `vec_proxy_equal()` and `vec_ptype2()`.

**Comment by lionel-** [comment]
Or they would be, if `match()` was generic. I don't think it is possible to dispatch with match.

**Comment by lionel-** [comment]
I think the only solution currently is to use `vec_in()` instead of `%in%`.
