### ISSUE TITLE
`new_data_frame()` attribute issues

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#883]
strips names if you provide extra attributes

``` r
library(vctrs)

new_data_frame(list(x = 1), n = 1L, stuff = "foo")
#>    
#> 1 1
```

won't let you add row names

``` r
library(vctrs)

row.names(new_data_frame(list(x = 1), n = 1L, row.names = "y"))
#> [1] "1"
```

I think the ordering of how attributes are added is a little off. The `SET_ATTRIB()` call will nuke all existing attributes, including names. So we could special case names by holding onto them and restoring them after calling that.

For manually added row names, currently they are added by the `SET_ATTRIB()` call, but then nuked by the `new_data_frame()` call.

**Comment by krlmlr** [comment]
Ideally I'd use `new_data_frame()` in tibble for reconstruction after subsetting. It would also support a lighter-weight `dplyr::dplyr_col_modify.data.frame()`.

I'm taking a stab here.

**Comment by lionel-** [comment]
@krlmlr will this be ok even though `new_data_frame()` has minimal data consistency checks?

**Comment by krlmlr** [comment]
I think so -- tibble and dplyr both take care of consistency before creating the output data frame.
