### ISSUE TITLE
I am using Jupyter Notebook and getting this when  I try to access columns in a data frame:  Error: 'vec_as_subscript' is not an exported object from 'namespace:vctrs' 

### ISSUE THREAD

**Issue by YassminAli00** [r-lib/vctrs#887]

**Comment by lionel-** [comment]
Have you tried reinstalling vctrs? What is your `sessionInfo()`, are you using any development versions of tidyverse or r-lib packages?

**Comment by YassminAli00** [comment]
I am using 'dplyr' I was getting the error when I use the select function to access columns. I installed vctrs as you suggested and it is working fine now. Thank you so much.
