### ISSUE TITLE
Throwing classed errors from C code

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#888]
We should make it easier to throw classed errors from C code. I'm suggesting to provide a drop-in replacement for `Rf_errorcall()` that calls into R for throwing a general-purpose classed error, and refine error classes as we proceed.

What's a good time for this change?

**Comment by lionel-** [comment]
I think it's easier to create an R-level thrower and call it from C the usual way.

**Comment by krlmlr** [comment]
Agreed. I'm proposing to make it easy to call the R-level thrower from C.

**Comment by lionel-** [comment]
And how would you make it easier than using `r_call()` like we do in conditions.c?

**Comment by lionel-** [comment]
I don't think we need to spend time on this now in any case, I'd like to send a patch release very soon because I'll be mostly out of office next week.

**Comment by krlmlr** [comment]
We should provide `stop_internal_vctrs(const char*)` and `stop_vctrs(const char*)` or something like that, calling into R like in `condition.c`, and then refine as necessary. Goal: no `Rf_errorcall(R_NilValue` in the code.

Also, check that all error messages end with a dot.

**Comment by lionel-** [comment]
I think this is about an `r_abort()` C callable https://github.com/r-lib/rlang/issues/921

> Also, check that all error messages end with a full stop.

This would probably cause issues.
