### ISSUE TITLE
vctrs_rcrd classes could be implemented as data frames, not lists

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#900]
@lionel- and I spoke about this awhile back, and I think we managed to convince ourselves that it makes sense to implement the rcrd class as an actual data frame with 1 column per field.

It might help with this problem:

``` r
library(vctrs)

x <- new_rcrd(list(x = 1:3, y = 3:5))

names(x) <- letters[1:3]
#> Error in NextMethod(): 'names' attribute [3] must be the same length as the vector [2]
```

We could store names as row names in the data frame. Alternatively we could just have a specially named column in the data frame, like `vctrs_rcrd::names`, but then things like the proxy would have to know to remove it. One thing to keep in mind is that row names are not allowed to be duplicated, but generally names are, so that might be a limitation to this approach.

We could have `names.vctrs_rcrd` forward to `vec_names()`, and `names<-.vctrs_rcrd` forward to `vec_set_names()`. We'd have to teach `vec_names()` and `vec_set_names()` to remove and set data frame row names, which they currently don't do, but I'm not sure we were ever convinced that that was the right decision.

Also, is this current implementation intended? If so, maybe we just need a `names<-` method that prevents adding names to a rcrd. You can add names to a POSIXlt though, so I feel like this should be allowed.

```r
> vctrs:::names.vctrs_rcrd
function(x) {
  NULL
}
```

**Comment by hadley** [comment]
I basically don't like the idea of extending the data frame class because I have no idea what precisely that implies because I don't understand how all the data frame methods work. I would much rather start from nothing and carefully add on the bits we need, rather than starting from something complex and having to carve off bits that don't work quite right.

**Comment by DavisVaughan** [comment]
That makes sense to me.

So if we keep vctrs_rcrd as a list do you want `names.vctrs_rcrd()` and `names.<-vctrs_rcrd()` to work? Or should `names()` continue to return `NULL` and `names<-` error?

**Comment by hadley** [comment]
I can't remember exactly how records work, but if `names()` should be compatible with `length()` and `$`/`[[`, and I suspect that means `names()` and `names<-` should error. (Unless we want names to act like row names, which I'm reasonable certain we don't)

**Comment by lionel-** [comment]
I was also thinking this would be an entirely separate class that would implement the vctrs interface.

I really want rcrd vectors to have names like all other vectors.

One way to achieve this would be to map `names()` to `rownames()`, and we'd have a new concept generic for querying the type of rownames which could be one of `"names"` (vctrs bare data frames, can have duplicates or empty names) or `"identifiers"` (base data frames). This generic would be used in internal routines to figure out how to treat row names.

**Comment by lionel-** [comment]
Also instead of providing a separate API with `fields()` we'd make the class transposable. So within methods you could transpose-in and transpose-out to modify the record columns, for example:

```r
t(map(t(x), foo))
```

**Comment by hadley** [comment]
@lionel- what's the goal of all this proposed work

**Comment by lionel-** [comment]
To experiment with data frames in new directions, and develop a data frame class that is truly a vector in the vctrs sense. To replace the `fields()` API by the common vector API. To get name-able record classes. To get a bare bones data frame class which can be used for programming with precise semantics.

I am _not_ suggesting that we need do this work now, in fact I don't think we should work on this right away. These are just ideas for what could be a useful primitive class in vctrs. We could just store record names in a special record field for the time being.

**Comment by lionel-** [comment]
Interesting idea, but this is not high priority.

**Comment by DavisVaughan** [comment]
Yea I also think keeping them as a list is probably the right approach to avoid dealing with any weirdness of data.frame being an S3 class, which was Hadley's original concern
