### ISSUE TITLE
support for "table"

### ISSUE THREAD

**Issue by romainfrancois** [r-lib/vctrs#904]
originally https://github.com/tidyverse/dplyr/issues/4963

``` r
vctrs::vec_c(table("tennis"))
#> Error: Can't find vctrs or base methods for concatenation.
#> vctrs methods must be implemented for class `table`.
#> See <https://vctrs.r-lib.org/articles/s3-vector.html>.
```

<sup>Created on 2020-03-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
@DavisVaughan could you please take a look at the minimal methods needed here?
