### ISSUE TITLE
vec_is(..., new_datetime()) too strict

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#905]
The `tzone` attribute is set for `Sys.time()` but not for `new_datetime()`, this is treated as a meaningful difference.

``` r
vctrs::vec_is(Sys.time(), vctrs::new_datetime())
#> [1] FALSE
```

<sup>Created on 2020-03-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Related: #561.

**Comment by DavisVaughan** [comment]
This strictness is part of the reason we have "partial" types. i.e. for factors

``` r
library(vctrs)

vec_is(factor("x"), factor())
#> [1] FALSE

vec_is(factor("x"), partial_factor())
#> [1] TRUE

vec_is(factor("x"), factor("x"))
#> [1] TRUE
```

<sup>Created on 2020-03-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I'm not sure what the best long term solution is here though. It might be something other than partial types

**Comment by lionel-** [comment]
To me this doesn't feel connected to partial types because I see timezone as a "detail" parameter of the type.

I think we'll need to bite the bullet and introduce a new generic for the is-a relationship.

**Comment by krlmlr** [comment]
Can we treat types equal if their proxies are equal?

**Comment by lionel-** [comment]
We can't, e.g. factors and integers have the same memory representation but represent different values.

**Comment by krlmlr** [comment]
I now see:

``` r
vctrs::vec_is(Sys.time(), vctrs::new_datetime())
#> [1] TRUE
```

<sup>Created on 2021-03-18 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by lionel-** [comment]
This is probably incidental. `vec_is()` is currently not guaranteed to work this way, it has design issues that are not solved yet.

**Comment by krlmlr** [comment]
Let's add a test while it lasts :zany_face:
