### ISSUE TITLE
Improve ptype2 and cast error messages

### ISSUE THREAD

**Issue by lionel-** [r-lib/vctrs#922]
* [x] Instead of "Lossy cast from x to y", mention "Converting from x to y loses precision"?

* [ ] Error FAQ about lossy casts.

**Comment by lionel-** [comment]
```r
#> Error: Can't cast `a` <fs_path> to `a` <fs_path>.
```

Should say "convert" instead of "cast". Would be nice to mention the type of input ("argument", "column", ...), in the same way we do for subscripts.

**Comment by hadley** [comment]
Also in the case where the two classes are the same, maybe we should print some hint suggesting that a method is missing and needs to be provided by the package authort?

**Comment by lionel-** [comment]
Good idea. Most of the time it should work once we finish implementing the fallback. But if `is_same_type()` returns `FALSE` even though the classes are the same, this hint would be useful.

**Comment by lionel-** [comment]
```
Can't convert from `times` <character> to <integer>.
=>
Can't convert `times` from <character> to <integer>.
```

And then maybe:

```
Can't convert from `times` <character> to `foo` <integer>.
=>
Can't convert `times` from <character> to the type of `foo` <integer>.
```

**Comment by lionel-** [comment]
We could improve the ptype2 errors along the same lines. Instead of:

> No common type for x and y.

It could be

> Can't combine x and y.

**Comment by hadley** [comment]
Actually maybe the `from` isn't needed?

```
Can't convert `times` <character> to <integer>.
Can't convert `times` <character> to the type of `foo` <integer>.
```

**Comment by hadley** [comment]
And do we need a hint?

```R
Can't combine `x` <character> to `y` <integer>.
Do you need to convert one of the arguments?
```

**Comment by batpigandme** [comment]
I like the "loses precision" and using combine and convert as needed. 
```r
#> Error: Can't cast `a` <fs_path> to `a` <fs_path>.
```
This will definitely read like nonsense to an end user, even if it's convert instead of cast. Is there a way that a user could allow for things to be more permissive while waiting for the author to implement a method? How rare do we think this will be?

**Comment by hadley** [comment]
I think the `can't cast <x> to <x>` problem is now (mostly) fixed so it should be rare for the user to see it.
