### ISSUE TITLE
vec_assign() doesn't update names

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#935]
but should?

Proposed invariant: `identical(vec_slice(vec_assign(x, i, value), i), value)` .

``` r
x <- c(a = 1, b = 2)
vctrs::vec_assign(x, 1, c(c = 3))
#> a b 
#> 3 2
```

<sup>Created on 2020-03-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
It shouldn't by default, but we might export the internal parameter that allows this once #924 is merged. Do you need it for tibble?

It makes sense to assign names when filling up a data structure after `vec_init()`.

**Comment by krlmlr** [comment]
No action needed, this is consistent with base:

``` r
x <- c(a = 1, b = 2)
x[1] <- c(c = 3)
x
#> a b 
#> 3 2
```

<sup>Created on 2020-04-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
