### ISSUE TITLE
In is.na<-, value can be any index

### ISSUE THREAD

**Issue by danhalligan** [r-lib/vctrs#947]
`is.na<-.vctrs_vct` asserts value argument is a logical.

https://github.com/r-lib/vctrs/blob/69cff44aa55791a5c7275b8a4575be8ef8550c61/R/type-vctr.R#L640

However, in base::R merge.data.frame it may be an index of values to set to NA. See (for example) this section of the merge.data.frame base R function:

```{r}
        if (all.x) {
            zap <- (lxy + 1L):(lxy + nxx)
            for (i in seq_along(y)) {
                if (is.matrix(y[[1]])) 
                  y[[1]][zap, ] <- NA
                else is.na(y[[i]]) <- zap
            }
        }
```

**Comment by hadley** [comment]
From the `is.na` docs:

``` r
(xx <- c(0:4))
#> [1] 0 1 2 3 4
is.na(xx) <- c(2, 4)
xx
#> [1]  0 NA  2 NA  4
```

<sup>Created on 2020-03-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
