### ISSUE TITLE
dimB partially matches dim?

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#948]
``` r
library(vctrs)

df <- structure(data.frame(a=1:2), dimB = 1)
vec_data(df)
#> Error in attributes(x) <- attrib: dims [product 2] do not match the length of object [1]
```

<sup>Created on 2020-03-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DavisVaughan** [comment]
Partial matching in the R level `has_dim()` in `attr()`! Would need `exact = TRUE`, but the better solution is probably to sync it with the C level `has_dim()`
