### ISSUE TITLE
Reconsider factor + character interaction

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#95]
I think maybe characters should be coerced to factors, with values out of range giving a warning?

**Comment by hadley** [comment]
At a minimum the drawings in the docs and vctrs behaviour no longer align so need to be updated.

**Comment by DavisVaughan** [comment]
👍 this would be helpful. I was planning on using) `class_pred` -> cast to factor and handle `NA` values -> cast to character, but was surprised to see that factors could not be cast to character.
