### ISSUE TITLE
vec_cast.ordered generic?

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#96]
Is this going to be implemented? I wanted `vec_cast.ordered.class_pred` so I could intelligently coerce to an ordered factor. Right now, with the new PR, `as.ordered()` eventually calls `vec_cast.factor.class_pred` because the ordered intermediate method doesn't exist.

**Comment by hadley** [comment]
Looking at the current code, I don't think it's necessary — since `ordered()` is only an additional class with no other attributes, it's just as easy to handle in the factor method.

**Comment by hadley** [comment]
If that doesn't make sense, give me a fuller description of the problem and I'll suggest how you might proceed.

**Comment by DavisVaughan** [comment]
I got it! The fact that the full class of `to` propagates to `vec_cast.factor.class_pred` means that I can check if `to` is `ordered` and handle appropriately. Nice design.

https://github.com/topepo/probably/blob/initial-class-pred-work/R/vctrs-compat.R#L109
