### ISSUE TITLE
`vec_cast.factor.factor` shaped handling

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#964]
The dim is currently not handled in `vec_cast.factor.factor()`. This method is run because right now we always fall back to the S3 dispatch in `vec_cast()` if any input is shaped.

``` r
library(vctrs)

x <- factor(c("a", "b", "c", "d"))
dim(x) <- c(2, 2)

vec_cast(x, x)
#> [1] a b c d
#> Levels: a b c d
```

<sup>Created on 2020-03-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

@lionel- has mentioned that it would be nice to always handle the shape for all foreign types. I think that will be better than special casing the factor method here

**Comment by DavisVaughan** [comment]
A test that we could add to `vec_assign()` after this is fixed:

```r
test_that("assignment restores attributes on shaped S3 objects correctly", {
  x <- factor(c("a", "b", "c", "d", "e", "f"))
  dim(x) <- c(3, 2)

  value <- factor(c("c", "d"))
  dim(value) <- c(1, 2)

  expect <- factor(c("c", "b", "c", "d", "e", "d"))
  dim(expect) <- c(3, 2)

  expect_identical(
    vec_assign(x, c(1, 3), value),
    expect
  )
})
```

**Comment by hadley** [comment]
I'm not sure if this is a general principle; dates (for example) don't seem like they've been designed to have a dim:

``` r
x <- Sys.Date() + 0:3
dim(x) <- c(2, 2)
x
#> [1] "2020-03-27" "2020-03-28" "2020-03-29" "2020-03-30"
```

<sup>Created on 2020-03-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DavisVaughan** [comment]
I don't think factors are either tbh https://stackoverflow.com/questions/28723059/can-we-get-factor-matrices-in-r

**Comment by lionel-** [comment]
It would be cheap for us to support S3 classes right? I'd just do it for consistency, since there is no cost.

**Comment by hadley** [comment]
I'm not convinced that it's worth the effort — I think a reasonable position is to say that `dim` only applies to atomic vectors and specific S3 classes like `table()`.

**Comment by lionel-** [comment]
Let's discuss shaped S3 vectors again when/if the need comes up.
