### ISSUE TITLE
Switch to `vec_cast()`

### ISSUE THREAD

**Issue by lionel-** [r-lib/vctrs#969]
- Throw incompatible type errors for unimplemented `vec_cast()` methods.
- Use `vec_cast()` in `vec_assign()`.

**Comment by DavisVaughan** [comment]
* Use `vec_cast()` in `vec_as_location()` https://github.com/r-lib/vctrs/blob/1a06f1fe6aa3732b5629483b5ea045d8e518647c/src/subscript-loc.c#L393

**Comment by lionel-** [comment]
Include `action` field in condition object so the generated message can be different if thrown from ptype2 (action = combine?) and cast (action = convert). Same approach as for subscript errors.
