### ISSUE TITLE
vec_is() too strict for data frames that append to class?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/vctrs#972]
``` r
df <- data.frame(a = 1)
class(df) <- c("data.frame", "foo")

is.data.frame(df)
#> [1] TRUE
vctrs::vec_is(df)
#> [1] FALSE
vctrs::vec_assert(df)
#> Error: `df` must be a vector, not a `data.frame/foo` object.
```

<sup>Created on 2020-03-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Appending the class can lead to undesired behavior for *existing* methods, but this is not necessarily wrong if the new class only implements own methods (mixin or multiple inheritance):

``` r
df <- data.frame(a = 1)
class(df) <- c("data.frame", "foo")

print.foo <- function(x, ...) {
  cat("Print overridden\n")
  invisible(x)
}

vctrs::s3_register("base::print", "foo")

# Not accessing overridden method:
df
#>   a
#> 1 1

# Works when reversing the class
class(df) <- c("foo", "data.frame")
df
#> Print overridden
```

<sup>Created on 2020-03-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
> Appending the class can lead to undesired behavior for existing methods, but this is not necessarily wrong if the new class only implements own methods (mixin or multiple inheritance):

I think this intuition is right. But currently there's really no way of writing mixins in R because the mixin class isn't reconstructed, and doesn't get a chance to display information in print methods. So I don't think this is a good reason.

**Comment by lionel-** [comment]
Closing this for now, we can revisit later.
