### ISSUE TITLE
Faster `df_type2()` when the names point to the same reference

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#979]
Pointed out by @hadley 

https://github.com/r-lib/vctrs/blob/0fee5a501a6f2cef5abd45ec0942b189f5815cb9/src/type-data-frame.c#L291-L310

We won't need any matching code if `x_names == y_names`

This would be important with `vec_unchop()` with a list of tibbles that all have the same names

**Comment by DavisVaughan** [comment]
I think there could be 3 levels of checks here:

1. `x_names == y_names`, identical reference - fast pass

2. If `x_names` and `y_names` are the same length, loop through them check if the names are all the same. Break early if any names are different. If names are all the same, use the same fast pass as 1

3. Current code path with matching

**Comment by lionel-** [comment]
> This would be important with vec_unchop() with a list of tibbles that all have the same names

Unless it's the exact same tibble from a `rep()`, there's little chance that these tibbles share the same names object.

The first two levels of check can be performed with a single call to `equal_object()` from equal.c.

**Comment by hadley** [comment]
@lionel- won't any `vec_slice()` or `df[x, , drop = FALSE]` reuse the names vector?

**Comment by lionel-** [comment]
Yes they will.
