### ISSUE TITLE
Discussion of promotion vs class hierarchy

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#980]
e.g. from Julia, https://docs.julialang.org/en/v1/manual/conversion-and-promotion/#Promotion-1

> It is important, however, not to confuse this with object-oriented (structural) super-typing, or Julia's notion of abstract super-types: promotion has nothing to do with the type hierarchy, and everything to do with converting between alternate representations

And this is the reason that `vec_ptype()` and `vec_cast()` can't rely on inheritance.

**Comment by lionel-** [comment]
I think the more general notion is coercion, which includes both casts and promotions. I don't love the definition of Julia because coercions do have everything to do with type hierarchies. It's just that the types and the hierarchies are implicit.
