### ISSUE TITLE
data.frame cast fallback

### ISSUE THREAD

**Issue by hadley** [r-lib/vctrs#981]
I think we may need a some data.frame fallbacks so that we get something like this:

```
vec_rbind(tibble(x = 1), data.table(x = 1))
# Warning: combining <tibble> and <data.table>; falling back to <data.frame>
```

(This is not a general regret that we're moving away from inheritance; it's a specific pragmatic fallback + warning for people working with multiple data frame subclasses)

**Comment by lionel-** [comment]
I like the idea, the warning will encourage people to normalise their inputs, and so their code won't be affected when the class authors end up implementing methods.

Implementation will probably require a sentinel data frame class to avoid repeat warnings.

**Comment by lionel-** [comment]
Somehow it makes more sense for data frames than for other types. For example it wouldn't make sense to coerce factors to integers with a warning.

Maybe the general rule is that if a class explicitly inherits from one of the base classes (including `data.frame`), then a fallback + warning is in order? (Not that we should rush implementing a general fallback.)
