### ISSUE TITLE
vec_rbind() fails for subclasses of tibble() 

### ISSUE THREAD

**Issue by michaelquinn32** [r-lib/vctrs#982]
Hi team!

@elinw and I are updating [ropensci/skimr](https://www.github.com/ropensci/skimr) for the dplyr v1 release. We are struggling with the behavior of `vec_rbind()`. 
https://github.com/ropensci/skimr/issues/582

We use a `skim_df` object which inherits from a tibble.

```
library(skimr)
skimmed <- skimr::skim(iris)
str(skimmed)
#> tibble [5 × 15] (S3: skim_df/tbl_df/tbl/data.frame)
#>  $ skim_type        : chr [1:5] "factor" "numeric" "numeric" "numeric" ...
#>  $ skim_variable    : chr [1:5] "Species" "Sepal.Length" "Sepal.Width" "Petal.Length" ...
#>  $ n_missing        : int [1:5] 0 0 0 0 0
#>  $ complete_rate    : num [1:5] 1 1 1 1 1
#>  $ factor.ordered   : logi [1:5] FALSE NA NA NA NA
#>  $ factor.n_unique  : int [1:5] 3 NA NA NA NA
#>  $ factor.top_counts: chr [1:5] "set: 50, ver: 50, vir: 50" NA NA NA ...
#>  $ numeric.mean     : num [1:5] NA 5.84 3.06 3.76 1.2
#>  $ numeric.sd       : num [1:5] NA 0.828 0.436 1.765 0.762
#>  $ numeric.p0       : num [1:5] NA 4.3 2 1 0.1
#>  $ numeric.p25      : num [1:5] NA 5.1 2.8 1.6 0.3
#>  $ numeric.p50      : num [1:5] NA 5.8 3 4.35 1.3
#>  $ numeric.p75      : num [1:5] NA 6.4 3.3 5.1 1.8
#>  $ numeric.p100     : num [1:5] NA 7.9 4.4 6.9 2.5
#>  $ numeric.hist     : chr [1:5] NA "▆▇▇▅▂" "▁▆▇▂▁" "▇▁▆▇▂" ...
#>  - attr(*, "data_rows")= int 150
#>  - attr(*, "data_cols")= int 5
#>  - attr(*, "df_name")= chr "`iris`"
#>  - attr(*, "groups")= list()
#>  - attr(*, "base_skimmers")= chr [1:2] "n_missing" "complete_rate"
#>  - attr(*, "skimmers_used")=List of 2
#>   ..$ numeric: chr [1:8] "mean" "sd" "p0" "p25" ...
#>   ..$ factor : chr [1:3] "ordered" "n_unique" "top_counts"
```

But if I drop a column from this data frame I cannot use `vec_rbind()`.

```
vctrs::vec_rbind(
  dplyr::select(skimmed, -n_missing),
  skimmed
)

Error: No common type for `..1` <skim_df<
  skim_type        : character
  skim_variable    : character
  complete_rate    : double
  factor.ordered   : logical
  factor.n_unique  : integer
  factor.top_counts: character
  numeric.mean     : double
  numeric.sd       : double
  numeric.p0       : double
  numeric.p25      : double
  numeric.p50      : double
  numeric.p75      : double
  numeric.p100     : double
  numeric.hist     : character
>> and `..2` <skim_df<
  skim_type        : character
  skim_variable    : character
  n_missing        : integer
  complete_rate    : double
  factor.ordered   : logical
  factor.n_unique  : integer
  factor.top_counts: character
  numeric.mean     : double
  numeric.sd       : double
  numeric.p0       : double
  numeric.p25      : double
  numeric.p50      : double
  numeric.p75      : double
  numeric.p100     : double
  numeric.hist     : character
>>.
```

I've tried some of the ptype logic, but it doesn't seem to solve it unless I provide a fully enumerated list of columns.

```
 skim_df <- function(...) {
   structure(
     tibble::tibble(...),
     class = c("skim_df", "tbl_df", "tbl", "data.frame"),
     data_rows = integer(),
     data_cols = integer(),
     df_name = character(),
     groups = list(),
     base_skimmers = character(),
     skimmers_used = list()
   )
}

vctrs::vec_rbind(
  dplyr::select(skimmed, -n_missing),
  skimmed,
  .ptype = skim_df()
)

Error: Can't convert from <skim_df<
  skim_type        : character
  skim_variable    : character
  complete_rate    : double
  factor.ordered   : logical
  factor.n_unique  : integer
  factor.top_counts: character
  numeric.mean     : double
  numeric.sd       : double
  numeric.p0       : double
  numeric.p25      : double
  numeric.p50      : double
  numeric.p75      : double
  numeric.p100     : double
  numeric.hist     : character
>> to <skim_df<>>.
```

I have been looking at users of vctrs, and I am not seeing example solutions to this problem. Do I need a `vec_ptype2()` method? 

This matter a lot to us, because our `partition()` function creates of list of `one_skim_df` objects that inherit from tibble, but usually have different sets of columns. We want to be able to join it back together.

**Comment by hadley** [comment]
Closely related to #981. I think we need to do something to provide a better fallback here so that at least you get a tibble/data.frame rather than an error.

But you'll also need to provide a `vec_ptype2()` and `vec_cast()` method. I think you can mostly make use of the existing data frame methods (by calling `vec_ptype2(as.data.frame(x), as.data.frame(y))` but you'll need to think about how to handle the attributes (i.e. what should happen if they're not equal). 

It looks like we also need to provide more documentation/examples for objects that inherit from data.frame.

**Comment by michaelquinn32** [comment]
Sorry, but do you have a minimal example that does this somewhere? I'm trying to implement something but am still lost.

I've got the following functions,

```
#' @export
vec_ptype2.skim_df <- function(x, y, ...) {
  vec_ptype2(
    as.data.frame(x),
    as.data.frame(y)
  )
}

#' @export
vec_cast.skim_df <- function(x, to, ...) {
  vec_cast(as.data.frame(x), to, ...)
}
```

I'm trying to bypass s3 dispatch since `NextMethod("vec_ptype2")` doesn't seem to work here. When I call the following, I get this trace.

```
library(skimr)
skimmed <- skim(iris)
dplyr::bind_rows(skimmed, dplyr::select(skimmed, -1))
Backtrace:
    █
 1. ├─dplyr::bind_rows(skimmed, dplyr::select(skimmed, -1))
 2. │ └─vctrs::vec_rbind(!!!dots, .names_to = .id)
 3. └─vctrs::vec_default_ptype2(x = x, y = y, x_arg = x_arg, y_arg = y_arg)
 4.   └─vctrs::stop_incompatible_type(x, y, x_arg = x_arg, y_arg = y_arg)
 5.     └─vctrs:::stop_incompatible(...)
 6.       └─vctrs:::stop_vctrs(...)
```

I can't seem to figure out how `vec_default_ptype2()`

* Gets the prototypes that it uses for its comparison, because when I looked that's what `x` and `y` appeared to be. They all appeared to be `skim_df` prototypes, but how that happened is unclear to me.
* Interacts with `vec_ptype2`. I don't see it being called anywhere.

Am I missing another method?

Thanks!

**Comment by DavisVaughan** [comment]
`vec_ptype2` and `vec_cast` use _double_ dispatch so definitely start with this vignette that describes that part if you haven't seen it yet https://vctrs.r-lib.org/articles/s3-vector.html

currently you probably need these and their corresponding cast methods:

```
vec_ptype2.skim_df.skim_df

vec_ptype2.skim_df.data.frame
vec_ptype2.data.frame.skim_df

vec_ptype2.skim_df.tbl_df
vec_ptype2.tbl_df.skim_df
```

With the way this is done internally, technically your single dispatch pieces `vec_ptype2.skim_df` are never called

**Comment by michaelquinn32** [comment]
Hi Davis!

Thanks for the help. I've started the implementation. Here:
https://github.com/ropensci/skimr/blob/vctrs/R/vctrs.R

I would like to be able to handle ptypes and casting with tbl_df objects too, but it seems that is not possible. When trying to import these messages, I see:
```
Running /usr/lib/R/bin/R CMD INSTALL \
  /tmp/RtmpSiszkO/skimr_2.1.tar.gz --install-tests
* installing to library ‘/usr/local/google/home/msquinn/R/x86_64-pc-linux-gnu-library/3.6’
* installing *source* package ‘skimr’ ...
** using staged installation
** R
** inst
** tests
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘skimr’:
 object 'vec_cast.tbl_df' not found whilst loading namespace 'skimr'
```

Which I assume is related to some of the dynamism here:
https://github.com/r-lib/vctrs/blob/master/R/zzz.R

Now, when trying to use `bind_rows`, I get a different error. This appears to be a C-level problem.

```
library(skimr)
skimmed <- skimr::skim(iris)
dplyr::bind_rows(skimmed, dplyr::select(skimmed, -1))
Error in vec_rbind(!!!dots, .names_to = .id) :
  STRING_PTR_RO() can only be applied to a 'character', not a 'integer'
```

Best wishes,
Michael

**Comment by lionel-** [comment]
Right we need to export `vec_ptype2.tbl_df()` and `vec_cast.tbl_df()` from somewhere. Eventually it should be exported from tibble, but isn't yet. Exporting from vctrs right away would cause issues when we do move the methods to tibble.

The coercion system has been in flux until now, but I think we're reaching stability. Maybe we should send a patch release of tibble that exports the double dispatch generic-methods, as well as `tib_cast()` and `tib_ptype2()`.

One workaround for you would be to look up `vec_cast.tbl_df` and `vec_ptype2.tbl_df` at runtime. First look them up in the vctrs namespace, and then in the tibble namespace if not found. With rlang:

```r
lookup_tibble_generics <- function(nm) {
  ns <- rlang::ns_env("vctrs")
  fn <- rlang::env_get(ns, nm, default = NULL)

  if (is.null(fn)) {
    ns <- rlang::ns_env("tibble")
    # This fails if not found in tibble
    fn <- rlang::env_get(ns, nm)
  }

  fn
}

delayedAssign("vec_cast.tbl_df", lookup_tibble_generics("vec_cast.tbl_df"))
delayedAssign("vec_ptype2.tbl_df", lookup_tibble_generics("vec_ptype2.tbl_df"))
```

Then register all methods for these tibble generics lazily as well, after the lookup (e.g. in the `.onLoad()` hook).

By the way this doesn't look right:

```r
vec_cast.skim_df.tbl_df <- function(x, to, ...) {
  tibble::as_tibble(x)
}
```

For `vec_cast()` the classes are the other way around than you'd expect given the signature because it first dispatches on `to` and then on `x`. So this method should be casting to skim-df instead of to tbl-df.

**Comment by lionel-** [comment]
We may be able to make these things simpler, see #985.

**Comment by hadley** [comment]
Also, I think we'll probably implement #981 prior to dplyr release, and then you wouldn't have to do anything in skimr. You probably would still eventually want to implement these methods so you have greater control over what happens in `bind_rows()` (and to possibly eliminate a warning), but there wouldn't be any rush.

**Comment by michaelquinn32** [comment]
Thanks everyone!

We have a bit of a hack in place so that the default skimr interface works. This shouldn't block the release of dplyr. But I am really looking forward to the rest of these issues being solved so that we can have better support of the new interfaces. Fallbacks would help a lot, and the guidance on double dispatch is especially appreciated.

**Comment by krlmlr** [comment]
Is exporting `vec_ptype2.tbl_df()` and `vec_cast.tbl_df()` compatible with vctrs 0.2.4? I don't mind a patch release on April 6 (one week after 3.0.0 release).

**Comment by michaelquinn32** [comment]
One more thing.

Is the reversed order true for vec_ptype2 as well?

By that, should the signature look like this?

```
vec_ptype2.y_type.x_type <- function(x, y, ...)
```

**Comment by lionel-** [comment]
No, it is only true for `vec_cast()` 😬

This is something I'd really really like to fix, but it gets harder as time passes since that's quite a breaking change.

@krlmlr I don't think this will be necessary thanks to issue 985.

**Comment by lionel-** [comment]
The process for implementing coercion methods for data frames is now documented here: https://vctrs.r-lib.org/reference/howto-faq-coercion-data-frame.html

Please also see this general reference about how coercion works in vctrs: https://vctrs.r-lib.org/reference/howto-faq-coercion.html

And the practical guide for implementing coercion methods for normal vectors might also be useful: https://vctrs.r-lib.org/reference/howto-faq-coercion.html

Any feedback on these would be very welcome!
