### ISSUE TITLE
Simplify double dispatch registration and lookup

### ISSUE THREAD

**Issue by lionel-** [r-lib/vctrs#985]
Regarding #982, I wonder if we could simplify the registration by registering all methods for `vec_ptype2()` and `vec_cast()` in the vctrs namespace.

For instance you'd register `vec_ptype2.character.foobar` as a `character.foobar` method for `vec_ptype2` instead of a `foobar` method for `vec_ptype2.character`. It feels like this should work?

That would simplify the registration process because the left methods wouldn't need to be exported or registered at all. Since they are no longer evaluated, it also feels cleaner that they don't need to exist. There wouldn't be multiple namespaces involved in the dispatch or registration, making the whole system more transparent and easier to document and use.

**Comment by hadley** [comment]
Yeah, I think that would work now. Does it even need any changes to vctrs? Can we just remove the old single dispatch generics and the old roxygen2 commands?

**Comment by hadley** [comment]
Oh because in the C code, you're looking for the namespace of the generic. You'd just need to look for the combined method in the vctrs namespace first, before falling back to the older approach.

**Comment by DavisVaughan** [comment]
> before falling back to the older approach

Would this just be to be backwards compatible with packages that have already implemented R level double dispatch methods with the current approach? Because the second level of dispatch will be in that package's namespace?

**Comment by hadley** [comment]
Right, I think we need the fallback for at least this release, otherwise we'll need to rush out release for glue etc.

**Comment by krlmlr** [comment]
Slightly related: {sf} registers `vec_ptype2.sfc()` via delayed registration, and `vec.ptype2.sfc.sfc()` and `....default()` via eager registration. This fails with current vctrs.

**Comment by krlmlr** [comment]
{sf} has 9 subclasses `"sfc"` -- 8 specific one and a catch-all `sfc_GEOMETRY`. Combining two different subclasses gives `sfc_GEOMETRY`, only combining same subclasses gives the same subclass. The latter is handled nicely by `vec_restore()`.

How do we avoid quadratic growth of methods? With double dispatch we only need to implement and dynamically register k * 8 methods, without d.d. it will be 8² = 64. Do we need a "supertype" as the first class component, perhaps put `"sfc"` in front of `"sfc_*"` in the class?

**Comment by krlmlr** [comment]
{tsibble} implements methods for `vec_ptype2.POSIXt()` which are gone as of #970. What is the "supertype" for `POSIXct` and `POSIXlt`?

Should we provide a new `vec_stype()` generic that returns `"POSIXt"` for time classes and `"sfc"` for sf classes? This would determine the methods called in `vec_ptype2()`.

**Comment by lionel-** [comment]
> How do we avoid quadratic growth of methods?

This growth is a feature. There shouldn't be coercion rules for everything and anything, only for the most important types. Also the answer to a problem in R generally shouldn't be to create a new type.

>  Do we need a "supertype" as the first class component, perhaps put "sfc" in front of "sfc_*" in the class?

No, we can't rely on class hierarchies to figure out what the richer type is.

> What is the "supertype" for POSIXct and POSIXlt?

I'm not familiar with the date/time classes, but if they have a similar resolution we probably just need to choose one as the reference.

**Comment by lionel-** [comment]
sf is a bit special because the classes fall back to an abstract geometry type, something we generally don't do in vctrs (like falling back to deparsing or chopping). We may need a special mechanism to support this.

A similar type to `sfc` is `list_of()`, and the abstract geometry list is like a `list()`. A first step towards supporting sfc would be to implement a variant of `list_of()` that falls back to list.

Ideally combining a `sfc<polygon>` and a `sfc<multipolygon>` would return the latter. Combining with something that isn't compatible falls back to the abstract type `sfc<ANY>`. These more refined rules aren't implemented yet though.

**Comment by krlmlr** [comment]
I'm trying to understand that in the context of sf. A "point" and a "line" is a list of point objects of the same type, similarly to `list_of` but not extending it. `vec_ptype2(point, line)` currently gives a "geometry" object, which is a list of arbitrary geometries. Are you suggesting to forbid `vec_ptype2(point, line)` and all other combinations, and require users to explicitly coerce to "geometry" first?

**Comment by lionel-** [comment]
>  Are you suggesting to forbid vec_ptype2(point, line) and all other combinations, and require users to explicitly coerce to "geometry" first?

No, there would still be a fallback to the abstract geometry type. The more refined coercion rules aren't important right now.

**Comment by krlmlr** [comment]
Does this mean that we need 81 or maybe 100 `vec_ptype2()` methods in sf for vctrs 0.3.0?

**Comment by lionel-** [comment]
I don't think you have understood my point. Maybe move the discussion to Slack?

**Comment by hadley** [comment]
Another idea: if `vec_ptype2.x.y` doesn't exist, should we automatically try `vec_ptype2.y.x`? That would allow you to half the number of methods you need to provide in many cases.

**Comment by lionel-** [comment]
I like the idea of halving implementations, though it'd probably still be good practice to implement both methods to avoid two lookups.
